### ISSUE TITLE
Cost management abilities

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/Zappa#10]
Could be out of scope, but would be great to be able to easily see how much a deployment has cost, ex https://github.com/Miserlou/django-aws-billing

**Comment by berezovskyi** [comment]
I think the good use could be to use billing to reconfigure API Gateway to throttle more aggressively or send notifications (SNS, SES)? I think just viewing is no better than viewing the console.

**Comment by Miserlou** [comment]
Ah, that's an interesting idea.

How do you view it in the console though? I thought you had to 'manually' parse the detailed bill Amazon dumps into an S3 bucket.

**Comment by berezovskyi** [comment]
Like this?

![image](https://cloud.githubusercontent.com/assets/64734/13103424/a6cecd72-d556-11e5-905b-b5dce19685a5.png)

**Comment by Miserlou** [comment]
Ah, well there you go.

**Comment by Miserlou** [comment]
Ahhhh, that's right, I remember why I wrote django-aws-billing now - we were using to bill our own customers based on resource consumption. That's well outside the scope of Zappa.
