### ISSUE TITLE
zappa manage doesn't accept parameter "-s" SETTINGS_FILE

### ISSUE THREAD

**Issue by davesave** [Miserlou/Zappa#1002]
Hi,

can you please add "SETTINGS_FILE" parameter to zappa manage command ?

**Comment by Miserlou** [comment]
Should work? If not, PR welcome..

**Comment by drewpc** [comment]
@Miserlou It doesn't work because the `zappa manage` command is the only sub command that doesn't inherit from [`env_parser`](https://github.com/Miserlou/Zappa/blob/master/zappa/cli.py#L304-L307).  I submitted a PR with a trivial fix for this.
