### ISSUE TITLE
keepwarm can create duplicate schedules

### ISSUE THREAD

**Issue by collingreen** [Miserlou/Zappa#101]
I don't have an exact repro for this but I was messing around trying to get something scheduled and ended up maxing out the events on my lambda function (causing this error: `An error occurred (LimitExceededException) when calling the PutTargets operation: The requested resource exceeds the maximum number allowed.`). When I checked the console, I had duplicates of the zappa keep warm event, which I had to manually delete before I could schedule something new.

**Comment by Miserlou** [comment]
Duplicates for the same function? Is this on -master?

**Comment by collingreen** [comment]
Yes and yes. I still need to make a repro though.

**Comment by Miserlou** [comment]
Looking at the code, I'd be surprised if this is still happening, but please try to reproduce if you can. I haven't been able to repro myself.

**Comment by collingreen** [comment]
This is on version 0.17.6 (a recent branch, but not old -- 5eb4e0ff1b1eecbcb8ac2b6f78f0ecbdce681dbe).

zappa_settings.json
```
{
    "dev": {
       "s3_bucket": "bucket-name",
       "app_function": "app.app",
       "http_methods": ["GET"],
       "parameter_route": 1,
       "events": [{
           "function": "app.name_of_relevant_function",
           "expression": "cron(0 0 * * * *)"
       }]
    }
}
```

I deleted all my event sources in the lambda console, then call:

`lambda schedule dev`

resulting in this error:

> An error occurred (LimitExceededException) when calling the PutTargets operation: The requested resource exceeds the maximum number allowed.

This created an event in lambda event sources named `Scheduled Event: zappa-keep-warm`.

Calling `lambda schedule dev` again creates another one (and raises the same error again).

<img width="939" alt="screen shot 2016-05-24 at 10 04 50 pm" src="https://cloud.githubusercontent.com/assets/5257160/15528750/cf382122-21fb-11e6-9649-76626c39e0a3.png">

**Comment by Miserlou** [comment]
0.18.0 published, this should be fixed.
