### ISSUE TITLE
zappa and swagger codegen

### ISSUE THREAD

**Issue by ctippur** [Miserlou/Zappa#1019]
# Summary
I am trying to use design first paradigm to deploy my app to aws. I have a swagger doc, through which I have generated a flask server code (tested it).
I want to take the flask code and feed it to zappa for aws api deployment.
This is all new to me. Since swagger codegen generates a mvc based code, how do I feed it to zappa?

# Context
This is not a bug. Just a question.

## Your Environment

* Zappa version used: 0.43.1
* Operating System and Python version: MacOS, 3.4
* The output of `pip freeze`:
aws-requests-auth==0.3.3
bash==0.3.1
beautifulsoup4==4.4.0
boto3==1.4.3
botocore==1.4.91
certifi==2017.4.17
chardet==3.0.4
click==6.7
clickclick==1.2.2
connexion==1.1.9
cx-Oracle==5.1.3
decorator==3.4.2
decorators==0.1
defusedxml==0.4.1
dj-database-url==0.2.0
Django==1.10
django-allauth==0.19.1
django-bootstrap-form==3.2
django-bootstrap-forms==0.1
django-bootstrap3==6.1.0
django-braces==1.4.0
django-cors-headers==1.0.0
django-custom-user==0.5
django-debug-toolbar==1.3.2
django-oauth-toolkit==0.9.0
django-oauth2-provider==0.2.6.1
django-password-reset==0.7
django-registration-redux==1.2
django-rest-auth==0.3.4
django-rest-swagger==0.3.4
django-tastypie==0.12.1
django-transaction-hooks==0.2
Django-transactional==0.6.1
django-transactional-cleanup==0.1.14
django-uuidfield==0.5.0
django-uuidfield-2==0.6.6
djangorestframework==3.3.1
djangorestframework-recursive==0.1.1
docutils==0.13.1
enum34==1.0.4
Flask==0.12.2
Flask-Cors==3.0.3
geocoder==1.20.0
geopy==1.11.0
httpie==0.9.2
httplib2==0.9.2
idna==2.5
inflection==0.3.1
itsdangerous==0.24
Jinja2==2.9.6
jmespath==0.9.0
json2html==0.3
jsonpickle==0.9.2
jsonschema==2.6.0
kafka-python==0.9.4
lucene-querybuilder==0.2
lxml==3.4.4
Markdown==2.2.0
MarkupSafe==1.0
neo4django==0.1.8
neo4jrestclient==2.1.0
numpy==1.10.2
oauth2==1.9.0.post1
oauthlib==1.0.1
ordereddict==1.1
Pillow==3.1.1
psycopg2==2.4.5
py2neo==2.0.7
Pygments==1.5
PyJWT==1.1.0
python-dateutil==2.6.0
python-mimeparse==0.1.4
python-social-auth==0.2.7
python3-openid==3.0.5
PyYAML==3.11
ratelim==0.1.6
requests==2.18.2
requests-oauthlib==0.4.2
s3transfer==0.1.10
shortuuid==0.4.2
six==1.9.0
slumber==0.7.1
sqlparse==0.1.16
swagger-spec-validator==2.1.0
Twisted==15.2.1
typing==3.6.1
urllib2-file==0.2.1
urllib2-prior-auth==0.2.0
urllib3==1.22
urllib5==5.0.0
Werkzeug==0.12.2
wikipedia==1.4.0
Yowsup==0.2
zope.interface==4.1.2
* Link to your project (optional):
* Your `zappa_settings.py`: 
{
    "dev": {
        "app_function": "test_api.app", 
        "profile_name": "test", 
        "s3_bucket": "zappa-sy432524"
    }
}

**Comment by ctippur** [comment]
Any takers pls?

**Comment by Miserlou** [comment]
What's the problem?

**Comment by ctippur** [comment]
Rich,

I have code generated via swagger codegen. This gets generated with a specific folder structure with models/ controllers. 
The question is how to port this structure to Zappa?

-S

**Comment by Miserlou** [comment]
Sorry, I need more specific information about what you are doing. You should also probably try experimenting on your own for your own needs. 

Closing this as a non-issue, you may want to join the Slack channel for discussion, put please remember the community isn't a forum just for free support.

**Comment by trickidicki** [comment]
I think this is an issue with Connexion, not Zappa.
