### ISSUE TITLE
Botocore version

### ISSUE THREAD

**Issue by carterthayer** [Miserlou/Zappa#1021]
Botocore version is too low to be compatible with [PyAthena](https://github.com/laughingman7743/PyAthena/).

## Context
I am trying to create an API deployed with Zappa that uses [PyAthena](https://github.com/laughingman7743/PyAthena/) to connect to the database.

## Expected Behavior
Both Zappa and PyAthena should be usable in the same virtual environment.

## Actual Behavior
If `botocore==1.5.40` (from Zappa) is installed, PyAthena will throw an `pkg_resources.VersionConflict` (when used, PyAthena will raise the exception simply on import) , the same will happen from running Zappa under `botocore>=1.5.52` as required by PyAthena.

## Possible Fix
Update botocore requirement to a more recent version.

## Steps to Reproduce
Using Python3 in a virtual environment, install Zappa and then PyAthena. Since PyAthena requires a higher version, a `zappa init` will throw a `pkg_resources.VersionConflict`.

## Your Environment
```
argcomplete==1.8.2
base58==0.2.4
boto3==1.4.4
botocore==1.5.90
certifi==2017.7.27.1
chardet==3.0.4
click==6.7
docutils==0.13.1
durationpy==0.4
future==0.16.0
futures==3.1.1
hjson==2.0.7
idna==2.5
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.16.1
monotonic==1.3
placebo==0.8.1
PyAthena==1.0.3
python-dateutil==2.6.1
python-slugify==1.2.4
PyYAML==3.12
requests==2.18.2
s3transfer==0.1.10
six==1.10.0
tenacity==4.4.0
toml==0.9.2
tqdm==4.14.0
troposphere==1.9.5
Unidecode==0.4.21
urllib3==1.22
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.43.1
```

**Comment by Miserlou** [comment]
Have you tried manually bumping boto?

**Comment by lggwettmann** [comment]
Same with AWS CLI.
