### ISSUE TITLE
Feature Proposal: zappa domain

### ISSUE THREAD

**Issue by kienpham2000** [Miserlou/Zappa#103]
While working through the instruction on how to create custom domain with Let's Encrypt, I think an automatic solution would be nice. 

awscli already has most of these covered here, probably a wrapper around it? 
http://docs.aws.amazon.com/cli/latest/reference/apigateway/create-domain-name.html

I'm proposing: 
`zappa domain mysub.example.com --provider=letsencrypt` will create the custom domain name

**Comment by Miserlou** [comment]
Ah, that's good, I think that is a new ability in the CLI. I'm into this idea.

I have been holding off on doing more domain stuff until they get their own free SSL stuff integrated with API Gateway, at which point we can drop the need for LE.

**Comment by Miserlou** [comment]
This is essentially implemented now with the `zappa certify` command.
