### ISSUE TITLE
Zappa deployment says successful, but always gives Error loading pysqlite2 or sqlite3

### ISSUE THREAD

**Issue by theochit** [Miserlou/Zappa#1032]
## Context
I'm trying to deploy a sample Django app in Zappa with python 3.6 on Windows 10. I have tried a couple different methods (following GunIO's youtube video, following the readme) which boil down to: create/run a virtual environment, install Django and Zappa, run Zappa init, and finally zappa deploy dev. My AWS account is correctly connected and Zappa init successfully creates s3 buckets for me. 

## Actual Behavior
So, each time I have done this process, deploy says it is successful, and gives me the link to my deployment. Every time, the link has a page which gives the following error report: 
`"{'message': 'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.', 'traceback': ['Traceback (most recent call last):\\n', '  File \"/var/task/handler.py\", line 434, in handler\\n    response = Response.from_app(self.wsgi_app, environ)\\n', '  File \"/var/task/werkzeug/wrappers.py\", line 903, in from_app\\n    return cls(*_run_wsgi_app(app, environ, buffered))\\n', '  File \"/var/task/werkzeug/wrappers.py\", line 57, in _run_wsgi_app\\n    return _run_wsgi_app(*args)\\n', '  File \"/var/task/werkzeug/test.py\", line 884, in run_wsgi_app\\n    app_rv = app(environ, start_response)\\n', \"TypeError: 'NoneType' object is not callable\\n\"]}"`

When I run `zappa tail` I get a long list, but here is the seemingly important part:
`[1501796081507] Instancing..
[1501796081508] Instancing..
[1501796083859] Error loading either pysqlite2 or sqlite3 modules (tried in that order): No module named '_sqlite3': ImproperlyConfigured
Traceback (most recent call last):
  File "/var/task/handler.py", line 491, in lambda_handler`

It gives this same error a few times throughout the tail report. As you probably know, this should be part of Python 3 so I can't use pip to install these packages.

## Possible Fix
My guess is that it has something to do with Python 3, but it seems like other people are able to use Python 3 just fine. 

I found an answer somewhere else that said I need to go to settings.py and include `zappa` in INSTALLED_APPS and ` zappa.middleware.ZappaMiddleware` in MIDDLEWARE_CLASSES, but that just broke the app altogether. including zappa worked, but I get errors saying `Error importing module: 'Module "zappa.middleware" does not define a "ZappaMiddleware" attribute/class'` and I have gotten `No module named zappa.middleware` as well.

## Steps to Reproduce

1. Install python 3.6.1
2. make a virtualenv and run it
3. pip install django zappa
4. zappa init
5. zappa deploy dev

## Your Environment

* Zappa version used: Newest as of today
* Operating System and Python version: Windows 10, Pyhon 3.6.1
* The output of `pip freeze`: 
`argcomplete==1.8.2
base58==0.2.4
boto3==1.4.4
botocore==1.5.40
certifi==2017.7.27.1
chardet==3.0.4
click==6.7
Django==1.11.4
docutils==0.14
durationpy==0.4
future==0.16.0
futures==3.1.1
hjson==2.0.7
idna==2.5
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.16.1
placebo==0.8.1
python-dateutil==2.6.1
python-slugify==1.2.4
pytz==2017.2
PyYAML==3.12
requests==2.18.3
s3transfer==0.1.10
six==1.10.0
toml==0.9.2
tqdm==4.14.0
troposphere==1.9.5
Unidecode==0.4.21
urllib3==1.22
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.43.1`
* Link to your project (optional):
* Your `zappa_settings.json`: (this template originally said zappa_settings.py but I get a json file) 
{
    "dev": {
        "aws_region": "us-west-2",
        "django_settings": "my_no_server.settings",
        "profile_name": "theo",
        "s3_bucket": "zappa-noserver-tap2"
    }
} 

Thank you for your time!

**Comment by theochit** [comment]
still having this problem... is anyone out there?

**Comment by nikbora** [comment]
Do you have to use Python 3.6? And if so do you have to use sqllite3 for Django DB engine? (which kinda makes no sense with Lambda anyways?). See: https://stackoverflow.com/a/44076628

**Comment by theochit** [comment]
Yes I do need Python 3 unfortunately, but maybe not 3.6 necessarily. I just tried on my other machine (barely works, almost forgot I had it) which has python 2.7 and it worked without an issue, so I'm not doing anything dumb in my setup.

I don't need sqllite3 for my DB engine.  Should I be using RDS? The webapp I ultimately want to deploy will output some XML files so I need some sort of DB but I am pretty new so correct me if I'm wrong about that.

**Comment by nikbora** [comment]
No worries. So you have to use 3.6 or 2.7 on Lambda, no other versions. In
terms of DB, RDS Postgres or MySql are your best options. Or if you don't
need DB and are just doing some other XML manipulation then a basic Flask
app without a DB would also work. This however is not a Zappa issues per se
so can probably be closed.

**Comment by theochit** [comment]
Thank you!! Modified it for postgresql and it's working now.

**Comment by ceefour** [comment]
I also got hit by this. (Anaconda4, Windows 10, Python3.6)

While I'll also be using postgresql, I'd like to know exactly why is this happening?

**Comment by rajkunkolienkar** [comment]
The issue is with Amazon AMI instances, not with Zappa / Chalice.

['sqlite3 error on AWS lambda with Python 3'](https://stackoverflow.com/questions/44058239/sqlite3-error-on-aws-lambda-with-python-3)
