### ISSUE TITLE
Feature Request: zappa tail --color

### ISSUE THREAD

**Issue by pjf** [Miserlou/Zappa#1038]
When piping tail output to a command, `zappa tail` automatically engages the `--no-color` option. This is usually what the user wants, but some users (ie: me) would love to enforce coloured output even if we're using pipes.

It would be amazing to have a `zappa tail --color` option that forces coloured output, regardless or what the default may otherwise have been.

Many thanks again for an *incredible* tool!

**Comment by zaraken** [comment]
https://github.com/zaraken/Zappa/tree/z-tail-force-color
Tested with python 3.6
Feel free to review, test and give feedback if anything isn't as it should be.

**Comment by Miserlou** [comment]
@zaraken - please send this as a Pull Request!

**Comment by zaraken** [comment]
https://github.com/Miserlou/Zappa/pull/1039
