### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by dperconti** [Miserlou/Zappa#1066]
Attempting to install and use zappa from a basic django application. I must be missing something, because I'm really not sure what's supposed to go in the `app_function` file. Is that auto-generated? Should the contents be the same as the wsgi file or something? I can't find any information on that at all. 

## Context
Simple and first time installation of zappa into vanilla django app

## Steps to Reproduce

1. Create Django app
2. install zappa
3. Attempt to deploy app

## Your Environment

```
$ python --version
Python 2.7.11
```

```
$ pip freeze
argcomplete==1.8.2
base58==0.2.4
boto3==1.4.5
botocore==1.5.40
certifi==2017.7.27.1
chardet==3.0.4
click==6.7
Django==1.11.3
django-rest-auth==0.9.1
django-taggit==0.22.1
djangorestframework==3.6.4
docutils==0.14
durationpy==0.5
future==0.16.0
futures==3.1.1
hjson==3.0.0
idna==2.6
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.16.1
placebo==0.8.1
python-dateutil==2.6.1
python-slugify==1.2.4
pytz==2017.2
PyYAML==3.12
requests==2.18.4
s3transfer==0.1.10
six==1.10.0
toml==0.9.2
tqdm==4.15.0
troposphere==1.9.5
Unidecode==0.4.21
urllib3==1.22
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.43.2
```

```
$ cat zappa_settings.json
{
    "dev": {
        "app_function": "tm.app",
        "aws_region": "us-west-2",
        "profile_name": "default",
        "s3_bucket": "trunkmatch-dev",
        "manage_roles": true, // Disable Zappa client managing roles.
        "role_name": "trunkmatch-dev-ZappaExecutionRole", // Name of your Zappa execution role. Default <project_name>-<env>-ZappaExecutionRole.
    }
}
```

## Deployment

```
$ zappa update dev
Calling update for stage dev..
Downloading and installing dependencies..
Packaging project as zip.
Uploading trunkmatch-web-dev-1503555130.zip (36.7MiB)..
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 38.5M/38.5M [00:16<00:00, 2.00MB/s]
Updating Lambda function code..
Updating Lambda function configuration..
Uploading trunkmatch-web-dev-template-1503555229.json (1.6KiB)..
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.62K/1.62K [00:00<00:00, 6.79KB/s]
Deploying API Gateway..
Scheduling..
Unscheduled trunkmatch-web-dev-zappa-keep-warm-handler.keep_warm_callback.
Scheduled trunkmatch-web-dev-zappa-keep-warm-handler.keep_warm_callback with expression rate(4 minutes)!
Your updated Zappa deployment is live!: https://2h0l38ky39.execute-api.us-west-2.amazonaws.com/dev
```

## Resulting error:

"{u'message': u'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.', u'traceback': ['Traceback (most recent call last):\\n', '  File \"/var/task/handler.py\", line 448, in handler\\n    response = Response.from_app(self.wsgi_app, environ)\\n', '  File \"/private/var/folders/57/dg7hsg513cj0k4yvzpmzk3840000gn/T/pip-build-sbSBw8/Werkzeug/werkzeug/wrappers.py\", line 903, in from_app\\n', '  File \"/private/var/folders/57/dg7hsg513cj0k4yvzpmzk3840000gn/T/pip-build-sbSBw8/Werkzeug/werkzeug/test.py\", line 884, in run_wsgi_app\\n', \"TypeError: 'NoneType' object is not callable\\n\"]}"

# What I've tried:
Setting `app_function` to numerous files, settings, and created "app" files, including:
1. wsgi file
2. settings.py
3. copy of manage.py
4. etc...

I think the problem is simply that I don't know what is supposed to be in the `app_function: "something.app"` file. There doesn't seem to be any documentation on that so any help is appreciated.

**Comment by jeroenleenarts** [comment]
Did you deploy and then add the hostname to your ALLOWED_HOSTS and then ran `zappa update`?

**Comment by dperconti** [comment]
Yes, updated `ALLOWED_HOSTS` with no luck. Going to try running `$ zappa tail` and working backwards to see what I can find.

**Comment by Miserlou** [comment]
Please read the install instructions: https://github.com/Miserlou/Zappa#installation-and-configuration

Django applications use the `django_settings` key rather than `app_function`.

**Comment by nickday** [comment]
I had the same issue - the error in my case was that my Django project and the virtualenv were the same name (there was a warning about this during `zappa init` which I missed).

**Comment by variable** [comment]
@dperconti have you fixed your problem? I am having the same issue...

**Comment by dperconti** [comment]
@variable Yes, I basically had to start fresh. Even after making changes based on @Miserlou's [suggestion](https://github.com/Miserlou/Zappa/issues/1066#issuecomment-324680904) of using the django_settings key rather than app_function I still had issues. I ended up just following @edgarroman's [guide here](https://edgarroman.github.io/zappa-django-guide/) line by line and got things working.
