### ISSUE TITLE
Feature request: specify endpoint_url to clients (for testing with e.g. localstack)

### ISSUE THREAD

**Issue by pjz** [Miserlou/Zappa#1068]
## Context
I'd like to be able to test my Zappa deploys up against various AWS-emulators or AWS-alikes - for instance [localstack](https://github.com/localstack/localstack).  To do so, there needs to be a way to specify the `endpoint_url` to all the calls to `boto_session.client()`.  

Note that this is more for testing systems than individual deploys: For instance, producer/consumer lambdas each on the end of SQS or SNS.

## Expected Behavior

I need a way to specify the `endpoint_url` to run against localstack for testing.  

## Actual Behavior

Can't do anything like it :(

## Possible Fix

I'd suggest putting the setting in `zappa_settings.json`.  I could then make a 'local' target just like the normal 'dev' and 'production' targets.

**Comment by Miserlou** [comment]
Is this something that can be configured during boto session setup, or does it need to be included for every boto call? Good feature, would accept PR happily.

Suggest `aws_endpoint_url` for the setting key.

**Comment by pjz** [comment]
It's the `endpoint_url` argument to the botocore `Session.client` call (documented [here](https://boto3.readthedocs.io/en/latest/reference/core/session.html?highlight=botocore.client.Config#boto3.session.Session.client)).

So... not Session setup, but Client setup.

**Comment by pjz** [comment]
and actually... ugh. Every client potentially needs a different endpoint.

**Comment by pjz** [comment]
How about a dict?  aws_endpoint_urls: { servicename: url } ?  so like:
```
    ...
    'aws_endpoint_urls': {
        's3': 'http://localhost:1234',
        'lambda': 'http://localhost:1235',
        ...
    }
    ...

```

**Comment by Miserlou** [comment]
Makes sense

**Comment by pjz** [comment]
Fixed the PR; what do you think?

**Comment by Miserlou** [comment]
Looks functionally good but stylistically, it needs explanatory docstrings, no `_` and no single-character variable names, per contributing guide, then I can merge. 👍 thanks!

**Comment by kingbuzzman** [comment]
@pjz Can i see your zappa.json to use as a template to setup localstack?

**Comment by j6k4m8** [comment]
for those who are looking for a zappa config example, I believe these are all of the services (and the correct names) for `localstack` compatibility:

```json
"aws_endpoint_urls": {
    "s3": "http://localhost:4566",
    "lambda": "http://localhost:4566",
    "apigateway": "http://localhost:4566",
    "iam": "http://localhost:4566",
    "cloudwatch": "http://localhost:4566",
    "acm": "http://localhost:4566",
    "logs": "http://localhost:4566",
    "route53": "http://localhost:4566",
    "sns": "http://localhost:4566",
    "sqs": "http://localhost:4566",
    "cloudformation": "http://localhost:4566",
    "dynamodb": "http://localhost:4566",
    "events": "http://localhost:4566"
}
```
