### ISSUE TITLE
module initialization error: Attempted relative import in non-package

### ISSUE THREAD

**Issue by kienpham2000** [Miserlou/Zappa#107]
Latest master is having this error when I deploy the same app. It works on using the pypi package. 

```
[1464069487659] module initialization error: Attempted relative import in non-package
```

**Comment by mathieu1** [comment]
I had this when installing using `pip install -e`. Installing using `pip install` worked.

**Comment by Miserlou** [comment]
Gonna need a bit more information that that, unfortunately I can't reproduce with just that.

**Comment by kienpham2000** [comment]
@mathieu1 you are right, without `-e` it works fine. I like to use latest master to be on edge. Thanks.

**Comment by Miserlou** [comment]
I'm not sure about -e.

I either use 

pip install zappa 

for the latest stable, or 

ln -s ~/Projects/Zappa/lib/Zappa/zappa zappa

for devving.

**Comment by joaovcarvalho** [comment]
I had the same issue but after installing zappa in the virtualenv it worked.
