### ISSUE TITLE
Confusing documentation about API key

### ISSUE THREAD

**Issue by alfonsomhc** [Miserlou/Zappa#1073]
## Context
I started using Zappa yesterday and I was amazed by how quickly I could take my Flask application and deploy it as a Lambda + Gateway API solution. It didn't take more than two hours! My next step was to add a layer of security and I chose to set up an API key. I got stuck with this and getting it to work required 4-5 hours.

## Expected Behavior

This is the current documentation for the API key:

> You can use the api_key_required setting to generate and assign an API key to all the routes of your API Gateway. After redeployment, you can then pass the provided key as a header called x-api-key to access the restricted endpoints. Without the x-api-key header, you will receive a 403. You'll also need to manually associate this API key with your usage plan in the AWS console. More information on API keys in the API Gateway.

Strictly speaking what the documentation says is true, and all information is there. However, as I user I don't think it reflects the process that I had to follow. When the user reads that (or at least when I did) one assumes that the process is as follows: 

a) Set api_key_required = true
b) Deploy/redeploy
c) Copy xxx from "Created a new x-api-key: xxx"
d) Send a request where you include the key xxx
e) You get the expected answer from the service

## Actual Behavior
This was the actual process for me:
a) Set api_key_required = true
b) Maybe I can just do `zappa update `? It fails (see #724 ), why? Ah true documentation actually tells you that update just updates the code, ok, then I will just...
c) Deploy/Redeploy the solution
d) I send a request with the key that I got. Wait, how I do that?
e) After some googling I find that I should use `curl --header "x-api-key: xxx"`
f) I send the request and I get a Forbidden error! Why, oh, why? 
g) After I check the setup in Amazon API Gateway, I find that xxx is actually the key id, not the value!
h) I send a new request with the right value for the key. I still get a Forbidden error!! Why!?
i) I double and tripple check that I'm in fact sending the request correctly. I double and tripple check that I'm not missing anything from the setup created in Amazon Lambda and Amazon API Gateway. However, I'm still getting the error. WHY!?
j) I search for related issues and I find #390 . The way I understand it is that if you are using Usage Plans, then something is going to go wrong. However, I'm don't know what Usage Plans are and the solution was working before I added key security. Then I shouldn't have to worry about this, right? Wait, where have I seen this "usage plans" before? It sounds familiar when I think about it...
k) More googling, read AWS documentation, re-read Zappa documentation (the last part of the quote above): "You'll also need to manually associate this API key with your usage plan in the AWS console.". Maybe they mean that you need to do something about the Usage Plan BEFORE I send requests? I need to try this...
l) I go to AWS console and create a new Usage Plan, connected the API and API Key that Zappa had created.
m) Send a new request and....it works!

## Possible Fix
I suggest to update the documentation as follows:

> You can use the api_key_required setting to generate an API key to all the routes of your API Gateway. The process is as follows:
> 1) Deploy/redeploy (update won't work) and write down the id for the key that has been created
> 2) Go to AWS console > Amazon API Gateway and 
>   a) select "API Keys" and find the key value
>   b) select "Usage Plans", create a new usage plan and link the API Key and the API that Zappa has created
> 3) Send a request where you pass the key *value* as a header called x-api-key to access the restricted endpoints. Note that without the x-api-key header, you will receive a 403.

**Comment by Miserlou** [comment]
Sorry for the inconvenience! This looks like a great solution, do you want to send a PR with those changes? It'd also be great if you could include the tip about `curl`. Thanks!

**Comment by alfonsomhc** [comment]
@Miserlou , thanks for your answer. Zappa has probably saved me weeks of work, so struggling a few hours with this issue is no problem. I'm happy to help, I will of course make the PR.

**Comment by Miserlou** [comment]
Fixed via merge, I think. Thanks!

**Comment by dragosLeahu** [comment]
The only fix I could find!!!!
