### ISSUE TITLE
Output swagger file and other AWS settings

### ISSUE THREAD

**Issue by glassresistor** [Miserlou/Zappa#1086]
## Context

I'm using Ansible to manage all of my other resources and plan on using it to wrap zappa to build our application servers.  I'd like to use zappa package to build the zip file but to use Ansible to manage the api gateway, dns, and ssl.

This will allow me to do more custom work and tune the behavior to our exact needs.  It would be really helpful if I could get zappa to output the swagger file and any other settings or configurations that would be helpful.

Some I would use zappa to generate with ansible and set with Ansible and some I would copyso out as static files, edit and then save them in my repo.  

Also if theres any deeper documentation about configuring the api gateway that would be fabulous.

**Comment by Miserlou** [comment]
Have you looked at the `zappa template` command?

**Comment by glassresistor** [comment]
Now i have thanks again
