### ISSUE TITLE
Add support for Lambda@Edge to support multi-region redundancy

### ISSUE THREAD

**Issue by dgonzo** [Miserlou/Zappa#1096]
Currently, it is not possible to put an A (alias) in front a [redundant multi-region deploy of lambda with api-gateway](https://forums.aws.amazon.com/thread.jspa?threadID=234312&start=0&tstart=0).

## Context
Ideally, CloudFront would be able to handle this, and some of the responses from AWS indicate that a fix is forthcoming. However, as of Sept 2017 using Rout53 A (alias) plus weighting will not resolve a custom domain name in API-gateway.

## Expected Behavior
Using the "global" configuration parameter or a new "edge" parameter would provision Lambda@Edge on available regions.

## Actual Behavior
Using the "global" configuration parameter creates separate lambda deployments for all regions; e.g. us-east-1-dev, us-east-2-dev, etc., etc.

## Possible Fix
There appears to be a hack using Lambda@Edge, which has been implemented at some level in serverless using a [plugin](https://github.com/silvermine/serverless-plugin-cloudfront-lambda-edge).

**Comment by Miserlou** [comment]
That sounds like a nice idea, but last time I checked, L@E doesn't support Python!

**Comment by dgonzo** [comment]
That does appear to be the case. I may implement a patch that uses a generic passthrough in node. If it works I'll share it back here.

**Comment by danielstockton** [comment]
L@Edge now support Python
