### ISSUE TITLE
Sckikit learn leads to Numpy ImportError

### ISSUE THREAD

**Issue by alfonsomhc** [Miserlou/Zappa#1108]
## Context
I have a working application that uses pandas and numpy (I can deploy it and it answers correctly curl requests). At some point I want to use scikit-learn in my application, so I pip install it in the virtual environment. However, after deploying I get errors (see below) when sending curl requests. This is weird because:
- The application doesn't actually use scikit-learn
- If I run the application locally, it works fine

## Expected Behavior
Installing scikit-learn in the same virtual environment should not impact the application

## Actual Behavior
When I send a curl request, I get this error:

```
[1505742412060] Missing required dependencies ['numpy']: ImportError
Traceback (most recent call last):
  File "/var/task/handler.py", line 505, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 239, in lambda_handler
  handler = cls()
  File "/var/task/handler.py", line 131, in __init__
  self.app_module = importlib.import_module(self.settings.APP_MODULE)
  File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/tmp/channel-recomme/channel_recommender/webapp/webapp.py", line 26, in <module>
  recommender = service_loader()
  File "/tmp/channel-recomme/channel_recommender/recommender/loader.py", line 23, in service_loader
  recommender = load_s3(recommender_filename, s3_bucket)
  File "/tmp/channel-recomme/trantor/aws/s3.py", line 55, in load_s3
  return pickle.loads(x)
  File "/tmp/channel-recomme/pandas/__init__.py", line 19, in <module>
  "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']
```

## Steps to Reproduce

1. I have an application that uses pandas. In the virtual environment I have pandas and numpy. I set `use_precompiled_packages` to true. I can deploy and it works fine. 
2. Pip install scipy in the virtual environment. I deploy the application (no changes in the code) and it stills works fine.
3. Pip install scikit-learn. The application works normally locally (as in the previous steps). However, after I deploy (no changes in the code), it doesn't answer to curl requests (unlike in the previous steps). I get the error above instead.

Notes:
- I have tried deleting the cached manylinux whl packages (numpy, scipy and pandas), but this doesnt change anything
- The error that I get is exactly the same as if I deployed my application with the initial virtual environment (no scipy, no scikit-learn) and set `use_precompiled_packages` to false

## Your Environment
* Zappa version used: latest (I installed the latest version today after the merge https://github.com/Miserlou/Zappa/pull/1107)
* Operating System and Python version: Ubuntu, Python 3.6.2
* The output of `pip freeze`:
boto3==1.4.7
botocore==1.7.2
click==6.7
docutils==0.14
Flask==0.12.2
itsdangerous==0.24
Jinja2==2.9.6
jmespath==0.9.3
MarkupSafe==1.0
numpy==1.13.1
pandas==0.20.3
python-dateutil==2.6.1
pytz==2017.2
s3transfer==0.1.11
scikit-learn==0.18.1
scipy==0.19.1
six==1.10.0
Werkzeug==0.12.2

* Your `zappa_settings.py`: 
{
    "dev": {
        "app_function": "project.webapp.webapp.app",
        "aws_region": "eu-west-1",
        "profile_name": "default",
        "s3_bucket": "project-dev",
        "slim_handler": true,
        "use_precompiled_packages": true,
        "api_key_required": false,
        "memory_size": 128
    },
    "production": {
        "app_function": "project.webapp.webapp.app",
        "aws_region": "eu-west-1",
        "profile_name": "default",
        "s3_bucket": "project-production",
        "slim_handler": true,
        "use_precompiled_packages": true,
        "api_key_required": true,
        "memory_size": 128
    }
}

**Comment by Miserlou** [comment]
Related? https://github.com/Miserlou/Zappa/issues/1104

**Comment by alfonsomhc** [comment]
@Miserlou , I wondered if this was related. As I wrote in "Steps to Reproduce", I have tried deleting the cached manylinux whl packages (numpy, scipy and pandas), but this doesnt change anything. Therefore, my guess is that it is not related, but I really don't know.

Is there a manylinux version of scikit learn? Zappa replaces numpy, scipy and pandas, but not scikit-learn...

**Comment by SongYunSeop** [comment]
Just package install, but not using?

**Comment by alfonsomhc** [comment]
@SongYunSeop , yes, just package install, not using it.

**Comment by alfonsomhc** [comment]
@Miserlou , I'm working on a minimum example that can show the error (or where I made a mistake, if that was the case). On the process I saw this:
```
Downloading and installing dependencies..
 - pandas==0.20.3: Downloading
100%|██████████████████████████████████████| 24.5M/24.5M [00:02<00:00, 9.58MB/s]
 - numpy==1.12.1: Downloading
HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=2)
Packaging project as gzipped tarball.
```
then I had a look at the whl files in the temp folder, and found that it resulted in an empty numpy package:
```
-rw-rw-r-- 1 alfonso alfonso        0 Sep 19 10:08 /tmp/cached_wheels/numpy-1.12.1-cp36m-manylinux1_x86_64.whl
-rw-rw-r-- 1 alfonso alfonso 24470422 Sep 19 10:08 /tmp/cached_wheels/pandas-0.20.3-cp36m-manylinux1_x86_64.whl
```
I think it would be a good idea to wait and try again if there is an error downloading the whl files...

**Comment by alfonsomhc** [comment]
Preparing this minimum example that can show the error, I was surprised that the numpy version that was getting included in the packaged project was not the one that was installed in the virtual environment. After some digging, I saw that `pip.get_installed_distributions()` returned libraries installed in my global environment (i.e. not the virtual environment that I use in the project). After some more digging, I see that the documentation tells you that zappa has to be installed in the virtual environment. I other new users could make the same mistake as me, so I would suggest that zappa checks that it is running from the project's virtual environment. I don't know how to do that, but hopefully there's some way of checking...

**Comment by alfonsomhc** [comment]
I can confirm that this is not a bug. I did this:
- Delete the previous virtual environment
- Create new virtual environment and activate it
- Install the latest zappa version and other packages that I need (e.g. numpy, pandas, scipy, scikitlearn) in the virtual environment
- Clean temp folders (/tmp/cached_pypi_info/ and /tmp/cached_wheels)
- Undeploy (`zappa undeploy dev`)
- Generate config file from scratch (`zappa init`)
- Redeploy (`zappa deploy dev`)

After that the project works correctly. There are probably many factors why things were not working two days ago:
- I was using zappa from a global environment, so the list of installed libraries didn't match the ones in the virtual environment
- Corrupted files in tmp folders
- Not sure about this, but I think that if you do `zappa update`, you need to wait a bit before your code is used by Lambda (i.e. if you do a curl request right after updating, the answer you get is from the cached application, not the updated one), but if you undeploy and deploy again, then the updated application is available right away.
