### ISSUE TITLE
Setting keep_warm: false after a default deployment leaves the old keep_warm_callback around

### ISSUE THREAD

**Issue by jleclanche** [Miserlou/Zappa#1119]
Zappa 0.44.3.

On default settings, `keep_warm` is set to true. If you do a `zappa deploy` with that, the keep_warm_callback will be created:

> Scheduling..
> Scheduled example-app-dev-zappa-keep-warm-handler.keep_warm_callback with expression rate(4 minutes)!

But then, setting `keep_warm` to false in the zappa settings will leave the callback lying around which can be confusing.

**Comment by Miserlou** [comment]
Yeah, this is the expected behavior. `deploy` will never remove event sources, only `unschedule` will do that. I know it's a little bit wonky.

**Comment by jleclanche** [comment]
@Miserlou Can this be either documented, or detected with a warning or something? This seems like a gotcha that a lot of people could hit without even knowing it.

**Comment by jleclanche** [comment]
(Either that or not setting keep_warm by default, YMMV on whether that's a good idea)

**Comment by Miserlou** [comment]
Add to doc

**Comment by jleclanche** [comment]
@Miserlou I just noticed that `unschedule` does not delete its matching [Cloudwatch Rules](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#rules:). Caveat to either fix or keep in mind.
