### ISSUE TITLE
Zappa Ignore File to keep unwanted files out of package

### ISSUE THREAD

**Issue by glassresistor** [Miserlou/Zappa#1122]
Currently I'm having to build my project and then do things like run collecstatic and compressor locally to publish static files and build the compressor CACHE folder.  Once that is done I don't need most of the static files or say my node_modules, all which get zipped by zappa package.

It would be great if I could include a zappaignore file which functions the same as gitignore but means those files are not included within the package.  I'm currently moving thing by hand but it would be more convenient if zappa could ignore them.

**Comment by Miserlou** [comment]
The `exclude` setting is supposed to account for this scenario. Any reason why that's not satisfactory?

**Comment by glassresistor** [comment]
Just that i didn't know it thanks!

**Comment by hustshawn** [comment]
So is there any ignore file can be used ?
