### ISSUE TITLE
Django - Existing repo with copy/pasted settings can't find environment variables

### ISSUE THREAD

**Issue by dperconti** [Miserlou/Zappa#1130]
## Context
This is probably something extremely simple, but I could use some help troubleshooting and fixing this. I have a django project that I wanted to start development on a different computer than the original computer where I started the project and initialized zappa. Because of this, I copied over the zappa settings into the new repository. From there I started the server as normal, but the environment variables were not able to be picked up.

 

## Expected Behavior
When starting the server (`python manage.py runserver`), the environment variables were working as expected. EG; I could use `is_local = os.environ.get('IS_LOCAL')` to obtain the value for the key `IS_LOCAL` in the zappa_settings.json file.

## Actual Behavior
The environment variables are not obtainable and resulting in the following error:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/donato/Documents/dev/personal/trunkmatch_main/trunkmatch-web/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/Users/donato/Documents/dev/personal/trunkmatch_main/trunkmatch-web/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 307, in execute
    settings.INSTALLED_APPS
  File "/Users/donato/Documents/dev/personal/trunkmatch_main/trunkmatch-web/env/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/Users/donato/Documents/dev/personal/trunkmatch_main/trunkmatch-web/env/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/donato/Documents/dev/personal/trunkmatch_main/trunkmatch-web/env/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/donato/Documents/dev/personal/trunkmatch_main/trunkmatch-web/trunkmatch/settings.py", line 28, in <module>
    DEBUG = eval(is_local)
TypeError: eval() arg 1 must be a string or code object
```

## Steps to Reproduce

1. Clone existing django project
2. Create and activate virtualenv
3. `zappa init`
4. replace zappa_settings.json with previous configurations
5. `python manage.py runserver`

## Your Environment
* Zappa version used: zappa==0.44.3
* Operating System and Python version: Python 2.7.11
* The output of `pip freeze`:

```
argcomplete==1.9.2
base58==0.2.4
boto==2.48.0
boto3==1.4.7
botocore==1.7.14
certifi==2017.7.27.1
chardet==3.0.4
click==6.7
Django==1.11.3
django-allauth==0.33.0
django-environ==0.4.4
django-rest-auth==0.9.1
django-storages==1.6.5
django-taggit==0.22.1
djangorestframework==3.6.4
docutils==0.14
durationpy==0.5
future==0.16.0
futures==3.1.1
hjson==3.0.0
idna==2.6
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.16.1
oauthlib==2.0.2
placebo==0.8.1
psycopg2==2.7.3
python-dateutil==2.6.1
python-openid==2.2.5
python-slugify==1.2.4
pytz==2017.2
PyYAML==3.12
requests==2.18.4
requests-oauthlib==0.8.0
s3transfer==0.1.11
six==1.11.0
toml==0.9.2
tqdm==4.15.0
troposphere==1.9.5
Unidecode==0.4.21
urllib3==1.22
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.44.3
```

* Your `zappa_settings.py`: 

```
{
    "dev": {
        "aws_region": "us-west-2", 
        "django_settings": "project.settings", 
        "profile_name": "default", 
        ...
        "environment_variables": {
            "IS_LOCAL": "False",
            ...
        }
    }
}
```

**Comment by nikbora** [comment]
Zappa doesn't really do anything when you just do `python manage.py runserver` locally, so its unlikely it would inject the environment variables. Is it possible that in the other project you had them in your local shell / environment separately? It should work as you expect it once deployed though.

**Comment by dperconti** [comment]
Hm... ok. it might have had a different environment then. Is there any way to run the project via zappa locally using those environment variables then?

**Comment by joer14** [comment]
I can't think of a natural way to ingest your `zappa_settings.json` config and use them to set your configs locally. I'd recommend you create a virtual environment and setup a postactivate file that sets those variables (which means having the variables specified twice - once in postactivate for dev purposes, and once in your `zappa_settings.json` config).

For future reference, you might get quicker responses for support questions like this on zappa slack.

**Comment by Miserlou** [comment]
Closing, right?

Maybe you want to do something like 

```python
if 'SERVERTYPE' in os.environ and os.environ['SERVERTYPE'] == 'AWS Lambda':
    import json
    import os
    json_data = open('zappa_settings.json')
    env_vars = json.load(json_data)['dev']['environment_variables']
    for key, val in env_vars.items():
        os.environ[key] = val
```
