### ISSUE TITLE
Issues with python-Levenshtein on OSX[we think]

### ISSUE THREAD

**Issue by glassresistor** [Miserlou/Zappa#1132]
Building projects which require python-Levenshtein on OSX causes issues.  When doing the same thing on a Debian system it works fine.

```
File "/var/task/Levenshtein/__init__.py", line 1, in <module>
   from Levenshtein import _levenshtein
ImportError: cannot import name '_levenshtein'
```
## Context
Python 3.6
Zappa versions 0.44 and 0.43
OSX 10.11.6

## Expected Behavior

Should be able to import Levenshtein into the project.  This error can be reproduced by having 

## Actual Behavior

Import error but only on OSX.

## Way to replicate
1.  add python-Levenshtein to requirements and install
2.  zappa deploy/update
3.  zappa invoke "import Levenshtein" 
4.  See failure on OSX but not Linux

## Your Environment

Zappa versions 0.44 and 0.43
OSX 10.11.6

* The output of `pip freeze`:
amqp==2.1.4
appnope==0.1.0
argcomplete==1.8.2
asn1crypto==0.23.0
awscli==1.11.160
base58==0.2.4
behave==1.2.5
behave-django==0.5.0
billiard==3.5.0.3
boto==2.48.0
boto3==1.4.5
botocore==1.5.40
celery==4.1.0
certifi==2017.7.27.1
cffi==1.11.0
chardet==3.0.4
click==6.7
colorama==0.3.7
cryptography==2.0.3
decorator==4.1.2
defusedxml==0.5.0
dj-database-url==0.4.2
Django==1.10.8
django-allauth==0.32.0
django-appconf==1.0.2
django-compressor==2.1.1
django-debug-toolbar==1.4
-e git://github.com/rossettistone/django-easy-audit.git@bf6c070e134fd557ffad0779b4b856afb555cf71#egg=django_easy_audit
django-extensions==1.9.1
-e git://github.com/bee-keeper/django-invitations@173524d7c462fbd6193421f67009f3d394c1a232#egg=django_invitations
django-jinja==2.4.0
django-storages==1.6.5
django-taggit==0.22.1
django-url-robots==2.0
djangorestframework==3.6.4
docutils==0.14
durationpy==0.5
factory-boy==2.9.2
fake-factory==0.7.2
Faker==0.8.4
future==0.16.0
futures==3.1.1
gunicorn==19.7.1
hjson==3.0.0
idna==2.6
ipdb==0.10.3
ipython==5.5.0
ipython-genutils==0.2.0
Jinja2==2.9.6
jmespath==0.9.3
kappa==0.6.0
kombu==4.1.0
lambda-packages==0.16.1
MarkupSafe==1.0
mixpanel==4.3.2
newrelic==2.70.0.51
oauthlib==2.0.4
olefile==0.44
parse==1.8.2
parse-type==0.4.2
pexpect==4.2.1
phonenumbers==8.8.0
pickleshare==0.7.4
Pillow==4.2.1
placebo==0.8.1
prompt-toolkit==1.0.15
psycopg2==2.7.3.1
ptyprocess==0.5.2
pyasn1==0.3.6
pycparser==2.18
Pygments==2.2.0
PyJWT==1.5.3
pyOpenSSL==17.3.0
PySocks==1.6.7
python-dateutil==2.6.1
python-http-client==1.2.3
python-Levenshtein==0.12.0
python-slugify==1.2.4
python3-openid==3.1.0
pytz==2016.10
PyYAML==3.12
rcssmin==1.0.6
reportlab==3.4.0
requests==2.18.4
requests-oauthlib==0.8.0
rjsmin==1.0.12
rsa==3.4.2
s3transfer==0.1.11
sendgrid==2.2.1
sendgrid-django==2.0.0
simplegeneric==0.8.1
six==1.10.0
smtpapi==0.3.1
sqlparse==0.2.3
toml==0.9.2
tqdm==4.15.0
traitlets==4.3.2
troposphere==1.9.6
twilio==6.1.0
ua-parser==0.7.3
Unidecode==0.4.21
urllib3==1.22
user-agents==1.1.0
vine==1.1.4
wcwidth==0.1.7
Werkzeug==0.12
whitenoise==3.3.1
wsgi-request-logger==0.4.6
zappa==0.43.2

* Your `zappa_settings.py`: 

```
{
    "development": {
        "aws_region": "us-east-1",
        "django_settings": "project.settings.development",
        "profile_name": "default",
        "s3_bucket": "cmr-development2-zappa",
	"environment_variables": {
	    "SECRET_KEY" :"secret key",
	    "TEST_USER_PASSWORD": "secret",
	    "DATABASE_HOST": "",
	    "DATABASE_PASSWORD": "",
	    "PURGED_DATABASE_HOST": "",
	    "PURGED_DATABASE_PASSWORD": "",
	    "AWS_ID": "",
	    "AWS_SECRET": "",
	    "BUCKET_NAME": ""
	}
    }
}
```

**Comment by glassresistor** [comment]
So it is in https://github.com/Miserlou/lambda-packages but when I run package it only its not listed during 

```
Downloading and installing dependencies..
 - reportlab==3.4.0: Using locally cached manylinux wheel
 - psycopg2==2.7.3.1: Using locally cached manylinux wheel
 - pillow==4.2.1: Using locally cached manylinux wheel
 - cryptography==2.0.3: Using locally cached manylinux wheel
 - cffi==1.10.0: Using locally cached manylinux wheel
```

So I think it just happens to work on Debian using the normal package but the OSX package isn't compatible.

Is the python-Levenshtein package 2.7 only?

**Comment by Miserlou** [comment]
Yes, you can see which packages are Py3-ready in the lambda-packages
manifest:
https://github.com/Miserlou/lambda-packages/blob/master/lambda_packages/__init__.py

**Comment by Miserlou** [comment]
Also, just out of curiosity - why that package? I've never used it before but it seems like a popular one? Geo/GIS-related?

**Comment by glassresistor** [comment]
I actually don't know.  Looking at the code is has something to do with calculating how much of something someone read is.

The __init__ file was the last piece for my understanding.  I have it working on lambda with the compiled build I have.  Should I try making a tar ball and doing a PR?

**Comment by glassresistor** [comment]
So looking at the `__init__` file psycopg2 is only listed with python2.7 but when it builds the package it still includes psycopg2 in list of dependencies.

I'm curious if I get Levenshtein working with lambda_packages will it then fail for psycopg2 on OSX because it will use the OSX binary?

Mainly trying to gauge how many packages I'll need to do.
