### ISSUE TITLE
"Failed to manage IAM roles" when using aws-vault 

### ISSUE THREAD

**Issue by jleclanche** [Miserlou/Zappa#1143]
I'm using aws-vault to generate temporary credentials.

Even when identifying as an administrator user with full access however, zappa gives me the error "Failed to manage IAM roles" upon deploy and update commands. `status` works fine however.

Any ideas?

PS: Using the non-temporary credentials for the same user works fine for `deploy`.

**Comment by Miserlou** [comment]
Never heard of `aws-vault`, no idea.

**Comment by jleclanche** [comment]
https://github.com/99designs/aws-vault This (I've been playing with it lately, I highly recommend trying it out if you haven't heard of it)

**Comment by Miserlou** [comment]
Going to close this as I don't think this is a Zappa related issue. Please let me know if you can diagnose anything more.

**Comment by jleclanche** [comment]
I'll look into it, but instinctively I highly doubt it's *not* a zappa issue. The rest of the commands work fine with temporary credentials,  but it fails on the one command.

**Comment by nicolastrres** [comment]
Hey @jleclanche, I'm using aws sts to generate temporary credentials as well, and I was facing a similar issue. Every time I was calling zappa update, I was getting the error "Failed to manage IAM roles". Looking to [this table](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_request.html#stsapi_comparison) I found out that I was using [GetSessionToken](http://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html) to generate the temporary credentials, but it has a limitation, you cannot call IAM APIs unless MFA information is included with the request. 
I found on the zappa readme [here](https://github.com/Miserlou/Zappa#using-custom-aws-iam-roles-and-policies) that you can do something like this:
```
{
    "dev": {
        ...
        "manage_roles": false, // Disable Zappa client managing roles.
        "role_name": "MyLambdaRole", // Name of your Zappa execution role. Default <project_name>-<env>-ZappaExecutionRole.
        ...
    },
    ...
}
```
By default, the Zappa client will create and manage the necessary IAM policies and roles to execute Zappa applications, with those lines you will manually manage your remote execution policies.

**Comment by nicolastrres** [comment]
Hey @jleclanche, I'm using aws sts to generate temporary credentials as well, and I was facing a similar issue. Every time I was calling zappa update, I was getting the error "**Failed to manage IAM roles**". Looking to [this table](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_request.html#stsapi_comparison) I found out that I was using [GetSessionToken](http://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html) to generate the temporary credentials, but it has a limitation, you cannot call IAM APIs unless MFA information is included with the request. 
I found on the zappa readme [here](https://github.com/Miserlou/Zappa#using-custom-aws-iam-roles-and-policies) that you can do something like this:
```
{
    "dev": {
        ...
        "manage_roles": false, // Disable Zappa client managing roles.
        "role_name": "MyLambdaRole", // Name of your Zappa execution role. Default <project_name>-<env>-ZappaExecutionRole.
        ...
    },
    ...
}
```
By default, the Zappa client will create and manage the necessary IAM policies and roles to execute Zappa applications, with those lines you will manually manage your remote execution policies.
But after those changes I was still getting an error `An error occurred (InvalidClientTokenId) when calling the GetRole operation`.
So I decided to change the approach and I created a Role, and I started using the [assumeRole](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html) to generate a temporary session token, and it worked.

**Comment by SoerenWeber** [comment]
I encountered the same problem when trying to use Zappa and aws-vault in combination. As @nicolastrres stated, temporary credentials that were created using [GetSessionToken](https://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html) will only have permission to make IAM API calls when MFA authentication was provided:
> You cannot call any IAM API operations unless MFA authentication information is included in the request.

Providing my [MFA identification number in `~/.aws/config`](https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#using-aws-iam-roles) solved the problem by gaining the missing permissions:

    mfa_serial = arn:aws:iam::123456789012:mfa/soeren
