### ISSUE TITLE
Help: Remote call zappa from outside project

### ISSUE THREAD

**Issue by ebertti** [Miserlou/Zappa#1144]
How can I call a remote call from another code, with and without zappa library?

1) I want to start a lambda made with zappa from a node project without using gatewayapi from aws;

    _Node -> SNS -> Zappa_

2) Another example is calling with boto3. Have some way to do it?

    _Python with Boto3 -> Async Call -> Zappa_

**Comment by jleclanche** [comment]
Zappa just deploys the Lambda. You can still manually add triggers for the lambda (start it via the aws sdk/api/boto/sns/s3 triggers/...).

**Comment by Miserlou** [comment]
Zappa also schedules the function triggers.

Closing this because I don't know what you're asking. Maybe join the Slack?
