### ISSUE TITLE
ACM certificates and deployments without Route53

### ISSUE THREAD

**Issue by jleclanche** [Miserlou/Zappa#1147]
Related: #1084 

If I want to deploy a site using Zappa that is:
- Using HTTPS
- With non-route53 DNS

It appears that is not supported at the moment, correct?

Now, for the Route53 side of things: I'm using Cloudflare for the dns on the domain I want to deploy to. If I don't use Route53 it looks like I won't be able to get rid of the stage name in the path, which is a fairly significant issue. Would there be a way to disable that?

HTTPS: Since Zappa was initially released, AWS added support for ACM certificates on the API gateway. This makes it much easier to manage long-term certificates, rather than go through Let's Encrypt (and it's still free). Is this something Zappa somehow supports?

I'm down to file pull requests and such for anything that isn't implemented, but I'd like some guidance on where to start and how to proceed first.

**Comment by TidyData** [comment]
Once I verified ownership with Amazon and possessed an ACM certificate I followed [connecting an ACM certificate with zappa](https://edgarroman.github.io/zappa-django-guide/walk_domain/#step-13-edit-the-zappa-settings-file), just ensure it is in the north virginia ACM location.

Did you succeed in removing the stage name of a [manual cloudfront](https://edgarroman.github.io/zappa-django-guide/walk_domain/#manage-your-own-cloudfront-distribution) using route53?

**Comment by jleclanche** [comment]
I didn't catch `certificate_arn`! That's great, I think it solves most of the issues.
Customizing the cloudfront distribution makes sense. I'm going to try out these options, thanks for the help.

@Miserlou The page linked here is super helpful, I think it'd be worth changing the readme to:
- Mention ACM support in the HTTPS section
- Mention the guide directly in the custom domain section.

**Comment by Miserlou** [comment]
This is already documented? https://github.com/Miserlou/Zappa#deploying-to-a-domain-with-aws-certificate-manager

If you have other changes, feel free to PR.

**Comment by jleclanche** [comment]
Wow, I totally missed that because it doesn't show up on ctrl+f "ACM" :(

**Comment by jleclanche** [comment]
Closing; this issue is nicely self-documenting and ACM was added to the readme.
