### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2339: ordinal not in range(128)

### ISSUE THREAD

**Issue by fompei** [Miserlou/Zappa#1151]
## Context
A framework that I'm trying to use requires Python 3.6 rather than Python 2.7
I've been using Anaconda virtual environment with Python 3.6 but it seems Zappa doesn't support Anaconda at the moment. I get an error when installing Zappa using virtualenv with Python 3.6.

I noticed in the README.md under **Installation and Configuration**,

> _Before you begin, make sure you are running Python 2.7 or Python 3.6 and you have a valid AWS account and your AWS credentials file is properly installed._

But in the issues comment field it states:
> Also, please make sure that you are running Zappa _from a virtual environment_ and are using Python 2.7 

## Questions
Is the support for Zappa only for Python 2.7? 
If Python 3.6 is supported, can someone help me understand the error being displayed?
If there isn't support, is there a work around for using Python 3.6 dependency that is installed through pip, but use Python 2.7 virtual environment?

 

## Expected Behavior

Virtual environment should successfully install zappa through pip

## Actual Behavior

Rather than installing, I receive an error 
```
(env) (xenial)aaron@localhost:~/Documents/morellonomicon$ pip install zappa
Collecting zappa
  Using cached zappa-0.44.3-py3-none-any.whl
Collecting argcomplete==1.9.2 (from zappa)
  Using cached argcomplete-1.9.2-py2.py3-none-any.whl
Collecting hjson==3.0.0 (from zappa)
  Using cached hjson-3.0.0.tar.gz
Collecting wsgi-request-logger==0.4.6 (from zappa)
  Using cached wsgi-request-logger-0.4.6.tar.gz
Collecting durationpy==0.5 (from zappa)
  Using cached durationpy-0.5.tar.gz
Collecting Werkzeug==0.12 (from zappa)
  Using cached Werkzeug-0.12-py2.py3-none-any.whl
Collecting requests>=2.10.0 (from zappa)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting botocore==1.7.14 (from zappa)
  Using cached botocore-1.7.14-py2.py3-none-any.whl
Collecting tqdm==4.15.0 (from zappa)
  Using cached tqdm-4.15.0-py2.py3-none-any.whl
Collecting futures==3.1.1 (from zappa)
  Using cached futures-3.1.1.tar.gz
Collecting base58==0.2.4 (from zappa)
  Using cached base58-0.2.4-py3-none-any.whl
Collecting six==1.11.0 (from zappa)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting lambda-packages==0.16.1 (from zappa)
  Using cached lambda_packages-0.16.1.tar.gz
Collecting troposphere>=1.9.0 (from zappa)
  Using cached troposphere-1.9.6.tar.gz
Requirement already satisfied: wheel==0.30.0 in ./env/lib/python3.6/site-packages (from zappa)
Collecting toml==0.9.2 (from zappa)
  Using cached toml-0.9.2.tar.gz
Collecting kappa==0.6.0 (from zappa)
  Using cached kappa-0.6.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-377_dpbk/kappa/setup.py", line 54, in <module>
        run_setup()
      File "/tmp/pip-build-377_dpbk/kappa/setup.py", line 22, in run_setup
        long_description=open_file('README.rst').read(),
      File "/home/aaron/Documents/morellonomicon/env/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2339: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-377_dpbk/kappa/
```

## Possible Fix

Create virtualenv using Python 2.7
`virtualenv --python=/usr/bin/python2.7 <name>`

## Steps to Reproduce

1. virtualenv venv
2. source venv/bin/activate
3. pip install zappa

## Your Environment

* Zappa version used:
Most current version from `pip install zappa`
* Operating System and Python version:
OS: Ubuntu 16.04.3 LTS
Python: 3.6 / 2.7
* The output of `pip freeze`:
```
aniso8601==1.2.0
asn1crypto==0.23.0
awscli==1.11.163
botocore==1.7.21
cffi==1.11.0
click==6.7
colorama==0.3.7
cryptography==2.0.3
docutils==0.14
Flask==0.12.2
Flask-Ask==0.9.7
idna==2.6
itsdangerous==0.24
Jinja2==2.9.6
jmespath==0.9.3
MarkupSafe==1.0
pyasn1==0.3.6
pycparser==2.18
pyOpenSSL==17.0.0
python-dateutil==2.6.1
PyYAML==3.12
rsa==3.4.2
s3transfer==0.1.11
six==1.10.0
Werkzeug==0.12.2
```
* Link to your project (optional):
* Your `zappa_settings.py`:

**Comment by fompei** [comment]
Seems the issue was with locale, 
[https://askubuntu.com/questions/162391/how-do-i-fix-my-locale-issue](url) for answers

**Comment by Miserlou** [comment]
You might want to report that to the Kappa project, the dependency which caused that.

**Comment by deoresheetal** [comment]
@aarlin https://askubuntu.com/questions/162391/how-do-i-fix-my-locale-issue is moved or deleted, I am getting same issue, can you share your fix here?

**Comment by fsecada01** [comment]
From linux shell, you can run the following commands to set the environmental variables
```
LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8
LANGUAGE=en_US:en
```

After that, you can run this as one line to fix your problem (presuming `sudo` and presuming that you installed `locales` from your package manager):
`sudo locale-gen --purge && locale-gen en_US_UTF-8`

If you're using docker, you can set this up from your Dockerfile:

```
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8
ENV LANGUAGE en_US:en

RUN apt-get update && apt-get upgrade -y && apt-get install locales -y
RUN locale-gen --purge && locale-gen en_US.UTF-8
```

**Comment by rahulchhabra07** [comment]
https://stackoverflow.com/a/54790348/4689310

**Comment by welty** [comment]
For any macos users experiencing this issue, I just ran the following two commands after the install failure:

```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

Afterwards, kappa installed successfully.
I found this was the least intrusive way to get it to work without having to run sudo anywhere.
