### ISSUE TITLE
Requirements version too strict for botocore

### ISSUE THREAD

**Issue by tgrant59** [Miserlou/Zappa#1152]
## Context

I'm installing `awscli` alongside `zappa` and running into a dependency mismatch. `awscli` always requires the most recent version of `botocore`, which causes a conflict with the version that Zappa requires.

Does Zappa necessarily require a specific locked version of `botocore` or would it be possible to add something like `botocore>=1.7.14` to the requirements file instead.

This problem arises when trying to create a lockfile with `pipenv`. I receive the error `Could not find a version that matches botocore<1.8.0,==1.7.14,==1.7.21,>=1.2.0,>=1.7.0`. The two packages that require specific versions are `awscli` and Zappa.

## Expected Behavior
Should install correctly alongside `awscli` and be lockable

## Actual Behavior
Installs, but blocks generation of a lockfile due to depencency mismatch

## Possible Fix
Don't be so specific in requirements.txt

**Comment by Miserlou** [comment]
Lots of people have asked.. I am _temporarily_ relenting on this issue. As soon as we started getting burned by outdated botos or old botos in bug reports, I'm putting it back.
