### ISSUE TITLE
@task_sns is broken, uses lambda as the task source instead of SNS topic

### ISSUE THREAD

**Issue by nightfurys** [Miserlou/Zappa#1157]
`@task_sns` decorator does not use SNS topic as the event source, instead it defaults to direct lambda invocation. This may be caused by the following commit which ignores args and kwargs passed to the `task()`

https://github.com/Miserlou/Zappa/commit/0e577022848988af1fdd14811f987f52f294f26d#diff-ddae33b752115be62322b2ef2f098203R306

* Zappa version used: Version: 0.44.3
* Python version: Python 2.7

**Comment by mcrowson** [comment]
I think you might be right. Would replacing
the line 
`service = 'lambda'`
with 
`service = kwargs.get('service', 'lambda')`

fix it?

**Comment by mcrowson** [comment]
I'm super surprised this hasn't come up until now if that indeed is the issue

**Comment by nightfurys** [comment]
I think this is problematic: 
```
    if func:  # Default Values
        service = 'lambda'
        lambda_function_name = os.environ.get('AWS_LAMBDA_FUNCTION_NAME')
        aws_region = os.environ.get('AWS_REGION')

    else:  # Arguments were passed
        service = kwargs.get('service', 'lambda')
        lambda_function_name = kwargs.get('remote_aws_lambda_function_name') or os.environ.get('AWS_LAMBDA_FUNCTION_NAME')
        aws_region = kwargs.get('remote_aws_region') or os.environ.get('AWS_REGION')
```

I think defaults for `service`, `lambda_function_name` and `aws_region` should be assumed if `kwargs` are not specified. So changing the if condition to the following might fix the issue

```
    if not kwargs:  # Default Values
        service = 'lambda'
        lambda_function_name = os.environ.get('AWS_LAMBDA_FUNCTION_NAME')
        aws_region = os.environ.get('AWS_REGION')

    else:  # Arguments were passed
        service = kwargs.get('service', 'lambda')
        lambda_function_name = kwargs.get('remote_aws_lambda_function_name') or os.environ.get('AWS_LAMBDA_FUNCTION_NAME')
        aws_region = kwargs.get('remote_aws_region') or os.environ.get('AWS_REGION')
```

**Comment by mcrowson** [comment]
Looks like it would work to me. You able to test this?

**Comment by nightfurys** [comment]
Yep, I did and found another issue downstream related to capturing the response. Publishing the message to the SNS topic fails when `capture_response` flag is at its default value of `False`. This is because`response_id` attribute is not initialized but accessed on line https://github.com/Miserlou/Zappa/blob/b0b832d02463cc4e861dc64a47808edcd1dfbc36/zappa/async.py#L166

I think the fix for this would be to include some of same handling code in constructor for `SnsAsyncResponse` as `LambdaAsyncResponse`
```
if capture_response:
            if ASYNC_RESPONSE_TABLE is None:
                print(
                    "Warning! Attempted to capture a response without "
                    "async_response_table configured in settings (you won't "
                    "capture async responses)."
                )
                capture_response = False
                self.response_id = "MISCONFIGURED"

            else:
                self.response_id = str(uuid.uuid4())
        else:
            self.response_id = None

        self.capture_response = capture_response
```

A better approach would be to refactor this into a base class and let dispatch mechanisms inherit it.

**Comment by mcrowson** [comment]
Please do, let's keep the issues separate.

**Comment by nightfurys** [comment]
Opened https://github.com/Miserlou/Zappa/issues/1209 to track the response capture issue. As for this issue, the fix would be what I suggested before

**Comment by Miserlou** [comment]
Implemented recommended fixes.
