### ISSUE TITLE
Allow Zappa to be run with the AWS credentials as environment variables or command line options.

### ISSUE THREAD

**Issue by glassresistor** [Miserlou/Zappa#1158]
Currently Zappa only works with AWS credentials stored in settings files.  I'm working in continuous deployment situation where the user running Zappa doesn't have a home folder(and its also in a chroot jail).

It would be really nice if Zappa working with the same environment variables as AWS cli and other tools or accepted command line options.  Both would be nice but I understand that command line options can be abused.

This would greatly improve my ability to automate Zappa in a shared build in environment.

**Comment by Miserlou** [comment]
Can you be a bit more specific? I think Zappa should respect environment variables already.

**Comment by paulclarkaranz** [comment]
I'm using environment variables to deploy from travis just fine: http://boto3.readthedocs.io/en/latest/guide/configuration.html#environment-variables

**Comment by glassresistor** [comment]
Odd I tried setting them myself but it didn't work.  Here is the relevant info from my machine, from the same shell I'm also able to use aws with the credentials in my environment.

I'm currently running this on Debian Jessie as well on Ubuntu Xenia on AWS.

```bash

pip freeze | grep boto
boto==2.48.0
boto3==1.4.7
botocore==1.7.14
┌───=[ mikela :: slimemold -( 0 )-[ ~/code/intake ]
└──(intake-zappa) env | grep AWS
AWS_SECRET_ACCESS_KEY=[redacted]
AWS_ACCESS_KEY_ID=[redacted]
(intake-zappa) 
┌───=[ mikela :: slimemold -( 0 )-[ ~/code/intake ]
└──(intake-zappa) zappa --version
0.44.3
(intake-zappa) 
┌───=[ mikela :: slimemold -( 0 )-[ ~/code/intake ]
└──(intake-zappa) python --version
Python 3.6.2
(intake-zappa) 
┌───=[ mikela :: slimemold -( 0 )-[ ~/code/intake ]
└──(intake-zappa) zappa update development
Calling update for stage development..
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/home/mikela/.virtualenvs/intake-zappa/lib/python3.6/site-packages/zappa/cli.py", line 2525, in handle
    sys.exit(cli.handle())
  File "/home/mikela/.virtualenvs/intake-zappa/lib/python3.6/site-packages/zappa/cli.py", line 484, in handle
    self.dispatch_command(self.command, stage)
  File "/home/mikela/.virtualenvs/intake-zappa/lib/python3.6/site-packages/zappa/cli.py", line 510, in dispatch_command
    self.load_settings(self.vargs.get('settings_file'))
  File "/home/mikela/.virtualenvs/intake-zappa/lib/python3.6/site-packages/zappa/cli.py", line 1951, in load_settings
    xray_tracing=self.xray_tracing
  File "/home/mikela/.virtualenvs/intake-zappa/lib/python3.6/site-packages/zappa/core.py", line 268, in __init__
    self.load_credentials(boto_session, profile_name)
  File "/home/mikela/.virtualenvs/intake-zappa/lib/python3.6/site-packages/zappa/core.py", line 2663, in load_credentials
    self.boto_session = boto3.Session(profile_name=profile_name, region_name=self.aws_region)
  File "/home/mikela/.virtualenvs/intake-zappa/lib/python3.6/site-packages/boto3/session.py", line 80, in __init__
    self._setup_loader()
  File "/home/mikela/.virtualenvs/intake-zappa/lib/python3.6/site-packages/boto3/session.py", line 120, in _setup_loader
    self._loader = self._session.get_component('data_loader')
  File "/home/mikela/.virtualenvs/intake-zappa/lib/python3.6/site-packages/botocore/session.py", line 726, in get_component
    return self._components.get_component(name)
  File "/home/mikela/.virtualenvs/intake-zappa/lib/python3.6/site-packages/botocore/session.py", line 922, in get_component
    self._components[name] = factory()
  File "/home/mikela/.virtualenvs/intake-zappa/lib/python3.6/site-packages/botocore/session.py", line 184, in <lambda>
    lambda:  create_loader(self.get_config_variable('data_path')))
  File "/home/mikela/.virtualenvs/intake-zappa/lib/python3.6/site-packages/botocore/session.py", line 279, in get_config_variable
    elif self._found_in_config_file(methods, var_config):
  File "/home/mikela/.virtualenvs/intake-zappa/lib/python3.6/site-packages/botocore/session.py", line 306, in _found_in_config_file
    return var_config[0] in self.get_scoped_config()
  File "/home/mikela/.virtualenvs/intake-zappa/lib/python3.6/site-packages/botocore/session.py", line 383, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile (default) could not be found

==============

Need help? Found a bug? Let us know! :D
File bug reports on GitHub here: https://github.com/Miserlou/Zappa
And join our Slack channel here: https://slack.zappa.io
Love!,
 ~ Team Zappa!

```

cc: @Miserlou

**Comment by Miserlou** [comment]
Post settings as well please! Might work without `profile`.

**Comment by glassresistor** [comment]
So 
```json
{
    "development": {
        "aws_region": "us-east-1",
        "django_settings": "project.settings.development",
        "profile_name": "default",
        "s3_bucket": "[redacted]",
	"environment_variables": {
           [redacted]
	},
    "exclude": ["node_modules", "static", "media", "staticfiles-cache", "tests", "fixtures"]
    }
}

**Comment by glassresistor** [comment]
Fixed thank you.

**Comment by Miserlou** [comment]
Did getting rid of profile do the trick?

**Comment by glassresistor** [comment]
Yes.  It would probably be good to document in the settings section and as an aside in the opening section during initial setup this to help avoid others having this issue.

**Comment by Miserlou** [comment]
👍

**Comment by nueverest** [comment]
Did this ever get documented?

**Comment by paulclarkaranz** [comment]
It is documented as a comment in the advanced settings section but since this also arises due to differences between init and deploy environments (my coworker ran into it last week too), and zappa_settings should be in version control, I think it should be documented in the init and/or deploy sections. Also init won't work without a ~/.aws/ setup but deploy etc will, seems to be crying out for a refactor.

**Comment by BradNation4Eva** [comment]
I encountered this issue myself in context of hooking up zappa as part of a CI pipeline. If you read the aws fineprint - profile names in the .aws CLI config file need to be preceeded with '**profile**'.
http://boto3.readthedocs.io/en/latest/guide/configuration.html#environment-variables

`The config file is an INI format, with the same keys supported by the shared credentials file. The only difference is that profile sections must have the format of [profile profile-name], except for the default profile. ` 

 For example:

# Example ~/.aws/config file.
[default]
aws_access_key_id=foo
aws_secret_access_key=bar

[**profile** dev]
aws_access_key_id=foo2
aws_secret_access_key=bar2

[**profile** prod]
aws_access_key_id=foo3
aws_secret_access_key=bar3

**Comment by sid137** [comment]
I copied zappa_settings.json (development) to  zappa_settings_ci.json and removed the `profile` key.

Then put in my AWS credentials as env vars, and set the CI to run `  zappa update -s zappa_settings_ci.json $environment` .  That seemed to do it.  only downside is the duplication of the settings file..

**Comment by caleb15** [comment]
Running `aws configure --profile yourProfileNameHere` fixed it. I also switched to using WSL instead of native windows.
