### ISSUE TITLE
api gateway {parameter_n} doesn't work with Requests Path cache

### ISSUE THREAD

**Issue by kienpham2000** [Miserlou/Zappa#116]
For some reason I can't enable API Gateway cache when having the Requests Path as {parameter_n}. These params were created by zappa.

Whenever I click on Caching checkbox, AWS gives that error message.
http://g.recordit.co/ShfT242WpM.gif

**Comment by Miserlou** [comment]
Hm, not sure about that one. What's the expected behavior? Does it work with a different format?

**Comment by kienpham2000** [comment]
@Miserlou yea it works normally if I create using different format (manually from UI)

I chatted with AWS support, exported the Swagger json after Zappa, the original Zappa config gives something like this:

```json
"/{parameter_1}": {
      "get": {
        "consumes": [
          "application/json",
          "multipart/form-data",
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "text/html"
        ],
```

AWS support said we need to add something like this after it 

```json
"parameters": [
          {
            "name": "parameter_1",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
```

I'll play with it later and see if that helps.

**Comment by Miserlou** [comment]
I suppose that would go here? https://github.com/Miserlou/Zappa/blob/master/zappa/zappa.py#L663

**Comment by kienpham2000** [comment]
looks like it, I'll play with it to see if that'll fix it.

**Comment by Miserlou** [comment]
We no longer use 'parameter_n'
