### ISSUE TITLE
Bad "END" token coloring in zappa manage diffsettings

### ISSUE THREAD

**Issue by jleclanche** [Miserlou/Zappa#1171]
Zappa 0.44.3

I ran `zappa manage dev diffsettings` to get my settings diff output. In those settings I have configured the following:

`REST_FRAMEWORK = {'DEFAULT_RENDERER_CLASSES': ('rest_framework.renderers.JSONRenderer',)} 

This is what it looks like in the output:

![image](https://user-images.githubusercontent.com/235410/31518178-1390b2b4-afa7-11e7-87e7-45bcad513080.png)

The "END" is being parsed and tokenized the same way as `[END] RequestId: ...`.

**Comment by Miserlou** [comment]
Ha!
