### ISSUE TITLE
Only install futures on python versions <= 2.7

### ISSUE THREAD

**Issue by emellis** [Miserlou/Zappa#1179]
## Context

 
Installing the futures package (https://pypi.python.org/pypi/futures) on python 3 results in a syntax error in some other libraries due to an old form of exception handling being used in the package. Here is an example from boto3:
```
test_venv/lib/python3.6/site-packages/boto3/s3/transfer.py:127: in <module>
    from s3transfer.exceptions import RetriesExceededError as \
test_venv/lib/python3.6/site-packages/s3transfer/__init__.py:134: in <module>
    import concurrent.futures

  File "/var/build/workspace/build-infrastructure-introspection/test_venv/lib/python3.6/site-packages/concurrent/futures/_base.py", line 381
      raise exception_type, self._exception, self._traceback
                                        ^
  SyntaxError: invalid syntax
```

## Expected Behavior

The futures package is part of the standard library in python 3 and should not be installed in these environments

## Actual Behavior

The futures package is installed in all python versions

## Possible Fix

Stop installing the futures package in python >= 3.0

## Steps to Reproduce
I am actually totally at a loss on how to reproduce this issue... It never occurs on my laptop (Mac OS 10.12.6 with python 3.6.2) but seems to occur with great frequency on my Jenkins executor (Amazon Linux 2017.09 with python 3.6.1).

## Your Environment

* Zappa version used: 0.44.3
* Operating System and Python version: Amazon Linux 2017.09 with python 3.6.1
* The output of `pip freeze`: 
* Link to your project (optional):
* Your `zappa_settings.py`:

**Comment by emellis** [comment]
See https://github.com/agronholm/pythonfutures/issues/41

**Comment by emellis** [comment]
Just tested a pip install straight from the repo and this issue seems to be fully resolved by my PR.

**Comment by monkut** [comment]
The zappa is ok, this is a pipenv issue. 

Already resolved in pipenv `master`, should be fixed in the next release.

If you want this working now you can use the following to install from the current master:
```
sudo python3.6 -m pip install git+git://github.com/pypa/pipenv.git@541b87abd5baa1b6528ab5938fc275b6e982d7e0 --user
```
