### ISSUE TITLE
Implement Releases on GitHub

### ISSUE THREAD

**Issue by mcrowson** [Miserlou/Zappa#1190]
## Context

 
Currently all commits go to master branch and the project is versioned and updated on pypi at various times. The master branch and pypi releases don't necessarily line up. They never line up for past releases.

## Expected Behavior

Release versions are browsable on GH

## Actual Behavior

No Versions

## Possible Fix

Start marking release when code is versioned and updated to pypi.

**Comment by Miserlou** [comment]
You can see which versions are releases in the git history - releases are marked with a prefixed `x.x.x - ` string, these are the versions released to PyPI. 

On the whole, for production I'd recommend that people use either a version and any successive minor version updates for a set-it-and-forget-it approach, or just run `master` if you're willing to do the work to keep your deploy maintained.

Once we are more stable - not likely any time soon - we can do "releases" which will work as "LTS" releases. These releases we can do on GitHub.

Does this answer the question? I can reopen if there's something I'm not seein ghere.
