### ISSUE TITLE
Cannot load native module 'Cryptodome.Cipher._raw_ecb'

### ISSUE THREAD

**Issue by exp0nge** [Miserlou/Zappa#1198]
## Context

 
I'm trying to use `pycryptodome` in my project. I'm on Python 3.6 on Windows 10. I can install it fine with pip into my virtualenv. However, when I update the site, it throws errors about not being able to load the module.

## Expected Behavior

Loads the module properly and I can go on about my way.

## Actual Behavior

`Cannot load native module 'Cryptodome'...`

## Steps to Reproduce

1. pip install pycryptodomex
2. Use it somewhere
3.

## Your Environment

* Zappa version used: 0.44.3
* Operating System and Python version: Win10, 3.6
* The output of `pip freeze`:
* Link to your project (optional):
* Your `zappa_settings.py`:

**Comment by exp0nge** [comment]
oops duplicate of #914

**Comment by exp0nge** [comment]
What I did was use vagrant with `ubuntu/trusty64`, installed Python 3.6 from source, used `python -m venv`  to create a virtual env then updated with zappa.

**Comment by bjinwright** [comment]
Try this https://github.com/capless/python-jose-cryptodome/blob/master/README.rst

**Comment by exp0nge** [comment]
@bjinwright Looks like it requires rewriting the API to use `jose`. Not worth it
