### ISSUE TITLE
Zappa with Flask cannot route unicode strings.

### ISSUE THREAD

**Issue by DingGGu** [Miserlou/Zappa#1199]
Zappa cannot route Unicode Strings
## Context
I'm using Zappa with Flask in Python3.6

Zappa cannot route string that include unicodes.

```python
@bp.route('/product/<name>')
def teacher(name):
    return flask.jsonify(dict(name=name))
```

Request To: "/product/123"
ResponseBody: {"name": "123"}

Request To: "/product/ㅁㄴㅇㄹ"
ResponseBody: Displaying Error 

Log:

```js
{
'message': 'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.',

'traceback': [
'Traceback (most recent call last):\\n', '  File \"/var/task/handler.py\", line 454, in handler\\n    response = Response.from_app(self.wsgi_app, environ)\\n', '  File \"/var/task/werkzeug/wrappers.py\", line 903, in from_app\\n    return cls(*_run_wsgi_app(app, environ, buffered))\\n', '  File \"/var/task/werkzeug/test.py\", line 884, in run_wsgi_app\\n    app_rv = app(environ, start_response)\\n', '  File \"/var/task/zappa/middleware.py\", line 70, in __call__\\n    response = self.application(environ, encode_response)\\n', '  File \"/var/task/flask/app.py\", line 1997, in __call__\\n    return self.wsgi_app(environ, start_response)\\n', '  File \"/var/task/flask/app.py\", line 1977, in wsgi_app\\n    ctx = self.request_context(environ)\\n', '  File \"/var/task/flask/app.py\", line 1938, in request_context\\n    return RequestContext(self, environ)\\n', '  File \"/var/task/flask/ctx.py\", line 242, in __init__\\n    self.url_adapter = app.create_url_adapter(self.request)\\n', '  File \"/var/task/flask/app.py\", line 1765, in create_url_adapter\\n    server_name=self.config[\\'SERVER_NAME\\'])\\n', '  File \"/var/task/werkzeug/routing.py\", line 1332, in bind_to_environ\\n    path_info = _get_wsgi_string(\\'PATH_INFO\\')\\n', '  File \"/var/task/werkzeug/routing.py\", line 1329, in _get_wsgi_string\\n    return wsgi_decoding_dance(val, self.charset)\\n', '  File \"/var/task/werkzeug/_compat.py\", line 176, in wsgi_decoding_dance\\n    return s.encode(\\'latin1\\').decode(charset, errors)\\n', \"UnicodeEncodeError: 'latin-1' codec can't encode characters in position 9-12: ordinal not in range(256)\\n\"
]
}
```

```
[1509065039838] 'latin-1' codec can't encode characters in position 9-12: ordinal not in range(256)
```

## Your Environment

* Zappa version used: 0.44.3
* Operating System and Python version: Python 3.6

**Comment by Miserlou** [comment]
This is a great bug, thanks for reporting. Could be upstream though?

Tell me - does this only occur on Python27? Could have been introduced when we added P36 support, or perhaps it's just a P3 corner case we haven't encountered yet.

**Comment by DingGGu** [comment]
@Miserlou 
I reproduce these bugs.

I setup new clean project and one source.

I made two diffrent version of virtual enviroment on my local.
```
$ pyenv virtualenv 3.6.2 zappa-test3
$ pyenv virtualenv 2.7.13 zappa-test
```

This code is same as between 3.6 and 2.7 where I used.
```python
from flask import Flask
import flask

app = Flask(__name__)

@app.route('/')
def main():
    return flask.jsonify(flask.request.url)

@app.route('/<name>/')
def name(name):
    return flask.jsonify(flask.request.url)

if __name__ == '__main__':
    app.run(debug=True)
```

And I Create those Zappa projects.

```
$ zappa init
```

Deploy to Lambda and API Gateway
```
$ zappa deploy
```



You can Test on here:

This link will be expired after 24 hours (this is my own aws accounts)

## Python 2.7
https://gsxt79wmi7.execute-api.ap-northeast-1.amazonaws.com/dev/
https://gsxt79wmi7.execute-api.ap-northeast-1.amazonaws.com/dev/ㅁㄴㅇㄹ <-- Unicode String
https://gsxt79wmi7.execute-api.ap-northeast-1.amazonaws.com/dev/1234

## Python 3.6
https://mh5glr8b3c.execute-api.ap-northeast-1.amazonaws.com/dev/
https://mh5glr8b3c.execute-api.ap-northeast-1.amazonaws.com/dev/ㅁㄴㅇㄹ <-- Unicode String
https://mh5glr8b3c.execute-api.ap-northeast-1.amazonaws.com/dev/1234

**Comment by DingGGu** [comment]
@Tipuch Awesome.

**Comment by zeus** [comment]
This patch makes django unicode urls unworkable :(
