### ISSUE TITLE
Using a delay vs botocore retrying

### ISSUE THREAD

**Issue by mathom** [Miserlou/Zappa#12]
I noticed this library uses a sleep to avoid AWS throttling requests - is there a reason the built in exponential retry handler that ships with botocore didn't work?

Also, I was curious why you have to sign your own request to put the integration method in: https://github.com/Miserlou/Zappa/blob/master/zappa/zappa.py#L509

**Comment by mathom** [comment]
I may have discovered why it has the sleep - is there a timing issue between publishing and it actually appearing on the gateway?

**Comment by Miserlou** [comment]
Botocore retrying seems like a much, much better solution than sleep(). That was just a quick hack to fix this for a user: https://github.com/Miserlou/django-zappa/issues/4

**Comment by Miserlou** [comment]
And I believe that the integration had to be done "manually" because boto didn't support multiple content mapping templates, but don't quote me on that!

**Comment by collingreen** [comment]
+1 on removing the delay -- the current setup adds 1 second for every endpoint, for every verb, which ends up adding 400+ seconds to a clean deploy in django-zappa.

**Comment by mathom** [comment]
I just got my [custom API Gateway exporter/importer](https://github.com/mathom/apigpen) functioning and was able to export and import the full API deployment of one of my django apps:

```bash
$ time apigpen --export 'ms-test' > ms32.yaml  
apigpen --export 'ms-test' > ms32.yaml  0.54s user 0.03s system 16% cpu 3.443 total

$ time apigpen --import 'test2' < ms32.yaml
zkkrdf3kw9
apigpen --import 'test2' < ms32.yaml  1.46s user 0.08s system 3% cpu 46.677 total
```

Importing at 46 seconds is not exactly blazing fast, but I didn't have to do any sleeping and didn't seem to need to sign any requests by hand (I just used the stock boto3 stuff). It should be possible to set up Zappa to create the API resources in a similar fashion. I'll take a look in the next few days!

**Comment by Miserlou** [comment]
Well, 46 seconds is an ~order of magnitude better than 400, so certainly an improvement there! And always nice to simplify code.

Looking forward to your analysis!

**Comment by mathom** [comment]
Hey @collingreen, I've got a branch set up to remove the sleeps and the manual request signing. You can try it out by installing the two branches (in this order):
```
pip install -U git+git://github.com/mathom/django-zappa.git@nosleep
pip install -U git+git://github.com/mathom/zappa.git@nosleep
```

Without the sleeping it takes about 40-50 seconds to setup the API. I've also added a progress bar but `tqdm` is kind of a pain to use the way I had to so I may drop that commit.

**Comment by collingreen** [comment]
@mathom hey, nice work! I'll check this out tomorrow. Your approach is much better than the naive retrying I was shoehorning in.

**Comment by Miserlou** [comment]
Ooo, that looks nice.. looking forward to your merge, @mathom!

**Comment by collingreen** [comment]
@mathom just ran through the whole thing and it worked like a charm - great work. I hope you can keep the progress bar -- that was on my list and, again, your implementation is much better than what I had started on.

:+1:

**Comment by mathom** [comment]
Awesome, if both of you guys are happy with the changes I'll push em to master. Let me know if you discover any issues with it!
