### ISSUE TITLE
Django TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by tiamot** [Miserlou/Zappa#1210]
After Deploying a Django application using Zappa, the following error is returned in the browser:
```
"{'message': 'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.', 'traceback': ['Traceback (most recent call last):\\n', '  File \"/var/task/handler.py\", line 454, in handler\\n    response = Response.from_app(self.wsgi_app, environ)\\n', '  File \"/var/task/werkzeug/wrappers.py\", line 903, in from_app\\n    return cls(*_run_wsgi_app(app, environ, buffered))\\n', '  File \"/var/task/werkzeug/test.py\", line 884, in run_wsgi_app\\n    app_rv = app(environ, start_response)\\n', \"TypeError: 'NoneType' object is not callable\\n\"]}"
```

## Context
When attempting to setup a base install of Django using python3, an error is shown after deployment wth zappa.

## Expected Behavior
A 404 page because no ALLOWED_HOSTS have been setup yet.

## Actual Behavior
The error described at the beginning of this ticket is shown in the browser window.

## Steps to Reproduce
1. `$ mkdir z`
2. `$ cd z`
3. `$ python3 -m venv ve` (Note: I would like to be able to use mkproject but couldn't make it work)
4. `$ source ve/bin/activate`
4. `$ pip install django zappa`
5. `$ django-admin startproject x .`
6. `$ python3 manage.py runserver`
7. `ctrl-c`
8. `$ zappa init`
9. `$ zappa deploy dev`
10. Open the deployment URL in a browser.

## Your Environment
Zappa Version: 

* Zappa version used: 0.44.3
* Operating System: OSX 10.12.6
* Django Version: 1.11.6
* Python version: 3.6.3w
* The output of `pip freeze`:
```argcomplete==1.9.2
base58==0.2.4
boto3==1.4.7
botocore==1.7.14
certifi==2017.7.27.1
chardet==3.0.4
click==6.7
Django==1.11.6
docutils==0.14
durationpy==0.5
future==0.16.0
futures==3.1.1
hjson==3.0.0
idna==2.6
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.16.1
placebo==0.8.1
python-dateutil==2.6.1
python-slugify==1.2.4
pytz==2017.3
PyYAML==3.12
requests==2.18.4
s3transfer==0.1.11
six==1.11.0
toml==0.9.2
tqdm==4.15.0
troposphere==2.0.2
Unidecode==0.4.21
urllib3==1.22
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.44.3
```
* Your `zappa_settings.py`: I don't have a sappa_settings.py. Here is my zappa_settings.json:
```json
{
    "dev": {
        "aws_region": "us-west-2",
        "django_settings": "mapper.settings",
        "profile_name": "bc",
        "project_name": "title-map",
        "runtime": "python3.6",
        "s3_bucket": "title-mapper"
    }
}
```

**Comment by tiamot** [comment]
Everything seems to work fine If I use `Python 2.7.14` and `Django 1.11`

**Comment by mrbox** [comment]
I have same behaviour- can't deploy any Python3 app with Zappa because of that- also tried to use docker as environment for zappa but it didn't help

**Comment by mrbox** [comment]
And I found a solution for this- default Django project tries to create sqlite3 database in the project folder- and lambda for Python3 doesn't support sqlite3. I see two solutions- switch to proper DB backend or https://stackoverflow.com/a/47006882/784743 - tested both of them and they work.

**Comment by Miserlou** [comment]
That's an interesting solution - this should be fixed in the next Zappa then!

Can you just drop the .so from https://github.com/Miserlou/lambda-packages/issues/66 into your project folder and have it work?

**Comment by mrbox** [comment]
I already did that- and for the clean django project it worked like a charm. However for 'regular' project, I'm getting the same error and `zappa tail` shows:
```
  File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 936, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 888, in get_code
  File "<frozen importlib._bootstrap_external>", line 455, in _validate_bytecode_header
ImportError: bad magic number in 'harvester': b'\x03\xf3\r\n'
```
which would mean that my venv for the 'big' project is out of date?

Also thing to remember is that syncdb won't work with clean Django- lambda doesn't allow to create files in place other than /tmp

**Comment by Miserlou** [comment]
If you are trying to use SQLite as a database with Zappa, please take a look at: https://github.com/Miserlou/zappa-django-utils#using-an-s3-backed-database-engine

**Comment by tiamot** [comment]
@Miserlou Thanks, I'm using Postgres. I'll try to deploy after updating my database settings. Looks like all this was caused by me trying to deploy the base install that uses SQLite.

**Comment by Miserlou** [comment]
SQLite + Python3 is fixed in Zappa 45.

**Comment by jonvaughan** [comment]
I had this error.  Commenting here because I haven't seen anyone make the same stupid mistake - I had zappa_settings.json in a directory above the one with manage.py in it (i.e. I ran zappa init in the wrong place)

**Comment by piraka9011** [comment]
Just a quick note if anyone comes across this as well is to make sure your virtualenv name isn't the same as your app.
