### ISSUE TITLE
Add unique deployment hash or version environment variable

### ISSUE THREAD

**Issue by sibblegp** [Miserlou/Zappa#1214]
## Add a deployment hash so that we can pass it along to error reporting and monitoring tools to show that a different version has been deployed and track issues across versions

This would be a very useful feature for such tools as Sentry and New Relic which track bugs and performance across deployments and compare them.  It would allow you to easily access an environment variable which changes with each update which you can then send to these systems as a version of your current deployment.

## Expected Behavior
There is no built in version tracking environment variable.

## Actual Behavior
There should be a built in version environment variable.

## Possible Fix
Add a uuid that is created once upon a deploy or update and saved into the deployment.  Set it as an environment variable whenever the app is run.

## Your Environment

* Zappa version used: 0.44.3
* Operating System and Python version:  Ubuntu 16 and Python 3.6
* The output of `pip freeze`:
```
alembic==0.9.5
analytics-python==1.2.8
argcomplete==1.9.2
base58==0.2.4
bcrypt==3.1.3
blessings==1.6
boto3==1.4.7
botocore==1.7.14
bpython==0.16
certifi==2017.7.27.1
cffi==1.11.2
chardet==3.0.4
click==6.7
curtsies==0.2.11
docutils==0.14
durationpy==0.5
Flask==0.12.2
Flask-Login==0.4.0
future==0.16.0
futures==3.1.1
greenlet==0.4.12
hjson==3.0.0
idna==2.6
itsdangerous==0.24
Jinja2==2.9.6
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.16.1
Mako==1.0.7
MarkupSafe==1.0
mysqlclient==1.3.12
packaging==16.8
pkginfo==1.4.1
placebo==0.8.1
psutil==5.4.0
pycparser==2.18
Pygments==2.2.0
PyMySQL==0.7.11
pyparsing==2.2.0
python-crontab==2.2.5
python-dateutil==2.6.1
python-editor==1.0.3
python-slugify==1.2.4
pytz==2017.2
PyYAML==3.12
raven==6.3.0
requests==2.18.4
requests-toolbelt==0.8.0
s3transfer==0.1.11
scandir==1.6
six==1.11.0
SQLAlchemy==1.1.14
toml==0.9.2
tqdm==4.15.0
troposphere==2.0.0
twine==1.9.1
Unidecode==0.4.21
urllib3==1.22
wcwidth==0.1.7
Werkzeug==0.12
wsgi-request-logger==0.4.6
WTForms==2.1
zappa==0.44.3
```

**Comment by Miserlou** [comment]
Sounds good to me, send a PR!

**Comment by sibblegp** [comment]
If anyone wants a little workaround in the meantime, I created a script to create a small file with the date and time which you can then hash:

#!/bin/bash

echo `date "+%m/%d/%y  %H:%M:%S"` >deploy_hash.file
zappa update storjdash

**Comment by Miserlou** [comment]
Merged! But updated after, see comments on the PR. Thanks!

**Comment by sibblegp** [comment]
Makes sense and sounds great!
