### ISSUE TITLE
Automatically build README.md Table of Contents

### ISSUE THREAD

**Issue by bxm156** [Miserlou/Zappa#1228]
Right now, it looks like doctoc is used to build the table of contents. Its a npm package, and isn't referenced in the codebase, besides the README.md. Looks like people would have to install the package manually ```npm install -g doctoc``` and then run it... I'm not sure if anyone does, or would remember to.

I think it would be cool if we could automate this somehow. Perhaps something other than doctoc could be used so that we don't have to use npm here.

**Comment by bxm156** [comment]
Another option would be to use doctoc as a pre-commit hook

https://github.com/thlorenz/doctoc#usage-as-a-git-hook
http://pre-commit.com/

However, since pre-commit was is actively used and developed by my work, I don't want to add it to this project without input from other active contributors to Zappa.

**Comment by Miserlou** [comment]
I think this is more of a bug in me rather than a bug in Zappa, but yes, this'd be nice. :) Currently I just run it whenever I remember that I need to. I should set this up as a pre-commit hook for myself.

Or, we over-engineer the absolute fuck out of this and set up a server-less DocTocBot akin to Doppins that runs whenever the code is pushed then sends a PR..

**Comment by scoates** [comment]
I took a stab at the over-engineered bit, with lambci. I think the most difficult part is *not* submitting the same PR repeatedly.

Maybe we could just have a notification that doctoc *would have* changed README.md, instead? Or maybe even with a patch?

FWIW, here's something close to what I had running (almost working; I think it would still take a little bit of tweaking) in my lambci:

```bash
#!/bin/bash

npm install doctoc
$(npm bin)/doctoc README.md

git status | grep README.md | grep modified
if [ ! $? -eq 0 ]; then
    echo "No changes."
    exit 0
fi

USER=$(git remote -v | grep origin | grep push | awk {'print $2'} | sed -e 's@\(.*\)[:/]\(.*\)/Zappa.git@\2@g')
HASH=$(git log -n1 | head -n1 | awk {'print $2'})
BRANCH="update-readme-toc-$HASH"
PR_USER="scoates"

git checkout -b $BRANCH

git commit -m"Update README TOC" README.md
git push origin $BRANCH

curl -H "Authorization: token $GITHUB_TOKEN" \
  -H "Content-Type: application/json" \
  -d "{\"title\": \"doctoc update\", \"body\": \"via makedoctoc.sh\", \"head\": \"$USER:$BRANCH\", \"base\": \"master\"}" \
  -XPOST https://api.github.com/repos/$PR_USER/Zappa/pulls
```

The problem is that if someone merges to master in a way that would generate a new TOC, this generates a new PR. Then if someone doesn't immediately merge that PR and there's another push to master, it would generate the PR again. Perhaps something simple like a hash of a `diff` on `README.md`, instead of the `$HASH` method above, could work. This script could check if the branch exists, and not PR if it does.

If we're interested in this, I can go ahead with it. It'll require a GitHub-token-privileged lambci to run somewhere (I volunteer to run it in my AWS account if it's helpful).

**Comment by bxm156** [comment]
Mind if I take a stab at a cleaner solution?

**Comment by scoates** [comment]
I don't mind, myself. Was mostly just putting this out there to see if we're (read: @Miserlou) even interested in actually doing this.

Ideally, actually, this would be a non-Zappa-specific solution, and it could run on other projects like the aforementioned Doppins and/or Stalebot, etc.

**Comment by bxm156** [comment]
I think this would work well as part of tox and as a git pre-commit hook. 

So the normal flow is a user makes changes, runs git commit, and this table becomes automatically updated. 

In an emergency, if a user didn't want this to occur, they could run `git commit --no-verify`, which bypasses all git pre-commit hooks.

In testing, where the normal flow described above is also ran, it will error if a change is needed.

**Comment by scoates** [comment]
Pardon my ignorance, but is there a way to have end-users always run pre-commit hooks without them manually setting them up? Last time I looked at this (admittedly, years ago), it was not possible to configure from the repository side.

I think a lot of our users are not sophisticated enough to do this, honestly. It really might be enough for @Miserlou to set up the hooks, as he mentioned. This doesn't solve the problem where he uses the button on GitHub to merge a PR, though.

**Comment by bxm156** [comment]
It's all automatic with tox

On Feb 28, 2018 8:26 AM, "Sean Coates" <notifications@github.com> wrote:

Pardon my ignorance, but is there a way to have end-users always run
pre-commit hooks without them manually setting them up? Last time I looked
at this (admittedly, years ago), it was not possible to configure from the
repository side.

I think a lot of our users are not sophisticated enough to do this,
honestly. It really might be enough for @Miserlou
<https://github.com/miserlou> to set up the hooks, as he mentioned. This
doesn't solve the problem where he uses the button on GitHub to merge a PR,
though.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Miserlou/Zappa/issues/1228#issuecomment-369293529>, or mute
the thread

**Comment by scoates** [comment]
I think I don't quite follow. You're assuming that the user runs tox? Or that whoever merges the PR runs tox?For someone who clicks "edit" in GitHub and fixes a typo, then submits a PR through the web UI, there's no tox in that flow, right?

Or do you mean it would run in Travis?

**Comment by bxm156** [comment]
So pre-commit hooks are defined in a per repo basis, in the repo,. They can run as part of the tox build, so yes they would also run in Travis, but I would have Travis ci fail the test if the toc hadn't been updated. This would occur if they user hadn't updated the toc manually in github edit ui, so they would have to fix their branch and update the toc. I don't know how often ppl edit the docs via github edit ui. 

Everyone who makes otherwise a regular commit will have run the hook. On a regular machine the hook runs and updates to toc, and adds it as part of the commit. 

Arguably a user could make a PR without running tox locally, which installs the hook. It would still be caught by Travis ci tho and the user would see their branch fail.

**Comment by bxm156** [comment]
This is the project we use at my work, we have many different hooks, from checking python style to making sure aws credentials are not committed.

https://pre-commit.com

We could do something similar, with a hook that runs doctoc

**Comment by scoates** [comment]
Ah, I see. You'd have tox *install* the hook. I don't think I'd like it if a project did this to me, at least without lots of warning.

I definitely agree, though, that adding a test to be sure that `doctoc` wouldn't change `README.md` is a simple and clean approach. 👍 on that method.

**Comment by bxm156** [comment]
It's interesting to me that bring up that you wouldn't want the project to do it without warning. I have used this for a long time, so I never thought about it in that way before. I do understand  the concern.

I think however it's all part of the risk you take when running tests. The commit hook only runs as part of commits on this repo. And it basically just runs python code, the same as just running tests. Tho perhaps it's a little less obvious what's happening in the background

**Comment by scoates** [comment]
A GitHub issue probably isn't the best medium to debate this kind of thing, but I expect someone else's code to execute when I run a test suite. I don't expect that code to be able to run in the future any time I use `git commit`. I think that's where it breaks down for me. This is also why git does not allow the repository to directly specify the pre-commit hook, I bet.

I also think it's different to require a team of paid developers, working on a project, to use a specific commit hook, and to expect the same thing of open source contributors.

**Comment by bxm156** [comment]
Understandable, like I said, I use it at my work a lot, so I have never really had input on how others feel about it.  I'm glad you brought up the concern tho because I believe it's totally valid. I think in some ways that's why I didn't make a pr with it when I made this issue. If it's not a route we want to take, that's fine.

**Comment by scoates** [comment]
To reiterate: adding a test that fails if `doctoc` *would* make changes sounds like a great approach to me.

**Comment by scoates** [comment]
I have most of this done, without resorting to npm. I'll push up a PR tonight.
