### ISSUE TITLE
Failed to generate or install certificate! 

### ISSUE THREAD

**Issue by sandeshnaroju** [Miserlou/Zappa#1240]
**My Domain SSL has expired. So I tried to create a new SSL key by doing** 

   > $ openssl genrsa 2048 > account.key; 

**And Added my Domain name and Path to zappa_settings.json file. 
I tried to run** 

  > $ zappa certify production

**This is what the Error I am getting**

> $ zappa certify production
Calling certify for stage production..
Are you sure you want to certify? [y/n] y
Certifying domain xxxx.domain.com ..
Error registering: 400 {
  "type": "urn:acme:error:malformed",
  "detail": "Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf]",
  "status": 400
}
Failed to generate or install certificate! :(

==============
I find the link [https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf](https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf)  has nothing but "404 Not Found" Error. what is the problem ? And also do we have to run $ zappa certify everytime we need to
 renew the certificate ?

**Comment by JonasMunck** [comment]
I had the same problem today - have submitted a PR.
