### ISSUE TITLE
Cant upload files with lambda to s3

### ISSUE THREAD

**Issue by talbenbasat** [Miserlou/Zappa#1250]
Hi,

I'm trying to use django with zappa and AWS.
I've created a basic project and some buckets to run with it.

Tried so many permissions and policies on the bucket and IAM role, with no success.

Any idea?

## Context
Python 3.6
running with virtualenvironment

## Expected Behavior
The file is uploaded to S3 and im transfered back to django admin

## Actual Behavior
The action fiails, no file is created and I recieve
{"message": "Endpoint request timed out"}

## Your Environment

'storages' is in my INSTALLED_APPS

This is in my settings file
```
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.environ.get('S3_BUCKET_NAME')
AWS_STORAGE_REGION = os.environ.get('S3_REGION')
AWS_HEADERS = {  # see http://developer.yahoo.com/performance/rules.html#expires
    'Expires': 'Thu, 31 Dec 2099 20:00:00 GMT',
    'Cache-Control': 'max-age=94608000',
}

MEDIA_URL = 'http://%s.s3.amazonaws.com/' % AWS_STORAGE_BUCKET_NAME
DEFAULT_FILE_STORAGE = "storages.backends.s3boto.S3BotoStorage"
```

in my zappa settings I have
```
 "aws_region": "eu-west-1",
        "vpc_config" : {
            "SubnetIds": [ "*****", "*******"], 
            "SecurityGroupIds": [ "******" ]
        },
        "profile_name": "default",
        "project_name": "****",
        "runtime": "python3.6",
        "s3_bucket": "MU BUCKET",
         "environment_variables": {
            "S3_REGION": "eu-west-1",
            "S3_BUCKET_NAME": "***********",
            "AWS_ACCESS_KEY_ID":"***********",
            "AWS_SECRET_ACCESS_KEY": "*************",
            "AWS_ACCESS_KEY":"***********",
            "AWS_SECRET_KEY": "**********************"
         },
      	"certificate_arn": "arn:aws:acm:***********,
```

This is my model
```
class Map(models.Model):
    name = models.CharField(max_length=128, default='')
    description = models.TextField(max_length=1023, default='', blank=True)

    pgm_file = models.FileField(upload_to=path_and_rename,
                                blank=False,
                                default='',
                                max_length=200)
```

```
from utils.utils import PathAndRename
path_and_rename = PathAndRename('./test')

class PathAndRename(object):

    def __init__(self, sub_path):
        self.path = sub_path

    def __call__(self, instance, filename):
        ext = filename.split('.')[-1]
        day = time.strftime('%y%m%d')
        # get filename
        if instance.pk:
            filename = '{}.{}'.format(instance.pk, ext)
        else:
            # set filename as random string
            timestamp = int(time.time())
            name = str(uuid4().hex[:3] + str(timestamp)[-5:])
            filename = '{}.{}'.format(name, ext)

        try:
            instance_type = type(instance).__name__
            username = instance.created_by.username
        except Exception:
            username = ''
            instance_type = ''

        return os.path.join(self.path, instance_type, username, day, filename)
```
Bucket policy
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublicReadGetObject",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3::MY_BUCKET/*"
        },
        {
            "Sid": "AllowS3Access",
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "arn:aws:iam::***********:role/ZAPPA-ROLE"
                ]
            },
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::MY_BUCKET",
                "arn:aws:s3:::MY_BUCKET/*"
            ]
        }
    ]
}
```

CORS
```
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>HEAD</AllowedMethod>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>DELETE</AllowedMethod>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
```

**Comment by edgarroman** [comment]
If your VPC subnets are private you will either:
1. have to create a NAT gateway to get to external S3
2. Create an S3 endpoint in your VPC subnets to allow your lambda to get access.

**Comment by talbenbasat** [comment]
@edgarroman  Thank you very very much!!
The endpoint solved the problem

**Comment by davidllauce** [comment]
Hi. I'm using S3 + lambda + django to upload files. I tested it on local http://127.0.0.1:8000/ connecting to S3 and saved the file on the correct S3 buscket, but when I zappa dev update in and I want to upload a file from lamda from https: // s5h4s4t98f. execute-api.us-west-2.amazonaws.com ... error "message" sale: "Exceeded endpoint request time".
Maybe I'm missing a permission in aws so I can save my Lambda Configuration files.

{
  "dev": {
    "aws_region": "us-west-2",
    "django_settings": "prueba.settings",
    "profile_name": "default",
    "project_name": "prueba",
    "runtime": "python3.6",
    "s3_bucket": "zappa-prueba",
    "vpc_config": {
      "SubnetIds": [
        "subnet-4*****",
        "subnet-b***",
        "subnet-c**"
      ],
      "SecurityGroupIds": [
        "sg-0204***f***"
      ]
    },
    "environment_variables": {
      "S3_REGION": "us-west-2",
      "S3_BUCKET_NAME": "prueba",
      "AWS_ACCESS_KEY_ID": "****",
      "AWS_SECRET_ACCESS_KEY": "****"
    }
  }
}
---------------------

AWS_S3_OBJECT_PARAMETERS = {
    'Expires': 'Thu, 31 Dec 2099 20:00:00 GMT',
    'CacheControl': 'max-age=94608000',
}

AWS_STORAGE_BUCKET_NAME = 'prueba'
AWS_S3_REGION_NAME = 'us-west-2'  # e.g. us-east-2
AWS_ACCESS_KEY_ID = '*****'
AWS_SECRET_ACCESS_KEY = '******'

# Tell django-storages the domain to use to refer to static files.
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME

# Tell the staticfiles app to use S3Boto3 storage when writing the collected static files (when
# you run `collectstatic`).


STATICFILES_LOCATION = 'static'
STATICFILES_STORAGE = 'custom_storages.StaticStorage'

MEDIAFILES_LOCATION = 'media'
DEFAULT_FILE_STORAGE = 'custom_storages.MediaStorage'

**Comment by prafulbagai708** [comment]
What do you mean by `Create an S3 endpoint in your VPC subnets to allow your lambda to get access.`?

**Comment by prafulbagai708** [comment]
`Create an S3 endpoint in your VPC subnets to allow your lambda to get access.` - Is there a way to do it via zappa_settings itself? I dont want to do it manually!

**Comment by SamuelNavarro** [comment]
Hi! @talbenbasat, @prafulbagai708, how you were able to resolve the issue? I created the endpoint but still facing the same problem.

**Comment by prafulbagai** [comment]
Go to `VPC > EndPoints > Create Endpoint`. Rest should be self-explanatory!

**Comment by SamuelNavarro** [comment]
Thanks for your answer. I've created the endpoint withing the vpc. Also I've selected the route tables with the subnets. I even have granted full Access in the policy but I'm still facing the same issue: I can't upload images from django admin.
