### ISSUE TITLE
Zappa and New Relic

### ISSUE THREAD

**Issue by tspecht** [Miserlou/Zappa#1255]
Hey! 

I'm using the latest version of Zappa and am trying to integrate NewRelic into my applications. I have both Django as well as Flask applications which I'd like to monitor with NewRelic. I integrated the framework as documented (by wrapping the WSGI application) and set the NewRelic timeout variables accordingly to make sure data is getting sent. 
In my NewRelic dashboard I'm able to see the project but no data is reported. Has anyone had success getting this running?

Thanks!

**Comment by kolanos** [comment]
@tspecht This doesn't really answer your question, but have you checked out IOpipe? It supports Zappa out-of-the-box and is designed specifically for AWS Lambda.

https://github.com/iopipe/iopipe-python

Full disclosure: I'm a dev and would be interested in your feedback.

**Comment by smithclay** [comment]
@tspecht Some New Relic customers have had some success running the full Python APM agent inside of AWS Lambda, but we're generally recommending people use the New Relic Infrastructure integration instead ([blog post here](https://blog.newrelic.com/2016/11/29/aws-lambda-integration-serverless-infrastructure/)). 

If you give me a shout at csmith@newrelic.com, can connect you with the product team. They're currently interviewing customers about the frameworks they use, etc.

**Comment by scoates** [comment]
Thanks @smithclay.
