### ISSUE TITLE
No Profile Region Sets zappa_settings.json region to null

### ISSUE THREAD

**Issue by mcrowson** [Miserlou/Zappa#1273]
## Context

https://github.com/Miserlou/Zappa/blob/master/zappa/cli.py#L1664

That line there causes the region to be set to null if there is not a region for the profile being used.

If that is the case we should not be setting the region key in the dict: https://github.com/Miserlou/Zappa/blob/master/zappa/cli.py#L1661

**Comment by jpchavat** [comment]
I tried removing _aws_region_ key from _zappa_settings.json_ and still rise the same error: 

`'botocore.exceptions.NoRegionError: You must specify a region.'`

There isn't a default region in zapppa.

As @mcrowson says, _aws_region_ was set to null after choosing default option in the next dialog:

`Would you like to deploy this application globally? (default 'n') [y/n/(p)rimary]:`

**Comment by mcrowson** [comment]
Even with that PR merged above your `zappa init` caused an 'aws_region' of null to be inserted? 

It looks for a saved profile in your aws config, then if there is a region setting in that config it sets it in the zappa_settings.json. So i'm not sure how a null would get set there. Mind stepping through it to see where the null entry comes from? 

And to the main point, there is no default region in zappa. It attempts to detect it from your local config. Zappa does not make any assumptions about the region.

**Comment by jpchavat** [comment]
My fault.

I went back into the log and found:
`We couldn't find an AWS profile to use. Before using Zappa, you'll need to set one up. See here for more info:`

After that, I selected the default option in:
`Would you like to deploy this application globally? (default 'n') [y/n/(p)rimary]:`
and zappa created the _zappa_settings.json_ with a _null_ value for the key _aws_region_.

**Comment by mcrowson** [comment]
ok. well you can specify an `aws_profile` to use in the config file, but that seems unrelated to this issue which i believe was addressed by the PR. Closing this issue for now.
