### ISSUE TITLE
Not able to used "nested" project folter

### ISSUE THREAD

**Issue by jonatasbaldin** [Miserlou/Zappa#1277]
## Context
When using Zappa, I'm not able to structure the problem as this:
```
/zappa_settings.json
/project/manage.py
/project/project/settings.py
```

Even using `"django_settings": "project.project.settings.py"` won't work. Instead, I'm forced to do this:
```
/zappa_settings.json
/manage.py
/project/settings.py
```

Using the `"django_settings": "project.settings.py"` configuration.

## Steps to Reproduce
1. Create a root folter
2. Create a Django Project
3. Runs `zappa init` to create a configuration file, it will point `django_settings` to `project.project.settings`.
4. Deploy the code.
5. When accessed, the log will show something like:
```
project.urls could not be imported
```

## Your Environment
* Zappa version used: 0.45.1
* Operating System and Python version: OSx 10.12.6 / Python 3.6
* The output of `pip freeze`: 
```
argcomplete==1.9.2
base58==0.2.4
boto3==1.4.8
botocore==1.8.6
certifi==2017.11.5
cfn-flip==0.2.5
chardet==3.0.4
click==6.7
Django==1.11.7
docutils==0.14
durationpy==0.5
future==0.16.0
hjson==3.0.1
idna==2.6
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.19.0
placebo==0.8.1
python-dateutil==2.6.1
python-slugify==1.2.4
pytz==2017.3
PyYAML==3.12
requests==2.18.4
s3transfer==0.1.12
six==1.11.0
toml==0.9.3
tqdm==4.19.1
troposphere==2.1.1
Unidecode==0.4.21
urllib3==1.22
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.45.1
```
* Your `zappa_settings.json`: 
```
{
    "dev": {
        "aws_region": "us-west-1",
        "django_settings": "project.project.settings",
        "project_name": "project",
        "runtime": "python3.6",
        "s3_bucket": "zappa-nj48kxgbr"
    }
}```

**Comment by jonatasbaldin** [comment]
I'm sorry, I mistyped it. 

Instead of `"zappa_settings": "project.project.settings.py"`, actually it is: `"django_settings": "project.project.settings.py`.

Will edit the issue.

**Comment by sid137** [comment]
For anyone stumbling on this, the trick to get it working is to use the following approach to generate your project:

```
mkdir projectapp
cd projectapp
```

And Instead of doing:
`django-admin startproject projectname
`
Use (notice the period at the end) :
`django-admin startproject projectname .
zappa init
`

**Comment by jonatasbaldin** [comment]
Yep, that worked.

Thanks!
