### ISSUE TITLE
{"message":"Forbidden"} when issuing a POST from an HTML From.

### ISSUE THREAD

**Issue by raymondbernard** [Miserlou/Zappa#1292]
When a POST is issued from an HTML form to the app we received a response of {message:forbidden}.
This only happens after the app is deployed to the API gateway.  
## Context

app.py
```
from flask import Flask, request,  flash, render_template


app = Flask(__name__)
app.secret_key = 'some_secret'


def send_message(message):
    print('******  Here the message from my form input  == ' + str(message))

@app.route('/', methods=["GET", "POST"])
def user():
    if request.method == "GET":
        print('I just issued a GET request!!!')

    if request.method == "POST":
        data = request.form
        message = data.get("message", "")
        if message:
            flash('This is your message ==   {} '.format(message))

        send_message(message)

    return render_template('index.html')


if __name__ == '__main__':
    app.run(port=5001, debug=True)
```

Here is a snippet of our index.html

```

            <form action="/" method="post" id="tweet_form" class="form-group" style="margin: 30px 15px;">
                <div class="form-group row">
                    <label for="message" class="col-form-label">Enter Tweet: </label>
                    <input type="text" id="tweet_graph" name="message" class="form-control" maxlength="140"
                           minlength="10" size="140">
                </div>
                <div class="form-group row">
                    <button type="submit" id="tweet_btn" class="btn btn-light">Tweet the Community Graph!</button>
                </div>
            </form>

```
## Expected Behavior

I expect this simple form to work remotely as it does locally. Being that I am very new to AWS and lambda, in general,
this might be a simple configuration issue. However, any guidance on this issue would be appreciated. 

## Actual Behavior

The app deploys and I can get to the form, but when I submit it, I  land on
 
https://xxxxxxxx.execute-api.us-east-1.amazonaws.com

{"message":"Forbidden"}

## Steps to Reproduce

1. Zappa init
2. Zappa deploy 
3. go to URL
4. enter form data.
5. click on submit.

## Your Environment

* Zappa version used: zappa==0.45.1

* Operating System and Python version: 
    Ubuntu 16.04 with Python 3.6

* The output of `pip freeze`:

```
argcomplete==1.9.2
base58==0.2.4
boto3==1.4.8
botocore==1.8.13
certifi==2017.11.5
cfn-flip==1.0.0
chardet==3.0.4
click==6.7
docutils==0.14
durationpy==0.5
Flask==0.12.2
future==0.16.0
hjson==3.0.1
idna==2.6
itsdangerous==0.24
Jinja2==2.10
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.19.0
MarkupSafe==1.0
pkg-resources==0.0.0
placebo==0.8.1
python-dateutil==2.6.1
python-slugify==1.2.4
PyYAML==3.12
requests==2.18.4
s3transfer==0.1.12
six==1.11.0
toml==0.9.3
tqdm==4.19.1
troposphere==2.1.2
Unidecode==0.4.21
urllib3==1.22
Werkzeug==0.13
wsgi-request-logger==0.4.6
zappa==0.45.1

```

* `zappa_settings.py`: '
```
{
    "devtest": {
        "app_function": "app.app",
        "aws_region": "us-east-1",
        "profile_name": "default",
        "project_name": "testportform",
        "runtime": "python3.6",
        "s3_bucket": "zappa-fqt1vggna"
    }


```

**Comment by LaundroMat** [comment]
It's probably a CSRF thing; I'm experiencing a similar problem. Can you check whether the csrf cookie is dropped?

**Comment by LaundroMat** [comment]
I solved it by explicitly setting the csrf cookie on the view that generates the page with the form on it. See #1291

**Comment by raymondbernard** [comment]
Gonna look at this further and will report back.   Thank you for your considerate and quick reply LaundroMat!

**Comment by raymondbernard** [comment]
I enabled CSRF in my app and form. 
imported CsrfProtect from flask_wtf forms. 
from flask import Flask, request,  flash, render_template
```

from flask_wtf import CsrfProtect

csrf = CsrfProtect()

app = Flask(__name__)

app.config.from_object('config')

csrf.init_app(app)
```


* new simpler form 
```

<form method="POST" action="/" id="message_form">
     <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <input type="text" name="message" value="testing 1 2 3" id="message_form" >
    <input type="submit" value="Submit form">
</form>
```
Didn't work. : (

**Comment by raymondbernard** [comment]
Ok, I figured it out !!! lol.  
Need to make the sure you call out the prefix of your AWS api path in the action field, so you are posting to the correct endpoint.
 action = '/<name of your prefix>'

so editing the below 
<form method="POST" action="/devtest" id="message_form">
worked for me!!!
