### ISSUE TITLE
Unsafe uses of temporary directory

### ISSUE THREAD

**Issue by rgov** [Miserlou/Zappa#1296]
In several location Zappa creates temporary directories by constructing paths rooted at `tempfile.gettempdir()`. The paths are likely predictable on some platforms due to subdirectory names that use to fixed strings or easily predictable values (such as the local time) This is risky behavior and is likely vulnerable to [TOCTTOU race conditions](https://en.wikipedia.org/wiki/Time_of_check_to_time_of_use).

From a quick audit, it looks like there are a few places where `tempfile` is used unsafely.

- In `zappa/letsencrypt.py`, encryption keys are written directly into the root temporary directory which seems very risky to me. These should definitely be changed to use a top-level temporary directory generated with `tempfile.mkdtemp()` which will have the correct permissions set.

- In `zappa/core.py`, it is used unsafely to populate `temp_project_path` and `temp_package_path`. These uses can be changed to simply use `tempfile.mkdtemp()` and the subsequent directory creation can be removed.

- In `zappa/core.py`, it is used to generate cache directories. Since it may be undesirable to re-populate the cache on every execution, maybe using `tempfile.mkdtemp()` is not the correct solution.

- In `zappa/cli.py`, it is used unsafely to download or copy an `account.key` file related to Let's Encrypt support.

**Comment by scoates** [comment]
Looks like this was fixed in #1299. Please reopen if not.
