### ISSUE TITLE
add code quality checker 

### ISSUE THREAD

**Issue by Xuefeng-Zhu** [Miserlou/Zappa#130]
It will be helpful to add code linter, like 
* Flake8
* https://github.com/integrations/sonarqube
* https://github.com/integrations/quantifiedcode
* https://github.com/integrations/codacy

**Comment by Miserlou** [comment]
Do you have a preferred service?

**Comment by Xuefeng-Zhu** [comment]
@Miserlou Actually, I did not have experience with these services, but https://github.com/integrations/codacy seems to be very promising.

**Comment by Miserlou** [comment]
Okay, I'm trying it out. I'm pretty opinionated about code, and a lot of these service favor terse idiomaticity over readability, which I don't. Let's see though..

**Comment by Miserlou** [comment]
Tried this, but disagree with the result: https://www.codacy.com/app/rich_3/Zappa/dashboard

**Comment by Xuefeng-Zhu** [comment]
The Code Style suggestion is a little bit weird.

**Comment by Xuefeng-Zhu** [comment]
I tried Quantifiedcode. The analysis result seems to be much better.
https://www.quantifiedcode.com/app/project/e6628bc59cc147dc8761b70538eb3502?groups=code_patterns%3A3P0qV6OB%3Af0,code_patterns%3AswQ4yi5C

**Comment by Miserlou** [comment]
Added QC and fixed a few of the issues. Thanks!
