### ISSUE TITLE
zappa schedule doesn't add CloudWatch event to the lambda Event source

### ISSUE THREAD

**Issue by kienpham2000** [Miserlou/Zappa#131]
It created the CloudWatch Rules but I have to update the CloudWatch Rules manually so that the event shows up in Event source of the lambda function. 

After I updated the Rules, the Event source is showing and the Scheduled event is triggering the function.

**Comment by Miserlou** [comment]
With latest from pip?

Are you talking about the keep warm or a custom event? A screenshot of the problem would be helpful here.

**Comment by kienpham2000** [comment]
latest from master. Custom event. 

Screenshot. You can see that the Custom event is using version 44. But the Lambda function doesn't have the Event source linked to it. My current workaround is to update the CloudWatch event manually and it will be linked at the Lambda function. 

![001](https://cloud.githubusercontent.com/assets/22681/15833108/0b8ba030-2bda-11e6-88e1-19249c625d75.jpg)

![002](https://cloud.githubusercontent.com/assets/22681/15833112/101f809e-2bda-11e6-9fba-9c4bc67b1c48.jpg)
