### ISSUE TITLE
Please clean up doppins branches

### ISSUE THREAD

**Issue by rgov** [Miserlou/Zappa#1312]
There are currently 187 branches for every minor update of every dependency, which degrades the usability of Git and GitHub.

Since these are not needed, please delete them.

    $ git branch -a | grep doppins | sed 's,remotes/origin/,,' | xargs -- git push -d origin

**Comment by scoates** [comment]
Looks legit to me. Any reason to not do this, @Miserlou?

**Comment by Miserlou** [comment]
Done so with `git branch -r --merged | grep -v master | sed 's/origin\///' | xargs -n 1 git push --delete origin`.

Closing now.
