### ISSUE TITLE
Dependency of python-slugify (Unidecode) is GPL licensed

### ISSUE THREAD

**Issue by mdodsworth** [Miserlou/Zappa#1320]
## Context

python-slugify was added to slugify the project name (here https://github.com/Miserlou/Zappa/commit/c0b86ca0df8c6d3ab0f5bd30ddbd99d4ccb19a6e). Although python-slugify is using the MIT license, it requires `Unidecode` which is GPL licensed. It's been deemed a non-issue for python-slugify (https://github.com/un33k/python-slugify/issues/7), but it'll likely still cause some people a little unnecessary heartburn when it shows up in their list of dependencies.

## Possible Fix

Given what functionality it's providing, seems like reinstating the original logic is reasonable.

**Comment by Miserlou** [comment]
Huh. That's interesting.
