### ISSUE TITLE
Certify with ACM not working

### ISSUE THREAD

**Issue by ayanguha** [Miserlou/Zappa#1321]
Here is my zappa settings:
"certificate_arn" : "arn:aws:acm:us-east-1:ACCOUNT_ID:certificate/GUID",
        "domain": "api.mydomain.com",

(of course masked)

I am running zappa certify, leading to following error:

`Traceback (most recent call last): File "/Users/ayan/myorg/myorg_env/lib/python2.7/site-packages/zappa/cli.py", line 2610, in handle sys.exit(cli.handle()) File "/Users/ayan/myorg/myorg_env/lib/python2.7/site-packages/zappa/cli.py", line 505, in handle self.dispatch_command(self.command, stage) File "/Users/ayan/myorg/myorg_env/lib/python2.7/site-packages/zappa/cli.py", line 610, in dispatch_command manual=self.vargs['manual'] File "/Users/ayan/myorg/myorg_env/lib/python2.7/site-packages/zappa/cli.py", line 1816, in certify self.zappa.update_route53_records(self.domain, dns_name) File "/Users/ayan/myorg/myorg_env/lib/python2.7/site-packages/zappa/core.py", line 1949, in update_route53_records is_apex = self.route53.get_hosted_zone(Id=zone_id)['HostedZone']['Name'][:-1] == domain_name File "/Users/ayan/myorg/myorg_env/lib/python2.7/site-packages/botocore/client.py", line 312, in _api_call return self._make_api_call(operation_name, kwargs) File "/Users/ayan/myorg/myorg_env/lib/python2.7/site-packages/botocore/client.py", line 579, in _make_api_call api_params, operation_model, context=request_context) File "/Users/ayan/myorg/myorg_env/lib/python2.7/site-packages/botocore/client.py", line 631, in _convert_to_request_dict params=api_params, model=operation_model, context=context) File "/Users/ayan/myorg/myorg_env/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit return self._emit(event_name, kwargs) File "/Users/ayan/myorg/myorg_env/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit response = handler(**kwargs) File "/Users/ayan/myorg/myorg_env/lib/python2.7/site-packages/botocore/handlers.py", line 586, in fix_route53_ids params[name] = orig_value.split('/')[-1] AttributeError: 'NoneType' object has no attribute 'split'`

Can anyone please help? 

I do not have a domain in Route 53, which is in the process of getting created. Can this be the reason?

Also, would really appreciate if the error msg is little more informative. I understand it is in botocore, not in zappa itself.

(I would like to take this opportunity to thank all contributors of zappa for saving my life more than once, and a happy new year to all in advance :))

* Zappa version used: 0.45.1
* Operating System and Python version: OSX, 2.7
* The output of `pip freeze`: 

pip freeze
aniso8601==1.3.0
argcomplete==1.9.2
base58==0.2.4
boto3==1.4.7
botocore==1.7.47
certifi==2017.11.5
chardet==3.0.4
click==6.7
docutils==0.14
durationpy==0.5
ecdsa==0.13
envs==1.2.4
Flask==0.12.2
flask-restplus==0.9.2
Flask-SQLAlchemy==2.3.2
functools32==3.2.3.post2
future==0.16.0
futures==3.1.1
hjson==3.0.1
idna==2.6
itsdangerous==0.24
Jinja2==2.10
jmespath==0.9.3
jose==1.0.0
jsonschema==2.6.0
kappa==0.6.0
lambda-packages==0.19.0
MarkupSafe==1.0
placebo==0.8.1
pycrypto==2.6.1
pycryptodome==3.3.1
PyMySQL==0.7.11
python-dateutil==2.6.1
python-jose-cryptodome==1.3.2
python-slugify==1.2.4
pytz==2017.3
PyYAML==3.12
request==0.0.22
requests==2.18.4
s3transfer==0.1.11
six==1.11.0
SQLAlchemy==1.1.15
toml==0.9.2
tqdm==4.19.1
troposphere==2.0.2
Unidecode==0.4.21
urllib3==1.22
warrant==0.6.0
Werkzeug==0.12.2
wsgi-request-logger==0.4.6
zappa==0.45.1

**Comment by nickpolet** [comment]
> I do not have a domain in Route 53, which is in the process of getting created. Can this be the reason?

What do you mean by this? If the certificate hasn't been verified yet, then you are going to get errors (which is somewhat to be expected). If you've sorted this out, please close this issue and explain what you did to resolve the issue.

**Comment by ayanguha** [comment]
the issue was resolved, once the proper domain was present
