### ISSUE TITLE
zappa install fails while collecting cfn_flip -> requires pytest-runner

### ISSUE THREAD

**Issue by cowgoat88** [Miserlou/Zappa#1339]
_pip install zappa_ fails while trying to collect _cfn_flip_
I was able to solve the issue with _pip install pytest-runner_, and then installing zappa.

## Expected Behavior
_pip install zappa_ should recognize _pytest-runner_ as a dependent package and install automatically

## Actual Behavior
pip install zappa
...
...
...
Collecting cfn_flip==1.0.0
  Using cached cfn_flip-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/pytest-runner/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) -- Some packages may not be found!
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) -- Some packages may not be found!
    No local packages or working download links found for pytest-runner
...
...
...
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/4l/r6m3plns4b5_5hbrd3t54dt40000gn/T/pip-build-pyjvv5jl/cfn-flip/

## Possible Fix
pip install pytest-runner

## Steps to Reproduce

1.
2.
3.

## Your Environment

* Zappa version used:
* Operating System and Python version:
max osx 
python3
* The output of `pip freeze`:
***after fixed***
argcomplete==1.9.2
base58==0.2.4
boto==2.48.0
boto3==1.5.9
botocore==1.8.23
certifi==2017.11.5
cfn-flip==1.0.0
chardet==3.0.4
click==6.7
Django==2.0.1
django-storages==1.6.5
docutils==0.14
durationpy==0.5
future==0.16.0
hjson==3.0.1
idna==2.6
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.19.0
placebo==0.8.1
pytest-runner==3.0
python-dateutil==2.6.1
python-slugify==1.2.4
pytz==2017.3
PyYAML==3.12
requests==2.18.4
s3transfer==0.1.12
six==1.11.0
toml==0.9.4
tqdm==4.19.1
troposphere==2.1.2
Unidecode==1.0.22
urllib3==1.22
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.45.1

**Comment by Miserlou** [comment]
This looks like `pypi`'s fault in this line: Download error on https://pypi.python.org/simple/pytest-runner/: [SSL: CERTIFICATE_VERIFY_FAILED]
