### ISSUE TITLE
No module named urls

### ISSUE THREAD

**Issue by nikssardana** [Miserlou/Zappa#1347]
I am trying to setup zappa with django using the tutorial explained in README
(https://edgarroman.github.io/zappa-django-guide/walk_core/)

After running zappa deploy dev and zappa update dev, I am getting an error message "No module Named urls"

## Expected Behavior
Standard Django 404 page

## Actual Behavior
Error page saying "ImportError: No module named urls"

* Zappa version used: 0.45.1
* Operating System and Python version:
Ubuntu 16.04, Python 2.7
* The output of `pip freeze`:
argcomplete==1.9.2
base58==0.2.4
boto3==1.5.12
botocore==1.8.26
certifi==2017.11.5
cfn-flip==1.0.0
chardet==3.0.4
click==6.7
Django==1.11
docutils==0.14
durationpy==0.5
future==0.16.0
futures==3.1.1
hjson==3.0.1
idna==2.6
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.19.0
placebo==0.8.1
python-dateutil==2.6.1
python-slugify==1.2.4
pytz==2017.3
PyYAML==3.12
requests==2.18.4
s3transfer==0.1.12
six==1.11.0
toml==0.9.4
tqdm==4.19.1
troposphere==2.1.2
Unidecode==1.0.22
urllib3==1.22
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.45.1

* Link to your project (optional):
* Your `zappa_settings.py`:

**Comment by cowgoat88** [comment]
This looks a django error.
Possible fix - add `from django.conf.urls import url, include` to your url.py files.

**Comment by efimerdlerkravitz** [comment]
and make sure the virtual env name is not identical to the project name

**Comment by nickpolet** [comment]
> and make sure the virtual env name is not identical to the project name

Just tested and this seems to be the reason. It should really be made more clear in the docs that you shouldn't name the virtualenv the same as the project. I seems to remember getting confused with this the first time I tried deploying.

**Comment by scoates** [comment]
Added a PR to include this in the documentation. However, Zappa itself does complain when you do this:

```
~/sctest$ zappa deploy
Calling deploy for stage dev..
Creating sctest-dev-ZappaLambdaExecutionRole IAM Role..
Creating zappa-permissions policy on sctest-dev-ZappaLambdaExecutionRole IAM Role.
Warning! Your project and virtualenv have the same name! You may want to re-create your venv with a new name, or explicitly define a 'project_name', as this may cause errors.
Downloading and installing dependencies..
Packaging project as zip.
…
```
