### ISSUE TITLE
uncaught exception in StopIteration (similar to #960)

### ISSUE THREAD

**Issue by teledyn** [Miserlou/Zappa#1349]
My app appears to work, but instead of returning a result to the browser, I get

`"{u'message': u'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.', u'traceback': ['Traceback (most recent call last):\\n', '  File \"/var/task/handler.py\", line 452, in handler\\n    response = Response.from_app(self.wsgi_app, environ)\\n', '  File \"/tmp/pip-build-mcJLe3/Werkzeug/werkzeug/wrappers.py\", line 903, in from_app\\n', '  File \"/tmp/pip-build-mcJLe3/Werkzeug/werkzeug/test.py\", line 903, in run_wsgi_app\\n', '  File \"/tmp/pip-build-mcJLe3/Werkzeug/werkzeug/wsgi.py\", line 704, in __next__\\n', 'StopIteration\\n']}"`

## Context
Using Python 2.7 under Ubuntu 17.10, but I'm new to lambda and python so it is likely there is just some part I am not understanding in the process.  I had created the virtualenv, then run zappa init and zappa deploy dev 

The app is fairly simple, it fetches data via google api, stores the result to dynamo using batch puts, exits

## Expected Behavior
I hit the given URL in google chrome.
After fetching data from google and logging to dynamo, I expect a json result from a call to the lambda function

## Actual Behavior
the fetching and logging appear to happen, but I get the traceback dumped to the browser.

## Possible Fix
I'm not certain I am returning the proper result from the lambda_handler -- my app is returning
 return {
        'statusCode': '400' if err else '200',
        'body': err.message if err else json.dumps(res),
        'headers': {
            'Content-Type': 'application/json',
        },
    }

## Your Environment
* Zappa version used: zappa==0.45.1
* Operating System and Python version: ubuntu 17.10 with Python 2.7.14
* The output of `pip freeze`:
argcomplete==1.9.2
base58==0.2.4
boto3==1.5.13
botocore==1.8.27
certifi==2017.11.5
cfn-flip==1.0.0
chardet==3.0.4
click==6.7
docutils==0.14
durationpy==0.5
future==0.16.0
futures==3.1.1
google-api-python-client==1.6.4
hjson==3.0.1
httplib2==0.10.3
idna==2.6
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.19.0
oauth2client==4.1.2
placebo==0.8.1
pyasn1==0.4.2
pyasn1-modules==0.2.1
python-dateutil==2.6.1
python-slugify==1.2.4
PyYAML==3.12
requests==2.18.4
rsa==3.4.2
s3transfer==0.1.12
six==1.11.0
toml==0.9.4
tqdm==4.19.1
troposphere==2.1.2
Unidecode==1.0.22
uritemplate==3.0.0
urllib3==1.22
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.45.1

* Link to your project (optional):
* Your `zappa_settings.py`: 
{
    "dev": {
      "app_function": "gaprocess.lambda_handler",
	  "keep_warm": false,
      "aws_region": "us-east-1", 
      "profile_name": "default", 
      "project_name": "analytics", 
      "runtime": "python2.7", 
      "s3_bucket": "hunchlambda",
	  "log_level": "DEBUG",
	  "slim_handler": false,
	  "timeout_seconds": 30
    }
}

**Comment by teledyn** [comment]
so much for my theory, I realized my return result wasn't necessary, all I needed was to return 'request', so I put a print statement just before the return, it prints, and the error then perhaps occurs after the handler returns?

**Comment by teledyn** [comment]
I upgraded to Werkzeug 0.14.1, same error, and zappa install/upgrade rolls it back to 0.12

**Comment by teledyn** [comment]
I commented out all the guts of my app leaving only a return statement and still get the error. version mismatch somewhere?

**Comment by teledyn** [comment]
fresh trivial application:
1) virtualenv ztest
2) cd ztest; source bin/activate
3) pip install zappa
4) zappa init

Okay, here's your zappa_settings.json:

{
    "dev": {
        "app_function": "hellolambda.lambda_handler", 
        "aws_region": "us-east-1", 
        "profile_name": "default", 
        "project_name": "ztest", 
        "runtime": "python2.7", 
        "s3_bucket": "zappa-thb9oojxf"
    }
}

5) zappa deploy
Deployment complete!: 

but the same error. 
6) pip freeze
argcomplete==1.9.2
base58==0.2.4
boto3==1.5.18
botocore==1.8.32
certifi==2017.11.5
cfn-flip==1.0.0
chardet==3.0.4
click==6.7
docutils==0.14
durationpy==0.5
future==0.16.0
futures==3.1.1
hjson==3.0.1
idna==2.6
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.19.0
placebo==0.8.1
python-dateutil==2.6.1
python-slugify==1.2.4
PyYAML==3.12
requests==2.18.4
s3transfer==0.1.12
six==1.11.0
toml==0.9.4
tqdm==4.19.1
troposphere==2.1.2
Unidecode==1.0.22
urllib3==1.22
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.45.1

**Comment by scoates** [comment]
`app_function` should point to a wsgi-compatible app (like a Flask `app` instance), not Lambda+API Gateway function, directly (Zappa wraps the WSGI app with its own lambda handler). It looks like your function is trying to return something that Lambda knows how to handle, not something Zappa knows how to handle.

Also, if you do `zappa tail` as the error message suggests, it should reveal a little more about what's going on (we don't necessarily want to expose more-sensitive info like this to the browser).
