### ISSUE TITLE
Non-string value in zappa_settings.environment_variables caused AttributeError

### ISSUE THREAD

**Issue by sshopov** [Miserlou/Zappa#1351]
Dear Zappatistas, 

I came across this minor thing: I had the following in my zappa_settings.json
`"environment_variables": {"FLASK_DEBUG": 0}`
I tried `zappa update dev` and got back 
```
ValueError("The following environment variables are not strings: {}".format(", ".join(non_strings)))
ValueError: The following environment variables are not strings: FLASK_DEBUG
``` 
followed by 
```
print("Error: {}".format(e.message))
AttributeError: 'ValueError' object has no attribute 'message'
```

It worked fine with:
`"environment_variables": {"FLASK_DEBUG": "0"}`

## Expected Behavior
Should properly report error without crashing. 

## Actual Behavior
Throws an exception about the exception. 

## Possible Fix
in cli.py line 1478
replace             
```raise ValueError("The following environment variables are not strings: {}".format(", ".join(non_strings)))```
with 
```raise ValueError("The following environment variables are not strings: {}".format(", ".join([str(non_string) for non_string in non_strings])))```

Also, it seems like ValueError does not have a message attribute, but can be printed like so str(e)

## Your Environment
* Zappa version used: 0.45.1
* Operating System and Python version: Windows10 Python3.6

**Comment by scoates** [comment]
Python 3 problem (works in Python 2). Will PR a fix.

**Comment by Miserlou** [comment]
:D

**Comment by jonbesga** [comment]
This is still an issue.

I'm getting:

`The following environment variables are not strings: DEBUG`

When settings an environment variable `"DEBUG": true`
