### ISSUE TITLE
Database Connection Caching/Reuse

### ISSUE THREAD

**Issue by ajaska** [Miserlou/Zappa#1354]
Hi, I've been using Zappa for a few different projects and it's been awesome except for one pain point in that having to re-establish a database connection on each request can be a bit expensive. 

I've seen a [hacky solution](https://www.jeremydaly.com/reuse-database-connections-aws-lambda/) for this, but that doesn't feel great and I don't know how the underlying mechanisms work (or how I'd go about this in Python).

I imagine this is a fairly common issue and was wondering if there were any best practices or suggestions around this.

**Comment by scoates** [comment]
Zappa doesn't handle database calls. Your app instantiation code can create database connections that can be persistent between calls, but there's nothing we can do if the container gets destroyed and recreated. That's just how serverless stuff works.

**Comment by ajaska** [comment]
Yeah, that makes sense to me. To clarify -- do I need to be doing anything special to achieve that sort of behavior? Do we have any ideas in general around how often containers get re-used vs destroyed?

**Comment by scoates** [comment]
I'm not particularly familiar with Django, so I won't have good advice, there, but in a simple Flask example, if you have `"app_function": "your_module.app"` in Zappa settings, you'd want something like this:

```python
# file:your_module.py
from flask import Flask
app = Flask(__name__)

# set up some stuff that will live for `app`'s lifespan, and doesn't run per-request
run_some_code_during_app_creation(app)

# Zappa's wsgi handler picks up your app object here

```

**Comment by ajaska** [comment]
Oh, that's a lot simpler than I thought. Thanks!
