### ISSUE TITLE
Enhancement request: Introduce Payload Compression options (AWS API Gateway)

### ISSUE THREAD

**Issue by ignacioHermosilla** [Miserlou/Zappa#1360]
## Context
Enhancement request: Introduce new available feature for AWS API Gateway:  [Payload Compression for an API ](https://aws.amazon.com/about-aws/whats-new/2017/12/amazon-api-gateway-supports-content-encoding-for-api-responses/?sc_channel=em&sc_campaign=Launch_RN20180110&sc_publisher=aws&sc_medium=em_&sc_content=launch_la_nontier1&sc_country=&sc_geo=&sc_category=mult&sc_outcome=launch&mkt_tok=eyJpIjoiTlRGa01tSTJPV1prTlRSaCIsInQiOiI4ZXVJMDk3ZmxaMm5oVGlDY21QUXZ3MnVyQ0tkZlFNM2UyanFmVUk4cjhLYUxSQklkNXhnaTZVVmZLNlZLQkowYUZ6VWs2c2RNaFpZWTl6NFo4dTZQWHk5R1FobXhkaENOMDVSTGJoWDh1SzJcLzJFOEU3RzhoSkJDUlhxSm5NTGEifQ%3D%3D)

## Expected Behavior
Be able to enable/disable the Payload Compression and set the [minimumCompressionsSize](https://docs.aws.amazon.com/apigateway/api-reference/resource/rest-api/#minimumCompressionSize) property related to that option.

## Actual Behavior
Unsupported

## Possible Fix
I can create a pull request with the implementation but I would like to discuss the names first.
My proposal are:

- payload_compression: True/False (default False)

- payload_minimum_compression_size: In bytes (0 to 10485760)

**Comment by rgov** [comment]
I think the documentation should reference security trade-offs with regard to the [CRIME attack](https://en.wikipedia.org/wiki/CRIME).
