### ISSUE TITLE
Tracking for MOSS initiatives

### ISSUE THREAD

**Issue by gene1wood** [Miserlou/Zappa#1364]
Rich, congratulations on your [Mozilla Open Source Support award](https://blog.mozilla.org/blog/2018/01/23/moss-q4-supporting-python-ecosystem/)!

How can we, the users of zappa, best track and follow the three initiatives you're planning to work on with this award that you called out, "Production Mode", "Server-less Microservice Library" and "Backlog"?

I'd also be curious to know the timeline of these initiatives so we know what to expect?

I see [this GitHub project](https://github.com/Miserlou/Zappa/projects/1) for Production Mode, should we use the GitHub projects function to track these 3 initiatives?

**Comment by Miserlou** [comment]
Yep, I'm going to be trying to use GitHub projects for at least the first milestone. I've never used GH projects before but it seems adequate for the task.

Heavy lifting will begin around Feb 1.

**Comment by gene1wood** [comment]
Looks like this didn't work out which is a shame. The [GitHub `Production Mode` project](https://github.com/Miserlou/Zappa/projects/1) didn't make progress and the Mozilla Open Source award was never collected as the first milestone wasn't completed.
