### ISSUE TITLE
Settings for hook event when `zappa deploy <something>`?

### ISSUE THREAD

**Issue by MU-Software** [Miserlou/Zappa#1373]
## Context
It's just like `git hooks`, if someone do something, scripts that mapped to that event in `zappa_settings.json` will be executed before (or 'and after') update. For example, There are bunch of images to compress before deploy, but I'm feeling too lazy to do that every time i update. If there are settings for hook on update, we can just do `zappa update production` and Voila! Everything will be done automatically!
So, Are there any settings like this?

## Expected Behavior
Execute scripts when do deploy/update/rollback or etc

## Actual Behavior
`None` ~maybe~

## Possible Fix
I really want to know :-P

**Comment by scoates** [comment]
Check out `callbacks` in `zappa_settings.json`. For this, you probably want to hook `zip`. [More info in the README](https://github.com/Miserlou/Zappa/blob/master/README.md#package).

The signature is `def settings(zappa_cli):` where `zappa_cli` is an instance of [ZappaCLI](https://github.com/Miserlou/Zappa/blob/master/zappa/cli.py#L73).
