### ISSUE TITLE
Add support for .gitignore

### ISSUE THREAD

**Issue by ojengwa** [Miserlou/Zappa#1383]
Automatically ignore paths in the .gitignore module or add support for something similar (like .dockerignore)

Currently, one has to manually add the paths to the `exclude` key.

**Comment by mcrowson** [comment]
Why would this be beneficial? I can't imagine those two files take up too much space in the package.

**Comment by Miserlou** [comment]
The thing is, it's quite possible you'd want the package to include something that's being ignored by git ( a credentials file, etc.). Exclude remains for now. Mayyyybe we could support a .zappaignore but I hate adding new forms of cruft.

**Comment by ojengwa** [comment]
I think it is certainly better than having to specify the paths in the `exclude` key. As it is, the `exclude` key is redundant (+maintainance cost) because one will mostly want to exclude same paths as defined in the `.gitignore` file anyway.
