### ISSUE TITLE
500 error when testing dev

### ISSUE THREAD

**Issue by umerm368** [Miserlou/Zappa#1384]
"{u'message': u'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.', u'traceback': ['Traceback (most recent call last):\\n', '  File \"/var/task/handler.py\", line 452, in handler\\n    response = Response.from_app(self.wsgi_app, environ)\\n', '  File \"c:\\\\users\\\\umer\\\\appdata\\\\local\\\\temp\\\\pip-build-jnugeu\\\\Werkzeug\\\\werkzeug\\\\wrappers.py\", line 903, in from_app\\n', '  File \"c:\\\\users\\\\umer\\\\appdata\\\\local\\\\temp\\\\pip-build-jnugeu\\\\Werkzeug\\\\werkzeug\\\\test.py\", line 884, in run_wsgi_app\\n', \"TypeError: 'NoneType' object is not callable\\n\"]}"
my zappa_setting.json
{
    "dev": {
        "app_function": "predictions.app",
        "aws_region": "us-east-1",
        "profile_name": "default",
        "project_name": "python-app-for-",
        "runtime": "python2.7",
        "s3_bucket": "zappa-07mh9iuct",
        "slim_handler": true
    }
}

**Comment by mcrowson** [comment]
The nonetype is not callable error is usually due to the project not finding a package required in the app. Does your virtualenv that you deployed/updated from contain all of the required packages?

**Comment by umerm368** [comment]
yes its contain all the packages.
but when i run from curl
its give ImportError
can you please guide me how can i fix this issue...

**Comment by nickpolet** [comment]
Can you print out the error that you get from "zappa tail". This is definitely a package missing. Print out your requirements.txt file (or "pip freeze"). I've encountered some packages not being able to run on Lambda a while ago. Ended up writing my own implementations of the packages causing issues.

Or, the packages are just not being sent to the Lambda function properly. Either way, going to need more info on the issue, like logs etc...
