### ISSUE TITLE
can't make 2 events in same s3 bucket

### ISSUE THREAD

**Issue by sshkim** [Miserlou/Zappa#1389]
## Expected Behavior
Created s3:ObjectCreated:* event schedule for {name}!

## Actual Behavior
s3:ObjectCreated:* event schedule for {name} already exists - Nothing to do here.

## Possible Fix
to make multiple event in s3

## Your Environment
setting file is like below

{
  "service1": {
    "events": [
      {
        "function": "name",
        "event_source": {
          "arn": "arn:aws:s3:::bucket",
          "key_filters": [
            {
              "type": "prefix",
              "value": "service1/"
            }
          ],
          "events": [
            "s3:ObjectCreated:*"
          ]
        }
      }
    ]
  },
  "service2": {
    "events": [
      {
        "function": "name",
        "event_source": {
          "arn": "arn:aws:s3:::bucket",
          "key_filters": [
            {
              "type": "prefix",
              "value": "service2/"
            }
          ],
          "events": [
            "s3:ObjectCreated:*"
          ]
        }
      }
    ]
  }
}

**Comment by efimerdlerkravitz** [comment]
It's a duplicate of https://github.com/Miserlou/Zappa/issues/1319 , I think you can close this one
