### ISSUE TITLE
Can't unschedule from latest master

### ISSUE THREAD

**Issue by kienpham2000** [Miserlou/Zappa#139]
$ zappa unschedule staging
Unscheduling..
unschedule_events() takes exactly 4 arguments (2 given)

**Comment by Miserlou** [comment]
Damn! Very good catch, this shouldn't have even made it through testing.

**Comment by Miserlou** [comment]
Really dumb bug, should at least be surface-fixed but I don't know if it's actually functional yet.

Did you figure out the syntax for doing events OTHER than scheduled tasks?
