### ISSUE TITLE
Remove old boto dependancy

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/Zappa#14]
Zappa currently uses two versions of boto. (This is the result of me reusing code from an old project).

It's just the code related S3, so it should be easy enough to replace with boto3 S3 stuff.

**Comment by vascop** [comment]
I'll pick this up if that's alright

**Comment by Miserlou** [comment]
Please, be my guest! Much appreciated!

**Comment by Miserlou** [comment]
Also could be a really great time to start integrating https://github.com/spulec/moto into our tests..

**Comment by mathom** [comment]
I was about to make this issue :smiley: 

Give me a ping if you need a hand with anything!

**Comment by vascop** [comment]
Can this be closed?

**Comment by mathom** [comment]
Yep, thanks!
