### ISSUE TITLE
Upload Zip Error

### ISSUE THREAD

**Issue by zkanda** [Miserlou/Zappa#141]
Hello,
I'm trying to deploy my application but I'm having this error.
```
An error occurred (InvalidRequest) when calling the CreateMultipartUpload operation: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
```

This is for `eu-central-1`, which supports lambda.

**Comment by Miserlou** [comment]
Haven't seen that one before! Thanks for reporting.

**Comment by zkanda** [comment]
@Miserlou I'm didn't try yet on other regions, but this can be related https://github.com/boto/boto3/issues/181.
Commenting out the `Callback` on upload works though.
```
s3.meta.client.upload_file(
    source_path, bucket_name, dest_path,
    # Callback=progress.update
)
```

The exception block doesn't seem to work as well.

**Comment by zkanda** [comment]
Seems this is fix in `django-zappa`, tried the master branch and there's no more error.
