### ISSUE TITLE
I am not able to do deploy operation

### ISSUE THREAD

**Issue by thanuj11** [Miserlou/Zappa#1413]
I TRIED TO DEPLOY MY DJANGO APPLICATION USING ZAPPA. AND MY DEPLOYMENT SAYS SUCCESSFUL AND WHEN I TRIED TO CHECK THE URL IT SAYS UNHANDLED EXCEPTION OCCURRED.

THIS IS ERROR THAT IS SHOWING UP WHEN I TRIED TO VIEW THE URL
"{'message': 'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.', 'traceback': ['Traceback (most recent call last):\\n', '  File \"/var/task/handler.py\", line 452, in handler\\n    response = Response.from_app(self.wsgi_app, environ)\\n', '  File \"/var/task/werkzeug/wrappers.py\", line 903, in from_app\\n    return cls(*_run_wsgi_app(app, environ, buffered))\\n', '  File \"/var/task/werkzeug/wrappers.py\", line 57, in _run_wsgi_app\\n    return _run_wsgi_app(*args)\\n', '  File \"/var/task/werkzeug/test.py\", line 884, in run_wsgi_app\\n    app_rv = app(environ, start_response)\\n', \"TypeError: 'NoneType' object is not callable\\n\"]}"

I AM USING PYTHON 3.6.1

## Expected Behavior
I WANT TO REACH TO THE HOME PAGE OF MY URL

## Steps to Reproduce

1.
2.
3.

## Your Environment

* Zappa version used:
* Operating System and Python version:
* The output of `pip freeze`:
* Link to your project (optional):
* Your `zappa_settings.py`:

**Comment by scoates** [comment]
From Slack, it looks like this was resolved. Closing. Please reopen with useful information if not.
