### ISSUE TITLE
How to upload big files?

### ISSUE THREAD

**Issue by weasteam** [Miserlou/Zappa#1419]
In django, I need to upload big files. To create a better user experience, I am using `@task` to asyn the file uploading, but I got `payload is too large`.

## Context
In my code, I am using Python 3.6. and Django Rest Framework. File data is POST as base64 encoded string. 

Once the API received the file, it files an task to write the file into S3.

It looks like the Lambda function can only take files smaller than 6M, and the async Lambda function can only take files smaller than 128K.
https://www.stackery.io/blog/RequestEntityTooLargeException-aws-lambda-message-invocation-limits/

In this case, how can I upload big files?

## Expected Behavior
Able to upload big files.

## Actual Behavior
500 Error on upload big files.

## Possible Fix
not sure yet.

## Steps to Reproduce
1. Go to https://stratospark-serverless-uploader.s3.amazonaws.com/index.html
2. Select a big file.

## Your Environment 
All are the newest version install in last week.
* Operating System and Python version: AWS Lambda 3.6

**Comment by Miserlou** [comment]
You're doing this the wrong way round - have the file uploads go straight to S3, then have that S3 event invoke your zappa function.

**Comment by weasteam** [comment]
Would you give me an example on how to do that?

**Comment by Miserlou** [comment]
https://github.com/Miserlou/Zappa#executing-in-response-to-aws-events

We should have an example for that use case on the blog but we don't, apparently. I've talked about this in my DjangoCon talk with example.

**Comment by scoates** [comment]
For what it's worth, you can even have end users upload directly to S3 through a [signed form](https://docs.aws.amazon.com/AmazonS3/latest/dev/HTTPPOSTForms.html).

**Comment by weasteam** [comment]
thanks a lot @Miserlou @scoates , I will go with @scoates 's solution.
