### ISSUE TITLE
Cannot cloudform an s3 event to trigger lambdas created with zappa package

### ISSUE THREAD

**Issue by brianrower** [Miserlou/Zappa#1421]
The s3 trigger functionality in zappa relies on the S3 notification configuration having a name matching the name of the function in your code that you want connected to the s3 trigger.

Example:
Your zappa settings has:
```{
  "dev": {
    "project_name": "my-project",
    ...
    "events": [
      {
        "function": "main.my_s3_handler",
        "event_source": {
          "arn": "arn:aws:s3:::this-is-my-bucker",
          "events": [
            "s3:ObjectCreated:*"
          ]
          ...
```
The s3 events configuration must be named "my-project:main.my_s3_handler" or zappa won't know what to do with the event.

That's fine if you're using `zappa deploy` because zappa deploy handles creating that event configuration with the correct name for you, however, if you're using zappa package, and want to cloud form the s3 event notification configuration, there's a problem: cloudformation doesn't allow you to set the name of the configuration, it just gives you a guid for the name.

## Possible Fix
Pull request coming soon.

## Your Environment
* Zappa version used: 0.45.1
* Operating System and Python version: Ubuntu 16.04, Python 3.6.1

**Comment by scoates** [comment]
Fixed in #1422
