### ISSUE TITLE
feature request: "status" command

### ISSUE THREAD

**Issue by monkeypants** [Miserlou/Zappa#143]
Something like `zappa status foo` command would be cool, if it told me interesting stuff about my current deployment environment (vs. current code).

What I really need is the endpoint of my deployed code (because I don't have a CNAME yet for my new code and I forgot the URL upload told me last night). That's why I went back to docs to learn how to ask, and was surprised that I couldn't find a way.

But thinking about it, I'd also like to know if the app is not-yet-deployed, deployed-and-clean (same as local) or deployed and dirty (different to local). And about the configuration (do I have a logging group, etc?). I'm sure there's a bunch of potentially useful information that could make it's way into a status command.

**Comment by Miserlou** [comment]
+1

I like this idea and it should be fairly easy to implement. Getting the URL of the existing deployed instance actually isn't as it seems, at least I haven't found an API in boto to do that. 

Detecting if the code is behind the current locally deployed package is interesting and would be very useful, but I'm not sure how to go about doing that without maintaining state. Any ideas?

**Comment by monkeypants** [comment]
plenty of unhelpful ideas, glad you asked. For example, if you can query state, can you upload deltas too? :) 

I understand why local state won't work, but what if state was stored as s3 metadata? zappa_*

**Comment by dtenenba** [comment]
I would also like this. I am stuck trying to find the endpoint of my deployment, I didn't note  it from the last time I was working on it. And in the console, Amazon API Gateway shows I have no APIs (which doesn't seem right) and Lambda shows I have no lambda functions. Yet I was able to `zappa update dev` successfully.

In the absence of this feature, is there some way I can discover my endpoint URL?

On a possibly related note, `zappa --help` shows there is a subcommand called `invoke` but `zappa invoke dev` returns:

```
'ZappaCLI' object has no attribute 'invoke'
```

Not sure what this subcommand is supposed to do, but maybe something that would indicate the endpoint url?

**Comment by Miserlou** [comment]
Preliminary 'status' command is now available in 0.19.5. 'Update' contains the API GW url as well now.
