### ISSUE TITLE
Strange error message with zappa

### ISSUE THREAD

**Issue by moon-chilled** [Miserlou/Zappa#1439]
I'm trying out zappa, with it automanaging aws roles/everything.  When I `zappa update`, it gives me a url which when I visit it just gives me `{"message": "Internal server error"}`.  `zappa tail` gives me this error message: Unable to import module 'handler': attempted relative import with no known parent package.

Here's my zappa_settings.json:

```json
{                                                                                                                                      
    "dev": {
        "app_function": "bsbbs.app",
        "aws_region": "us-west-2",
        "project_name": "bsbbs",
        "runtime": "python3.6",
        "s3_bucket": "bsbbs-zappa"
   }
}
```

And here's my main file:

```python
from flask import Flask                                                                                                                
  
app = Flask(__name__)

@app.route("/")
def slash():
    return "It's a BSBBS!"

if __name__ == "__main__":
    app.run()
```

I'm on python3.6, in a virtualenv, on arch.  Pip freeze output:

```
click==6.7
Flask==0.12.2
itsdangerous==0.24
Jinja2==2.10
MarkupSafe==1.0
Werkzeug==0.14.1
```

URL: https://58dy8s6y4m.execute-api.us-west-2.amazonaws.com/dev/

**Comment by Elronnd** [comment]
(Note: it works fine if I run it on localhost with regular python so it must be a zappa/lambda problem)

**Comment by Miserlou** [comment]
If your file called bsbbs.py?

**Comment by Elronnd** [comment]
Yep.

**Comment by Miserlou** [comment]
Where are you calling Zappa from?

should be:
```
$ ls 
bsbbs.py zappa_settings.json
$ zappa deploy
```

**Comment by Elronnd** [comment]
I'm calling zappa update, not deploy (deploy says I've already deployed), and I also have an 'env' dir (for the virtualenv) and a requirements.txt, but aside from that yep.

**Comment by madeddie** [comment]
@Elronnd how come you pip freeze doesn't show zappa? Could you try installing zappa into your virtualenv and trying again?
