### ISSUE TITLE
Way to limit concurrent executions?

### ISSUE THREAD

**Issue by vvalorous** [Miserlou/Zappa#1445]
## Context
Recovering from rouge script issue and trying to see if there was a mechanism within Zappa deployment to set concurrent executions on a per function basis.

Python 2.7/3.6 -->
2.7

## Expected Behavior
A setting variable within the settings_file to able to add/limit concurrent execution limit on the deployed functions.

## Your Environment

* Zappa version used: 0.45.1
* Operating System and Python version:

**Comment by efimerdlerkravitz** [comment]
You can do it through the aws. Have a look at https://aws.amazon.com/blogs/compute/managing-aws-lambda-function-concurrency/

**Comment by domingohui** [comment]
It would be great to be able to control the concurrency limit via the Zappa settings file as well :D

**Comment by aqt01** [comment]
+1 I'm also waiting for this great feature!

**Comment by snowman2** [comment]
Related to #1628

**Comment by snowman2** [comment]
Addressed in #1989
