### ISSUE TITLE
Zappa doesn't include env/lib64 files during zipping

### ISSUE THREAD

**Issue by cidzor** [Miserlou/Zappa#149]
Zappa will process libraries found in the env/lib folder (as in virtualenv env), but not in the env/lib64 folder.

This is reproducible by doing <code>zappa deploy dev</code> inside of an AWS EC2 AMI instance after doing <code>pip install</code> to get any 64-bit version libraries.

**Comment by Miserlou** [comment]
This is a great bug, can you give me a specific package this happens on so
i can write a fix and a test?

From my phone..

**Comment by sc6** [comment]
In particular, <code>pip install python-ldap</code>. This was done while inside a virtualenv on a AWS EC2 AMI instance.

**Comment by Miserlou** [comment]
I think this is fixed, please verity though.
