### ISSUE TITLE
[DISCUSS ME] Try to detect 'stale' pyc files

### ISSUE THREAD

**Issue by collingreen** [Miserlou/Zappa#150]
zappa only packages .pyc files, but if you have not actually run your code since the last change (for example, making a settings-only update), your code will look right but your .pyc files will not be updated before zappa happily packs them up and deploys them to lambda, which ends up being a really confusing bug to chase down.

Correctly 'detecting stale pyc files' is no easy task, but maybe we can prevent this particular situation by first walking the file tree for .py files and, if no matching .pyc exists or if it does but the modified time is older than the .py, shouting during deploy/update that things look a bit wonky. This might pair with a settings option to suppress this warning or add a whitelist for it if there are actual use cases where this is intended.

Does this make sense? Is this missing anything seriously important about the .py <-> .pyc relationship?

**Comment by Miserlou** [comment]
I think this is already addressed: https://github.com/Miserlou/Zappa/blob/master/zappa/zappa.py#L352

Is that not a satisfactory solution?

**Comment by Miserlou** [comment]
Gonna close this, feel free to reopen!

**Comment by collingreen** [comment]
That seems like a very reasonable solution (aside from the comment implying the reverse order - the code looks right though). Maybe I'm wrong about how I ran into this issue. Will try to reproduce -- leave closed until proven otherwise.
