### ISSUE TITLE
Tag release commits with version in repository for easier code browsing/inspection

### ISSUE THREAD

**Issue by mattaustin** [Miserlou/Zappa#1502]
## Context
This issue is git / github / repository / release process related, rather than a bug in zappa code.

## Expected Behavior
Most projects tag their release commits with the version so that changes/diffs/checkouts of code is made easy for users. E.g. if I want to see code changes made between versions (or between the latest released version and 'master') using the `git diff` command, I can use tags rather than commit hashes (a lot more user friendly).

## Actual Behavior
Github shows no tags on this repository.

## Possible Fix
Please tag historical release commits with version and push. Update release process to include tagging new versions.

**Comment by Miserlou** [comment]
Yeah, I should do this properly.  You can see the released versions as the ones which have version numbers in the commit messages though.

**Comment by scoates** [comment]
@miserlou: in case it's helpful:

```bash
for c in `git log --all --grep='^0\.' | grep commit | awk {'print $2'}`; do
    git show $c | head -n5 > /tmp/gitlogmsg; VER=$(cat /tmp/gitlogmsg | tail -n1 | awk {'print $1'})
    git tag v$VER $c
    rm /tmp/gitlogmsg
done
```

**Comment by scoates** [comment]
I just ran this and then `git push --tags upstream`:

![](http://scoates-captured.s3.amazonaws.com/bXta6RBf.png)

👍  closing
