### ISSUE TITLE
Feature request: Include custom domain base path mapping on zappa settings

### ISSUE THREAD

**Issue by alexandrefvb** [Miserlou/Zappa#1504]
## Context
When deploying an application using zappa there is no option to specify the base path mapping on API gateway custom domain configuration. With this limitation it is not possible to use the same domain to deploy different APIs changing only the  base path.

## Expected Behavior

If a user want to deploy an API using an existing domain in a different base path he specifies the base_path option in zappa settings stage configuration and zappa create/update base path mappings according to this configuration. 

## Actual Behavior

There is no option to make this configuration.

## Possible Fix

Include an option on stages configuration to specify the base path to use on custom domain mapping.
Change certify command to do the base path mapping configuration on AWS API Gateway.

## Steps to Reproduce

N/A

## Your Environment

N/A

**Comment by cl1ent** [comment]
i think this issue can be closed. the feature has been merged in (see above).
just use the `base_path` option in your apps config. its also documented in the readme:


`"base_path": "your-base-path", // Optional base path for API gateway custom domain base path mapping. Default None.`

**Comment by alexandrefvb** [comment]
It was resolved in PR #1505
