### ISSUE TITLE
govcloud deployment option

### ISSUE THREAD

**Issue by mark-hoffmann** [Miserlou/Zappa#1519]
## Context

Govcloud now supports everything needed to deploy a Zappa stack. There are a couple of changes that need to be made to the source code to correctly process a deployment to govcloud.

## Expected Behavior

Should be able to specify us-gov-west-1 and have a successful deployment.

## Actual Behavior

An error occurs when activating the CloudFormation stack in S3. The error is as follows:
`*** botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the CreateStack operation: S3 error: All access to this object has been disabled`
This occurs during the call in core.py on line 1884 in the `self.cf_client.create_stack()` function. 

The original problem occurs because the url being passed into the create_stack() function is pointing to `https://s3.amazonaws.com/<bucket_name>/<template_name>.json` as opposed to `https://s3-us-gov-west-1.amazonaws.com/<bucket_name>/<template_name>.json`.

If you fix that url being passed, it begins to create the stack appropriately, however, it does not complete. In the CloudFormation logs it complains about the API Gateway gateway resource attempting to deploy using "Edge" configuration, which appears not to be available in govcloud. Instead, we would need to specify in our template for API Gateway to use "Regional" as the EndpointConfiguration like so:

"Api":{"Properties":{"Description":"Created automatically by Zappa.","Name":"zappa-test-dev"},"Type":"AWS::ApiGateway::RestApi","Properties" : {"EndpointConfiguration" : {"Types" : ["REGIONAL"]}, "Name" : "zappa-test-dev"}}

As opposed to what is currently being generated, which is:

"Api":{"Properties":{"Description":"Created automatically by Zappa.","Name":"zappa-test-dev"},"Type":"AWS::ApiGateway::RestApi"}

Resources:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-restapi-endpointconfiguration.html
https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/govcloud-abp.html

I am not sure if doing just those two things will fully fix govcloud integration, however, it is a good start.

Once implemented, we can probably also remove the aws region warnings that are prompted on in `load_credentials()` in core.py.

## Possible Fix

1. Update s3 url if using a govcloud region that gets passed into self.cf_client.create_stack() on line 1884 in core.py
2. Update the creation of CloudFormation template if using govcloud to explicitly use "REGIONAL" instead of defaulting to "EDGE" as shown above

## Steps to Reproduce

1. Initialize project with a region of us-gov-west-1 in zappa_settings.json file
2. Make bare minimum hello world flask app
3. zappa deploy <stage>

## Your Environment

* Zappa version used: 0.45.1
* Operating System and Python version: macOS High Sierra 10.13.3
* The output of `pip freeze`: argcomplete==1.9.2
base58==0.2.4
boto3==1.7.29
botocore==1.10.29
certifi==2018.4.16
cfn-flip==1.0.3
chardet==3.0.4
click==6.7
docutils==0.14
durationpy==0.5
Flask==1.0.2
Flask-Cors==3.0.4
future==0.16.0
hjson==3.0.1
idna==2.6
itsdangerous==0.24
Jinja2==2.10
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.19.0
MarkupSafe==1.0
placebo==0.8.1
python-dateutil==2.6.1
python-slugify==1.2.4
PyYAML==3.12
requests==2.18.4
s3transfer==0.1.13
six==1.11.0
toml==0.9.4
tqdm==4.19.1
troposphere==2.3.0
Unidecode==1.0.22
urllib3==1.22
Werkzeug==0.14.1
wsgi-request-logger==0.4.6
zappa==0.45.1

* Link to your project (optional):
* Your `zappa_settings.py`: 
{
    "dev": {
        "app_function": "main.app",
        "aws_region": "us-gov-west-1",
        "profile_name": "default",
        "project_name": "zappa-test",
        "runtime": "python3.6",
        "s3_bucket": "zappa-test",
        "keep_warm":false,
        "use_precompiled_packages": true,
        "manage_roles": false,
        "role_name": "<my_custom_role>",
        "role_arn": "<my_custom_role_arm>",
        "environment_variables": {
            "LOCATION" : "aws"
        }
    }
}

**Comment by Miserlou** [comment]
This is an excellent ticket!

Obviously, I have no familiarity with GovCloud, but would be happy to add support for it. However, how can I test and verify that it works without access to it? 

Did you try your proposed fixes? If you send a PR I'd be happy to merge it, but I'd rather not publish/advertise this support without anybody actually ever trying it.

**Comment by mark-hoffmann** [comment]
I would be more than happy to test out whatever is needed. I will try and get the changes into a PR, but first I need to become a little more familiar with the codebase before I do so since it would be touching a number of different components.  I was just hardcoding what I needed as I was debugging. Will keep you updated with PR progress though.

**Comment by mark-hoffmann** [comment]
I fixed the code and tested deploying my test app through govcloud and everything seemed to go smoothly. I can reach my endpoint just fine.

Pull Request: https://github.com/Miserlou/Zappa/pull/1523

**Comment by mark-hoffmann** [comment]
Pull Request was merged and closed
