### ISSUE TITLE
Update to support werkzeug >= 0.12

### ISSUE THREAD

**Issue by aminhusni** [Miserlou/Zappa#1526]
> Could not find a version that matches werkzeug==0.12,>=0.14
> - Werkzeug [required: ==0.12, installed: 0.14.1]
 This is colliding with everything that is using the new version. 

## Your Environment

* Zappa version used: 0.45.1
* Operating System and Python version: Ubuntu 16.04 TLS
* The output of `pip freeze`: 
`absl-py==0.2.2
argcomplete==1.9.2
astor==0.6.2
base58==0.2.4
bleach==1.5.0
boto3==1.7.35
botocore==1.10.35
certifi==2018.4.16
cfn-flip==1.0.3
chardet==3.0.4
click==6.7
docutils==0.14
durationpy==0.5
Flask==1.0.2
future==0.16.0
gast==0.2.0
grpcio==1.12.1
h5py==2.8.0
hjson==3.0.1
html5lib==0.9999999
idna==2.6
itsdangerous==0.24
Jinja2==2.10
jmespath==0.9.3
kappa==0.6.0
Keras==2.2.0
Keras-Applications==1.0.2
Keras-Preprocessing==1.0.1
lambda-packages==0.19.0
Markdown==2.6.11
MarkupSafe==1.0
numpy==1.14.4
pandas==0.23.0
placebo==0.8.1
protobuf==3.5.2.post1
python-dateutil==2.6.1
python-slugify==1.2.4
pytz==2018.4
PyYAML==3.12
requests==2.18.4
s3transfer==0.1.13
scipy==1.1.0
six==1.11.0
tensorboard==1.8.0
tensorflow==1.8.0
termcolor==1.1.0
toml==0.9.4
tqdm==4.19.1
troposphere==2.3.0
Unidecode==1.0.22
urllib3==1.22
Werkzeug==0.14.1
wsgi-request-logger==0.4.6
zappa==0.45.1`

**Comment by paulclarkaranz** [comment]
This is fixed [on master](https://github.com/Miserlou/Zappa/blob/master/requirements.txt#L22) but not on PyPI yet.

**Comment by paulclarkaranz** [comment]
This can be closed.

**Comment by apoclyps** [comment]
@paulclarkaranz any updates on which this may be fixed on PyPI?
