### ISSUE TITLE
Bring basic support for AWS China

### ISSUE THREAD

**Issue by LKI** [Miserlou/Zappa#1564]
## Context

I've tried to setup zappa in AWS China, and noticed that we lacked support for AWS China.

I want to know if someone is working on it?

If currently there is nobody working on it, may I work on some PR to bring basic supports for AWS China.

## Expected Behavior

AWS China is isolated from AWS Global, there are only two regions in AWS China (cn-north-1/cn-northwest-1)
We may have these functionality for basic support:

- [ ] a clear 5-minutes demo
- [ ] some document about the region differences

## Actual Behavior

Currently it's not possible to deploy zappa on AWS China if not customizing zappa.

## Possible Fix

Main obstacles are:

* lack of AWS functionality. Route53/ACM/Edge-optimized API/EnvironmentVariablesFeature/... are not available in AWS China. (#1553 )
* arn difference. resources for AWS China starts with "arn:aws-cn". (#1338 )
* encoding. the `kappa` package ran into error if system encoding is not utf-8. (https://github.com/garnaat/kappa/pull/126)

## More

Welcome to leave any comment under this issue.

**Comment by ArnoldGitHub** [comment]
Hi Lirian,

It is nice to know someone also want to deploy to AWS China.

I also want to deploy to AWS China using Zappa.

However, I’ve got official reply from one of the AWS sales, that they don’t support CloudFront in AWS China. In which I believe CloudFront is one of the most important modules for deploying via Zappa?

If there is any help that I can contribute to bring Zappa to run on AWS China, please let me know, and I’m glad to work on it.

Regards,
Arnold

**Comment by LKI** [comment]
Hi @ArnoldGitHub ,

It's true that CloudFront is unavailable in AWS China, we use other CDN alternatives (qiniu).
So I plan to disable these absent AWS modules during zappa deploy. (CloudFront, Route53, etc...)

Currently I'm trying to deploy to AWS China by customizing zappa.
After that, I may submit some PRs, and it's very nice to have you review/re-test the code.

Thanks~

**Comment by staneslevski** [comment]
Hi @LKI 

Did you make any progress on this? I'm currently finding the same problem because zappa is not suitable for AWS China.

Thanks.

**Comment by LKI** [comment]
Hi @staneslevski ,

I didn't work on this issue now.
We choose self-hosted k8s cluster for better control (which cost more).

More ~~outdated~~ information which may helps:
I successfully deployed zappa to AWS China after I made these changes:
- Disable Route53/ACM/EnvironmentVariables
- Adjust arn names the same way as `us-gov-west-1`
- Pass ICP Recordal by submitting a case

Thanks.

**Comment by staneslevski** [comment]
Hi Lirian, 

Thanks very much for your answer, I’ll do a deeper dive into Zappa and see if I can get it to work. 

Best regards, 

Tom

**Comment by saern** [comment]
@LKI When you suggest `Disable Route53/ACM/EnvironmentVariables`, exactly how did you go about doing this? As I get the error `EnvironmentVariablesFeature is not supported in cn-northwest-1 region`

**Comment by LKI** [comment]
@saern I fork the repo and add some `if` statements. You can search `us-gov` in source codes, and modify in same logic.

one of the Environment Variables modify point: [core.py](https://github.com/Miserlou/Zappa/blob/84e80471a390a4f03a54d8db592f0a462d3ccac6/zappa/core.py#L1073)

one of the us-gov if statement: [core.py](https://github.com/Miserlou/Zappa/blob/84e80471a390a4f03a54d8db592f0a462d3ccac6/zappa/core.py#L1558)

**Comment by linjungz** [comment]
Hi @LKI , I'm also trying to deploy Zappa for AWS China region and thanks for your sharing of the modification. As Route53/ACM/EnvironmentVariables are all available now,  is it possible that you could re-open this issue so that we could move on to make Zappa support China region? Thanks
