### ISSUE TITLE
Upgrade or lift pip max version requirement

### ISSUE THREAD

**Issue by nixjdm** [Miserlou/Zappa#1588]
## Context
Zappa cannot currently be installed with the most modern released version of pip, which right now it 18.0. Zappa has the restriction `pip<=10.1.0,>=9.0.1`. I do not know if zappa is actually incompatible with pip 18.0, but presumably a change in the tests would determine this pretty easily.

## Expected Behavior
You'd be able to install with modern pip.

## Actual Behavior

```
zappa 0.46.2 has requirement pip<=10.1.0,>=9.0.1, but you'll have pip 18.0 which is incompatible.
```

## Possible Fix
Changing https://github.com/Miserlou/Zappa/blob/master/requirements.txt#L13 to either `pip>=9.0.1, <=18.0`, or `pip>=9.0.1`

## Steps to Reproduce
if pip and zappa are installed:
`pip install -U pip`

or if zappa isn't installed yet:
`pip install -U pip; pip install zappa`

**Comment by CurroRodriguez** [comment]
@nixjdm Are you taking care of this? I did a quick scan of the project, and I saw `pip` is imported at: https://github.com/Miserlou/Zappa/blob/master/zappa/core.py#L475, but I don't see it being used at all. Instead, `pip` is being called through `subprocess`, in which case, it shouldn't matter the version of `pip` installed on the machine. It looks like the import is some dead code.

**Comment by nixjdm** [comment]
@CurroRodriguez I was going to let the issue sit for a bit for discussion, but since you asked, here you go #1594! I preferred the solution of removing the upper limit to the version number.

I do see the `import pip` in that one location, but also the comment for it. https://github.com/Miserlou/Zappa/blob/12ac82e71deeffcb03dbb6549be4f6f60d537382/zappa/core.py#L473-L475

I don't know what that means in context, but it's certainly enough to deter me from messing with it. If removing that is warranted, it'd be better in it's own issue.

Lifting the version upper limit was all I was really after here.

**Comment by gregroberts** [comment]
Trying to install zappa in a virtualenv will fail unless you:

- initialise the virtualenv with --no-pip
- activate virtualenv
- download get-pip.py
- run `python get-pip.py pip==9.....`
- pip install zappa


+1 for removing upper version limit in requirements.txt!
