### ISSUE TITLE
Quart incompatiblity

### ISSUE THREAD

**Issue by gaul** [Miserlou/Zappa#1589]
I cannot deploy a simple quart application to AWS:

```python
#!/usr/bin/env python3

from quart import Quart

app = Quart(__name__)

@app.route("/")
def func() -> str:
    return "text"
```

```
$ cat zappa_settings.json 
{
    "dev": {
        "app_function": "githubwatch.app",
        "aws_region": "us-west-2",
        "profile_name": "default",
        "project_name": "githubwatch",
        "runtime": "python3.6",
        "s3_bucket": "zappa-79287bsxw"
    }
}

$ zappa update
(pip 18.0 (/home/gaul/.virtualenvs/githubwatch/lib/python3.6/site-packages), Requirement.parse('pip<=10.1.0,>=9.0.1'), {'zappa'})
Calling update for stage dev..
Warning! Your project and virtualenv have the same name! You may want to re-create your venv with a new name, or explicitly define a 'project_name', as this may cause errors.
Downloading and installing dependencies..
 - yarl==1.2.6: Using locally cached manylinux wheel
 - typed-ast==1.1.0: Using locally cached manylinux wheel
 - multidict==4.3.1: Using locally cached manylinux wheel
 - aiohttp==3.3.2: Using locally cached manylinux wheel
 - sqlite==python36: Using precompiled lambda package
Packaging project as zip.
Uploading githubwatch-dev-1534366852.zip (14.8MiB)..
100%|█████████████████████████████████████████████████████████████████████████████████| 15.5M/15.5M [00:07<00:00, 2.01MB/s]
Updating Lambda function code..
Updating Lambda function configuration..
Uploading githubwatch-dev-template-1534366866.json (1.6KiB)..
100%|███████████████████████████████████████████████████████████████████████████████████| 1.62K/1.62K [00:05<00:00, 313B/s]
Deploying API Gateway..
Scheduling..
Unscheduled githubwatch-dev-zappa-keep-warm-handler.keep_warm_callback.
Scheduled githubwatch-dev-zappa-keep-warm-handler.keep_warm_callback with expression rate(4 minutes)!
Error: Warning! Status check on the deployed lambda failed. A GET request to '/' yielded a 500 response code
```

The CloudFront logs contain the inscrutable:

```
__call__() takes 2 positional arguments but 3 were given 
```

Any suggestions on how to debug this further?  This works correctly when using Flask.

**Comment by scoates** [comment]
have you tried resolving this? 
> Warning! Your project and virtualenv have the same name! You may want to re-create your venv with a new name, or explicitly define a 'project_name', as this may cause errors.

**Comment by gaul** [comment]
After changing my venv name I encounter the same symptoms.

**Comment by kamyarghasemlouDH** [comment]
I have the same issue:
```Traceback (most recent call last):
	File "/var/task/handler.py", line 505, in handler
    	response = Response.from_app(self.wsgi_app, environ)
    File "/var/task/werkzeug/wrappers.py", line 939, in from_app
    	return cls(*_run_wsgi_app(app, environ, buffered))
    File "/var/task/werkzeug/test.py", line 923, in run_wsgi_app
    	app_rv = app(environ, start_response)
    File "/var/task/zappa/middleware.py", line 70, in __call__
    	response = self.application(environ, encode_response)
	TypeError: __call__() takes 2 positional arguments but 3 were given
```

**Comment by scoates** [comment]
From the [Quart README](https://gitlab.com/pgjones/quart/blob/master/README.rst):
> Quart is designed to be fully compatible with the Flask public API

However, [`quart.Quart.__call__()`](https://gitlab.com/pgjones/quart/blob/master/quart/app.py#L1656) is incompatible with [`flask.flask.__call__()`](https://github.com/pallets/flask/blob/master/flask/app.py#L2305):

> `def __call__(self, scope: dict) -> Union[Callable, 'Quart']:`

> `def __call__(self, environ, start_response):`

If it were me, I'd probably try to make a FlaskCompatibleQuart that inherits Quart and fixes this, but I'm not sure it's possible without digging in a lot more than I have time for.

I don't necessarily think it's a good idea for Zappa itself to support another API without lots of traction.

**Comment by scoates** [comment]
Going to close this one, since this seems to be (from their own doc; it's *not* compatible with Flask) a problem with Quart.

Willing to reconsider if other maintainers disagree.

**Comment by kamyarghasemlouDH** [comment]
Thanks for the quick response @scoates .
Will try to get it running by your FlaskCompatibleQuart suggestion, will update this comment if I get it working. might also open a ticket for Quart for this incompatibility.
Thanks again :)

**Comment by kamyarghasemlouDH** [comment]
I implemented the `FlaskCompatibleQuart` as:
```
class FlaskCompatibleQuart(Quart):
    def __call__(self, environ, start_response):
        logger.info(str(environ))
        environ['type'] = 'http'
        return super(FlaskCompatibleQuart, self).__call__(environ)
```
but more errors kept happening, we have decided that zappa+async probably would not be worth the invested time, so abandoning it.
Hope this might help someone down the road. :)

**Comment by sunnysid3up** [comment]
I'm going through a similar thing with FastAP, which is also an async framework. The log says `__call__() missing 1 required positional argument: 'send'` :(
