### ISSUE TITLE
warn before deploy if zappa is not locally installed (or handle it)

### ISSUE THREAD

**Issue by collingreen** [Miserlou/Zappa#160]
Right now the deployed code will break with an import error if zappa is not installed in the virtual environment. This could be caught during deploy time and either cause the commit to abort or use the global zappa instead.

Could also bring the zappa handler out into its own package and only ship that in the lambda zip to save a little space and automatically handle it being in the virtualenv.

**Comment by Miserlou** [comment]
Is this related to https://github.com/Miserlou/Zappa/issues/159?

**Comment by collingreen** [comment]
Yes, it is exactly that problem. #159 is closed because the problem was identified but this could help reduce future confusion.

**Comment by Miserlou** [comment]
This seems to be fixed.
