### ISSUE TITLE
"exception_handler" does not work.

### ISSUE THREAD

**Issue by ohjeyong** [Miserlou/Zappa#1609]
### **"When I set custom handler in zappa_settings, it isn't applied."**

I found this when I set sentry setting in django project.
I installed zappa_sentry and then, set exception_handler just like below.
````
{
    "production": {
        ...
        "exception_handler": "zappa_sentry.unhandled_exceptions",
        ...
    }
}
````
Then, enter command "zappa update production", and I raise error on purpose.
In zappa tail,
````
Traceback (most recent call last):
  File "/var/task/django/core/handlers/exception.py", line 34, in inner
  response = get_response(request)
  File "/var/task/django/core/handlers/base.py", line 156, in _get_response
  response = self.process_exception_by_middleware(e, request)
  File "/var/task/django/core/handlers/base.py", line 154, in _get_response
  response = response.render()
  File "/var/task/django/template/response.py", line 106, in render
  self.content = self.rendered_content
  File "/var/task/django/template/response.py", line 81, in rendered_content
  template = self.resolve_template(self.template_name)
  File "/var/task/django/template/response.py", line 65, in resolve_template
  return get_template(template, using=self.using)
  File "/var/task/django/template/loader.py", line 19, in get_template
  raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: admin/change_list__.html
````
However, there was no error report in sentry.

So I made custom handler like this,
````
something.py

def handle_error(e, exception, context):
    print("BOOOOOOOM!")
    return False
````
then I set exception_handler in zappa_settings to 'something.handle_error'.
I raise error on purpose and see zappa tail production.
I expect "BOOOOOOOM" and traceback, but there is no "BOOOOOOOM" print, just traceback above.
When I set handle_error function return True, still zappa tail print same traceback above.
Even I set exception_handler like this random string,
````
{
    "production": {
        ...
        "exception_handler": "qwer",
        ...
    }
}

````
still zappa tail print same traceback above.

Of course, I enter command "zappa update production" before every test and I even tried redeploy(zappa undeploy production, and zappa deploy production), but still same.

## Expected Behavior

custom exception handler applied.

## Actual Behavior

Any exception handler doesn't applied.

## Steps to Reproduce

1. set exception_handler in zappa_settings to any custom handler
2. raise error
3. see zappa_tail or sentry or any method that can verify whether exception_handler works. 

## Your Environment

* Zappa version used: 0.46.1, 0.46.2 (I tested two versions, and still same result.)
* Operating System and Python version: Docker lambci/lambda:build-python3.6
* The output of `pip freeze`:
argcomplete==1.9.3
Babel==2.6.0
base58==1.0.0
boto==2.49.0
boto3==1.7.74
botocore==1.12.4
certifi==2018.8.24
cfn-flip==1.0.3
chardet==3.0.4
click==6.7
coolsms-python-sdk==2.0.3
Django==2.1.1
django-phonenumber-field==2.0.1
django-storages==1.7
djangorestframework==3.8.2
djangorestframework-camel-case==1.0b1
docutils==0.14
durationpy==0.5
future==0.16.0
hjson==3.0.1
idna==2.7
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.20.0
phonenumbers==8.9.13
placebo==0.8.2
psycopg2-binary==2.7.5
pycryptodome==3.6.6
python-dateutil==2.7.3
python-dotenv==0.9.1
python-slugify==1.2.4
pytz==2018.5
PyYAML==3.12
raven==6.9.0
requests==2.19.1
s3transfer==0.1.13
six==1.11.0
toml==0.9.6
tqdm==4.19.1
troposphere==2.3.3
Unidecode==1.0.22
urllib3==1.23
Werkzeug==0.14.1
wsgi-request-logger==0.4.6
zappa==0.46.2
zappa-sentry==0.2.3
* Link to your project (optional):
* Your `zappa_settings.py`: 
{
    "production": {
        "aws_region": "ap-northeast-2",
        "django_settings": "config.settings.production",
        "project_name": "blahblah",
        "runtime": "python3.6",
        "s3_bucket": "blahblah",
        "certificate_arn": "blahblah",
        "domain": "blahblah",
        "vpc_config": {
            "SubnetIds": ["blahblah"],
            "SecurityGroupIds": ["blahblah"]
        },
        "exception_handler": "qwer",
        "environment_variables": {
            "SENTRY_DSN": "blahblah"
        }
    }
}

**Comment by jneves** [comment]
Hi,

your issue is caused by django is not passing the exception up to sentry. Either configure django to not "eat" the exception or use the standard sentry integration with django: https://docs.sentry.io/clients/python/integrations/django/

If no one else proposes a PR on zappa_sentry, I'll add it to the docs (I'm the maintainer).

**Comment by ohjeyong** [comment]
@jneves Thanks. I solve this problem by setting sentry integration according to sentry doc, and set default transport as HTTPTransport. You are right. Django handle every unhandled exception in django code, so that lambda_handler can't get exception. Thanks a lot!!
