### ISSUE TITLE
Keep getting "File exists" error on Amazon Linux when creating ZIP

### ISSUE THREAD

**Issue by subratbasnet** [Miserlou/Zappa#163]
It worked fine on OSX, but when I tried to do it on Amazon Linux (since Lambda uses Amazon Linux, wanted binaries to be compatible), I get the following issue. It's almost like ".zip" is missing in the filename

Could it be a memory issue since it works fine on OSX with 8GB RAM vs 1 GB RAM on Amazon Linux.

```
(env_microservices)[ec2-user@ip-10-5-5-243 webservices_root]$ ls
api.py  config  env_microservices  __init__.py  lib  microservices.py  middleware  requirements_microservices.txt  resources  zappa_settings.json
(env_microservices)[ec2-user@ip-10-5-5-243 webservices_root]$ cat zappa_settings.json
{
    "dev": {
       "s3_bucket": "[redacted]",
       "app_function": "microservices.app",
       "debug": true
    }
}

(env_microservices)[ec2-user@ip-10-5-5-243 webservices_root]$ free -m
             total       used       free     shared    buffers     cached
Mem:           995        616        378          0         35        455
-/+ buffers/cache:        125        869
Swap:         1023          0       1023

(env_microservices)[ec2-user@ip-10-5-5-243 webservices_root]$ zappa update dev
Packaging project as zip...
**[Errno 17] File exists: '/tmp/1467423037'**
```

**Comment by Miserlou** [comment]
That's interesting. I really need to have an Amazon Linux test box, I use OSX locally. 

The filename is supposed to be based on the unixtime stamp, so that is a funny one. Maybe the way that zip files are created/updated is different on OSX and Linux?

If you are compiling open-source binaries for lambda, please consider contributing them back to lambda-packages!

**Comment by mjgorman** [comment]
Ran into the same issue today on Amazon Linux, trying to see if some SSL issue with boto s3 session are related to libs from OSX, Memory shouldn't be related I'm on a c4.large instance.

**Comment by mjgorman** [comment]
Looks like this is an issue with the copy in both systems. OSX will just move on where as linux refuses to copy to a directory that exists. Looks like the distutils copy_tree does work, however when i implemented and tested there doesn't isn't an ignore/exclude like shutil's implementation... so you end up zipping the zip you are creating, bloating file size a bunch.

**Comment by fermuch** [comment]
I just tried Zappa for the first time and found this bug while executing `zappa deploy dev`.

**Comment by fermuch** [comment]
I just tried using this implementation of copytree http://stackoverflow.com/a/22331852/1151683 and it seems to work well. All tests are passed, and the resulting zip size is correct.

**Comment by mjgorman** [comment]
@Miserlou Made a PR with the implementation @fermuch found added via a helper module. Probably needs a little more testing, but wanted to at least get it up there for review. #203

**Comment by Miserlou** [comment]
Merged in @mjgorman's PR and added a test. Cracking!
