### ISSUE TITLE
error at initializing zappa

### ISSUE THREAD

**Issue by prashantbaditya** [Miserlou/Zappa#1630]
## Context
received error while initializing zappa

## Steps to Reproduce

1.
2.
3.

## Your Environment

![error](https://user-images.githubusercontent.com/43376906/46337272-c5032f80-c64a-11e8-830c-0759b2db3f87.JPG)

**Comment by swedishmike** [comment]
Which version of Python are you running this under? Is it the same version you installed pip installed Zappa with initially?

I think you get this error if you run code for Python 2.7 under Python 3.6.

The correct syntax for this under Python 3.6 should be

`os.chmod(temp_settings.name, 0o644)`

**Comment by swedishmike** [comment]
@prashantbaditya  Which version of Zappa are you running?

I just checked the code for cli.py here: https://github.com/Miserlou/Zappa/blob/master/zappa/cli.py and that contains `os.chmod(temp_settings.name, 0o644)` and not  `os.chmod(temp_settings.name, 0644)` as in your case.

If you try a `pip install -U zappa` in your virtual environment - does that help with your issue?

**Comment by prashantbaditya** [comment]
current python version is 3.7 which is the latest and for zappa, I used below commands to install:
pip install django zappa
I tried pip install -U zappa as menioned above and received below error
![error1](https://user-images.githubusercontent.com/43376906/46344251-2d0f4100-c65e-11e8-9380-5d1dda29af29.JPG)

**Comment by swedishmike** [comment]
Since AWS Lambda currently only supports Python 2.7 and 3.6 I would recommend that you install 3.6 instead (or alongside) of Python 3.7 and use that.

The error message you are getting also seems to indicate that there is something wrong with your Python installation.

**Comment by prashantbaditya** [comment]
Thanks @swedishmike ...It worked...

**Comment by swedishmike** [comment]
Glad to hear that it works for you now. If all's ok - are you good to close this issue?

**Comment by prashantbaditya** [comment]
yes
