### ISSUE TITLE
Feature: Add option for API Gateway custom access logging

### ISSUE THREAD

**Issue by snowman2** [Miserlou/Zappa#1665]
## Context
API Gateway supports access logging:
![image](https://user-images.githubusercontent.com/8699967/47169094-3fc57f00-d2c8-11e8-8cd8-830638303e64.png)

## Possible Solution

Maybe provide options:
- access_logging (boolean)
- access_logging_log_format (optional, with default provided)
- access_logging_cloudwatch_group (optional, with default provided)

See [this link](https://forum.serverless.com/t/how-to-setup-custom-access-logging-for-api-gateway-using-serverless/3288/5) with a solution at the bottom comment.

**Comment by trollefson** [comment]
I am interested in a PR @snowman2
