### ISSUE TITLE
How I can support one authmodule for both local develop and serverless environment

### ISSUE THREAD

**Issue by jjuu** [Miserlou/Zappa#1677]
My application is restful, authorized with a token named "s_token", that in header.
Some of my APIs need auth with token, but others not.
I want to verify the token if necessary. Or, I just need to get the "user_id".

So I want to know if there is a solution for this.
1. Can I mark which methods need verified, and which are not. 
    Or I do this in the api gateway authorizer
2. To use the same authorizer for the local flask, what do I need to do.
3. The login_required decorator, means the method should be verified.

**Comment by paulclarkaranz** [comment]
If you want to use the same code paths when deployed and locally then just don't use an authorizer lambda and use a flask module. Once you get it working locally it should work just fine deployed without any configuration changes in Zappa.
