### ISSUE TITLE
Exit Code 0 on Exception

### ISSUE THREAD

**Issue by gricey432** [Miserlou/Zappa#169]
Zappa returns a 0 exit code when the operation fails, causing my Jenkins to mark the build as success even though it failed.

My specific example is calling
`zappa deploy dev`
when the lambda function already exists, which results in
`An error occurred (ResourceConflictException) when calling the CreateFunction operation: Function already exist: testfunction`
zappa then exits with a 0 status and the Jenkins build passes

**Comment by Miserlou** [comment]
Excellent bug! Would love to know more about your Zappa/Jenkins setup.

**Comment by gricey432** [comment]
Sure, so at the moment our release process for staging and production is using Jenkins to package up our program and then use Salt Stack to distribute it to EC2 instances.
I am setting it up so that it packages up our Pyramid app and deploys it on Lambda / API Gateway, Zappa seemed a pretty perfect fit, so I'm just trying it out.
The Jenkins setup itself is pretty simple, just an EC2 instance with a job. This way every time someone pushes to Bitbucket, Jenkins should use Zappa to build and release to staging.
Here's the job config, if you're interested:
`
PYENV_HOME=$WORKSPACE/.pyenv/

# Delete previously built virtualenv
if [ -d $PYENV_HOME ]; then
    rm -rf $PYENV_HOME
fi

# Create virtualenv
virtualenv --no-site-packages $PYENV_HOME
. $PYENV_HOME/bin/activate

# Install auth package
pip install --quiet -e $WORKSPACE/auth/auth_server/

# Install Zappa
pip install --quiet zappa

# Build and dist
cd auth/auth_server
#zappa deploy dev  # For initial deploy
zappa update dev  # For updating deployment
`

**Comment by Miserlou** [comment]
Oh, great! Thanks for sharing this!

Did you try Pyramid with Zappa manually yet? I haven't tried that yet myself, I'd like to know if there's any Pyramid-specific stuff that could benefit from documentation.

**Comment by gricey432** [comment]
I'm having a hard time trying to figure out how I'm supposed to port over my `.ini` file with all my pyramid config and database connection strings over to Zappa.
In #43 there is talk about a `zappa.ini` file, but I can't see anything in the instructions or the code about `.ini` files at all

**Comment by Miserlou** [comment]
I'd recommend pegging Zappa to a known 'good' version for you during the pip install --quiet zappa. Nothing is guaranteed as stable until we get a 1.0.0 though!

**Comment by Miserlou** [comment]
A simple fix for this should be pushed in the latest Zappa version, 0.19.4. I don't think it's perfect but at least it's something.

Thanks for reporting this!

**Comment by gricey432** [comment]
@Miserlou if you're still interested, I never got Pyramid working with Zappa and just switched to Flask
