### ISSUE TITLE
slim_hanlder = true, Still -> (InvalidParameterValueException) when calling the UpdateFunctionCode operation: Unzipped size must be smaller than 262144000 bytes

### ISSUE THREAD

**Issue by LourdesMoran** [Miserlou/Zappa#1693]
## Summary:
slim_handler = true in zappa_settings not working as expected. Can't deploy or update a large project.
 
## Context
I am using Python 3.6, Zappa 0.47.0.  Running Zappa inside docker a container 'lambci/lambda:build-python3.6'. Project size is around 250 MB.

## Expected Behaviour
As per the docs, setting slim_handler to true should trigger creation of a small handler file and the rest of the project should be loaded from S3 at run time.

## Actual Behavior
The Error:
 + zappa update stage1 --zip s3://my-bucket/build.zip
zbuild_1  | Calling update for stage stage1..
zbuild_1  | Updating Lambda function code..
zbuild_1  | Oh no! An error occurred! :(
zbuild_1  | 
zbuild_1  | ==============
zbuild_1  | 
zbuild_1  | 
zbuild_1  | ==============
zbuild_1  | 
zbuild_1  | Need help? Found a bug? Let us know! :D
zbuild_1  | File bug reports on GitHub here: https://github.com/Miserlou/Zappa
zbuild_1  | And join our Slack channel here: https://slack.zappa.io
zbuild_1  | Love!,
zbuild_1  |  ~ Team Zappa!
zbuild_1  | Traceback (most recent call last):
zbuild_1  |   File "/var/lang/lib/python3.6/site-packages/zappa/cli.py", line 2710, in handle
zbuild_1  |     sys.exit(cli.handle())
zbuild_1  |   File "/var/lang/lib/python3.6/site-packages/zappa/cli.py", line 508, in handle
zbuild_1  |     self.dispatch_command(self.command, stage)
zbuild_1  |   File "/var/lang/lib/python3.6/site-packages/zappa/cli.py", line 555, in dispatch_command
zbuild_1  |     self.update(self.vargs['zip'], self.vargs['no_upload'])
zbuild_1  |   File "/var/lang/lib/python3.6/site-packages/zappa/cli.py", line 924, in update
zbuild_1  |     num_revisions=self.num_retained_versions
zbuild_1  |   File "/var/lang/lib/python3.6/site-packages/zappa/core.py", line 1104, in update_lambda_function
zbuild_1  |     response = self.lambda_client.update_function_code(**kwargs)
zbuild_1  |   File "/var/lang/lib/python3.6/site-packages/botocore/client.py", line 320, in _api_call
zbuild_1  |     return self._make_api_call(operation_name, kwargs)
zbuild_1  |   File "/var/lang/lib/python3.6/site-packages/botocore/client.py", line 623, in _make_api_call
zbuild_1  |     raise error_class(parsed_response, operation_name)
zbuild_1  | botocore.errorfactory.InvalidParameterValueException: An error occurred (InvalidParameterValueException) when calling the UpdateFunctionCode operation: Unzipped size must be smaller than 262144000 bytes

## Steps to reproduce
zappa update stage1 --zip s3://my-bucket/build.zip

## My Zappa settings (.yml):

common:
  django_settings: django_project.settings
  lambda_description: The Cloud API
  runtime: python3.6
  slim_handler: true
  timeout_seconds: 300

stage1:
  aws_region: us-east-1
  debug: true
  extends: common
  keep_warm: false
  log_level: DEBUG
  manage_roles: false
  memory_size: 1024
  profile_name: default
  project_name: django-project
  role_name: my-role
  s3_bucket: my-bucket

**Comment by gloriamacia** [comment]
@LourdesMoran why has this issue been closed? Which command did you run to solve it?
