### ISSUE TITLE
Lambda now supports python 3.7

### ISSUE THREAD

**Issue by jgissend10** [Miserlou/Zappa#1710]
https://aws.amazon.com/blogs/compute/python-3-7-runtime-now-available-in-aws-lambda/

**Comment by adulion** [comment]
could we get an ETA on zappa supporting 3.7?

**Comment by chris-erickson** [comment]
See #1581 for one attempt.

**Comment by purificant** [comment]
Proposed patch: https://github.com/Miserlou/Zappa/pull/1762

**Comment by jgissend10** [comment]
https://github.com/Miserlou/Zappa/pull/1762 is merged!
