### ISSUE TITLE
Support for Lambda layers

### ISSUE THREAD

**Issue by jgissend10** [Miserlou/Zappa#1716]
Lambda now supports layers and custom run times: https://aws.amazon.com/blogs/aws/new-for-aws-lambda-use-any-programming-language-and-share-common-components/

With this the lambda libs could be a layer and no longer a dep that has to be deployed.

**Comment by jhorman** [comment]
Has anyone attempted to manually create a base layer, and then `exclude` as much as possible when deploying?

**Comment by deejvince** [comment]
I used zap package to prepare a clean Zappa archive, I had to move the content of that archive inside a /python sub directory to support where lambda layers look for the layer content - and the. Uploaded the new zip as a layer manually.
I then created a new function referencing the new layer and was able to run a flask app in the lambda environment while kicking it off from the Zappa handler in the layer.
Wish there was a setting to make package or even deploy directly to lambda layer

**Comment by farridav** [comment]
Implementing the ability to include layers (#1752 ) is a great start, though beyond that, perhaps automatically packaging up all project dependencies into a separate layer, and hashing a Profile/requirements file to see if the layer needs republishing, would ensure that most deployment artifacts are lightweight..

**Comment by aralmpa** [comment]
Up untill today I have been using a fork of Zappa ([bahoo's](https://github.com/bahoo/Zappa/)) to apply layers to my Zappa deployed Lambda and it was working. I thought that the release 0.50 - [merged pull request #2027](https://github.com/Miserlou/Zappa/commit/379c0bf822eef91faccaa57fcf0111be21430cb1)  - provided Lambda layers support but a deployment I made just now does **not** add **any** layers to the function. Is this a bug?

**Comment by jneves** [comment]
Probably. Can you share a config I can test with, please?

**Comment by aralmpa** [comment]
Yes of course - this is the zappa_settings.json I use:
```
{
  "dev": {
    "aws_region": "eu-west-1",
    "django_settings": "persefoni.settings",
    "project_name": "persefoni",
    "runtime": "python3.6",
    "memory_size": 1024,
    "s3_bucket": "persefoni-zappa-deployment",
    "keep_warm": false,
    "endpoint_configuration":["REGIONAL"],
    "slim_handler": false,
    "touch": false,
    "layers": ["arn:aws:lambda:eu-west-1:472486572044:layer:geodjango-spatial-libraries-aralmpa:2"],
    "exclude": [
      "boto3*",
      "botocore*"
    ],
    "environment_variables": {
      "GDAL_LIB_PATH": "/opt/lib/libgdal.so.20.4.3",
      "GEOS_LIB_PATH": "/opt/lib/libgeos_c.so.1",
      "PROJ_LIB": "/opt/lib/data",
      "GDAL_DATA": "/opt/lib/data",
      "PREFIX": "/dev",
    },
    "vpc_config": {
      "SubnetIds": [
        "subnet-af2383f5",
        "subnet-4ac2b402"
      ],
      "SecurityGroupIds": [
        "sg-3e2cd94e"
      ]
    }
  }
}
```
Note: The layer I am pointing to I created manually through Terraform script and then I added the arn to the settings above.

Is there a way to debug this when deploying? I mean like an increased verbosity flag? Or someone needs to clone the repo and test it locally?

Thanks in advance!

**Comment by jneves** [comment]
Just checking something: how big is the layer?

**Comment by aralmpa** [comment]
The compressed file (.zip) is 51.8 MB

**Comment by jneves** [comment]
@aralmpa I'm an idiot, sorry. Yes, that PR was merged, but after 0.50.0 was released. That functionality will be in 0.51.0 which I just prepared for release in #2059, so should be out in the next 2 days. Sorry I missed this bit earlier.

**Comment by aralmpa** [comment]
Thank you a lot for resolving the issue and releasing these features! I confirm that 0.51 worked fine with layers.

**Comment by jneves** [comment]
Thanks and sorry for the confusion.
