### ISSUE TITLE
How to update the code from a different computer

### ISSUE THREAD

**Issue by weasteam** [Miserlou/Zappa#1718]
This is not a bug. I had this question I could not find any solutions.

I have computer A, that already deployed the code.

Now I do not have access to the computer A. I got computer B. I downloaded the repository code, installed the virtual environment and requirement package. 

What should I do to only update the code and keep/use all previous lambda functions, et.al?

**Comment by weasteam** [comment]
That is the first thing I tried:
```
Calling update for stage production.
Warning! Couldn't get function xxx in us-east-1 - have you deployed yet?
```

**Comment by paulclarkaranz** [comment]
Hmm, works for me for updating from travis. Is the existing function actually in us-east-1? If `aws_region` isn't set in zappa_settings.json I think it falls back to the default from ~/.aws/config. Otherwise I would assume there is some difference between the checked in zappa_settings.json and the one that it was originally from.

**Comment by weasteam** [comment]
Yes, the function exists in us-east-1, and it is still running. I check the lambda function. it is there.

I am using exactly the same zappa_settings.json. 

Let me know what other information can I provide to help you debug. The only difference I guess is the python version and zappa version.

I was using `zappa==0.45.1`. I updated it to the latest one since it does not comparable with PyYAML.

**Comment by weasteam** [comment]
OK, I found the problem. I created a wrong AWS profile.

For those have the same issue. 
* first try `zappa tail production`, this will show you the error message if the AWS profile is wrong.
* `zappa update production` could not provide you the correct error message if the AWS profile is not correct.
