### ISSUE TITLE
issue with installing zappa

### ISSUE THREAD

**Issue by tutzy1** [Miserlou/Zappa#1738]
## Context
While trying to install zappa in my venv (python 3.6), I've got this error, and doesn't find any solution:

Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\tutzy\AppData\Local\Temp\pip-install-2nv6ra7n\kappa\setup.py", line 54, in <module>
        run_setup()
      File "C:\Users\tutzy\AppData\Local\Temp\pip-install-2nv6ra7n\kappa\setup.py", line 22, in run_setup
        long_description=open_file('README.rst').read(),
      File "C:\Program Files\Python36\lib\encodings\cp1255.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9c in position 2341: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\tutzy\AppData\Local\Temp\pip-install-2nv6ra7n\kappa\

## Steps to Reproduce

1.
2.
3.

## Your Environment

* Zappa version used: trying to install the newest
* Operating System and Python version: win 10, python 3.6
* The output of `pip freeze`: 
Django==2.1.4
pytz==2018.7
* Link to your project (optional):
* Your `zappa_settings.py`:

**Comment by AlanSwenson** [comment]
I may be TOTALLY wrong but, seeing "kappa" several times in your error, could you possibly have accidentally typed "kappa" instead of "zappa"?

**Comment by tutzy1** [comment]
kappa is one off zappa's requirements

**Comment by AlanSwenson** [comment]
ok, Totally off it is....

**Comment by tutzy1** [comment]
But I've already fixed it by installing kappa manually. The problem was at the encoding function when it runs the kappa's readme file. Don't know if it happened something went wrong specifically on my computer or not...

**Comment by heatherwang39** [comment]
How to install kappa manually? Just faced the same question.
