### ISSUE TITLE
Retrieving API Gateway URL

### ISSUE THREAD

**Issue by alexrkopp** [Miserlou/Zappa#1745]
Is it possible to programmatically capture the final API gateway URL to the service at the end of the deployment? At first glance, it doesn't seem like the callback hooks have access to this URL.

Thanks!

**Comment by paulclarkaranz** [comment]
Apart from looking at the zappa_settings if you are on a custom domain name then it looks like no. [Here](https://github.com/Miserlou/Zappa/blob/4cf80b2a0212a5a8111f0f66348b46ef39507ed1/zappa/core.py#L1991) is where zappa figures out the URL to print out on deployment, you could adapt that.

**Comment by alexrkopp** [comment]
Thanks. Looks like I could just add a callback:

```
def post_deploy(zappa_cli):
    api_gateway_url = zappa_cli.zappa.get_api_url(zappa_cli.lambda_name, zappa_cli.api_stage)
```

Closing this issue.
