### ISSUE TITLE
500. From Zappa: 'module' object has no attribute 'py'

### ISSUE THREAD

**Issue by araines** [Miserlou/Zappa#175]
I've built a very simple "Hello World" following this guide:

https://gun.io/blog/serverless-microservices-with-zappa-and-flask/

It all deployed fine, but when I hit the deployed end point I get the following error:

```
500. From Zappa:
'module' object has no attribute 'py'

Traceback (most recent call last):
  File "/var/task/handler.py", line 147, in handler
    app_function = getattr(app_module, settings.APP_FUNCTION)
AttributeError: 'module' object has no attribute 'py'
```

**Comment by collingreen** [comment]
Hi there!

Can you post your zappa_settings.json? Your error makes me think your app_function is 'app.py', which zappa will try to import using python, which will result in that error. You probably want something like `my_app.app`.

**Comment by araines** [comment]
You were right, my `app_function` was set to `app.py` - I'm clearly not very good at following simple instructions on the blog!  I couldn't see the problem at all, many thanks for sorting it out for me 👍  All working now.
