### ISSUE TITLE
Error in handler when using multi-value headers

### ISSUE THREAD

**Issue by jedestep** [Miserlou/Zappa#1755]
## Context

If an API gateway or ALB is configured to use multi-value headers, the handler module is unable to find the request headers and breaks in two places:
1. when setting script name based on the Host header (this is all that's seen in production because the lambda crashes here)
2. when forwarding the wsgi request via werkzeug, because no dict called 'headers' is included.

## Expected Behavior
Headers should all be combined into a single dict called 'headers'.

## Actual Behavior
Lambda crashes ignominiously with this error: `'NoneType' object has no attribute 'get'`.

## Possible Fix
Simple, just combine `multiValueHeaders` and `headers` into a single dict. I have a PR for this I have been working on.

## Steps to Reproduce

1.
2.
3.

## Your Environment

* Zappa version used:
* Operating System and Python version:
* The output of `pip freeze`:
* Link to your project (optional):
* Your `zappa_settings.py`:

**Comment by paulclarkaranz** [comment]
There is actually two other PRs for this already #1659 #1675. One of them already has tests.

**Comment by jedestep** [comment]
Correct me if I'm wrong but #1659 doesn't appear to support multi-valued headers in handler? #1756 does also include tests.

**Comment by jedestep** [comment]
Any other thoughts on this?

**Comment by jedestep** [comment]
Two PRs relating to this issue have been merged, so closing.
