### ISSUE TITLE
GET response without CORS headers

### ISSUE THREAD

**Issue by mark-mishyn** [Miserlou/Zappa#1758]
## Context
I've enabled CORS in `zappa_settings.json` with `"cors": true` (and `"binary_support": false`)
Now if I send request OPTIONS, I see CORS headers in response, but if request method is GET - there are **no** CORS headers. 

I also tried to enable CORS manually in AWS console. Still the same.
Also I've tried `django-cors-headers` with disabled cors in `zappa_settings.json` 

## Expected Behavior
Response for GET requests with CORS headers.

## Actual Behavior
Response for GET requests **without** CORS headers. OPTIONS works fine.

## Possible Fix
Use application-level CORS (doesn't work on Lambda for me, but works on my server)

##  The link to a live example
https://k8zhte0yjj.execute-api.us-west-1.amazonaws.com/dev/

## Your Environment

* Zappa version used: 0.47.1
* Operating System and Python version: Ubuntu 18.04, Python 3.6
* The output of `pip freeze`:
argcomplete==1.9.3
boto3==1.9.75
botocore==1.12.75
certifi==2018.11.29
cfn-flip==1.1.0.post1
chardet==3.0.4
Click==7.0
Django==1.11.18
docutils==0.14
durationpy==0.5
future==0.16.0
hjson==3.0.1
idna==2.8
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.20.0
placebo==0.8.2
psycopg2==2.7.6.1
python-dateutil==2.6.1
python-slugify==1.2.4
pytz==2018.9
PyYAML==3.13
requests==2.21.0
s3transfer==0.1.13
six==1.12.0
toml==0.10.0
tqdm==4.19.1
troposphere==2.4.0
Unidecode==1.0.23
urllib3==1.24.1
Werkzeug==0.14.1
whitenoise==4.1.2
wsgi-request-logger==0.4.6
zappa==0.47.1
* `zappa_settings.py`: 
```
{
    "dev": {
        "aws_region": "us-west-1",
        "django_settings": "frankie.settings",
        "profile_name": null,
        "project_name": "zappatest_empty",
        "runtime": "python3.6",
        "s3_bucket": "sisuserbucket",
        "cors": true,
        "binary_support": false,
        "timeout_seconds": 30,
        "vpc_config": {
            "SubnetIds": ["subnet-01efd98b0e62260b4"],
            "SecurityGroupIds": ["sg-0eef31646150c67fd"]
        }
    }
}

```

**Comment by mark-mishyn** [comment]
Sorry guys, my mistake.

I just didn't include "Origin" header to request, so CORS headers were not presented in response.

**Comment by rinatio** [comment]
@mark-mishyn Could you please tell if you still had to use `django-cors-headers` or simply having `"cors": true` in zappa settings did it for you?

**Comment by mark-mishyn** [comment]
@rinatio I still use `django-cors-headers` and I don't use `"cors": true` in zappa settings.
