### ISSUE TITLE
Read timeout for pypi.python.org is too short for a slow network

### ISSUE THREAD

**Issue by wolfg1969** [Miserlou/Zappa#1759]
## Context

When using Zappa with  a slow Internet connection (Sometimes I get a slow connection for the sites out of my country), it is always failed to download packages (manylinux wheel package) from pypi.python.org. 

## Expected Behavior

Can download the packages successfully.

## Actual Behavior

Got the error
```
HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=2)
```
Sometimes includes a broken package in lambda zip and causes runtime error. Eg. a Pillow import error.

## Possible Fix

I made a PR which adds a timeout option for deploy, package, update command. But I feel it isn't a good solution.  

## Steps to Reproduce

1. Create a Django app, add mysqlclient to requirements
2. Run `zappa update` with a slow network.

**Comment by snowman2** [comment]
Another solution would be to use the environment variable `PIP_TIMEOUT`.

**Comment by wolfg1969** [comment]
No. PIP_TIMEOUT doesn't work for this. 
See https://github.com/Miserlou/Zappa/blob/master/zappa/core.py#L818

**Comment by snowman2** [comment]
Ah, I see. Interesting.

**Comment by snowman2** [comment]
Thoughts on using it in the code so you don't have to pass it around as much?
timeout = os.environ.get("PIP_TIMEOUT", 2)

**Comment by wolfg1969** [comment]
@snowman2 yes, I agree. I'll try it soon.

**Comment by wolfg1969** [comment]
@snowman2 #1766

**Comment by catsclaw** [comment]
Is there a solution to this? A workaround? If you on a slow network are you just fucked?

**Comment by catsclaw** [comment]
The really egregious part is that Zappa continues running and reports success, so I can't even write a script that will rerun it over and over again until it works.

**Comment by wolfg1969** [comment]
#1810
