### ISSUE TITLE
Will Zappa incur Data Transfer Out charges?

### ISSUE THREAD

**Issue by Swordyjohn** [Miserlou/Zappa#1772]
It looks to me that my Zappa Site is being server through API Gateway based on the logs, which uses the data transfer model of EC2 (1st GB free then $0.09 for next 9.99 TB). Will Zappa incur these charges?

**Comment by mojimi** [comment]
Of course? Why wouldn't it? Zappa is simply an AWS "auto configurer" (simply for the user as it is quite a amazingly complex tool)

**Comment by nickpolet** [comment]
@Swordyjohn can you please close this issue as it has been answered and is not an issue directly related to Zappa.
