### ISSUE TITLE
Migrating from Sanic(or any ASGI) to Flask + Zappa's Async?

### ISSUE THREAD

**Issue by mojimi** [Miserlou/Zappa#1794]
I have a Sanic application that utilizes python's executor and asyncio to generate files paralel to the server request handling, I would like to know if this is possible to do with Flask + Zappa and no other depencies like Celery or SQS/SNS? Has anyone managed to do this with no issues?

I've found this bit here https://blog.zappa.io/posts/zappa-introduces-seamless-asynchronous-task-execution
where i'm assuming it simply invokes another lambda to call that function? So in the end it should give the same result as a executor. I was just a little worried as that post is from 2017 and I haven't found anything in the docs about it.

**Comment by NikolaJankovic** [comment]
It's discussed in more detail in the documentation: https://github.com/Miserlou/Zappa#asynchronous-task-execution
