### ISSUE TITLE
Django Push Notifications not working

### ISSUE THREAD

**Issue by Blutude** [Miserlou/Zappa#1804]
I migrated my app to AWS Lambda and Zappa is working perfectly fine, except for push notifications. They use to work well on the digital ocean server, I didn't do any modifications to that part of the code. I am using the django-push-notifications package https://github.com/jazzband/django-push-notifications. Django crashes on this line of code `device.send_message(message=request.data["message"], extra=request.data['extra'], badge=allBadgesCount)`
Here is my stacktrace:
`File "/var/task/django/core/handlers/exception.py", line 35, in inner
  response = get_response(request)
  File "/var/task/django/core/handlers/base.py", line 128, in _get_response
  response = self.process_exception_by_middleware(e, request)
  File "/var/task/django/core/handlers/base.py", line 126, in _get_response
  response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/task/django/views/decorators/csrf.py", line 54, in wrapped_view
  return view_func(*args, **kwargs)
  File "/var/task/django/views/generic/base.py", line 69, in view
  return self.dispatch(request, *args, **kwargs)
  File "/var/task/rest_framework/views.py", line 483, in dispatch
  response = self.handle_exception(exc)
  File "/var/task/rest_framework/views.py", line 443, in handle_exception
  self.raise_uncaught_exception(exc)
  File "/var/task/rest_framework/views.py", line 480, in dispatch
  response = handler(request, *args, **kwargs)
  File "/var/task/social/views.py", line 628, in post
  device.send_message(message=request.data["message"], extra=request.data['extra'], badge=allBadgesCount)
  File "/var/task/push_notifications/models.py", line 167, in send_message
  **kwargs
  File "/var/task/push_notifications/apns.py", line 113, in apns_send_message
  certfile=certfile, **kwargs
  File "/var/task/push_notifications/apns.py", line 66, in _apns_send
  client = _apns_create_socket(certfile=certfile, application_id=application_id)
  File "/var/task/push_notifications/apns.py", line 38, in _apns_create_socket
  use_alternative_port=get_manager().get_apns_use_alternative_port(application_id)
  File "/var/task/apns2/client.py", line 38, in __init__
  self.__credentials = CertificateCredentials(credentials, password)
  File "/var/task/apns2/credentials.py", line 29, in __init__
  ssl_context = init_context(cert=cert_file, cert_password=password)
  File "/var/task/hyper/tls.py", line 131, in init_context
  context.load_cert_chain(cert, password=cert_password)
FileNotFoundError: [Errno 2] No such file or directory`

I am not sure what causes this. I couldn't find any "No such file or directory" issues related to that.

## Your Environment
Here are my zappa settings if that helps:
`{
    "staging": {
        "aws_region": "ca-central-1",
        "django_settings": "spap.settings",
        "profile_name": "default",
        "project_name": "spap",
        "runtime": "python3.6",
        "s3_bucket": "zappa-4ptzm651m",
        "keep_warm": true
    }
}`

**Comment by Blutude** [comment]
I now understand that the issue is related to not finding the certificate file needed for Apple Push Notifications. Can I upload that file to AWS Lambda?

**Comment by nickpolet** [comment]
You should be able to include the certificate file in the zappa build/zip process (make sure the file isn't excluded in **zappa_settings.json**). You can then serve the file [like this](https://github.com/Miserlou/Zappa#serving-static-files--binary-uploads).

Another thing to keep in mind... Lambda functions cannot talk to the outside world without using an [Internet Gateway](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Internet_Gateway.html) with AWS. You can communicate with anything on your VPC, but nothing outside it. You might need to set that up before your function code can communicate to the outside world and send Push notifications.

**Comment by Blutude** [comment]
So I found a way for zappa to access the certificate file. My issue now is that my code gets stuck on the line `device.send_message(...)` which is suppose to send a remote notification through apple. I don't get an error, but after 30 seconds, the zappa request times out. I'm assuming it is related to what you mentioned, about having to use an Internet Gateway. I read the documentation you provided and tried to do it myself but I have a very low understanding of this so I am having trouble. Am I suppose to create a gateway between my lambda function and the Apple Push Notification services? Or between my lambda function and the entire internet? Following your documentation I tried creating a subnet but I was asked about the ipv4 cidr block and was not sure what to write for that. Could you provide some details?

**Comment by Blutude** [comment]
This helped me out! https://gist.github.com/reggi/dc5f2620b7b4f515e68e46255ac042a7

**Comment by monkeypants** [comment]
looks like you have sorted this out @Blutude, do you need anything more before this ticket can close?

**Comment by Blutude** [comment]
Nope, all good! The main issue with this is that I had no idea what my problem was. The code was just stuck at device.send_message(). I don't know if there is a way to indicate what the issue is but that would be helpful!

**Comment by monkeypants** [comment]
I'm not a maintainer, I can't close this ticket. Can you do it @Blutude please?
