### ISSUE TITLE
CORS issue: 0.48 release returns same value multiple times in access-control-allow-origin

### ISSUE THREAD

**Issue by vijayparne** [Miserlou/Zappa#1825]
## Expected Behavior
access-control-allow-origin: https://www.example.com

## Actual Behavior
access-control-allow-origin: https://www.example.com, https://www.example.com, https://www.example.com

## Your Environment

* Zappa version used: 0.48
* Operating System and Python version: macOS 10.14: Mojave and python 3.6
* The output of `pip freeze`: 
* Link to your project (optional):
* Your `zappa_settings.py`:  
{
  "dev": {
    "app_function": "myapi.app.app",
    "cors": true,
    "binary_support": false,
  }
}

**Comment by jneves** [comment]
Looks related to #1821

**Comment by jneves** [comment]
Could you check if https://github.com/Miserlou/Zappa/pull/1828 works for you?

**Comment by sookyeomKim** [comment]
[https://github.com/Miserlou/Zappa/pull/1828/files](url)
![스크린샷 2019-03-20 오후 6 02 01](https://user-images.githubusercontent.com/8381017/54673086-e1cde980-4b3c-11e9-8720-1e30d29d9cd1.png)

It worked very well.

**Comment by jedestep** [comment]
LGTM, I seem to have misunderstood the intended behavior of this case. Thanks for digging in @jneves.

**Comment by jneves** [comment]
@vijayparne can you confirm this is fixed in 0.48.2?

**Comment by vijayparne** [comment]
@jneves it works. Thanks
