### ISSUE TITLE
Using my own packages

### ISSUE THREAD

**Issue by dluiscosta** [Miserlou/Zappa#1836]
Currently I work with a mono repository setup, and have all my coded functionalities (both python packages and lambdas) split between side-by-side folders, so I can separate responsibilities and reuse code. My desire is to be able to import my own packages and, as seamlessly as possible, deploy those dependencies with Zappa alongside the actual lambda using them.

For now I've been setting a .sh script to copy the files from each of my own required dependencies to the folder of the active virtualenv on the moment of deploy, which works, but starts to get messy and cumbersome when I have to start managing cycles and the dependencies of dependencies (...).

I know setting private npms could be a way to solve my problem, but it seems like much work too. Can zappa package help me somehow? (Sincerelly, I didn't understand it's use from the docs)

Since Zappa does not yet support Layers, what is the recommended approach to doing this?

**Comment by jneves** [comment]
Layers support is waiting on users taking it for ride and reporting back. If you're interested in it, check https://github.com/Miserlou/Zappa/pull/1752 and report back on the ticket.

**Comment by jneves** [comment]
Zappa now supports layers.
