### ISSUE TITLE
Is the blog relevant?

### ISSUE THREAD

**Issue by dimaqq** [Miserlou/Zappa#1838]
The latest post on https://blog.zappa.io/ is from 2017.
Yet the URL is prominently displayed both on zappa.io and in the github project title.
It's mixed signals at best.

**Comment by mojimi** [comment]
Zappa is amazing but this repository is a bit of a ghost town

**Comment by youcandanch** [comment]
@mojimi I wouldn't necessarily call it a ghost town; there's a lot of activity on the Slack channel, but yes, there's probably some lift to do here as far as keeping things up to date.
