### ISSUE TITLE
deployed code can't find library

### ISSUE THREAD

**Issue by dtenenba** [Miserlou/Zappa#185]
Hi, continuing the saga from my misguided [PR](https://github.com/Miserlou/lambda-packages/pull/8#issuecomment-232789565)....

Here is a minimal test case to reproduce my problem which is that when I deploy an app that depends on a specific package (which is installed in my virtualenv) the package can't be found. As mentioned before the package in question has no C code. One possible issue is that it is not already in a pip repository, it's in github, so you need a special pip command line (see below) to install it.

Here are the steps to reproduce it:

```
mkdir zaptest
cd zaptest
virtualenv venv
. venv/bin/activate
pip install -e "git+https://github.com/basespace/basespace-python-sdk.git#egg=src&subdirectory=src"
pip install zappa flask # this failed for some reason, but:
pip install --upgrade zappa flask #... this worked
vi zappa_settings.json
```

Contents of `zappa_settings.json`:

```
{
    "dev": { // The name of your environment
       "s3_bucket": "dtenenba-lmbda", // The name of your S3 bucket
       "app_function": "your_module.app" // The python path to your WSGI application function. In Flask, this is your 'app' object.
    }
}
```

Create the bucket:

```
aws s3 mb s3://dtenenba-lmbda
vi your_module.py
```

Contents of `your_module.py` are the same as `my_app.py` from [the tutorial](https://gun.io/blog/serverless-microservices-with-zappa-and-flask/) except I've added an import of the basespace package, so the whole thing looks like this:

```
from flask import Flask
from BaseSpacePy.api.BaseSpaceAPI import BaseSpaceAPI
app = Flask(__name__)

@app.route('/')
def index():
    return "Hello, world!", 200

# We only need this for local development.
if __name__ == '__main__':
    app.run()

```

Deploy and test:

```
zappa deploy dev
curl -i https://tu496brbai.execute-api.us-east-1.amazonaws.com/dev 
```

`curl` returns:

```
HTTP/1.1 200 OK
Content-Length: 0
Connection: keep-alive
Date: Fri, 15 Jul 2016 16:44:56 GMT
Location:
Set-Cookie:
Status:
x-amzn-RequestId: 7650ab40-4aab-11e6-8aba-e1eb676565c9
X-Frame-Options:
X-Cache: Miss from cloudfront
Via: 1.1 affec1a0de50d1f690b08b468f7d2156.cloudfront.net (CloudFront)
X-Amz-Cf-Id: Je7OWSM9bdpmxGc5lRmKP3AZwYjiE5D77tPj3grYmP44npvRMRboTQ==

```

Kind of odd that it returns `200` though there was an error (and it did not return the Hello World message). `zappa tail dev` says:

```
[1468601096764] No module named BaseSpacePy.api.BaseSpaceAPI
[1468601096764] No module named BaseSpacePy.api.BaseSpaceAPI: ImportError
Traceback (most recent call last):
  File "/var/task/handler.py", line 249, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 107, in lambda_handler
    return cls().handler(event, context)
  File "/var/task/handler.py", line 234, in handler
    raise e
```

Is there something I need to do to get this working or is it an issue in Zappa? Thanks in advance for your help.

**Comment by dtenenba** [comment]
I should mention that in an interactive python shell on my machine (in the virtualenv) I can load the basespace package just fine:

```
In [1]: from BaseSpacePy.api.BaseSpaceAPI import BaseSpaceAPI

In [2]:
```

So it's just on the deployment that I'm having a problem.

**Comment by dtenenba** [comment]
Although, hmm, it doesn't work in a `python` (as opposed to `ipython`) shell:

```
>>> from BaseSpacePy.api.BaseSpaceAPI import BaseSpaceAPI
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named BaseSpacePy.api.BaseSpaceAPI
```

I should note that `ipython` is installed in my virtualenv (as well as outside of it).

**Comment by dtenenba** [comment]
Maybe I am running into [this issue](https://stackoverflow.com/questions/15048316/pip-install-into-virtualenv-from-github-using-e-option-fails-to-add-package-to) , though it isn't clear if any of the solutions would work in the context of Zappa.

**Comment by dtenenba** [comment]
OK, solved this. The fix was to remove my virtualenv, recreate it, activate it, and before doing anything else, update pip inside the virtualenv:

    pip install -U pip setuptools

Then I install my package from github as above, and other dependencies, and I can then import the package from within python, ipython, and the zappa deployment.

**Comment by Miserlou** [comment]
Weird! Thanks for chasing this one down and documenting it, too. Hopefully this helps some other people as well.

**Comment by dtenenba** [comment]
Just some more notes on this for me and anyone else who comes across this, because there is still more to this issue. I just ran across it again and additional steps were required to get things to work.

It turns out that if you have a virtualenv called `env` activated, and you run a command like this:

    pip -e git+https://github.com/basespace/basespace-python-sdk.git@0e9d30790ec58fcf673534aeb62d3645b063fd14#egg=BaseSpacePy-master&subdirectory=src

...it will actually install the package in the `src` subdirectory of `env`, not the (e.g.) `lib/python2.7/site-packages` directory. Things will seem to work locally (i.e. you can import the package in your scripts and using `python` and `ipython`), but when deploying with zappa you will get an error in your zappa logs that the package cannot be found.

So the next thing I tried was cloning the repository of this other python package and installing it by using `setup.py`. First I uninstalled the current installation of the package and removed the `src` directory:

```
pip uninstall BaseSpacePy
rm -rf env/src
```



```
git clone git@github.com:basespace/basespace-python-sdk.git
cd basespace-python-sdk/src
python setup.py install
```

Although this installs the package in the "right place," I still had the same problem when deploying with Zappa. I then noticed that this package was installed in a different way than the others; whereas the others had a WHEEL file, this one did not. So I then tried to install this package as a wheel, and that was the ticket to success:

```
# first uninstall it cd basespace-python-sdk-src
pip uninstall BaseSpacePy
# we are still in the  basespace-python-sdk-src directory, so:
python setup.py sdist bdist_wheel # creates the wheel
pip install  dist/BaseSpacePy-0.3-py2-none-any.whl # installs the wheel

```

Now I was able to deploy to zappa and it found my library.

This approach seems like a bit of a hack, but it works. I'll probably write up a script to automate it. But it is a lot more complicated than the command I was using before, which was simply:

    pip install -r requirements.txt

I guess the takeaway is that if you are instaling a package from github, especially one where the actual package code is in a subdirectory of the repository, things are not quite as straightforward.

I'm not sure how much of this (if any) is something that zappa has control over, or if it's a problem at the AWS Lambda level. So I won't reopen the issue at this point. It does seem that someone (whether it's Zappa or Lambda) is very finicky about how packages are installed in one's virtualenv.

**Comment by Miserlou** [comment]
Woah!

This is excellent sleuthing! Thanks very much for reporting back your findings!

I think this can actually be something that be incorporated into Zappa core, now that it has been accurately identified. This warrants a new ticket.

Would you mind starting a new ticket called "Properly Package Source and Non-Wheel Dependencies", with a link back to this issue? Thanks!
