### ISSUE TITLE
Zappa update shows no api URL

### ISSUE THREAD

**Issue by bjorntheart** [Miserlou/Zappa#187]
Unlike your example in the documentation, when I update I see no API Gateway URL.

<img width="833" alt="screen shot 2016-07-19 at 11 18 14" src="https://cloud.githubusercontent.com/assets/53244/16944801/889e679e-4da2-11e6-9c50-1d733edfde1b.png">

<img width="1437" alt="screen shot 2016-07-19 at 11 18 46" src="https://cloud.githubusercontent.com/assets/53244/16944820/9ec97db0-4da2-11e6-9129-d9b0af52181d.png">

**Comment by Miserlou** [comment]
This is fixed in 309fe08, thanks for reporting.

**Comment by bjorntheart** [comment]
That was quick!
