### ISSUE TITLE
Is Python3.7 officially supported now?

### ISSUE THREAD

**Issue by C-Kenny** [Miserlou/Zappa#1900]
In the docs and issue template, Zappa assumes running Python `3.6`.

**Comment by elcolie** [comment]
My project is running with `Python 3.7.3`
On thing to concern is I have to deploy with `Linux` based OS. Otherwise it will has a problem with `C` level dependencies for example cryptographic libraries

**Comment by gerosalesc** [comment]
Yes just keep in mind that you should use asynchronous module instead of async as this is a reserved word in 3.7 as seen in #1666 and solved in #1762

**Comment by jneves** [comment]
Yes, and 3.8 too.
