### ISSUE TITLE
-bash: zappa: command not found

### ISSUE THREAD

**Issue by 3lonious** [Miserlou/Zappa#1921]
## Context
i solved my issue by uninstalling pip and python and re setting up the environment and installation ect

**Comment by 3lonious** [comment]
i have not solved the issue and continue to get errors and seems to be no end in site. help would be amazing, thanks.

<img width="592" alt="Screen Shot 2019-08-22 at 1 24 40 AM" src="https://user-images.githubusercontent.com/46793692/63499194-38d54300-c47c-11e9-88be-dc6b1ba5f9d2.png">

**Comment by 3lonious** [comment]
ok so i found this in my activate file and im pretty confused as to why this is set up this way, is it possible someone who worked for me did something malicious here with the code to steal my deployments? my folder is not this folder that the file is pointing at, is this activate file suspicious? im basicly freaking out here cuz i dont know why this file is set up pointing virtual_env to a folder that is 2 years old and i deleted from my computer yesterday to clean up and since my ability to run deployments is messed up and so confused as to the fact this other folder i had forgot about is controlling my deployments?
<img width="722" alt="Screen Shot 2019-08-22 at 3 02 32 AM" src="https://user-images.githubusercontent.com/46793692/63505931-4fce6200-c489-11e9-83fb-d8cbae6eaff2.png">

**Comment by 3lonious** [comment]
<img width="1275" alt="Screen Shot 2019-08-22 at 1 37 48 AM" src="https://user-images.githubusercontent.com/46793692/63506290-16e2bd00-c48a-11e9-8251-12a0ed0bc7f9.png">

**Comment by daseulll** [comment]
I configured the virtual environment without pyenv, then I solved the issue.
