### ISSUE TITLE
Is there documentation for this thing???

### ISSUE THREAD

**Issue by sleepychild** [Miserlou/Zappa#1933]
## Steps to Reproduce

1.
2.
3.

## Your Environment

* Zappa version used:
* Operating System and Python version:
* The output of `pip freeze`:
* Link to your project (optional):
* Your `zappa_settings.py`:

**Comment by dpretty** [comment]
@sleepychild The README is reasonably comprehensive... is there anything specific which is lacking from README.md?

**Comment by sleepychild** [comment]
@dpretty , how should I know. That's why I asked.
