### ISSUE TITLE
pyenv-compatible deployment

### ISSUE THREAD

**Issue by puhitaku** [Miserlou/Zappa#195]
Your Zappa with normal virtualenv works flawlessly and I want it to work also with pyenv.

Pyenv generates a config file named `.python-version` in working directory calling `$ pyenv local venv` and I've implemented auto-detection of it. I'm ready to issue PR if you like it.

Thanks!

**Comment by Miserlou** [comment]
This is an interesting idea, I don't know very much about pyenv though. Zappa currently only supports Python 2.7 though - isn't PyEnv for managing different python versions?

Still, PRs a more than welcome, as long as the test coverage doesn't decrease and there's documentation!

**Comment by puhitaku** [comment]
My words were too few. pyenv can manage also venvs like different python versions while auto-activation functionality is still active.

Anyway, I've created new PR!

**Comment by Miserlou** [comment]
This is merged and will be published in the next version of Zappa! Yay!
