### ISSUE TITLE
Zappa Websites are not working

### ISSUE THREAD

**Issue by kareemcoding** [Miserlou/Zappa#1976]
I'm unable to access any websites for Zappa.

Both the blog (https://blog.zappa.io/) or the root websites (https://zappa.io/)

**Comment by kareemcoding** [comment]
Any news on this? Is this repo even alive?

**Comment by quakehead** [comment]
see #1969. @Miserlou isn't active anymore. I don't know why @Miserlou didn't assign another maintainer. Maybe we need to create a team or organization that maintains Zappa?

**Comment by lifenautjoe** [comment]
Holy freaking cow, this project is abandoned? 😱

**Comment by jneves** [comment]
No, but there's been an issue where the zappa.io domains have become unreachable and only one person can sort it out and we're having problems contacting him. Eventually we'll make the decision whether to just drop the zappa.io domain, but at the moment we're still hopeful we can sort it out.

**Comment by lifenautjoe** [comment]
Thanks for clearing that up @jneves !

**Comment by emilepetrone** [comment]
Has there been any progress on this? It's a shame the site is down because it gives the false impression that the project is dead. Ping @Miserlou

**Comment by xncbf** [comment]
Zappa is dead?

**Comment by jneves** [comment]
No, just the zappa.io domain. I'll clean up the docs in a few days.

**Comment by lifenautjoe** [comment]
@jneves Why is this closed? The websites are still offline.

**Comment by jneves** [comment]
@lifenautjoe they are not part of the project anymore, we don't have control over the domain, so they are lost. If you're interested, the blog content is available at https://github.com/Miserlou/zappa-blog

**Comment by amiryal** [comment]
@jneves the project tagline still reads “Serverless Python https://blog.zappa.io/”. Does the team of collaborators have the ability to update or remove that reference?

**Comment by dmitrijs-balcers** [comment]
Perhaps the blog should be hosted on github pages instead?
It would be more comfortable to read rather than reading and navigating through files.
