### ISSUE TITLE
PLEASE DONATE A SMALL AMOUNT TO THIS PROJECT

### ISSUE THREAD

**Issue by mattmillen888** [Miserlou/Zappa#1981]
It takes a-lot of time and effort to create great products

By donating a very small amount every month to this project it would help to add lots of enhancements and keep the project updated and going with regular updates.

Too many people expect everything for nothing these days and good people get tired of doing things for nothing.

As I see it the small amount that Rich is asking to keep him and his team going with regular updates is minimal for the great product that Zappa is.

I find it very disappointing that the Python community has not supported him more. If everyone was just to donate a small amount each month, they would easily achieve their goal plus more, which would only mean things get resolved quicker with more developers!

Hopefully the next person that sees this will act as i did and donate!
https://www.patreon.com/zappa

Long live Zappa!!

**Comment by TheDumbfounds** [comment]
Would love to hear @Miserlou comment on whether he'd still be interested to continue
zappa if the funding goal was reached.

**Comment by ambientlight** [comment]
How old is that Patreon page? Very strange to not see this not posted by @Miserlou himself
