### ISSUE TITLE
General question about large uploads.

### ISSUE THREAD

**Issue by corpulent** [Miserlou/Zappa#1983]
I am running DRF.

```
django==3.0.1
django-storages==1.8
django-filter==2.2.0
djangorestframework==3.11.0
djangorestframework-jwt==1.11.0

psycopg2-binary==2.8.4
zappa==0.48.2
django-anymail[mailgun]==7.0.0
botocore==1.14.5
boto3==1.11.5
python-magic==0.4.15
```

And I am trying to upload a large file over 10MB through an endpoint I created.  Small files work.  I am not seeing any errors in the Django/Lambda logs.  The only response I get is:

```
{
    "message": "Internal server error"
}
```

I maxed out the lambda memory, and timeout.  Is this a problem with API gateway?

**Comment by aralmpa** [comment]
Hello there,

Not sure this is the cause but seems related: Lambda event object (request / invocation payload) for request-response mode is around 6MB - [Lambda Service Limitations](https://docs.aws.amazon.com/lambda/latest/dg/limits.html)

**Comment by corpulent** [comment]
@aralmpa I ended up using aws s3 presigned url to handle large uploads.  I just wish there was more detail about the error from API Gateway.  `Internal server error` does not really say much.
