### ISSUE TITLE
Drop support for Python versions < 3.6

### ISSUE THREAD

**Issue by mbeacom** [Miserlou/Zappa#1994]
Python 2.x is now end of life and will no longer receive updates.

##  Context

Python 2.x and 3.{4, 5} are either no longer supported or don't have official AWS Lambda runtimes.

Some additional references in favor of this change:

- [Python Clock - Lapsed](https://pythonclock.org/)
- [Python 3 Statement](https://python3statement.org/)
- [Pandas drops Python 2 support - July 2019](https://pandas.pydata.org/#v0-25-0-final-july-18-2019)
- [NumPy drops Python 2 support - Proposed January 2019](https://numpy.org/neps/nep-0014-dropping-python2.7-proposal.html)
- [Pytest drops Python 2 support](https://pytest.readthedocs.io/en/latest/py27-py34-deprecation.html)
- [PEP-373 - 2.7 Lifecycle](https://www.python.org/dev/peps/pep-0373/)

## Possible Fix
I propose we add a deprecation notice in the next patch for 0.49.x and increment the minor (`0.49.0` -> `0.50.0`), dropping support for Python versions `< 3.6` by setting python min requirement, removing six/compat support, and convert relevant code to Python 3.6+.

**Comment by jneves** [comment]
So, this has been done more by accident than I would have liked, as 0.49 doesn't work on 2.7 and that was missed it on the preparation of the release. As nobody is thinking of going back, I'll update the README and Changelog to note that 0.48.2 was the lst one with 2.7 support. Sorry for the unexpected update.
