### ISSUE TITLE
Using pip-tools to manage dependencies

### ISSUE THREAD

**Issue by jneves** [Miserlou/Zappa#1997]
Currently zappa has several pinned dependencies that make it likely that it works, but also makes it hard to keep using as time passes because of other packages dependency updates.

For this I believe we should be separating the hard requirements from the pinned ones.

pip-tools allows us to do that, while not having two collections of requirements that need to be updated individually.

## Context

See many complaints throughout the years.

## Expected Behavior
Installing zappa should work with an open-ended set of dependencies until a specific one doesn't work.

## Actual Behavior
Some installations only work if people ignore the dependency requirements.

## Possible Fix
With pip-tools, updating a requirement would be adding it in requirements.in or test_requirements.in as needed and then running:

`pip-compile -o test_requirements.txt requirements.in test_requirements.in && cp test_requirements.txt requirements.txt && pip-compile -o requirements.txt requirements.in`

**Comment by monkut** [comment]
Just a random comment about my experience with pipenv.

I've been using [pipenv](https://github.com/pypa/pipenv) for a little over a year now for most of my projects.

It has built in support for (standard) requirements, `packages`,  and (test) requirements `dev-packages`.  It also allows you to maintain a list of requirement versions unbound by their dependency versions, but maintains the ability to create a version exact _build_ using the _sync_ command.

sample Pipfile:
```
[[source]]
url = 'https://pypi.python.org/simple'
verify_ssl = true
name = 'pypi'

[requires]
python_version = '2.7'

[packages]
requests = { extras = ['socks'] }
records = '>0.5.0'
django = { git = 'https://github.com/django/django.git', ref = '1.11.4', editable = true }
"e682b37" = {file = "https://github.com/divio/django-cms/archive/release/3.4.x.zip"}
"e1839a8" = {path = ".", editable = true}
pywinusb = { version = "*", os_name = "=='nt'", index="pypi"}

[dev-packages]
nose = '*'
unittest2 = {version = ">=1.0,<3.0", markers="python_version < '2.7.9' or (python_version >= '3.0' and python_version < '3.4')"}

```

It seems similar to what you are doing here to manage test/development requirements.

These automatically update the related `Pipfile` and `Pipfile.lock` files, which would replace the traditional `requirements.txt` files.
```
# Adding a requirement -- adds to Pipfile [packages]
pipenv install desired-pypi-package

# Adding development/test specific package -- adds to Pipfile [dev-packages]
pipenv install desired-pypi-package --dev
```

To then prepare a new development environment for dev:
```
# prepare virtualenv with exact requirements/requirement-dependency versions including develolpment/test requirements
pipenv sync --dev
```

Of course a switch to using pipenv would affect a your users so it's a choice made with caution.
It does look there are tools to convert a Pipfile/Pipfile.lock to the traditional _requriements.txt_.

https://github.com/frostming/pipfile-requirements

**Comment by jneves** [comment]
@monkut tried it with zappa - ended up with a broken set of incompatible packages and, even if worked, would be limited to 2 sets of dependencies when I want at least 3 in the end (production, tests and dev)

**Comment by jneves** [comment]
(which I found really strange as it uses pip-tools dependency engine)

**Comment by gopalmeena** [comment]
I have not used this package manager [poetry](https://github.com/python-poetry/poetry), but it seems that poetry keeps things simple and clean to use. I hope this may help.

**Comment by mbeacom** [comment]
Poetry would probably make the most sense in this case, as this is a package/module repository and publishing a package.
