### ISSUE TITLE
Add 'Rollback' Capability

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/Zappa#2]
It'd be nice if we could do something like

    python manage.py rollback dev 

to return the previously deployed function, or

    python manage.py rollback dev

to rollback 5 versions, etc.

**Comment by graemeglass** [comment]
:+1: on this idea. 

Also I think you mean: 

> python manage.py rollback dev 5 

to rollback 5 versions of dev

**Comment by Miserlou** [comment]
Ah, yes.

**Comment by Miserlou** [comment]
Hey @graemeglass - how would you feel about trying to implement this?

**Comment by graemeglass** [comment]
@Miserlou Happy to give it a try. Will attempt to carve out some time near the end of this week.

**Comment by Miserlou** [comment]
Great! Looking forward to it.
