### ISSUE TITLE
Customizable IAM policies

### ISSUE THREAD

**Issue by puhitaku** [Miserlou/Zappa#200]
Zappa's hard-coded default IAM policies (assume / attach policy) are enough for doing most things but I'd like to customize them for advanced usage.

My idea is that defining the name of external JSON files which includes IAM's policy on `zappa_settings.json` then Zappa reads the external JSONs on deployment.

I've made new PR for this idea. Please consider merging this!

**Comment by Miserlou** [comment]
Merged! Thank you very much for your contribution!
