### ISSUE TITLE
How do I set up a CI/CD pipeline using AWS CodePipeline for a Flask application deployed using Zappa?

### ISSUE THREAD

**Issue by rupam-kundu** [Miserlou/Zappa#2001]
I need a step by step guide on setting up a CI/CD pipeline using AWS CodePipeline for a Flask application deployed using Zappa.

**Comment by taylorgoodallau** [comment]
You'll need to start my looking at the documentation & following each of the deploy steps locally. 
Once you can do this it's a matter of moving that over to your CI/CD. You will need something a long the following lines. You might find some further information here as well 

https://stackoverflow.com/questions/54124119/how-to-deploy-to-aws-using-ci-cd-for-zappapython

- A Python 3 Docker Image 
- Install virtualenv with pip
- activate virtual env
- install pip packages 
- create a s3 bucket ( handle error if it already exists ) 
- zappa undeploy production --yes
- zappa deploy *YOUR_ENV*
- zappa certify *YOUR_ENV* --yes 
- zappa invoke *YOUR_ENV*  *your handler*


Goodluck!

**Comment by rupam-kundu** [comment]
Thanks for the reply.
