### ISSUE TITLE
Disabling the cookie encoding feature

### ISSUE THREAD

**Issue by avengerpenguin** [Miserlou/Zappa#202]
I have a use case where I am making a small service whose purpose is to set a particular cookie, which is obviously mangled by the time it comes out via the Zappa middleware.

I thought perhaps it could be possible to disable that feature in cases where we know we are only sending the one cookie.

I might have a go at proposing this in a pull request, but wanted to raise an issue in case there was any useful discussion that would help me. I'm not 100% clear on the reason for the cookie hack as it is (are we limited to one response header value per header name?) I'm also not 100% clear on whether it's possible to read the settings from within the middleware.

**Comment by Miserlou** [comment]
This should be medium-doable with a toggle. Gotta make sure there is test coverage for it though.

**Comment by avengerpenguin** [comment]
From what I can see so far, I can prove the concept of adding a boolean to the zappa_settings.json that is used by the handler to decide whether to use the middleware or not. It looks like the middleware only does the cookie thing, but I suppose if it did more later, the config could be passed into the middleware constructor.

**Comment by Miserlou** [comment]
Ah, that makes sense.

**Comment by Miserlou** [comment]
How's this coming, @avengerpenguin  :) ?

**Comment by Miserlou** [comment]
We no longer use the cookie-encoding hack.
