### ISSUE TITLE
Latest version is not hosted on Github and no requirements.in file on pypi.org hosted package

### ISSUE THREAD

**Issue by 0xFF1E071F** [Miserlou/Zappa#2031]
## Context

Hello. 
1. I couldn't download the latest version 0.50.0 from packages github releases page.
2. Latest version is hosted on pypi.org and there is no "requirements.in" file in that package. So i got an error while installing
## Expected Behavior

After the command `python3.8 setup.py build`, package should be built as intended
## Actual Behavior

I got this error:
```
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    with open(os.path.join(os.path.dirname(__file__), 'requirements.in')) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.in'
```

## Possible Fix

I have changed "requirements.in" to requirements.txt. We can do that.
But also you can reupload package with requirements.in file.

## Your Environment

* Zappa version used: 0.50.0
* Operating System and Python version: PisiLinux and Python3.8

**Comment by jneves** [comment]
You can get it here: https://github.com/Miserlou/Zappa/blob/master/requirements.in

**Comment by jneves** [comment]
Release created on github. Will have to understand why requirements.in is missing from the pypi package though.

**Comment by 0xFF1E071F** [comment]
Thank you
It is working as intended
Closing the issue.

**Comment by jneves** [comment]
Fixed in https://github.com/Miserlou/Zappa/commit/3a4f77b800f239f2d1007f20e95b07cf3613539a
