### ISSUE TITLE
Doppins automated PRs

### ISSUE THREAD

**Issue by mbeacom** [Miserlou/Zappa#2039]
Is there any chance a collaborator could disable doppins and cleanup all of the conflicting PRs spanning back to 2017..?  That would eliminate 38 unnecessary/wont fix PRs from the total 130 currently open.
The doppins integration seems to have been a problem since it was enabled... and dependency management in general.

Refs:
#1312 
#1678 

CC @mcrowson @jneves

**Comment by mcrowson** [comment]
We're still discussing internally pinning to specific requirement numbers or not. That said, Doppins hasn't really been used to stay up to date with pinning anyhow. Doppins is now off and the old PRs removed. Might go back to it in the future, but currently the PRs are just unused baggage.

**Comment by mbeacom** [comment]
Awesome, thanks!
