### ISSUE TITLE
Not sure what's causing this error.

### ISSUE THREAD

**Issue by jaoxford** [Miserlou/Zappa#2040]
The application I'm creating receives messages from an SQS queue and performs some Database interacation. Which works the first time.
But then when trying to run again, I get this message on the Lambda application:
```
"{'message': 'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.', 'traceback': ['Traceback (most recent call last):\\n', '  File \"/var/task/handler.py\", line 531, in handler\\n    with Response.from_app(self.wsgi_app, environ) as response:\\n', '  File \"/var/task/werkzeug/wrappers/base_response.py\", line 287, in from_app\\n    return cls(*_run_wsgi_app(app, environ, buffered))\\n', '  File \"/var/task/werkzeug/test.py\", line 1096, in run_wsgi_app\\n    app_rv = app(environ, start_response)\\n', \"TypeError: 'NoneType' object is not callable\\n\"]}"
```

Any ideas what this is?

**Comment by kwangsooshin** [comment]
Me too... I also saw that error code. What is the problem?

**Comment by aralmpa** [comment]
Hello there,

I guess you did not find any solution yet. Can you share some more details? Where did this message appear? Can you share the zappa_settings.json?

**Comment by jaoxford** [comment]
I dropped the project.

So I have no idea what fixed it.
