### ISSUE TITLE
Dateutil version bump

### ISSUE THREAD

**Issue by chris-erickson** [Miserlou/Zappa#2066]
`python-dateutil` is pinned at 2.6.0, but it's starting to [conflict with some things](https://github.com/spulec/freezegun/issues/333) like `freezegun` that would like a newer version.  It seems like dependabot has been been fighting for this a while too: https://github.com/Miserlou/Zappa/pulls?q=is%3Apr+dateutil+is%3Aclosed

I couldn't locate much rationale for this being pinned, could it be bumped to `>=2.7.0`?

**Comment by jasonrhaas** [comment]
Also newer versions of `python-dateutil` support iso parsing natively using `dateutil.parser.isoparse()`, which has a big performance improvement over using `dateutil.parser.parse()`.

https://dateutil.readthedocs.io/en/latest/parser.html#dateutil.parser.isoparse

**Comment by tommie-lie** [comment]
This is a duplicate of #1927 which contains preliminary work and a updated explanation.

**Comment by chris-erickson** [comment]
We only need a couple dozen of these requests, so, closing.
