### ISSUE TITLE
Virtual Env Setting Windows

### ISSUE THREAD

**Issue by syphon7** [Miserlou/Zappa#207]
When you set the environment variable for VIRTUAL_ENV in Windows it appends /lib/python2.7/site-packages. It should be /Lib/site-packages in Windows.

**Comment by Miserlou** [comment]
Oh man, I'll bet there's more too. We haven't really done any testing at all on Windows yet, and I don't know of any ways to do Windows testing with a CI. 

PR's are also graciously accepted, but really we just need somebody who can really dive into it on Windows.

Thanks for reporting!

**Comment by syphon7** [comment]
Sure thing. I just submitted a small PR, but I'll keep an eye out for more. Great library!

**Comment by Miserlou** [comment]
Merged! Takk!

**Comment by garnold54** [comment]
Just ran into this issue. Any idea when this will make it into a release?

**Comment by Miserlou** [comment]
Latest release was pushed yesterday, are you using that? If not, can you paste your error here, or open a new ticket if it's a different issue?

**Comment by garnold54** [comment]
I just did a `pip install zappa --upgrade` and it installed version 0.20.2. However the problem persists and I double checked my `zappa.py` and it does not contained the fix from the pull request

**Comment by Miserlou** [comment]
Huh. That's weird. I'm looking at my own master branch and I see it, but I don't see it in the 0.20.2 code. I don't know how that happened.

Reopening until fixed.

**Comment by Miserlou** [comment]
Totally my fault. -dev never got brought into master.
