### ISSUE TITLE
Zappa 0.51.0 Not pulling updated files for the zip -- zappa update not working

### ISSUE THREAD

**Issue by emilynielson** [Miserlou/Zappa#2091]
When running zappa update with 0.51.0 the files that have been updated are not pulled into the zip and thus the updated code is not deployed
 Can't send updated code via zappa update

Python 3.7.4
## Expected Behavior

The zip should be updated with the updated files and sent via the zip to the lambda
## Actual Behavior

old code continues to get sent to the lambda
## Steps to Reproduce

1.
2.
3.

## Your Environment

* Zappa version used: 0.51.0
* Operating System and Python version: 
macOS Mojave Version 10.14.6
Python 3.7.4
* The output of `pip freeze`:
appnope==0.1.0
argcomplete==1.9.3
arrow==0.15.5
attrs==19.3.0
autopep8==1.5.2
backcall==0.1.0
bcrypt==3.1.7
beautifulsoup4==4.9.0
boto3==1.10.34
botocore==1.13.34
certifi==2020.4.5.1
cffi==1.14.0
cfn-flip==1.2.2
chardet==3.0.4
click==7.1.1
coverage==5.1
cryptography==2.9
datadog==0.35.0
decorator==4.4.2
docutils==0.15.2
durationpy==0.5
envdir==1.0.1
envlog==0.1.1
Flask==1.1.2
furl==1.2.1
future==0.16.0
hjson==3.0.1
idna==2.9
importlib-metadata==1.6.0
Inject==4.1.2
ipython==7.13.0
ipython-genutils==0.2.0
itsdangerous==1.1.0
jedi==0.17.0
Jinja2==2.11.2
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.20.0
lxml==4.5.0
MarkupSafe==1.1.1
more-itertools==8.2.0
mypy==0.770
mypy-extensions==0.4.3
orderedmultidict==1.0.1
packaging==20.3
paramiko==2.7.1
parso==0.7.0
partnerpub==0.1.0
pexpect==4.8.0
pickleshare==0.7.5
pip-tools==4.5.1
placebo==0.9.0
pluggy==0.12.0
prompt-toolkit==3.0.5
ptyprocess==0.6.0
py==1.8.1
pycodestyle==2.5.0
pycparser==2.20
Pygments==2.6.1
PyNaCl==1.3.0
pynamodb==4.3.1
pyparsing==2.4.7
pysftp==0.2.9
pytest==5.4.1
pytest-cov==2.8.1
python-dateutil==2.6.1
python-slugify==1.2.4
PyYAML==5.3.1
requests==2.23.0
s3transfer==0.2.1
six==1.14.0
soupsieve==2.0
text-unidecode==1.3
toml==0.10.0
tqdm==4.19.1
traitlets==4.3.3
troposphere==2.6.0
typed-ast==1.4.1
typing-extensions==3.7.4.2
Unidecode==1.1.1
urllib3==1.25.8
wapoarc==1.10.1
wcwidth==0.1.9
Werkzeug==0.16.1
wsgi-request-logger==0.4.6
zappa==0.51.0
zipp==3.1.0
* Link to your project (optional):
* Your `zappa_settings.json`:

**Comment by emilynielson** [comment]
found it was a project issue not a zappa issue. Sorry!

**Comment by North46** [comment]
Having the same issue.  Can you expand on what your problem/solution was?
thx
