### ISSUE TITLE
Page not found due to stage in URL

### ISSUE THREAD

**Issue by alf-scotland** [Miserlou/Zappa#2095]
I deployed a Django app following the instructions [here](https://romandc.com/zappa-django-guide/) and all worked until recently. Now I am faced with an error 404 that the page cannot be found as the stage (`/dev`) is not part of my url configuration.

## Context
I have honestly no clue why this is no longer working, I seem to be not able to figure out the root cause. I have searched quite a bit for solutions, but all I could find was to change the script path, also mentioned here #1084 - but I do not want to use a custom domain, the cryptic AWS Lambda link is fine.

## Expected Behavior
The Django app should work fine, it used to work before.

## Actual Behavior
I am faced with an error that the `Page not found at /` ... and `The current path, dev/, didn't match any of these`, while I thought `dev/` should not be part of the path.

## Your Environment

* Zappa version used: 0.51.0
* Operating System and Python version: Mac OS & Python 3.7
* The output of `pip freeze`:
```
argcomplete==1.11.1
asgiref==3.2.7
astroid==2.4.0
autopep8==1.5.2
boto3==1.13.5
botocore==1.16.5
bump2version==1.0.0
certifi==2020.4.5.1
cfn-flip==1.2.3
chardet==3.0.4
click==7.1.2
diff-match-patch==20181111
Django==3.0.5
django-crispy-forms==1.9.0
django-login-required-middleware==0.5.0
django-reversion==3.0.7
django-reversion-compare==0.12.2
django-s3-storage==0.13.0
docutils==0.15.2
durationpy==0.5
future==0.18.2
hjson==3.0.1
idna==2.9
importlib-metadata==1.6.0
isort==4.3.21
jmespath==0.9.5
kappa==0.6.0
lazy-object-proxy==1.4.3
Markdown==3.2.1
mccabe==0.6.1
mysqlclient==1.4.6
pip-tools==5.1.2
placebo==0.9.0
pycodestyle==2.5.0
pylint==2.5.0
PyMySQL==0.9.3
python-dateutil==2.6.1
python-dotenv==0.13.0
python-slugify==4.0.0
pytz==2020.1
PyYAML==5.3.1
requests==2.23.0
rope==0.16.0
s3transfer==0.3.3
six==1.14.0
sqlparse==0.3.1
text-unidecode==1.3
toml==0.10.0
tqdm==4.46.0
troposphere==2.6.1
typed-ast==1.4.1
urllib3==1.25.9
Werkzeug==0.16.1
wrapt==1.12.1
wsgi-request-logger==0.4.6
zappa==0.51.0
zipp==3.1.0
```
* Link to your project (optional): https://cqrxu6pil3.execute-api.eu-central-1.amazonaws.com/dev
* Your `zappa_settings.json`: 
```json
{
    "dev": {
        "aws_region": "eu-central-1",
        "django_settings": "coi.settings",
        "profile_name": "default",
        "project_name": "coi-project",
        "runtime": "python3.7",
        "s3_bucket": "zappa-gvu5po0y7",
        "timeout_seconds": 60,
        "vpc_config" : {
            "SubnetIds": [
                "subnet-03bc56...",
                "subnet-04d36...",
                "subnet-0f815..."
            ],
            "SecurityGroupIds": [ "sg-089..." ]
        }
    }
```

**Comment by auslaner** [comment]
Is the API gateway still there in your AWS console?

**Comment by alf-scotland** [comment]
@auslaner Thanks for coming back. I was never able to figure out why it broke so I simply created it from scratch again and now everything works as expected. Forgot to close the actual issue here.
