### ISSUE TITLE
ERROR: zappa 0.51.0 has requirement python-dateutil<2.7.0, but you'll have python-dateutil 2.8.1 which is incompatible.

### ISSUE THREAD

**Issue by amsal-muhammad** [Miserlou/Zappa#2108]
python-dateutil<2.7.0 is an outdated version and many packages require python-dateutil>= 2.7.5.

Please update the version of python-dateutil requirement of Zappa.

* Zappa version used: 0.51.0
* Operating System and Python version: 3.7.7 Mac OS

**Comment by tommie-lie** [comment]
This is a duplicate of #1927.
