### ISSUE TITLE
documentation link is not working

### ISSUE THREAD

**Issue by avinash-bhosale** [Miserlou/Zappa#2130]
*Zappa documentation link is not working*

I tried to acccess https://blog.zappa.io/, but its not loading

**Comment by bigsee** [comment]
Perhaps related to [#2114] already reported?

**Comment by avinash-bhosale** [comment]
Yes actually. its already reported

**Comment by MerreM** [comment]
Is this project dead?

**Comment by jneves** [comment]
No, we're sorting some issues out as a maintainer suddenly left.

**Comment by avinash-bhosale** [comment]
> No, we're sorting some issues out as a maintainer suddenly left.

can someone make community-fork and continue with that

**Comment by MerreM** [comment]
Any eta?

**Comment by tobiashochguertel** [comment]
any update? can we help?

**Comment by MerreM** [comment]
https://github.com/MerreM/Zappa I'm going to try and move development to here.

https://join.slack.com/t/zappagroup/shared_invite/zt-ludx5h93-khGw664m9I5hlm1EXvhlEg
