### ISSUE TITLE
The API keys generated in deploy step are never deleted

### ISSUE THREAD

**Issue by parroyo** [Miserlou/Zappa#220]
The API key generated on the deploy step when the option 'api_key_required' is enabled is not deleted when running zappa undeploy.

**Comment by Miserlou** [comment]
Hey @mjgorman - can you take a look at this one?

**Comment by mjgorman** [comment]
Yeah, small oversight. I'll make a PR after I get home from DefCon

**Comment by Miserlou** [comment]
Thank you!

**Comment by Miserlou** [comment]
Fixed in https://github.com/Miserlou/Zappa/pull/229 - thanks for reporting, thanks for fixing!
