### ISSUE TITLE
It's not possible to use AWS SQS queues from Zappa

### ISSUE THREAD

**Issue by parroyo** [Miserlou/Zappa#221]
It's not possible to use AWS SQS queues from Zappa.

I guess the 'Resource' value for SQS in ATTACH_POLICY is not correct. 
The current value is:
`"arn:aws:sqs:::*"`
But it should be:
`"arn:aws:sqs:*:*:*"`

I couldn't find the right AWS documentation, but with the proposed syntax works fine for me.

**Comment by Miserlou** [comment]
Thanks for reporting this! I just pushed a fix in b33f42e, literally seconds before your PR! :)
