### ISSUE TITLE
Zappa template object has no attribute add_description error,  cfn_flip dependency

### ISSUE THREAD

**Issue by erix-mx** [Miserlou/Zappa#2223]
Hello everyone, Everything was working great, but now I get this error, I ran my successful pipeline, but it gave me the same error

![Bitmap](https://user-images.githubusercontent.com/82125058/124652739-12e39c80-de62-11eb-9874-fd070087e180.png)

I also had to add the **cfn_flip** dependency, this was not happening before, did something update?

**Comment by YankeeTube** [comment]
same issue

**Comment by dustin022** [comment]
Same issue, but it looks like for me it was related to this package troposphere updating from 2.7.1 to 3.0.1 as a dependency of zappa, I downgraded it back to 2.7.1 in my pipeline and fixed my issue

pipenv run pip install --upgrade troposphere==2.7.1

noticed it after doing a diff between my runs:

troposphere         2.7.1
to
troposphere         3.0.1

**Comment by YankeeTube** [comment]
@dustin022 Thank u!

**Comment by erix-mx** [comment]
Thank you very much @dustin022 , it also worked for me, now the pipeline marks me correctly.
