### ISSUE TITLE
JSON error responses are converted to HTML

### ISSUE THREAD

**Issue by claudeatsafe** [Miserlou/Zappa#223]
I am building a little Flask-based REST-API and deploying it with Zappa. It seems like it is not possible to return a valid JSON as error message. Zappa injects HTML headers before the actual error message. 

Error response in my local dev env:
```json
{
    "message": "Run 1703f7dc-4bd3-4f49-8674-5d849c0019 does not exist"
}
```
Error response from Zappa:
```html
<!DOCTYPE html>404
<meta charset="utf-8" />{
    "message": "Run 1703f7dc-4bd3-4f49-8674-5d849c0019 does not exist"
}
```

**Comment by Miserlou** [comment]
This is related to https://github.com/Miserlou/Zappa/issues/190

Fortunately, a solution has been found, we're just waiting for the PR from @randuhmm

**Comment by claudeatsafe** [comment]
Great! Looking forward to the fix.

**Comment by Miserlou** [comment]
I think this is fixed now.
