### ISSUE TITLE
S3 bucket is not reused with `slim_handler: True`

### ISSUE THREAD

**Issue by simsong** [Miserlou/Zappa#2243]
When Zappa is using the `slim_handler`, it does not reuse the temporary S3 bucket that it creates --- Even when zappa `update` command is used. This results  in the creation of many, many, many temporary buckets, until the quota is reached.
## Context
This is similar to #1643, except that user is encountering problems with temporary buckets are not needed for the Zappa operation. 

## Expected Behavior
The created bucket should be reused. Right now, the name is not resused. 

## Actual Behavior
New buckets keep getting created.

## Possible Fix
After a bucket is created, update that `zappa_settings.json` file to note the bucket name.

## Your Environment

* Zappa version used: 0.58.0
* Operating System and Python version: MacOS

**Comment by souravjamwal77** [comment]
Hi @simsong, the new and official Zappa repo is [Here](https://github.com/zappa/Zappa)
I think you're already on our Slack channel.

**Comment by simsong** [comment]
Yup. I will migrate this issue.

**Comment by simsong** [comment]
Migrated to https://github.com/zappa/Zappa/issues/1333

**Comment by souravjamwal77** [comment]
Hi @simsong , you wanted to use ARM images for lambda deployments. I have made ARM docker images for lambdas, ping me on our official Zappa slack channel.

**Comment by simsong** [comment]
Thanks! I'm burried in something else right now. 
The big thing I want, I think, is to figure out how to use 'layers'. I have gigabytes of data in models that don't need to be uploaded to S3 each time...
