### ISSUE TITLE
Feature request: more flag-aware zappa cookie

### ISSUE THREAD

**Issue by mgalvey** [Miserlou/Zappa#227]
Right now, it looks from the middleware code like the only "metadata" value that gets inherited by the zappa cookie is expiration date, the oldest of which is bubbled up to the zappa cookie. I'd like for there to be an option for the middleware to be aware of flags like Secure and HttpOnly, and if any cookie contains these flags, the zappa cookie inherits them as well.

I think it should probably be an option that has to be explicitly set, since this kind of inheritance by default could violate user expectations if they're relying on javascript-accessible cookies.

Is there any reason that this couldn't be done?

**This is the end of the formal feature request.**

Also, I came across a related bit of information regarding a nasty hack that may enable more than one cookie (turning this into a workable solution would likely be ugly): https://forums.aws.amazon.com/thread.jspa?messageID=701434#jive-message-725953. I'm not saying that this should necessarily be factored into the Zappa code, but it is a potential way to allow users to set more than one cookie, assuming it works in the first place.

Off the top of my head, you could do a similar setup to the parameter_depth option, where the user sets a number in zappa_settings.json and Zappa iterates through that number of different casings for the set-cookie header and creates those mappings in API gateway.

**Comment by Miserlou** [comment]
Don't think is relevant anymore, we no longer use the encoding hack.
