### ISSUE TITLE
Come up with a Zappa organization/communication plan

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/Zappa#23]
The project is still small and manageable right now, but we've already got 3 different projects, and we _may_ need a way to communicate outside of GitHub issues.

I personally like GitHub issues, but it might be easier to collaborate if we had a real-time forum as well.  Mailing list? IRC? Gitter? Web chat? Slack? I don't know what the community would like the most.

**Comment by collingreen** [comment]
:+1: any of the above (with a slight lean toward slack for search and announcements).

FYI - I tried to email you about this twice. There may be a hole in the Internet somewhere between our emails.

**Comment by mathom** [comment]
Issues are fine with me, but realtime stuff could be useful. I like slack as well since I already use it for work :grinning:

**Comment by Miserlou** [comment]
@Doerge - how do you feel about Slack? That seems to be the going consensus..

**Comment by Doerge** [comment]
I have very little experience with any of these, so I will just follow along. Slack sounds fine!

**Comment by Miserlou** [comment]
Okay, I have created a Slack channel - zappateam.slack.com

I have no idea how to add you guys.

**Comment by Miserlou** [comment]
https://slackautoinviter.herokuapp.com/ <---
