### ISSUE TITLE
Validate zappa_settings.json before uploading

### ISSUE THREAD

**Issue by smp** [Miserlou/Zappa#247]
It's quite easy to forget a comma or other simple formatting mistakes. Please consider validating settings.json prior to full zip/upload/deploy to avoid issues proactively.

**Comment by Miserlou** [comment]
On the client side, we actually use _hson_ rather than json. Should we use that server side as well? I've been holding off on that as it seems server side settings should be more strict.

**Comment by Miserlou** [comment]
Wait, I'm actually confused by what you mean by this. Can you give me an example?

**Comment by collingreen** [comment]
It came up in slack - essentially the problem is that if you have a syntax error in your zappa_settings.json file, the error doesn't show up until you actually run the code on lambda, and the error it gives isn't very helpful in chasing down the actual problem.


```
[1471201248450] need more than 1 value to unpack: ValueError
Traceback (most recent call last):
  File "/var/task/handler.py", line 249, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 107, in lambda_handler
    return cls().handler(event, context)
  File "/var/task/handler.py", line 123, in handler
    module, function = whole_function.rsplit('.', 1)
```

> sees a missing comma in his zappa_config

**Comment by Miserlou** [comment]
I think this is taken care of?
