### ISSUE TITLE
Zip not appearing on S3

### ISSUE THREAD

**Issue by gricey432** [Miserlou/Zappa#250]
From what I can gather in the docs, if I provide a `s3_bucket` in the config I should expect the deployment zips to be stored there. My code is deploying fine to lambda but isn't uploading to the S3 bucket.
Am I doing something wrong here or have I misunderstood what the bucket is used for?

**Comment by Miserlou** [comment]
The zip in the simply s3 bucket gets deleted by Zappa after deployment/update is finished simply to save on the cost of storing it. It's not used for anything once the function is registered. Is that a feature you need? It could be made into an optional flag I suppose but I don't see the point.

**Comment by gricey432** [comment]
My use case for keeping them is an artefact history, like the existing flag for not deleting the local zip. Afaik you can only download the latest code bundle from Lambda, it'd be nice to have a versioned archive on S3.
Couple this with a feature I've just suggested #254, if Zappa could delete old versions I would still want a way to download old artefacts. No point rolling some custom artefact storage if Zappa is already putting them on S3 and the delete could just be disabled.

**Comment by Miserlou** [comment]
What do you need them for? I think the `rollback` command should work even if they're not on S3 still.

**Comment by gricey432** [comment]
If I start deleting old versions as suggested in #254 I doubt the rollback will work.
I need them for auditing, if a package introduces a bug but the version has been deleted, it'd be easy to get a zip off s3 and ensure the package runs on lambda exactly as it did at the time. It's not the end of the world to not have it, but it'd just be a nice feature for enterprise style deployments where there are artefact requirements.

**Comment by gricey432** [comment]
If you think this is all a bit outside the scope of Zappa it'll be easy to just upload them to S3 after Zappa is done. If you think it makes sense to have, I'm happy to put it in and make a PR.

**Comment by Miserlou** [comment]
Auditing is a great use case to consider, then I suggest that we split the current `delete_zip` advanced setting into `delete_local_zip` and `delete_s3_zip`, default true for both.

**Comment by collingreen** [comment]
Also, coherent filenames for the zips -- perhaps timestamps?

**Comment by Miserlou** [comment]
I think they're already unix epoch timestamps..

**Comment by collingreen** [comment]
Sounds perfect :)

**Comment by gregdetre** [comment]
Thanks for this suggestion and solution. As a new user, I had expected that disabling the 'delete_zip' setting would leave the .zip on S3. It took a while before I realized it referred to the local .zip - so I think splitting it into two settings makes sense.

**Comment by Miserlou** [comment]
Fixed by @mcrowson ! :D
