### ISSUE TITLE
Zappa init error

### ISSUE THREAD

**Issue by ccverak** [Miserlou/Zappa#259]
Hi there,
I'm trying to get started with Zappa but I can't initialize with zappa init, I'm using pyenv and pyenv-virtualenv, I have already activated the env but zappa init keeps saying:
```
Zappa must be run inside of a virtual environment!
Learn more about virtual environments here: http://docs.python-guide.org/en/latest/dev/virtualenvs/
```

if I enter to the python shell and type  `hasattr(sys, 'real_prefix') ` it returns True
can you please help?
Details:

python version 2.7.12
zappa version 0.21.0
`pyenv which python` and `pyenv which zappa` are pointing to the pyenv virtualenv I created

**Comment by Miserlou** [comment]
Ah, I don't really know too much about pyenv. We should do testing with that too.

What happens if you try
`not ( hasattr(sys, 'real_prefix') or hasattr(sys, 'base_prefix') )`

in your pyenv?

**Comment by Miserlou** [comment]
Or not ( hasattr(sys, 'prefix') or hasattr(sys, 'real_prefix') or hasattr(sys, 'base_prefix') )

**Comment by Miserlou** [comment]
Poke

**Comment by collingreen** [comment]
@ccverak bump
