### ISSUE TITLE
Boto should Handle Loading Credentials

### ISSUE THREAD

**Issue by cancan101** [Miserlou/Zappa#26]
Why [all this logic to load credentials](https://github.com/Miserlou/Zappa/blob/8841e4affd02003ca4a6368ef830c892350b9d18/zappa/zappa.py#L764-L796)? Boto does all of this: http://boto.cloudhackers.com/en/latest/boto_config_tut.html#boto-config

**Comment by mathom** [comment]
:+1: I agree, we should probably have botocore do the heavy lifting.

PS: we're moving to 100% boto3 and the docs can be found at http://boto3.readthedocs.org/en/latest/

**Comment by Miserlou** [comment]
Agreed.
