### ISSUE TITLE
Error - Attempted relative import in non-package Zappa with django

### ISSUE THREAD

**Issue by yuvalfer** [Miserlou/Zappa#260]
Hi,

I'm trying to deploy a django app using zappa (not zappa-django).
while the app work with runserver, and zappa successfully deploy.

Lambda logs module initialization error: Attempted relative import in non-package 

Attached my Zappa setting and django settings

[settings.txt](https://github.com/Miserlou/Zappa/files/425236/settings.txt)
[zappa_settings.txt](https://github.com/Miserlou/Zappa/files/425237/zappa_settings.txt)

Thanks.

**Comment by Miserlou** [comment]
You'll need to post the full traceback please.

**Comment by yuvalfer** [comment]
This is all the output I get from the lambda function.
I've used "log_level": "DEBUG"

**Comment by yuvalfer** [comment]
This is all the output I get from the lambda function.
I've used "log_level": "DEBUG"

**Comment by Miserlou** [comment]
..?
