### ISSUE TITLE
Detecting if running inside Zappa or vanilla Flask

### ISSUE THREAD

**Issue by gricey432** [Miserlou/Zappa#271]
I've got a Flask app which is going to be deployed both on AWS using Zappa and just as a normal flask app on a server.
In my views, I'd like to detect if I am running in zappa or if I'm running standalone, is there a way to do this? Some value in the request maybe?

**Comment by Miserlou** [comment]
There currently isn't a way to do this it looks like, other than by setting a custom environment variable. It used to be possible from the WSGI request, but I took that out.

Would locally setting an environment variable before the WSGI call be sufficient?

**Comment by collingreen** [comment]
@miserlou - Why was it taken out of the wsgi request?

Either way, adding it as a local environment var (or maybe as a header? that seems pretty common as well) should be fairly straightforward, and I think it probably makes sense to have a standard way to detect if running in zappa/lambda or not.

There was a discussion/issue/pr/?? about setting environment variables from zappa_settings.json, but I can't seem to find it -- that might be an existing/good-enough solution.

**Comment by Miserlou** [comment]
Another thought is to check if your app/path is running out of /var/task

**Comment by collingreen** [comment]
That will give you lambda, but it might be worth it to separate the two pieces of platform (zappa vs the infrastructure).

**Comment by Miserlou** [comment]
I added this to handler, is it satisfactory?

```
        # Let the system know that this will be a Lambda/Zappa/Stack
        os.environ["SERVERTYPE"] = "AWS Lambda"
        os.environ["FRAMEWORK"] = "Zappa"
        os.environ["PROJECT"] = settings.PROJECT_NAME
        os.environ["STAGE"] = settings.API_STAGE
```

**Comment by Miserlou** [comment]
Also added local environment_variables: https://github.com/Miserlou/Zappa#local-environment-variables

**Comment by gricey432** [comment]
Sorry I didn't respond, took a few days off work. Looks good to me, cheers.
