### ISSUE TITLE
Packages with '.' in the name fail

### ISSUE THREAD

**Issue by gricey432** [Miserlou/Zappa#272]
Python packages with `.` in the name such as `zope.sqlalchemy` fail to be imported properly on lambda.
The file structure is
```
/site-packages
    /zope
        /sqlalchemy
            __init__.py
            (other files)
```
When executed on lambda it fails to import `zope.sqlalchemy`.

I'm currently working around this in my Jenkins job by doing
```
touch $WORKSPACE/.pyenv/lib/python2.7/site-packages/zope/__init__.py
```
before running Zappa.

Is this something that could / should be built into Zappa?

**Comment by Miserlou** [comment]
Good one, related: https://github.com/Miserlou/Zappa/issues/45

PRs welcome..
