### ISSUE TITLE
API Gateway can probably set the Location header for redirects

### ISSUE THREAD

**Issue by mathom** [Miserlou/Zappa#28]
Based on [this forum post](https://forums.aws.amazon.com/thread.jspa?threadID=203889) and some experimentation I believe it's now possible to set the Location header for redirects. For example, I have a lambda function as follows:
```javascript
exports.handler = function(event, context) {
    if (/^[^.]+\.mydomain.com$/.test(event.Host)) {
        context.succeed({'Location': event.Location});    
    }
    else {
        context.fail('Invalid Host');
    }
};
```

This can be set as a header on the 301 with the following mapping:
<img width="1012" alt="screen shot 2016-02-24 at 4 51 26 pm" src="https://cloud.githubusercontent.com/assets/399441/13303790/e4bb15a8-db16-11e5-8092-f7aa4d2faecc.png">

**Comment by Doerge** [comment]
I think the gateway already sets the header for redirects. The setup is just a bit complicated, as it must handle other response codes as well.

The basics (as I understand) is that the handler calls some app (Django/flask) and then interprets the result. Based on that, it either returns the response normally, (200), or raises an exception with a special payload in the body.

This is the handler after the app have returned a response:

```python
        # To ensure correct status codes, we need to
        # pack the response as a deterministic B64 string and raise it
        # as an error to match our APIGW regex.
        # The DOCTYPE ensures that the page still renders in the browser.
        if response.status_code in [400, 401, 403, 404, 500]:
            content = "<!DOCTYPE html>" + str(response.status_code) + response.data
            b64_content = base64.b64encode(content)
            raise Exception(b64_content)
        # Internal are changed to become relative redirects
        # so they still work for apps on raw APIGW and on a domain.
        elif response.status_code in [301, 302]:
            # Location is by default relative on Flask. Location is by default
            # absolute on Werkzeug. We can set autocorrect_location_header on
            # the response to False, but it doesn't work. We have to manually
            # remove the host part.
            location = response.location.split(environ[u'HTTP_HOST'])[1]
            raise Exception(location)
```

The gateway parses exceptions and handles them differently based on the payload in the exception.
E.g. for a redirect we look for an exception like `raise Exception('/my/redirect/location')`.

zappa.py line 622-625'ish configures the gateway:

```python
elif status_code in ['301', '302']:
    selection_pattern = '\/.*'
    response_templates = {content_type: REDIRECT_RESPONSE_TEMPLATE for content_type in self.integration_content_types}
    response_parameters["method.response.header.Location"] = "integration.response.body.errorMessage"
```

The `selection_pattern` above is an expression which looks for exception payloads that starts with forward slash.

This is transparent from inside the app. You just return a 301 or 302 response.

Or is there a simpler/better way of doing this?

**Comment by mathom** [comment]
Ah, that makes sense. Looking over the mapping again, looks like it's already working like I was thinking it should.

Thanks for the explanation!

**Comment by Doerge** [comment]
No problemo! Took me quite a while to grok!
