### ISSUE TITLE
Lambda Memory not Updated

### ISSUE THREAD

**Issue by SectorNine50** [Miserlou/Zappa#282]
After having deployed the project using the default memory settings, I decided I didn't need 512 MB, and changed the setting down to 128 in my zappa_settings.json file and ran `zappa update dev`.  I found that the memory setting on the Lambda function wasn't updated, so I ended up changing it manually within the AWS console.

Not a huge deal, but figured I'd submit an issue.

**Comment by Miserlou** [comment]
Yeah, this is actually annoying for a few other reasons. 

We should be able to call update_function_configuration(**kwargs) to update any of these:    
 
FunctionName='string',
    Role='string',
    Handler='string',
    Description='string',
    Timeout=123,
    MemorySize=123,
    VpcConfig={
        'SubnetIds': [
            'string',
        ],
        'SecurityGroupIds': [
            'string',
        ]
    },

**Comment by Miserlou** [comment]
Fixed!
