### ISSUE TITLE
Environment variables not being passed to Lambda?

### ISSUE THREAD

**Issue by keitaoouchi** [Miserlou/Zappa#287]
I'm using `zappa==0.21.0`, and it appears environment variables are not being passed to Lambda. Keys like `PROJECT` and `STAGE` are also not being passed.

When I dump os.environ.keys() from Lambda:

```
for key in os.environ.keys():
    print(key)
```

Output is:

```
AWS_LAMBDA_FUNCTION_VERSION
LAMBDA_TASK_ROOT
PATH
LD_LIBRARY_PATH
LAMBDA_CONSOLE_SOCKET
AWS_LAMBDA_FUNCTION_NAME
AWS_REGION
AWS_SESSION_TOKEN
AWS_SECURITY_TOKEN
LAMBDA_RUNTIME_DIR
LANG
AWS_LAMBDA_FUNCTION_MEMORY_SIZE
LAMBDA_LOG_FD
PYTHONPATH
AWS_LAMBDA_LOG_GROUP_NAME
AWS_DEFAULT_REGION
AWS_LAMBDA_LOG_STREAM_NAME
AWS_ACCESS_KEY_ID
LAMBDA_SHARED_MEM_FD
LAMBDA_CONTROL_SOCKET
LAMBDA_RUNTIME_LOAD_TIME
AWS_SECRET_ACCESS_KEY
```

My `zappa_settings.json` is something like this:

```
{
  "prod": {
    "api_key_required": false,
    "cache_cluster_enabled": false,
    "aws_region": "ap-northeast-1",
    "app_function": "frontend.api.app",
    "s3_bucket": "xxxxxxxxxxx",
    "events": [
      {
        "function": "backend.job.xxx",
        "expression": "cron(30 03 * * ? *)"
      }
    ],
    "http_methods": [
      "GET"
    ],
    "exclude": ["*.gz", ".idea", "*.iml", "doc", ".env*", ".git*", "requirements.dev*", "command"],
    "environment_variables": {
      "HOGE": "fuga"
    }
  }
}
```
Are there any missing settings in my zappa_settings.json?

**Comment by Miserlou** [comment]
Hey Keita!

Sorry, the version documented on the README is behind the currently
published version! Please use -master for now, I will update the version on
pip very soon. Normally it doesn't get this far behind, but this time it
requires some special upgrade code.

**Comment by Miserlou** [comment]
Remote environment variables will still work, local ones were just added
yesterday.

**Comment by keitaoouchi** [comment]
YEAH, It worked :metal: 

Thank you for your reply!!!
