### ISSUE TITLE
Every time I run 'zappa deploy', it creates a new keep_warm rule

### ISSUE THREAD

**Issue by gregdetre** [Miserlou/Zappa#297]
I'm running `zappa deploy dev` with the following `zappa_settings.json`:

```
{
    "dev": {
        "app_function": "app.app", 
        "s3_bucket": "zappa-qxdsodm6o"
    }
}
```

As I understand it, the `keep_warm` setting is True, by default.

The problem is that every time I deploy, it adds a new `keep_warm` rule (I have deployed 5 times):

![screenshot 2016-09-01 11 37 50](https://cloud.githubusercontent.com/assets/802920/18173716/ab666f5c-7038-11e6-8a32-c89220d38525.png)

Isn't this a bug?

**Comment by Miserlou** [comment]
As far as I can tell, the bug is actually in the AWS Web Console - those
aren't actually scheduled rules any more.

**Comment by Miserlou** [comment]
Fixed in latest PR! I think!

**Comment by aectann** [comment]
Yep it was :)
