### ISSUE TITLE
Custom domain instructions leave you hanging

### ISSUE THREAD

**Issue by gregdetre** [Miserlou/Zappa#298]
I've been following the very clear instructions here:

https://github.com/Miserlou/Zappa/blob/master/docs/domain_with_free_ssl_dns.md

I have created my `account.key` and successfully run `zappa certify`, but I don't know what to do next.

Do I have to create an AWS API Gateway resource that matches the `domain` in `zappa_settings.json`? Do I just have to wait an hour, and then try visiting the domain in a browser?

Apologies for my ignorance - everything in the docs is super up to this point!

**Comment by gregdetre** [comment]
Ok, I'm sorry. This was carelessness. I waited a little longer, and suddenly the domain magically worked!

On re-reading the doc, it does say: "You can now use your SSL-secured Zappa application on your target domain. Note that the first time you run this command, it can take around 45 minutes for Amazon to create your domain, and it'll take about 60 seconds every time after that."

I didn't read it carefully enough.

**Comment by Miserlou** [comment]
:)
