### ISSUE TITLE
Zappa cookie handling

### ISSUE THREAD

**Issue by Doerge** [Miserlou/Zappa#31]
Here's a scenario which my current attempt at a WSGI middleware can't handle regarding multiple cookies (I think the Django-zappa middleware solution can't handle it either.)

1. Set 2 cookies from your app, `foo` and `bar`. (Django or flask).
2. Read them from another page and ensure they exist.
3. Update `foo` with new value.
4. Read them both. Only foo will be set since we have overwritten the old `zappa` cookie which contained both, with one that only contained `foo`.

Possible fixes:

- Don't package all cookies into one. Encode them individually.
- Force the app (Django/flask) to update all cookies at once.

I think we should do first option as it respects the HTTP semantics instead of hiding them. Unless there are complications I haven't considered?

**Comment by Miserlou** [comment]
Ah. Shitty. Hm.

We have to do that cookie-packing thing because we can only pass one through API Gateway. That's why we have to make the Zappa "supercookie".

So, I think we have to have to echo back all of the cookies that were received unless in addition to the updated cookie, unless they're explicitly set to nothing. 

Does that make sense?

**Comment by Doerge** [comment]
Hmmm... Yes and no.

I'm not sure I understand how it works. Is the mapping only performed in  `TEMPLATE_MAPPING` in `zappa.py` or does it also happen elsewhere?

Can't we pack multiple cookies into one header? Like "Cookies": "foo=123; bar=456; Path=/"?

**Comment by Miserlou** [comment]
No, unfortunately that's why we need to do all of this - [cookies require individual lines](http://stackoverflow.com/a/18967872).

Still, I don't think that this is insurmountable - it's just a state problem. We just have to keep track of what goes in and make sure it matches what comes out.

**Comment by Doerge** [comment]
Closing this. The WSGI middleware now handles multiple cookies.

**Comment by Miserlou** [comment]
:moneybag: :moneybag: :moneybag:
