### ISSUE TITLE
zappa.io should redirect to www.zappa.io

### ISSUE THREAD

**Issue by ssilverm** [Miserlou/Zappa#311]
going to zappa.io results in a DNS error.

www.zappa.io works fine.

**Comment by Miserlou** [comment]
Yeah, it should! This is really annoying, I thought I could do this in Route53 but it's giving me some guff.

**Comment by Miserlou** [comment]
Normally, it's better to stay off the apex domain, but Amazon seems to think the opposite. I might do this the other way round, so that www. points to the apex.

**Comment by clburlison** [comment]
This looks like it can be closed.

**Comment by mjhea0** [comment]
It looks to still be an issue, at least one my end -

1. https://www.zappa.io/ - works
1. https://zappa.io/ - breaks
1. zappa.io/ - breaks

**Comment by stonygrunow** [comment]
the naked domain (non-www) does not work for me either. If you are using Amazon's route53, then an A record to an Alias should work.
