### ISSUE TITLE
AWS_IAM authentication

### ISSUE THREAD

**Issue by slank** [Miserlou/Zappa#314]
I have an API I'd like to put behind AWS_IAM authentication. I see that `apigateway.put_method` is always called with `authorizationType='none'`. If there's no in-flight change to add support for IAM authentication, I'll submit a PR.

**Comment by Miserlou** [comment]
Right now the closes thing we have is API-key secured endpoints, IAM would be a welcome addition. 

https://github.com/Miserlou/Zappa#enabling-secure-endpoints-on-api-gateway

**Comment by slank** [comment]
My PR seems to do the job, but it adds code to a currently untested codepath and slightly reduces coverage. I'm happy to pay penance on another issue, but anything I do to increase coverage will be somewhat out of scope for this issue.

**Comment by Miserlou** [comment]
I got confused here for a second - you have two accounts!

If the PR works and there is documentation for it, I'm all for it! We can try to bring up the coverage when the next testing sprint happens.

I guess my only question before merge is why did you make 'none' become "NONE"? Is there any AWS documentation showing what the convention is about this?

**Comment by slank** [comment]
Oops, sorry about the confusion! I must have created the PR in a different browser session!

I changed the case of the value because those are the options displayed for that field in the API Gateway console (see this [AWS blog post](https://aws.amazon.com/blogs/compute/introducing-custom-authorizers-in-amazon-api-gateway/)). The API Gateway docs also [mention](https://docs.aws.amazon.com/apigateway/api-reference/resource/method/#authorizerId) that the value when choosing a custom authorizer is `CUSTOM`, so using `NONE` and `AWS_IAM` seemed more consistent.
