### ISSUE TITLE
[question] Distinct lambda per route?

### ISSUE THREAD

**Issue by asadoughi** [Miserlou/Zappa#315]
This might be a dumb question, but why isn't there a distinct lambda per route? For example:
```{python}
@app.route("/hello")
def hello():
    return "Hello!"


@app.route("/goodbye")
def forward():
    return "Goodbye!
```
will define one lambda for both `/hello` and `/goodbye` instead of one lambda for `/hello` and one for `/goodbye`. What are the tradeoffs in defining a distinct lambda per route versus one lambda for both routes?

**Comment by Miserlou** [comment]
Why would there be a distinct lambda for each?

If you'd like to discuss further, please join our Slack channel: https://slack.zappa.io
