### ISSUE TITLE
Extra redirects after redirection performed

### ISSUE THREAD

**Issue by koriaf** [Miserlou/Zappa#318]
* Make default new Django (1.10, 1.9) project with stable Zappa (0.22.7 in my case). Ignore database and other steps, it won't be required.

* urls.py:
```
from django.conf.urls import url
from django.contrib import admin
from django.views.generic import RedirectView, TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html')),
    url(r'^admin/', admin.site.urls),
    url(r'^redirect/$', RedirectView.as_view(url='/'))
]
```

* settings.py: add app itself into INSTALLED_APPS and create templates directory and add index.html here with some sane text content and empty line at the end.

* Configure zappa as usual:
```
{
    "dev": {
        "django_settings": "zappa_test.settings", 
        "s3_bucket": "zappa-test-dev",
        "domain": "zappa1.XXXX.org",
        "lets_encrypt_key": "s3://zappakeys/zappa1.XXXX.org.key",
        "aws_region": "ap-southeast-2",
        "http_methods": ["GET", "POST"],
    }
}
```

* deploy app and have url https://xxxx.execute-api.ap-southeast-2.amazonaws.com/dev

* do curl to check if responses are sane (you can mix steps and run them multiple times)
```
curl https://xxxx/dev/ -v (see sane text from index.html)
curl https://xxxx/dev/redirect/ -v (see redirection html - expected)
curl https://xxxx/dev/ -v (see sane text from index.html again)
```

* update zappa to current github version (`pip install git+https://github.com/Miserlou/Zappa.git`), run `zappa update`

* Then curl again:
```
curl https://xxxx/dev/ -v (see sane text from index.html, expected)
curl https://xxxx/dev/redirect/ -v (see redirection html - expected)
curl https://xxxx/dev/ -v (redirection HTML instead of sane text - why?)
any other url: redirection html
```

* if custom domain name assigned then it's just redirects forever.

After that any request, even to non-existent url, returns same HTML redirection to index page. Hope you can reproduce it :-)

**Comment by Miserlou** [comment]
Thanks for reporting this! Excellent reproduction report, please give me a little time to try to find who to blame. :)

**Comment by Miserlou** [comment]
Confirmed.

**Comment by Miserlou** [comment]
I hate this error.

**Comment by Miserlou** [comment]
Got it! Wasn't what I expected, it was an unanticipated result of reusing the middleware, not the WSGI.
