### ISSUE TITLE
Implement WSGI app interface

### ISSUE THREAD

**Issue by bbangert** [Miserlou/Zappa#32]
Zappa does not actually implement a WSGI app wrapper, it does translate a JSON dict into a WSGI environ, perhaps the function in wsgi.py should be named create_wsgi_environ instead.

The zappa_django project contains a lambda handler however that almost implements a proper WSGI app wrapper.

That handler should be extracted into zappa and fixed to truly call a WSGI app, this would make it much easier to add support for any framework using WSGI.

**Comment by bbangert** [comment]
I can take a quick stab at a PR todo this.

**Comment by Doerge** [comment]
I have made some progress towards this here: [https://github.com/Doerge/Zappa](https://github.com/Doerge/Zappa) but my WSGI understanding is limited so any comments or other efforts are most welcome!

**Comment by mathom** [comment]
You might take a look at the werkezeug stuff in https://github.com/Miserlou/django-zappa/issues/9

**Comment by Doerge** [comment]
Btw. @bbangert join us on Slack here: [https://slackautoinviter.herokuapp.com/](https://slackautoinviter.herokuapp.com/)

**Comment by bbangert** [comment]
I took a rough guess at this func here:
https://github.com/bbangert/Zappa/blob/master/zappa/wsgi.py#L117

**Comment by Doerge** [comment]
Awesome!

One thing that springs to mind: I think we need exceptions raised on anything but 200. There is a small explanation as to why [over here on issue 28](https://github.com/Miserlou/Zappa/issues/28).

**Comment by Miserlou** [comment]
Implemented in 0.14.0
