### ISSUE TITLE
Example for SNS source event

### ISSUE THREAD

**Issue by ccverak** [Miserlou/Zappa#321]
Hi there, I'm trying to create a subscription to a previously created SNS Topic through events source, do you have any example I can take a look at? basically, I don't know how should I structure the JSON and pass the Topic, etc.

**Comment by parroyo** [comment]
Hey @ccverak, If you mean how to structure the zappa_settings file, this is an example:

```
        "events": [
            {
                "function": "<module.function>",
                "event_source": {
                    "arn":  "<arn of the SNS topic>",
                    "events": [
                        "sns:Publish"
                    ]
                }
            }
        ]
```

And your function should receive event and context as arguments:
```
def readTopic(event, context):
   ....
```

I hope it helps.

**Comment by ccverak** [comment]
Hi @parroyo That's exactly what I needed, Thanks!
