### ISSUE TITLE
how do you debug errors

### ISSUE THREAD

**Issue by tbarbugli** [Miserlou/Zappa#324]
I just deployed a Django app but nothing works (deploy went fine). running check management command returns:

```
populate() isn't reentrant: RuntimeError
Traceback (most recent call last):
  File "/var/task/handler.py", line 460, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 208, in lambda_handler
    raise ex
RuntimeError: populate() isn't reentrant
```

And any request to the app outputs:

```
{
    "message": "An uncaught exception happened while servicing this request.", 
    "traceback": [
        "Traceback (most recent call last):\n", 
        "  File \"/var/task/handler.py\", line 386, in handler\n    response = Response.from_app(self.wsgi_app, environ)\n", 
        "  File \"/private/var/folders/41/q6bnwcwn07lg0_4zdwfsq2gc0000gn/T/pip-build-4PP29N/Werkzeug/werkzeug/wrappers.py\", line 865, in from_app\n", 
        "  File \"/private/var/folders/41/q6bnwcwn07lg0_4zdwfsq2gc0000gn/T/pip-build-4PP29N/Werkzeug/werkzeug/test.py\", line 871, in run_wsgi_app\n", 
        "TypeError: 'NoneType' object is not callable\n"
    ]
}
```

Unless I missed something these errors are completely useless; is there any way you can find more information about what is not working with a deployment?

**Comment by Miserlou** [comment]
Which Django version is this? Somebody else had this error before, don't remember what it was. Second..

**Comment by Miserlou** [comment]
Also, which Zappa version? This was supposed to be fixed. ping @koriaf

**Comment by tbarbugli** [comment]
`zappa==0.23.1`
`Django==1.9.5`

**Comment by koriaf** [comment]
Have you installed zappa < 0.23 in this virtualenv? Does it reproduce for different Django version (1.10 for example)? Does zappa deploy & zappa undeploy help (if you change zappa version)?

**Comment by tbarbugli** [comment]
started a fresh virtualenv and installed latest zappa from pip, should I try older versions of Zappa?

**Comment by tbarbugli** [comment]
undeploy + install django 1.10 + deploy gave me the same result

**Comment by koriaf** [comment]
Any chance your project calls django.setup() or apps.populate() inside it? May be some 3rd party library does.

Does it trivial test project or already having some stuff inside? It looks like a threading problem which I can't reproduce.

**Comment by Miserlou** [comment]
Cannot reproduce with a fresh install, tested 1.8, 1.9 and 1.10.

**Comment by Miserlou** [comment]
Gonna close without more info, as I tried to repro but couldn't. Feel free to reopen if necessary.

**Comment by koriaf** [comment]
Btw, this task have more life that I expected.
Errors are getting lost somewhere, and we get this error. It can be safely replaced to message "Were was an exception, look for it in `zappa tail` output."

As I see when something bad happens on lambda/zappa side, original exception gets eaten by this message, and no debug information shown to user.

May be worth forking werkzeug and make more detailed explanation about what happened in such cases.

Today I got this error when newrelic package wasn't pushed to zappa (fixed by `ln -s newrelic-2.70.0.51/newrelic/ ./newrelic`); and some guy got it because django wasn't able to make local log file, and I can't even imagine how many people have it because of some environment problems, unrelated to zappa, and never see the source exception.

**Comment by codalprashant** [comment]
My requirements.txt file
========================================================================

base58==0.2.4
boto3==1.4.1
botocore==1.4.70
cffi==1.8.3
click==6.6
cryptography==1.5.3
Django==1.9
docutils==0.12
enum34==1.1.6
futures==3.0.5
hjson==2.0.2
idna==2.1
ipaddress==1.0.17
jmespath==0.9.0
kappa==0.6.0
lambda-packages==0.10.0
ndg-httpsclient==0.4.2
placebo==0.8.1
pyasn1==0.1.9
pycparser==2.17
pyOpenSSL==16.2.0
python-dateutil==2.6.0
python-slugify==1.2.1
PyYAML==3.12
requests==2.11.1
s3transfer==0.1.9
six==1.10.0
tqdm==4.9.0
troposphere==1.8.2
Unidecode==0.4.19
Werkzeug==0.11.11
wsgi-request-logger==0.4.6
zappa==0.28.3
==========================================================================

Ubunut 14.04


Working for me

**Comment by marcelchastain** [comment]
I spent about 12 hours wrestling with this error from 2 of my local environments
1. osx 10.11, virtualenv, python 2.7.11, django 1.8.6
2. virtualenv ubuntu 14.04 x86 64, virtualenv, python 2.7.11, django 1.8.6

Every time I deployed, I encountered `RuntimeError: populate() isn't reentrant`. 
Tried all kinds of exotic debugging techniques to see if multiple threads were in play, etc. Nothing.
Still affecting me.

My coworker, OTOH, deployed from his machine (same virtualenv setup) and it worked immediately.
Only difference I can tell is the python version - I had 2.7.11, he had 2.7.6.

Attached are exact pip versions which work on my coworker's machine, but fail on mine.

@koriaf @Miserlou, any chance this might be related to python version?

Is there any additional information I can give you to help debug the issue, since I can reproduce?
[requirements-pip-freeze.txt](https://github.com/Miserlou/Zappa/files/629231/requirements-pip-freeze.txt)

**Comment by danielwhatmuff** [comment]
I have the same error. Only log output I get even in debug mode is "NoneType' object is not callable".

**Comment by marcelchastain** [comment]
@danielwhatmuff I ended up checking out the code on a (free tier) ec2 instance and just deploying from there. Actually ends up saving me time because the upload speed is so fast!

**Comment by monkut** [comment]
Seeing the same issue here when trying to run `zappa manage dev migrate` for the first time.

`zappa manage dev check` returned the same error, but looking at the `zappa tail` output I see that the zappa handler doesn't appear to find one of my django apps....

my guess is it doesn't like my foreignkeys to another django app using the `models.ForeignKey("APPNAME.MODELNAME") notation?  circular-ish dependency issue, or load order issue?

```
 ...
  File "/var/task/handler.py", line 143, in __init__
  wsgi_app_function = get_django_wsgi(self.settings.DJANGO_SETTINGS)
  File "/var/task/zappa/ext/django_zappa.py", line 20, in get_django_wsgi
  return get_wsgi_application()
  File "/tmp/myproj/django/core/wsgi.py", line 12, in get_wsgi_application
  django.setup(set_prefix=False)
  File "/tmp/myproj/django/__init__.py", line 24, in setup
  apps.populate(settings.INSTALLED_APPS)
  File "/tmp/myproj/django/apps/registry.py", line 89, in populate
  app_config = AppConfig.create(entry)
  File "/tmp/myproj/django/apps/config.py", line 90, in create
  module = import_module(entry)
  File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'myapp'
```

**Comment by monkut** [comment]
looking into the django code base, this simply isn't finding my package defined in INSTALLED_APPS when run from lambda.  

... can't think why it cannot properly find my django app (package), may be the app name conflicts with some other existing module name or 3rd party app used?

**Comment by monkut** [comment]
Ok, I think I this issue for my case.

I had a django project layout like this:
```
── README.md
├── lambda-requirements.txt
├── requirements.txt
├── static
├── zappa_settings.json
└── projectname
    ├── appone
    │   ├── __init__.py
    │   ├── admin.py
    │   ├── apps.py
    │   ├── fixtures
    │   ├── migrations
    │   ├── models.py
    │   ├── tests.py
    │   └── views.py
    ├── manage.py
    ├── apptwo
    │   ├── __init__.py
    │   ├── admin.py
    │   ├── apps.py
    │   ├── models.py
    │   ├── templates
    │   ├── tests.py
    │   ├── urls.py
    │   └── views.py
    ├── projectname
    │   ├── __init__.py
    │   ├── db.sqlite3
    │   ├── settings
    │   │   ├── __init__.py
    │   │   ├── base.py
    │   │   ├── dev.py
    │   │   └── local.py
    │   ├── urls.py
    │   └── wsgi.py
    ├── templates
```

So in this layout `zappa_settings.json` was at the top level, and I need to set my `django_settings` like this:

```
{
   "dev": {
        ...
        "django_settings": "projectname.projectname.settings.dev",
        ...
    }
}
```

While this allowed me to seemingly get things working I ran into this `populate()` error when attempting to run, `zappa manage dev migrate` initially.  Digging in further I found that by using `zappa tail` my set application, `appone` defined in `INSTALLED_APPS` was not being found.
(even after renaming my app, thinking that I had some potential naming conflict...)

Finally, moving the `zappa_settings.json` configuration file from the project root directory, `./zappa_settings.json`, to within the initial project directory, `./projectname/zappa_settings.json`, resolved the issue, and I was able to run the initial `zappa manage dev migrate` command successfully!

**Comment by olujedai** [comment]
I had this same issue. @monkut's suggestion resolved this for me.

**Comment by oxbits** [comment]
I was having a similar issue.

I was trying to switch from mysql aurora serverless to postgresql aurora serverless.

Eventually installed `psycopg2-binary` per this issue...

https://github.com/Miserlou/Zappa/issues/800

that worked for me.
