### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by RyPoints** [Miserlou/Zappa#327]
I'm into lambda, python and scalability and this project looks really promising.  I followed the instructions here: https://gun.io/blog/serverless-microservices-with-zappa-and-flask/

The Flask code does work on my local machine.  However, when I curled the API endpoint I saw an error.  Any idea what could be causing it?  Details included.

Ryan

**zappa.py**
```
from flask import Flask
app = Flask(__name__)

@app.route('/')
def index():
    return "Hello, world!", 200

# We only need this for local development.
if __name__ == '__main__':
    app.run()
```

**zappa_settings.json**
```
{
    "dev": {
        "s3_bucket": "mypoints-lambda-bucket",
        "app_function": "zappa.app",
        "aws_region": "us-west-2"
    }
}
```

**Deploy**
```
(env)computer:zappa rypoints$ zappa deploy dev
Packaging project as zip...
Uploading zip (2.6MiB)...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.69M/2.69M [00:01<00:00, 2.32MB/s]
Scheduling..
Scheduled zappa-dev-zappa-keep-warm-handler.keep_warm_callback!
Creating API Gateway routes (this only happens once)..
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1008/1008 [01:38<00:00, 10.61 endpoint/s]
Deploying API Gateway..
Deployment complete!: https://y621rwn7rj.execute-api.us-west-2.amazonaws.com/dev

```
**Error**
```
(env) computer:zappa:zappa rypoints $ curl -l https://y621rwn7rj.execute-api.us-west-2.amazonaws.com/dev
{
    "message": "An uncaught exception happened while servicing this request.", 
    "traceback": [
        "Traceback (most recent call last):\n", 
        "  File \"/var/task/handler.py\", line 386, in handler\n    response = Response.from_app(self.wsgi_app, environ)\n", 
        "  File \"/private/var/folders/2_/pk_q8jwd0kzg8023273xvjb09_t9_x/T/pip-build-5QL0jU/Werkzeug/werkzeug/wrappers.py\", line 865, in from_app\n", 
        "  File \"/private/var/folders/2_/pk_q8jwd0kzg8023273xvjb09_t9_x/T/pip-build-5QL0jU/Werkzeug/werkzeug/test.py\", line 871, in run_wsgi_app\n", 
        "TypeError: 'NoneType' object is not callable\n"
    ]
}
```

**Comment by Miserlou** [comment]
I think this might be because your file is called zappa.py, can you try
renaming and updating settings?

From my phone..

**Comment by RyPoints** [comment]
@Miserlou You were 100% correct about that.

I renamed zappa.py to apptastic.py, renamed the app in zappa_settings.json and `ran zappa update dev`.  It then deployed, created a zappa-dev lambda function (that wasn't there before) and when the endpoint is opened in the browser it now says 'Hello world!' instead of displaying an error.

I'm really excited to be able to take a look at this.  Thanks a lot for your help!

**Comment by Miserlou** [comment]
👍 😃

**Comment by sathishsms** [comment]
Me too facing the same issue. thought the app file name is different
https://94xd533qud.execute-api.us-west-2.amazonaws.com/dev


zappa_settings.json
`{
    "dev": {
        "debug": true,
        "log_level": "DEBUG"
        "s3_bucket": "zappa-satheesh"
        "app_function": "heptagonApp.app", 
    }
}

`(venv) root@osboxes:~/awsIotBackend# ls
heptagonApp.py  venv  zappa_settings.json
`

**Comment by dperconti** [comment]
Having the same issue for the most part with Django. I created a new issue here: https://github.com/Miserlou/Zappa/issues/1066

**Comment by bogdanalov** [comment]
Hi guys. I am experiencing the same issue. My filename is the default one(app.py) but when I deployed it -  I am getting this: 
`"{u'message': u'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.', u'traceback': ['Traceback (most recent call last):\\n', '  File \"/var/task/handler.py\", line 454, in handler\\n    response = Response.from_app(self.wsgi_app, environ)\\n', '  File \"c:\\\\users\\\\bogdan~1\\\\appdata\\\\local\\\\temp\\\\pip-build-zelbvh\\\\Werkzeug\\\\werkzeug\\\\wrappers.py\", line 903, in from_app\\n', '  File \"c:\\\\users\\\\bogdan~1\\\\appdata\\\\local\\\\temp\\\\pip-build-zelbvh\\\\Werkzeug\\\\werkzeug\\\\test.py\", line 884, in run_wsgi_app\\n', \"TypeError: 'NoneType' object is not callable\\n\"]}"`  I tried re-deploying with different virtualenvironments and I am still getting this. Any ideas what is causing this? I deployed several services with no problems in the past. zappa==0.44.3 version

**Comment by raniel90** [comment]
> @Miserlou You were 100% correct about that.
> 
> I renamed zappa.py to apptastic.py, renamed the app in zappa_settings.json and ran `zappa update dev`. It then deployed, created a zappa-dev lambda function (that wasn't there before) and when the endpoint is opened in the browser it now says 'Hello world!' instead of displaying an error.
> 
> I'm really excited to be able to take a look at this. Thanks a lot for your help!

Works for me! Thanks!
