### ISSUE TITLE
How to delete the CloudFront distribution created by certify?

### ISSUE THREAD

**Issue by jayfk** [Miserlou/Zappa#334]
When running `zappa certify prod`, I'm getting the following error:

```
Certifying domain www.greatest-domain.com..
Setting DNS challenge..
Waiting for DNS to propagate..
An error occurred (BadRequestException) when calling the CreateDomainName operation: The domain name you provided is already associated with an existing CloudFront distribution.
Remove the domain name from the existing CloudFront distribution or use a different domain name.
If you own this domain name and are not using it on an existing CloudFront distribution, please contact support.
Failed to generate or install certificate! :(

==============

Need help? Found a bug? Let us know! :D
File bug reports on GitHub here: https://github.com/Miserlou/Zappa
And join our Slack channel here: http://bit.do/zappa
Love!,
 ~ Team Zappa!
```

The AWS CloudFront page in the AWS console is completely empty

![screen shot 2016-09-21 at 17 49 52](https://cloud.githubusercontent.com/assets/2930472/18718561/50479c26-8024-11e6-9109-b99a076c688e.png)

Where to go from here?

**Comment by Miserlou** [comment]
That's interesting, have you done something manually before? I don't think
we use CloudFront for anything in Zappa, it should just be pure Route53.

**Comment by jayfk** [comment]
> That's interesting, have you done something manually before?

No. I've noticed that redirects stopped working and I thought that maybe an `update` is doing the trick. This wasn't helping, so I `undeploy`ed and re`deploy`ed.

> I don't think we use CloudFront for anything in Zappa, it should just be pure Route53.

Isn't CloudFront the glue between Route53 and API Gateway that routes incoming requests?

When I take a look at the raw request headers, there are some CloudFront related:

```
Via: 1.1 8813babdd85ca691e150294142d51c61.cloudfront.net (CloudFront)
X-Amz-Cf-Id: TV6ypPcx4Ku2EasEEqOnhaG0fszz4Qx5bUG9GDe4iCtSw4yy-aBwbg==
X-Cache: Miss from cloudfront
```

**Comment by Miserlou** [comment]
> Isn't CloudFront the glue between Route53 and API Gateway that routes incoming requests?

I don't think so? We just use Route53 DNS for the LE challenge to get the certs, then use that to create the APIG endpoint. No CF required. Check your Route53 console?

**Comment by slacis** [comment]
Go to AWS API-Gateway and check the 'custom domain names' section. That's where you can point an API to a cloudfront URL. It's a bit strange but if you re-deploy you have to find custom domain (which i believe is created by zappa) and then add your re-deployed API into the 'API Mappings' section.

**Comment by jayfk** [comment]
I wasn't able to reproduce the issue, closing it for now.

**Comment by Miserlou** [comment]
I actually just got burned by this myself. Fixed in master.

**Comment by neotheicebird** [comment]
```
Calling certify for environment dev..
Warning! AWS Lambda may not be available in this AWS Region!
Warning! AWS API Gateway may not be available in this AWS Region!
Are you sure you want to certify? [y/n] y
Certifying domain spacetime.education..
Setting DNS challenge..
Waiting for DNS to propagate..
Deleting DNS challenge..
An error occurred (BadRequestException) when calling the CreateDomainName operat
ion: The domain name you provided is already associated with an existing CloudFr
ont distribution.
Remove the domain name from the existing CloudFront distribution or use a differ
ent domain name.
If you own this domain name and are not using it on an existing CloudFront distr
ibution, please contact support.
Failed to generate or install certificate! :(

==============

Need help? Found a bug? Let us know! :D
File bug reports on GitHub here: https://github.com/Miserlou/Zappa
And join our Slack channel here: https://slack.zappa.io
Love!,
 ~ Team Zappa!
```

This happens when I try `zappa certify` again. The first time it went well.

**Comment by netflash** [comment]
Same story here

```
Calling certify for environment dev_api..
Are you sure you want to certify? [y/n] y
Certifying domain MYDOMAIN
Setting DNS challenge..
Waiting for DNS to propagate..
Deleting DNS challenge..
An error occurred (BadRequestException) when calling the CreateDomainName operation: The domain name you provided is already associated with an existing CloudFront distribution.
Remove the domain name from the existing CloudFront distribution or use a different domain name.
If you own this domain name and are not using it on an existing CloudFront distribution, please contact support.
Failed to generate or install certificate! :(
```

what also could be helpful - when I first time run the `certify` it didn't create a route53 name record

```
zappa -v
0.41.0
```

**Comment by netflash** [comment]
Actually that CNAME record is a key point here. After I created that record and re-run certify again I got OK from zappa

```
Calling certify for environment dev_api..
Warning! If you have already certified this domain and are calling certify again, you may incur downtime.
You can avoid this downtime by calling certify with --manual and rotating your certificate yourself through the AWS console.
Are you sure you want to certify? [y/n] y
Certifying domain MYDOMAIN
Setting DNS challenge..
Waiting for DNS to propagate..
Deleting DNS challenge..
Updating domain name!
Certificate updated!
```
