### ISSUE TITLE
zappa manage env createsuperuser fails with TTY message

### ISSUE THREAD

**Issue by Antman261** [Miserlou/Zappa#335]
I'm building a brand new project using zappa+django, and so far after setting up VPC + DB, migrating, and now trying to create a new superuser on this fresh database, I can't successfully run `createsuperuser` via `zappa manage`. Full error message follows:

```
$ zappa manage dev 'createsuperuser --username anthony --email [redacted]'
START RequestId: ea487bc2-8095-11e6-b6c0-7b14e4bc6362 Version: $LATEST
Zappa Event: {u'manage': u'createsuperuser --username anthony --email [redacted]'}
Superuser creation skipped due to not running in a TTY. You can run `manage.py createsuperuser` in your project to create one manually.
create_superuser() takes exactly 4 arguments (3 given): TypeError
Traceback (most recent call last):
  File "/var/task/handler.py", line 460, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 208, in lambda_handler
    raise ex
TypeError: create_superuser() takes exactly 4 arguments (3 given)
```

Am I missing something?

I realise other people probably run these problematic commands from other servers or locally. However I feel like this command is particularly important and should be possible? I don't particularly want to wrestle with connecting my local env to a remote db behind a VPC or firing up an EC2 instance and SSHing in every time I need to run these commands.

**Comment by Miserlou** [comment]
This is almost certainly a bug in Zappa, I think it's just not passing the arguments and only taking the first. I just didn't test thoroughly enough, only using the 'status' command, not commands that took arguments.

You MIGHT be able to do `zappa manage "createsureuser bob"` in the meantime, but if not then I'll push a fix later today and update this ticket.

**Comment by Miserlou** [comment]
Yeah, this is certainly the bug:

```python
self.invoke(command_env[-1], "manage")
```

**Comment by Miserlou** [comment]
Okay, this is fixed in 0.25.0! The "" trick will actually work for old versions, but you don't need it on 0.25.0.

Unfortunately, createsuperuser is actually an interactive command, so it won't work anyway. Fortunately, I've added in a new feature: `invoke --raw`, which will allow you execute arbitrary python on the remote deployment. A snippet for using this to create Django super users is linked to in the README now.

Thanks for reporting!

**Comment by Miserlou** [comment]
I should have read your report properly from the beginning, you were already using quotes before I knew that was possible.

**Comment by Antman261** [comment]
I came up with a workaround too:


**zappa_helpers.py**
```
from django.contrib.auth.models import User


def create_superuser():
    User.objects.create_superuser('anthony', 'anthony@example.com', 'password')
```

`zappa invoke env zappa_helpers.create_superuser`
