### ISSUE TITLE
Django: Running the first migration

### ISSUE THREAD

**Issue by subodh-malgonde** [Miserlou/Zappa#336]
I just deployed my Django code to zappa. I have created a RDS instance and provided the database url in `environment_variables`. Now I am trying to create the tables by running `zappa manage dev migrate`. The operation times out after 30 secs and the tables have not been created.

**Comment by subodh-malgonde** [comment]
I decided to execute like migrate, createsuper user etc by remotely connecting to my database and running `python manage.py <command>` in the command line. Connection to the remote database is done using [dj-database-url](https://github.com/kennethreitz/dj-database-url).

**Comment by delhiverymanuj** [comment]
Facing probem in running initial migration command. 
Zappa Event: {u'command': u'migrate'}
need more than 1 value to unpack: ValueError
Traceback (most recent call last):
  File "/var/task/handler.py", line 476, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 208, in lambda_handler
    raise ex
ValueError: need more than 1 value to unpack
