### ISSUE TITLE
Escaping single quotations.

### ISSUE THREAD

**Issue by RyPoints** [Miserlou/Zappa#352]
Having so much fun building awesome things with this!

I saw this issue recently though.  I have a query string with a single quote:

`amazonaws.com/dev?q=youtube+cody%27s+lab`

Lambda returns:

`{"message": "Could not parse request body into json: Unrecognized character escape \'\'\' (code 39)\n at [Source: [B@7984599b; line: 26, column: 29]"}`

I think it is a zappa issue because if I run the same code locally in Flask using:

`127.0.0.1:5000/?q=youtube+cody%27s+lab`

Then it outputs the expected results.

**Comment by Miserlou** [comment]
Excellent bug.

**Comment by Miserlou** [comment]
Fixed in master, I think has been fixed since 27.
