### ISSUE TITLE
Domain with Free SSL Setup

### ISSUE THREAD

**Issue by RyPoints** [Miserlou/Zappa#358]
Followed the instructions here:

https://github.com/Miserlou/Zappa/blob/master/docs/domain_with_free_ssl_dns.md

$ zappa certify
Certifying domain domainname.com..
Setting DNS challenge..
Waiting for DNS to propagate..
Certificate updated!

I then waited two hours.  However, when I attempted to go to the domain in the web browser I get a can't find the server error.

If I go here and put in domainname.com it does find the nameservers.

https://www.whatsmydns.net/#NS/

Are there any additional configuration steps?

**Comment by Miserlou** [comment]
Can you post your zappa_settings, please?

**Comment by RyPoints** [comment]
zappa_settings.json
```
{
    "dev": {
        "s3_bucket": "bucketseat",
        "app_function": "zeekyr.app",
        "aws_region": "us-west-2",
        "domain": "zeekyr.com", // Your target domain
       	"lets_encrypt_key": "account.key", // Path to account key
    }
}
```

**Comment by Miserlou** [comment]
Hm. Is the domain on Route53? Do you see anything on your Route53 console page?

**Comment by RyPoints** [comment]
Yes.

<img width="950" alt="route53" src="https://cloud.githubusercontent.com/assets/10441971/18818636/85d9c3e8-8333-11e6-92dd-2a440ce9b3d8.png">

**Comment by Miserlou** [comment]
Hm, the ACME challenge stuff is there, so it looks like it's done
something, so I don't know why it hasn't propagated yet.

**Comment by RyPoints** [comment]
It did seem a little buggy setting it up.  I followed the tutorial, but at first my name servers hadn't become visible to the outside world.  Then once they were I went in the account and there were who sets of hosted zones for the same domain and every time I did the certify it would attempt to do the ACME thing on the second hosted zone, even though the first hosted zone was the one that propagated to the outside world.  It looks like for some reason zappa created the second hosted zone area.  I created the first following the tutorial.  So then I deleted the second hosted zone area, deleted all ACME info for the first hosted zone and ran it again and it certified, but I haven't been able to access the domain yet.

Should I delete the hosted zone and start over?  I'm not sure where to go from here.

**Comment by RyPoints** [comment]
I deleted the TXT and re-certified.  I'll see if anything changes in 60 minutes.

**Comment by RyPoints** [comment]
Deleting and re-certifying didn't change anything and it actually doesn't let me delete and recreate the NS or SOA record sets.  Delete Record Set does not enable when those options are selected.  

Any ideas?

**Comment by Miserlou** [comment]
Hm. Bummer! 

This is actually a tough one, I'm not really sure what could be going on.

Two theories:
One is that it's because you're not in `us-east-1`. I don't know why that would matter, but that's where I built it on.

The other is that it's because you're on an APEX domain rather than a subdomain. Can you try with `test.yourdomain.tld`?

**Comment by RyPoints** [comment]
So I created search.zeekyr.com to see if everything will work on a subdomain.  Unlike for the apex domain, the subdomain in Route 53's hosted zones didn't pre-propagate the nameservers when I created it, so I pasted the same nameservers as were in the apex domain.  After a couple days I'm still not seeing propagation:

https://www.whatsmydns.net/#NS/search.zeekyr.com

Was pasting the same nameservers as the apex domain used okay to do?

**Comment by Miserlou** [comment]
`certify` is designed so that you don't have to manually copy or paste
anything - it should JustWork^tm. It will automatically _make_ the
subdomain in R53. I don't know what manually copypasting will do to the
process.

**Comment by RyPoints** [comment]
Ah...okay.  I created a separate NS record for search.zeekyr.com and waited for it to propagate like the apex record, but maybe that was the wrong approach.

I deleted the NS record for search.zeekyr.com and then ran `zappa certify`.  It created a new acme-challege TXT for the subdomain and also a CNAME entry for the subdomain and reported success:

```
Certifying domain search.zeekyr.com..
Setting DNS challenge..
Waiting for DNS to propagate..
Created a new domain name. Please note that it can take up to 40 minutes for this domain to be created and propagated through AWS, but it requires no further work on your part.
Certificate updated!
```

I'll see if that functions in an hour.

**Comment by Miserlou** [comment]
https://search.zeekyr.com/ works fine for me now

**Comment by RyPoints** [comment]
Same for me.  Is there a way I can get zeekyr.com and www.zeekyr.com to also function?

**Comment by Miserlou** [comment]
Surely you can just repeat the same process?

**Comment by RyPoints** [comment]
It appeared to work for the www.  I'll wait 20 minutes for it to come up and then see about the apex.

**Comment by RyPoints** [comment]
www is up.  Seeing about the apex.

**Comment by RyPoints** [comment]
Unlike the others, the apex didn't come up.  Maybe I can just do a redirect from https://zeekyr.com to https://www.zeekyr.com.  That would probably be fine.

**Comment by RyPoints** [comment]
To get the apex working, create a type A record set.  Use the apex for the name and for the value put in your cloudfront.net address listed under the CNAME.  I used my www.zeekyr.com entry.  Then run `zappa certify` on the apex and your good to go!

https://zeekyr.com now pulls up the main address.  Thanks for your help!
