### ISSUE TITLE
Allow Scheduled Events to take Arguments

### ISSUE THREAD

**Issue by mcrowson** [Miserlou/Zappa#359]
in the zappa_settings.json, allow scheduled events to take arguments. This would possible include another key to the event dict possibly.

```
{
     "expression": "rate(10 minutes)",
     "function": "path.to.funk",
     "function_kwargs": {"key": "val"}
}
```

**Comment by Miserlou** [comment]
This seems like a handy feature, but is this even possible with scheduled event sources?

**Comment by mcrowson** [comment]
It looks like it would be passed as an input with the target:

https://github.com/Miserlou/Zappa/blob/master/zappa/handler.py#L291 
http://boto3.readthedocs.io/en/latest/reference/services/events.html#CloudWatchEvents.Client.put_targets

But that then overwrites the event info created by cloudwatch and gets rid of things like 'detail-type' which makes the handler not able to deal with the event.

https://github.com/Miserlou/Zappa/blob/master/zappa/handler.py#L291

I'll keep digging, but so far this isn't promising.

**Comment by mcrowson** [comment]
This might be possible now that CW Put-Targets supports InputTransformation: 

https://aws.amazon.com/about-aws/whats-new/2017/03/amazon-cloudwatch-events-now-supports-input-transformation-of-events/

I'll take another look into this if someone doesn't get to it first.
