### ISSUE TITLE
Flask make_response with status 412 is being recieved as status 200 in jQuery

### ISSUE THREAD

**Issue by alliefitter** [Miserlou/Zappa#361]
I'm trying to return an error to an Ajax call with a status 412 when form data fails validation. However the response from the AWS has a status code of 200. The 412 status is in the header, but either the browser or jQuery itself seems to ignore it. Below is my Flask code:

```
        if cls._model.data['errors']:
            return make_response(json.dumps(cls._model.data['errors']), 412)
```
jQuery code:
```
    jq.ajax({
            url: [ '/dev/setMACs?id=', getOrderID() ].join(""),
            data: { macs: macs },
            type: 'POST'
        }).done(function(data, status) {
            setSuccess();
            ShopifyApp.redirect([ '/orders/', getOrderID() ].join(""));
        }).fail(function(jqXHR, status, error) {
            var error_string = jqXHR.responseText,
                errors;
            try {
                errors = JSON.parse(error_string);
            } catch (e) {
                return setErrors([{error: "An internal error has occurred. Be a peach and tell Allie."}]);
            }
            return setErrors(errors);
        });
```
Response:
![screenshot from 2016-09-26 16-51-12](https://cloud.githubusercontent.com/assets/13684558/18853183/7ff7bef4-8409-11e6-8a05-773b5cd9383c.png)

```
Connection: keep-alive
Content-Length: 615
Content-Type: text/html; charset=utf-8
Date: Mon, 26 Sep 2016 21:21:36 GMT
Location: 
Set-Cookie: zappa=c9j3qbyX7zUqxS8wyDaHUu6hLy6XSpzdYHtgeg7XRYwPsP4yxGYZ5MsFzHqpMgj2A6w9ZQ1aXZTVJ5anYagNXzHqc3UcHb6hT29Fph9dPV2waY185j9AMgwJymt1SnQr2ZiswTDfThUS3WoHVXAdsNH82ZYQyoxH4STYwkP5B9Y7BUEzSaMJAeGuAD81npKDSvGfyHyfZHUFyTYzfND832usMRa2bHRXsQZr3fempPowfQq2iuPzhUuU581Kp5wMUkWbwud4Cd5WkUNgqR35jtp8etgc; Path=/
Via: 1.1 dddbce278f81f85c0d8ad70ec0b24e44.cloudfront.net (CloudFront)
X-Amz-Cf-Id: yl9z09DEjID_9eFYRrP4MosO4nIeZuvqPJX0Lx435xM9iomierxBDw==
X-Cache: Miss from cloudfront
status: 412
x-amzn-RequestId: 34dae97d-842f-11e6-a7ef-3fde74051edb
```

**Comment by Miserlou** [comment]
Related: https://github.com/Miserlou/Zappa/issues/303

I think this is now possible to fix, assuming you don't need the set-cookie header and the response type isn't text/html.

**Comment by alliefitter** [comment]
Thanks for the quick response. The response is JSON. The data is passed over just fine. I'm just unable to get the `fail` method to execute. Obviously, I can easily implement a workaround(and will have to for the time being.) to catch this in the `success` method, but that's hacky. Regardless, thanks for the hard work. Otherwise I haven't had any real issues. Very impressive bit of software.

**Comment by Miserlou** [comment]
Thanks!

Yeah, I'd say just look for the header explicitly in the mean-time. This will hopefully be fixed in the not-too-distant future now that we know it's at least possible, but it means finding a free day to really chase it down.

**Comment by Miserlou** [comment]
Fixed! More info here: Fixed! More info here: https://blog.zappa.io/posts/unhacking-zappa-with-new-apigateway-features
