### ISSUE TITLE
Make use of new Proxy and ANY for API Gateway

### ISSUE THREAD

**Issue by gricey432** [Miserlou/Zappa#363]
API Gateway as introduced a greedy proxy and ANY features, which are perfect for Zappa, replacing all the API Gateway Resource and Method generation as well as allowing for unlimited `/` in urls without config.
https://aws.amazon.com/blogs/compute/easier-integration-with-aws-lambda-and-amazon-api-gateway/
Zappa should switch to using this new approach.

**Comment by Miserlou** [comment]
Yap, we're looking it. Discussion here: https://github.com/Miserlou/Zappa/issues/303 - PRs welcome

**Comment by randuhmm** [comment]
I just noticed this today! Looks like the days of "hackish" configurations are over.

**Comment by Miserlou** [comment]
Fixed! More info here: https://blog.zappa.io/posts/unhacking-zappa-with-new-apigateway-features
