### ISSUE TITLE
Local testing?

### ISSUE THREAD

**Issue by pjz** [Miserlou/Zappa#364]
Is there any way to test a "Zappa app" locally?  Presume I'm on an airplane without wifi and would like to test my deployment locally - is this possible?

**Comment by Miserlou** [comment]
Just run it like it were any other app, for the most part. You could try using a WSGI server like Unicorn with Zappa's Middleware installed in it? But for local testing, you can normally just use the Flask/Django/Whatever debug server you normally would.

What specifically are you asking about? It's a valid question but I'm not sure how to answer.

**Comment by pjz** [comment]
Oh! Alright then! Clearly I need to RTFM a bit more often :)

**Comment by mojimi** [comment]
I still believe it's a valid question for packages support and such, but it's mostly a documentation example.

The way I see it you would setup a machine using Amazon Linux distro, use zappa package to build everything into a docker and test from there, but some tested documentation on how to do this would be great
