### ISSUE TITLE
zappa_settings Request.

### ISSUE THREAD

**Issue by mguidone** [Miserlou/Zappa#367]
I would be really nice if there were a way to specify the lambda function name in the settings, instead of taking the directory name and appending the release tag.

{
    "lambda_function_name": "my-function-name"
}

**Comment by Miserlou** [comment]
You can specify `project_name` in the settings, but I thinkkkk it'll still append the stage.

**Comment by mguidone** [comment]
Sorry I missed that.   Perfect.
