### ISSUE TITLE
Can't get basic example to work, works fine locally with Flask.

### ISSUE THREAD

**Issue by campbellmcneill** [Miserlou/Zappa#376]
Hey,

Trying to get this most simple service up and running. The code is as follows:

```
from flask import Flask
app = Flask(__name__)

@app.route('/')
def index():
    return "{ message: 'Hello, world!' }", 200

# We only need this for local development.
if __name__ == '__main__':
    app.run()
```

This returns the following error:

```
{
    "message": "An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.", 
    "traceback": [
        "Traceback (most recent call last):\n", 
        "  File \"/var/task/handler.py\", line 394, in handler\n    response = Response.from_app(self.wsgi_app, environ)\n", 
        "  File \"/private/var/folders/s_/4zq_rfdj2h9_ttyx4z4g_k7c0000gp/T/pip-build-UZ2eCY/Werkzeug/werkzeug/wrappers.py\", line 865, in from_app\n", 
        "  File \"/private/var/folders/s_/4zq_rfdj2h9_ttyx4z4g_k7c0000gp/T/pip-build-UZ2eCY/Werkzeug/werkzeug/wrappers.py\", line 57, in _run_wsgi_app\n", 
        "  File \"/private/var/folders/s_/4zq_rfdj2h9_ttyx4z4g_k7c0000gp/T/pip-build-UZ2eCY/Werkzeug/werkzeug/test.py\", line 871, in run_wsgi_app\n", 
        "TypeError: 'NoneType' object is not callable\n"
    ]
}
```

Works fine locally with flask. Anyone got any ideas? Tried the same thing on a PC and a Mac from fresh, same result.

Thanks.

(edited to add code blocks)

**Comment by collingreen** [comment]
Can you post your zappa_settings.json?

**Comment by campbellmcneill** [comment]
Here they are:

{
    "dev": {
        "app_function": "data_service.py", 
        "s3_bucket": "campbellm-mhdata",
	"aws_region": "us-east-1"
    }
}

**Comment by Miserlou** [comment]
Your app function isnt a function

From my phone..

**Comment by campbellmcneill** [comment]
Sorry must be missing something. Doesn't seem different from the example which doesn't work for me either:

https://github.com/Miserlou/Zappa/blob/master/example/app.py

Had it working in other contexts previously...

**Comment by Miserlou** [comment]
Yeah, you have `"app_function": "data_service.py", `, you need `"app_function": "data_service.app",`

**Comment by campbellmcneill** [comment]
Thank you! That worked, so simple!

**Comment by Miserlou** [comment]
👍
