### ISSUE TITLE
How to deploy a Django app with the django rest framework

### ISSUE THREAD

**Issue by maralad** [Miserlou/Zappa#380]
I get this error when trying to deploy a Django rest framework api.
What do I need to do with Cloud Formation or is it possible to use Zappa to deploy a Django rest framework?

`..Stack creation failed. Please check your CloudFormation console. You may also need to `undeploy``

**Comment by Miserlou** [comment]
Is this with `master` or 0.26.0? Are there errors in your CloudFormation logs?
