### ISSUE TITLE
Provided role cannot be assumed by principal 'events.amazonaws.com'.

### ISSUE THREAD

**Issue by cho-is** [Miserlou/Zappa#381]
I am getting:

```
ClientError: An error occurred (ValidationException) when calling the PutRule operation: Provided role 'arn:aws:iam::00000000000:role/theRole' cannot be assumed by principal 'events.amazonaws.com'.
```

Role policy is:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iam:GetRole",
                "iam:PutRolePolicy"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "iam:PassRole"
            ],
            "Resource": [
                "arn:aws:iam::00000000000:role/theRole"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "apigateway:DELETE",
                "apigateway:GET",
                "apigateway:PATCH",
                "apigateway:POST",
                "apigateway:PUT",
                "events:PutRule",
                "events:PutTargets",
                "events:ListRules",
                "lambda:AddPermission",
                "lambda:CreateFunction",
                "lambda:DeleteFunction",
                "lambda:GetFunction",
                "lambda:ListVersionsByFunction",
                "lambda:UpdateFunctionCode",
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:PutObject",
                "s3:CreateMultipartUpload",
                "s3:AbortMultipartUpload",
                "s3:ListMultipartUploadParts",
                "s3:ListBucketMultipartUploads"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```

Any  help would be much appreciated!

**Comment by Miserlou** [comment]
PutRole and PutRolePolicy may be different?

**Comment by gottk** [comment]
Not sure if this will help but what I do in case of Roles and policies:

First, you need a file for assumePolicy.json
Which looks like that:
{
  "Version" : "2012-10-17",
  "Statement": [{
    "Effect": "Allow",
    "Principal": {
      "Service": [
        "apigateway.amazonaws.com",
        "lambda.amazonaws.com",
        "events.amazonaws.com",
        "s3.amazonaws.com"
      ]
    },
    "Action": [ "sts:AssumeRole" ]
   }]
}


Here it's significant to provide all of the services you want to be accessible for your policy/ role
In your case, it should be the same as I have.

you create your role with this:
aws iam create-role --role-name $roleName --assume-role-policy-document $assumePolicyPath

Furthermore, you have a Policy.json for your project which looks like the following:

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": "arn:aws:s3:::*"
        }
    ]
}

Now you are able to create the policy:

aws iam create-policy --policy-name $policyName --policy-document $policyPath


And as, last step you are able to attach the role to the policy:
aws iam attach-role-policy --role-name $roleName --policy-arn $policyArn

I hope this was helpful

**Comment by smoll** [comment]
@cho-is The reason you are getting this error is "events.amazonaws.com" is not listed as a Trusted Entity for role `theRole`.

One way to fix this is by going to https://console.aws.amazon.com/iam/home?region=us-east-1#roles/theRole (obviously, adapt this link to your region + real role name) > Trust Relationships tab > Edit Trust Relationships button > paste in

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": [
          "lambda.amazonaws.com",
          "apigateway.amazonaws.com",
          "events.amazonaws.com"
        ]
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

this error should go away. For the record, I got the above document by allowing Zappa to `manage_roles: true` (and then disabling it, after it set up what it needed).

**Comment by cho-is** [comment]
@smoll amazing thank you very much that would be the case. I will test this out and see if it is working now.

**Comment by diasjorge** [comment]
I'm getting the same error: For me the fix was to set keep_warm to false.

I checked and events.amazonaws.com is definitely in the trusted relationships for ZappaLambdaExecution Role that is created by zappa.

I tried to check was the missing part for the policy created by default is but couldn't find it.

**Comment by kienpham2000** [comment]
Setting `"keep_warm": false` works for me. I think the default should be false?

**Comment by GregorySaxton** [comment]
Great suggestion @smoll worked for me too. Now on to the other issues!

**Comment by vitodsk** [comment]
Hello, @smoll suggestion didn't work for me, that's how my policy document appears:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": [
          "apigateway.amazonaws.com",
          "lambda.amazonaws.com",
          "events.amazonaws.com"
        ]
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

seems ok, but I am still having the same error....
