### ISSUE TITLE
Make project_name A Required Setting

### ISSUE THREAD

**Issue by mcrowson** [Miserlou/Zappa#383]
The project_name currently defaults to pwd. When have multiple working environments for developers or CI servers this can lead to deployment issues that are not straight forward to troubleshoot. If it stays as an optional setting, maybe update the warning from:

Warning! Couldn't get function - have you deployed yet?

to

Warning! Couldn't get function - It is not deployed or was deployed under a different project_name.

**Comment by Miserlou** [comment]
Did you set the project up using `init`? It could be put in there but I don't think it needs to be a required setting.

**Comment by mcrowson** [comment]
I did not use init, just made the JSON. I think putting it in init, updating that warning, and possibly adding a warning on deploy as well if project_name isn't specified in the settings. I would think most prod-level deployments will come across this scenario at some point so it would be good to communicate the project_name importance.
