### ISSUE TITLE
Cooke Expiration in WSGI Middleware

### ISSUE THREAD

**Issue by Doerge** [Miserlou/Zappa#39]
Goal:
After unpacking cookies in the middleware, discard any that might be expired, before feeding them to the WSGI-app.

Normally the client would do this, but the zappa cookie is encoded so the expiration attributes are not accessible to the client.

Right now we use Werkzeug's cookie parser, but it throws away everything else but the key=value. So exp. date or other stuff is discarded. Use (perhaps) the stdlib for parsing cookies: https://docs.python.org/2/library/cookie.html#Cookie.BaseCookie.load

If anyone begins work on this, please leave a note here.

**Comment by Miserlou** [comment]
Okay, I think this is completed now. Can you take a look and confirm everything is in order?
