### ISSUE TITLE
Unicode problems

### ISSUE THREAD

**Issue by jakekara** [Miserlou/Zappa#397]
Any idea why a django app in Py2.7 that works fine locally would give this error when deployed? I'm not suggesting this is a bug; probably my own stupidity.

'unicode' does not have the buffer interface
Request Method:	POST
Request URL:	[...]
Django Version:	1.10.2
Exception Type:	TypeError
Exception Value:	
'unicode' does not have the buffer interface
Python Executable:	/usr/bin/python2.7
Python Version:	2.7.12
Python Path:	
['/var/task',
 '/var/runtime/awslambda',
 '/var/runtime',
 '/usr/lib/python27.zip',
 '/usr/lib64/python2.7',
 '/usr/lib64/python2.7/plat-linux2',
 '/usr/lib64/python2.7/lib-tk',
 '/usr/lib64/python2.7/lib-old',
 '/usr/lib64/python2.7/lib-dynload',
 '/usr/local/lib64/python2.7/site-packages',
 '/usr/local/lib/python2.7/site-packages',
 '/usr/lib64/python2.7/site-packages',
 '/usr/lib/python2.7/site-packages',
 '/usr/lib64/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/var/task']

**Comment by Miserlou** [comment]
Is that for Zappa 26 or 27? Can you confirm that it happens with both? Somebody else reported this in Slack but I haven't been able to reproduce it yet.

**Comment by jakekara** [comment]
27

**Comment by Miserlou** [comment]
Try downgrading to 26 and redeploying?

**Comment by jakekara** [comment]
OK. will report back.

**Comment by jakekara** [comment]
I'm no longer getting that error, and that probably fixed it. 

I'd like to be able to give a more affirmative response, but I'm on to the next error, which is a timeout connecting to RDS, but I think that's just my own config error at this point.

By the way, thanks for creating zappa. It's awesome and so was Frank.

**Comment by Miserlou** [comment]
Dang, something in 27 borked this then. Can you tell me more about your config so that I can reproduce? Is this a Flask or Django app?

**Comment by jakekara** [comment]
This was my first time using Zappa (and Lambda as well). 

I made a fresh django app, hooked it up to s3 for static files, and RDS for the database, ran collectsatic, made a super user, and then deployed. locally, it worked fine. When I deployed it, the admin login page was served properly, but then when I submitted the login form, that's when I got the error. 

Here's a pip freeze of my environment:

base58==0.2.3
boto==2.42.0
boto3==1.4.0
botocore==1.4.56
click==6.6
Django==1.10.2
django-storages==1.5.1
docutils==0.12
futures==3.0.5
hjson==2.0.2
jmespath==0.9.0
kappa==0.6.0
lambda-packages==0.8.0
MySQL-python==1.2.5
placebo==0.8.1
python-dateutil==2.5.3
python-slugify==1.2.1
PyYAML==3.12
requests==2.11.1
s3transfer==0.1.8
six==1.10.0
tqdm==4.8.4
troposphere==1.8.1
Unidecode==0.4.19
Werkzeug==0.11.11
wsgi-request-logger==0.4.5
zappa==0.26.0

**Comment by jondanao** [comment]
I can confirm it works on `0.26.0` but throws an unicode error on `0.27.0`.

**Comment by Miserlou** [comment]
Just pushed a potential fix if anybody wants to try it out..

**Comment by jondanao** [comment]
Tested twice. Works well. Thanks @Miserlou
