### ISSUE TITLE
Allow supplying existing custom certificate in settings

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/Zappa#401]
Let's Encrypt support is already working nicely, but we might as well add the ability to supply a local PEM that has already been created.

**Comment by Miserlou** [comment]
Suggest we add the

`certificate_cert, `certificate_key` and `certificate_chain` fields in the settings unless you can think of better names!

**Comment by Miserlou** [comment]
Related? https://github.com/Miserlou/Zappa/issues/565

**Comment by atif1996** [comment]
Its probably best to keep the actual certificate outside of source control.  Really, once you've installed the custom certs into aws, they should be destroyed.  However, there should be some way to map the custom domain name to the deployed api gateway.  

At the moment, that mapping has to be a manual step.  Would be nice if zappa looked for the existence of custom domain names matching the "domain" field in the settings.  If one is found, it would map that to the newly deployed api gateway.
