### ISSUE TITLE
Error keeping warm

### ISSUE THREAD

**Issue by fermuch** [Miserlou/Zappa#403]
(Pressed enter by error)

```
[1476748267924] Zappa Event: ...zappa-keep-warm-handl.keep_warm_callback...
[1476748267924] No module named handl: ImportError
Traceback (most recent call last):
  File "/var/task/handler.py", line 476, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 208, in lambda_handler
    raise ex
ImportError: No module named handl
```

Zappa version: 0.27.1

**Comment by Miserlou** [comment]
Whats the error

From my phone..

**Comment by fermuch** [comment]
I pressed enter instead of tab so I created the issue without a description. Sorry. I edited the content already.

**Comment by Miserlou** [comment]
What's your Zappa version?

Is your project_name/`pwd` quite long?

**Comment by fermuch** [comment]
*Zappa version:* 0.27.1

My project name is quite large, yeah. It's 26 characters. Is that a problem? What's the limit?

**Comment by Miserlou** [comment]
Yeah, it's supposed to truncate at it, but it looks like it's doing it
wrong. Try setting `project_name` to something smaller?

**Comment by fermuch** [comment]
Changed the project name to 15 characters long. Before this problem it was 17 characters long.
Ran `zappa update` and still having the same error.
Do I need to redeploy?
