### ISSUE TITLE
Using flaks abort function - return status code empty

### ISSUE THREAD

**Issue by gottk** [Miserlou/Zappa#412]
Hy,

I have currently a GET function, which looks like the following:

@app.route('/requestMarkup', methods=['GET'])
def request_markup():

    req_markup = {'Work' : []}
    sqs = boto3.resource('sqs')

    queue = sqs.get_queue_by_name(QueueName='ZappaReadyQueue')
    messages = []
    messages = queue.receive_messages(MaxNumberOfMessages=1, WaitTimeSeconds=5)

    if len(messages) == 0:
       app.logger.info("Zero Messages on the Queue")
       abort(404)
    else:
       for message in messages:
          app.logger.info(message)
          body = json.loads(message.body)
          message.delete()
          req_markup = body
       return json.dumps(req_markup)

As you can see I use abort(404), cause I would like to return a 404 code if my queue is empty.

My zappa settings file looks like the following:

{
    "@@stage@@": {
        "app_function": "my_app.app",
        "s3_bucket": "@@S3Bucket@@",
        "aws_region":"@@awsRegion@@",
        "assume_policy": "@@assume_policy@@",
        "attach_policy": "@@assume_policy@@",

        "integration_response_codes": [200, 404],
        "keep_warm": false,
        "events":[{
            "function": "my_app.work_queue_manager_@@stackName@@",
            "expression": "rate(1 minute)"
        }],

        "log_level": "INFO",
        "http_methods": ["GET", "POST", "OPTIONS"],
        "method_response_codes": [200, 404],
        "debug" : true,
        "manage_roles": false,
        "role_name": "@@role_name@@"
    }
}

If I run FLASK locally, I get my 404 as status:
Request: curl -H 'Content-Type: application/json' -v http://127.0.0.1:5000/requestMarkup

*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 5000 (#0)
> GET /requestMarkup HTTP/1.1
> Host: 127.0.0.1:5000
> User-Agent: curl/7.45.0
> Accept: */*
> Content-Type: application/json
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 404 NOT FOUND
< Content-Type: text/html
< Content-Length: 233
< Server: Werkzeug/0.11.11 Python/2.7.10
< Date: Wed, 19 Oct 2016 01:18:07 GMT
< 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
* Closing connection 0

if I run it now with my zappa application:

curl -H 'Content-Type: av https://....execute-api.ap-southeast-2.amazonaws.com/dev/requestMarkup
* Rebuilt URL to: v/
* getaddrinfo(3) failed for v:80
* Couldn't resolve host 'v'
* Closing connection 0
curl: (6) Couldn't resolve host 'v'
*   Trying 52.84.207.22...
* Connected to .....execute-api.ap-southeast-2.amazonaws.com (52.84.207.22) port 443 (#1)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
* 	 subject: C=US; ST=Washington; L=Seattle; O=Amazon.com, Inc.; CN=*.execute-api.ap-southeast-2.amazonaws.com
* 	 start date: Jun  3 00:00:00 2016 GMT
* 	 expire date: Jun  4 23:59:59 2017 GMT
* 	 subjectAltName: rwbbrdgf7f.execute-api.ap-southeast-2.amazonaws.com matched
* 	 issuer: C=US; O=Symantec Corporation; OU=Symantec Trust Network; CN=Symantec Class 3 Secure Server CA - G4
* 	 SSL certificate verify ok.
> GET /dev/requestMarkup HTTP/1.1
> Host: ......execute-api.ap-southeast-2.amazonaws.com
> User-Agent: curl/7.45.0
> Accept: */*
> Content-Type: application/json
> 
< HTTP/1.1 200 OK
< Content-Length: 0
< Connection: keep-alive
< Date: Wed, 19 Oct 2016 01:19:54 GMT
< Access-Control-Allow-Origin: *
< Location: 
< Set-Cookie: 
< Status: 
< x-amzn-RequestId: 214571be-959a-11e6-baab-c3a6f1dae07d
< X-Frame-Options: 
< X-Cache: Miss from cloudfront
< Via: 1.1 49d473f12cd3746d92748f257e16ca9e.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: MjbAOp48sACN_8NoajGXukY2IPXNQMEpUbEHfST1Xvu87R7lf12F1w==
< 
* Connection #1 to host ......execute-api.ap-southeast-2.amazonaws.com left intact

Any help would be appreciated

**Comment by Miserlou** [comment]
?

**Comment by gottk** [comment]
Hey, I found the solution for it, thats why i closed the issue

Date: Tue, 18 Oct 2016 19:41:59 -0700

**Comment by Miserlou** [comment]
What was the solution? For others.

**Comment by gottk** [comment]
As I needed a way to enable CORS automatically I currently wrote my own swagger file up - I only had an implementation for 200 errors and no others. I updated the Swagger and now it works perfectly fine.
