### ISSUE TITLE
Temporary files aren't cleaned up after deployment

### ISSUE THREAD

**Issue by sasha42** [Miserlou/Zappa#42]
I've been playing a lot with zappa lately, and consequently it's generated a lot of temporary files. Unfortunately it appears that these temporary files aren't cleaned up. In my case they were in `/var/folders/4s/xxxxxxxx/T`, and took up several gb of space. Here is what it looks like in a disk analyser:
![screen shot 2016-03-12 at 14 52 53](https://cloud.githubusercontent.com/assets/1775702/13724561/d0e15026-e889-11e5-9587-08baa1439ff6.png)

**Comment by Miserlou** [comment]
Good catch - just changed how we do the zip package creation and forgot to clean up. Takk!
