### ISSUE TITLE
Problems with django management commands

### ISSUE THREAD

**Issue by jnlaia** [Miserlou/Zappa#421]
First of all, thanks for Zappa. I haven't been able to use it properly so far (see below), but I'm pretty sure once I get past these initial problems I'll be using it heavily.

I'm probably doing something very silly, as I'm not being able to run the migrations for the default django project with the default app.

```sh
$ zappa manage dev migrate

Zappa Event: {u'raw_command': u'migrate'}
name 'migrate' is not defined: NameError
Traceback (most recent call last):
  File "/var/task/handler.py", line 476, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 208, in lambda_handler
    raise ex
NameError: name 'migrate' is not defined
```

The other manage commands seem to be failing as well
```sh
$ zappa manage dev "shell --version"

Zappa Event: {u'raw_command': u'shell --version'}
name 'shell' is not defined: NameError
Traceback (most recent call last):
  File "/var/task/handler.py", line 476, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 208, in lambda_handler
    raise ex
NameError: name 'shell' is not defined
```

and

```sh
$ zappa manage dev showmigrations admin

Zappa Event: {u'raw_command': u'showmigrations admin'}
invalid syntax (<string>, line 1): SyntaxError
Traceback (most recent call last):
  File "/var/task/handler.py", line 476, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 208, in lambda_handler
    raise ex
  File "<string>", line 1
    showmigrations admin
                       ^
SyntaxError: invalid syntax

```

The django page is up, and I can see the admin login page (the only url that is configured by default).

My virtual environment
```sh
$ cat requirements.txt 
base58==0.2.3
boto3==1.4.1
botocore==1.4.62
click==6.6
Django==1.10.2
docutils==0.12
futures==3.0.5
hjson==2.0.2
jmespath==0.9.0
kappa==0.6.0
lambda-packages==0.10.0
pkg-resources==0.0.0
placebo==0.8.1
python-dateutil==2.5.3
python-slugify==1.2.1
PyYAML==3.12
requests==2.11.1
s3transfer==0.1.9
six==1.10.0
tqdm==4.8.4
troposphere==1.8.2
Unidecode==0.4.19
Werkzeug==0.11.11
wsgi-request-logger==0.4.6
zappa==0.27.1
```

**Comment by jnlaia** [comment]
I was using the version 0.27.1, the one installed via pip. Using the current master b42b719f4359b279fa4c332bca1c0137edcee8d0 I get a different error:

```sh
$ zappa manage dev migrate
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/home/jnlaia/tests/zappa/venv/local/lib/python2.7/site-packages/zappa/cli.py", line 1458, in handle
    sys.exit(cli.handle())
  File "/home/jnlaia/tests/zappa/venv/local/lib/python2.7/site-packages/zappa/cli.py", line 207, in handle
    self.dispatch_command(command, environment)
  File "/home/jnlaia/tests/zappa/venv/local/lib/python2.7/site-packages/zappa/cli.py", line 255, in dispatch_command
    if len(command_env) < 2:
NameError: global name 'command_env' is not defined

==============
```

Commit 823efccdca820644496ebfa601d15e55b4ba0b86 introduced this error. There are many `command_env` around that are not defined, and should be instead `self.vargs['command_env']`.
This will fix the current bug, and will allow one to reproduce the original error.

**Comment by stuross** [comment]
I've found a work around. 
```
        if raw_python == 'manage':
            command = {'manage': function_name}
        elif raw_python:
            command = {'raw_command': function_name}
        else:
            command = {'command': function_name} # This is really a string
```
 I'll try and get a PR up soon

**Comment by jnlaia** [comment]
I've made a workaround as well. The origin of the problem is the one you are mentioning, but if you notice, the function invoke in which that code is sitting takes as an argument a boolean, whereas it is being called with a completely different argument (a string 'manage'). I don't think it is a good practice to have a variable in a function that can be either a string or a boolean, depending on where it was called.

My workaround was basically adding a new argument to this invoke function called command, that would default to None.

In any case, I think some of the come in this file is quite fragile, and it should be made more robust and elegant... and maintainable.

**Comment by stuross** [comment]
@jnlaia for sure a better way to go about it. 

This might be another issue, but I'm having trouble running migrations in general. when i showmigrations there are no migrations shown. It seems to be related to https://code.djangoproject.com/ticket/23406 and how zappa doesn't copy over the source code if a pyc object is found (https://github.com/Miserlou/Zappa/blob/master/zappa/zappa.py#L424)

I've been able to get around this buy just deleting the pyc files and updating. Anybody else have this issue?

**Comment by jnlaia** [comment]
@stuross I was having that same issue, but I didn't think about it too much. Your explanation makes sense. I suggest you open a new ticket.

**Comment by Miserlou** [comment]
@stuross - that's a really great find. Thanks.
