### ISSUE TITLE
Variables not defined

### ISSUE THREAD

**Issue by jnlaia** [Miserlou/Zappa#422]
I've first mentioned this problem in https://github.com/Miserlou/Zappa/issues/421, but I guess it is a different topic, so it should have its own issue. 

Using the current master b42b719f4359b279fa4c332bca1c0137edcee8d0 I get the error:

``` sh
$ zappa manage dev migrate
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/home/jnlaia/tests/zappa/venv/local/lib/python2.7/site-packages/zappa/cli.py", line 1458, in handle
    sys.exit(cli.handle())
  File "/home/jnlaia/tests/zappa/venv/local/lib/python2.7/site-packages/zappa/cli.py", line 207, in handle
    self.dispatch_command(command, environment)
  File "/home/jnlaia/tests/zappa/venv/local/lib/python2.7/site-packages/zappa/cli.py", line 255, in dispatch_command
    if len(command_env) < 2:
NameError: global name 'command_env' is not defined

==============
```

There are many `command_env` around line 255 in `zappa/cli.py` that are not defined, and should be replaced by `self.vargs['command_env']`.

The current version in pip 0.27.1 does not have this problem.

**Comment by Miserlou** [comment]
Yeah, this is just really sloppy coding after a recent refactor, this shouldn't have made it through testing. Will fix ASAP.

**Comment by Miserlou** [comment]
Phew, not my fault.

**Comment by Miserlou** [comment]
Leaving open until this gets better test coverage.
