### ISSUE TITLE
Documentation request: compare/contrast with chalice

### ISSUE THREAD

**Issue by pjz** [Miserlou/Zappa#433]
AWS touts https://github.com/awslabs/chalice as their serverless framework; can someone compare/contrast with Zappa?  Consider that a PHB is going to say "why should we use Zappa instead of Chalice?"

**Comment by Miserlou** [comment]
Yeah, that's been a long time coming, I'd like to stack it up against all of the various frameworks out there. TL;DR - Zappa wins. 😄

**Comment by Miserlou** [comment]
Blogged about here: https://blog.zappa.io/posts/comparison-zappa-verus-chalice
