### ISSUE TITLE
Don't Copy Pyc Files for Django Migrations

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/Zappa#436]
Related to: https://github.com/Miserlou/Zappa/issues/421#issuecomment-256211615

Don't apply the -pyc logic for Django migrations if we want them to actually work. This is an annoying quirk, thank you for @stuross for noticing this. We need a Django-specific maintainer.

**Comment by jackuoll** [comment]
I ran into the same issue and put 
"exclude": [*.pyc"], in the zappa_settings.json
Is there any reason for not excluding globally pyc files?

**Comment by Miserlou** [comment]
Good interim solution, @jackuoll!

We simply prefer compiled python for the file size savings. This also introduces (very occasional) bugs where expired code is chosen, although we try to avoid that whenever possible.

**Comment by jondanao** [comment]
The `"exclude": ["*.pyc"]` is a fantastic workaround. Thanks @jackuoll!
