### ISSUE TITLE
Zappa is not PEP-8 compliant

### ISSUE THREAD

**Issue by clenimar** [Miserlou/Zappa#437]
being PEP-8 compliant improves code readability a lot.
what do you think?
I can tackle this one.

**Comment by Miserlou** [comment]
How do you mean?

I don't approve of PEP-8 zealotry, in fact, in the name of code readability. I _will_ absolutely accept PRs that make code more readable!. However, PEP-8 compliance is not a design goal of Zappa.

Closing this issue accordingly, but please do feel free to improve the code readability if you can.

**Comment by clenimar** [comment]
well, at least wrapping the code to a line length that avoids the need of horizontal scroll.
what do you think?

**Comment by Miserlou** [comment]
That is generally okay, yes.
