### ISSUE TITLE
Split Up the Readme

### ISSUE THREAD

**Issue by mcrowson** [Miserlou/Zappa#438]
As zappa's documentation has gotten really big, the readme has grown with it. I suggest having a high level overview with links in the readme, and a link to the complete documentation a-la readthedocs or something similar.

**Comment by Miserlou** [comment]
Why?

**Comment by mcrowson** [comment]
Same reason you break any application up as it gets bigger: easier to maintain, consume, and grow.

**Comment by collingreen** [comment]
Micro Readmes! The real future of development!

**Comment by jnlaia** [comment]
I think there is one important advantage of having one big readme file: one can search for a string in the entire document and go to the relevant section easily.

**Comment by mafrosis** [comment]
2 cents: I prefer the single large README

**Comment by Miserlou** [comment]
Yep, me too. "Just because" isn't a good enough reason for me. Closing to prevent any further bikeshedding. 

This, however, still needs to be resolved: https://github.com/Miserlou/Zappa/issues/243
