### ISSUE TITLE
Problems certifying naked domain

### ISSUE THREAD

**Issue by kwellman** [Miserlou/Zappa#443]
Certifying has worked well for me with a subdomain, but can't get it to work when certifying a naked domain.
 
    $ zappa certify production                                           
    Calling certify for environment production..                                                                             
    Certifying domain mydomain.com..                                                                               
    Setting DNS challenge..                                                                                            
    Waiting for DNS to propagate..                                                                                     
    Deleting DNS challenge..                                                                                           
    An error occurred (InvalidChangeBatch) when calling the ChangeResourceRecordSets operation:         
    RRSet of type CNAME with DNS name mydomain.com. is not permitted at apex in zone 
    mydomain.com.                                    
    Failed to generate or install certificate! :(   

If I understand correctly, it seems like an A record is required instead of a CNAME when setting the apex domain (http://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-custom-domains.html).

**Comment by Miserlou** [comment]
Yeah, this is annoying. 

If we can confirm that using A instead of CNAME is possible, then we could update to do the code to use that for apex domains. That'd be the best option here.

Other option is to run your service off of a subdomain like www, then use S3 to route the the apex to the dubdubdub.

**Comment by chromakey** [comment]
The DNS spec says that you can't use CNAME records for domain apexes, only A records.  The pain in the neck is that AWS doesn't give you IP addresses for a lot of things (API Gateway/Lambda being one of them).  Hypothetically, we could look at setting up an ALIAS record (something specific to Route 53) to the Cloudfront distribution which would allow you to do what you're hoping for.

**Comment by Miserlou** [comment]
Hm. I think there's no way to to that via API because you can't get the CF distribution URL except from the console (I think??), but we could have the client block and give manual instructions and a `Continue?` before certifying..

**Comment by chromakey** [comment]
Unfortunately I don't know off the top of my head.  In a perfect world the workflow would be:

1. Set the verification record in Route 53 for Let's Encrypt

2. Update API Gateway with the certificate and custom domain so that the Cloudfront distribution can be created

3. Capture the Cloudfront distribution URL

4. Set an ALIAS record pointing to the Cloudfront distribution for the apex of the domain.

I can take a look at this tonight after work if no one's able to jump on this sooner.

**Comment by Miserlou** [comment]
Sounds great! thanks @chromakey !

**Comment by mikeblum** [comment]
I  was able to do this workflow by writing a plugin:

[Let's Encrypt an API Gateway](https://github.com/mikeblum/acme-api-gateway)

A few caveats to this approach:

1. the domain must be administered through Route 53
2. haven't implemented auto-renew yet

**Comment by chromakey** [comment]
It looks like it's hypothetically possible to do this.  

API Gateway returns the distributionDomainName value when create_domain_name() is run:

http://boto3.readthedocs.io/en/latest/reference/services/apigateway.html#APIGateway.Client.create_domain_name

We're able to create ALIAS records with change_resource_record_sets():

http://boto3.readthedocs.io/en/latest/reference/services/route53.html#Route53.Client.change_resource_record_sets

I'll try to work on this when I can, but I can't promise when that will be.  I forked the project and got the test suite passing on my local, so it's a start at least.

**Comment by Miserlou** [comment]
Cool, feel free to hop in the Slack if you need any help!

**Comment by kwellman** [comment]
I created a fork to do this. Works for me.

See pull request: #451 (description below)

Create an "Alias" record to handle apex domains. 

Parameters for record was set by following http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html

- EvaluateTargetHealth must be False when alias target is a cloudfront distribution (says so in the console).
- HostedZoneId should be set to Z2FDTNDATAQYW2 for cloudfront targets (see AWS link above)

**Comment by chromakey** [comment]
Looks great.  Nice work!

**Comment by Miserlou** [comment]
This is merged now, thanks everybody!
