### ISSUE TITLE
get rid of `remote_env_bucket` and let `remote_env_file` understand s3:// URLs

### ISSUE THREAD

**Issue by pjz** [Miserlou/Zappa#456]
It seems strange that `lets_encrypt_key` understands a `s3://` URL but `remote_env_bucket` and `remote_env_file` take up two fields for the same data type. Why not make `remote_env_file` be able to understand a `s3://` URL as well ?  It would simplify configuration a bit.

**Comment by Miserlou** [comment]
Yeah, I like sticking with the s3:// convention

**Comment by collingreen** [comment]
+1 - this also makes it easier to be cross platform in the future

**Comment by Miserlou** [comment]
Fixed by #478
