### ISSUE TITLE
Having two hosted zones (one public and one private) with same name makes certify with let's encrypt (DNS auth) fail

### ISSUE THREAD

**Issue by acharp** [Miserlou/Zappa#459]
When you have two hosted zones (one public and one private) with the same name under the same registered domain, deploying to this domain with let's encrypt certificate using DNS auth doesn't work.

What happens is that the `_acme-challenge.XX.XX` link always end up in the private hosted zone. Therefore let's encrypt can't access it so the validation process fails with error:
`DNS problem: NXDOMAIN looking up TXT for _acme-challenge.XX.XX`

I guess it would be good if Zappa was able to handle this particular case.

Solution seems simple:
In `get_best_match_zone()` in `zappa.py` we just need to check if the matched zone is private or not, then continue until finding a public one and return None (or fail ?) if there isn't any public hosted zone for the domain. 
If the issue is agreed I can work on it.

**Comment by Miserlou** [comment]
That's an excellent find! Thank you!

Sounds like you've got a good test environment for that, do you wan to submit a Pull Request for that fix? Would be happy to accept.

**Comment by acharp** [comment]
Great ! Yes I'll do the modification+tests and submit a PR when done.

**Comment by Miserlou** [comment]
Nice! You are awesome.

**Comment by sridhar562345** [comment]
```py
    def get_best_match_zone(all_zones, domain):
        """Return zone id which name is closer matched with domain name."""

        # Related: https://github.com/Miserlou/Zappa/issues/459
        public_zones = [zone for zone in all_zones['HostedZones'] if not zone['Config']['PrivateZone']]

        zones = {zone['Name'][:-1]: zone['Id'] for zone in public_zones if zone['Name'][:-1] in domain}
        if zones:
            keys = max(zones.keys(), key=lambda a: len(a))  # get longest key -- best match.
            return zones[keys]
        else:
            return None
```

Can someone explain?
Why are we using `zone['Name'][:-1]`, what's the need of excluding the last character?
