### ISSUE TITLE
Not working with other regions??

### ISSUE THREAD

**Issue by 7wonders** [Miserlou/Zappa#46]
No matter what region I set it will always end up in us-east-1. One thing I noticed straight away is that upload_to_s3 is missing locationconstraint on create_bucket:

```
s3.create_bucket(Bucket=bucket_name, CreateBucketConfiguration={
                'LocationConstraint': self.aws_region
            })
```

Will dig around and see what else is required.

**Comment by 7wonders** [comment]
Seems its only the above and setting the correct region on line 185 of zappa.py which I guess can be fixed in the cli deploy with a simple:

```
self.zappa.aws_region = self.zappa_settings[self.api_stage].get('aws_region', 'us-east-1')
```

**Comment by Miserlou** [comment]
Good catch! Thanks for reporting!

**Comment by Miserlou** [comment]
CLI.py is pretty new and needs more real-world lovin', it seems!

Be careful that not all regions support Lambda and Lambda->VPC yet!

**Comment by 7wonders** [comment]
Yeah, I noticed that also the update cli doesnt take into account that the bucket is already created so returns false:

```
An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it.
Couldn't create bucket.
An error occurred (InvalidParameterValueException) when calling the UpdateFunctionCode operation: Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist.
```

Great work BTW. Saves a real ball ache messing around with api gateway!

**Comment by Miserlou** [comment]
Are you updating on a new bucket? 

TBH the 'create_bucket' function is more of an.. easter-egg than anything else, you should probably set the bucket explicitly in your zappa_settings.json. But fixed that part of the code too.

Tx!

**Comment by 7wonders** [comment]
Well, I started with using an existing bucket but then that error was thrown so then I changed to a new bucket which worked fine. Then when I went to update it looks like it tries to create a bucket again as part of the upload_to_s3 method right?
