### ISSUE TITLE
Allow importing local files for callbacks

### ISSUE THREAD

**Issue by TronPaul** [Miserlou/Zappa#468]
If your project is small it doesn't really make sense to install a module to your virtualenv or system modules just for callbacks. For example:

`zappa_settings.json`
```
{
    "dev": {
        "app_function": "myapp.app",
        "callbacks": {
                "post": "myapp.post_callback"
            }
    }
}
```

The above will fail because `importlib` will not search the working directory for modules to import. Given that zappa is only compatible with Python 2.7 I think that `imp` should be used over `importlib` and that on an `ImportError` the current working directory is also searched for modules to load.

**Comment by Miserlou** [comment]
That sounds like a fair idea to me, but we need to find a Python3 compatible solution because Py3 Lambda is on the horizon..

**Comment by TronPaul** [comment]
If Python3 compatibility is a requirement there would need to be 2 codepaths. 1 if `imp` can be imported (2.7), 1 if not (3 with `importlib`). I can take a stab at making a PR.

**Comment by Miserlou** [comment]
Sounds good!

**Comment by Miserlou** [comment]
Poke

**Comment by TronPaul** [comment]
I finally got around to trying to implement this, but I wasn't able to get both single python files and folder packages working at once. I think I need to do more reading on python import conventions. If someone else wants to give this a go, feel free.

**Comment by tsarpaul** [comment]
Hi, I was able to implement the feature and I want to make a pull request.
Would it be OK to override the current way to install a callback since it would be a breaking change?

**Comment by Miserlou** [comment]
What is your proposed change? Is there anyway way to remain backwards-compatible? Feel free to send the PR so I can take a look at what you've got.
