### ISSUE TITLE
bash completion file?

### ISSUE THREAD

**Issue by pjz** [Miserlou/Zappa#470]
Anyone have a bash completion file for zappa?  A nice to have, for sure, but still handy.

**Comment by Miserlou** [comment]
Today I Learned..

I actually use Zappa via aliases ("zu = zappa update", etc..)

**Comment by Miserlou** [comment]
Reopening this.

This PR introduced a ton of new bugs and I shouldn't have accepted it. Undoing this all manually and not accepting any changes without 100% test coverage.

**Comment by pjz** [comment]
Marked fixed in zappa/Zappa#62
