### ISSUE TITLE
Unable to use subfolders in S3 for storing access key for Let's Encrypt

### ISSUE THREAD

**Issue by khaliullov** [Miserlou/Zappa#477]
Hello, I've tried to store access.key of Let's Enctypt in S3 bucket's subfolder, but got 404 error, because S3 URL was incorrectly parsed. Instead of using of /full/path used just first node because they splitted by slash ('/')

**Comment by Miserlou** [comment]
Good catch, want to submit a PR? 👍

**Comment by Miserlou** [comment]
Woah, you submitted one before I even finished typing my comment! 💯

**Comment by Miserlou** [comment]
Since we're actually going to be re-using this code for #456, would you mind refactoring this into a utility function and adding a test for different key paths? Thanks!

**Comment by khaliullov** [comment]
@Miserlou OK, I'll try.

**Comment by khaliullov** [comment]
@Miserlou added `parse_s3_url` function
