### ISSUE TITLE
Dynamic routes not working?

### ISSUE THREAD

**Issue by laolsson** [Miserlou/Zappa#48]
First off, thanks for an amazing project! I've just started trying it out and I've run in to a problem.

This programming works locally:
`import flask

app = flask.Flask(__name__)

@app.route('/client/<id>', methods=['GET'])
def hello(id):
    return 'Hello ' + id

	
if __name__ == '__main__':
	app.run()`

But when I deploy I and try with something like 
`https://107uk4y3sh.execute-api.ap-northeast-1.amazonaws.com/prod4/client/VVV`

I get {"message":  "Missing Authentication Token"} 

Is there anything I need to do in zappa_settings.json to get this work. Changing the code to just have /client as path works fine.

Thanks

**Comment by Miserlou** [comment]
That code doesn't work locally either. You need to add <id> to the route string.

**Comment by laolsson** [comment]
My bad, pasted the wrong code. This works locally:
```
import flask

app = flask.Flask(__name__)

@app.route('/client/<id>', methods=['GET'])
def hello(id):
    return 'Hello ' + id

	
if __name__ == '__main__':
	app.run()
```

But not when deployed

**Comment by Miserlou** [comment]
Going to sleep now, will check in the morning. Thanks for reporting.

**Comment by Miserlou** [comment]
Works for me.. https://k6ox1w18i7.execute-api.us-east-1.amazonaws.com/dev/client/hello

**Comment by Miserlou** [comment]
Maybe it doesn't work in Asia Pacific region yet? Try US East?

https://oo8j6uj6i1.execute-api.us-east-1.amazonaws.com/dev4/client/VVV

**Comment by collingreen** [comment]
I just had the same issue when creating a brand new lambda (not zappa) endpoint with an api gateway in us-west-2 -- could just be slow setup of the api gateway part (it does warn about a potential 15 minute setup time).

**Comment by laolsson** [comment]
zappa works fine, this was a PEBKAC problem: for some reason I had set the 'parameter_depth' parameter to 1

**Comment by Miserlou** [comment]
Ah, okay! (I just did that for the demo demo gif to make it go faster!)
