### ISSUE TITLE
How is this good, and especially better than CGI?

### ISSUE THREAD

**Issue by Kwpolska** [Miserlou/Zappa#49]
> With a traditional HTTP server, the server is online 24/7, processing requests one by one as they come in. If the queue of incoming requests grows too large, some requests will time out. With Zappa, each request is given its own virtual HTTP "server" by Amazon API Gateway. Each request then calls your application from a memory cache in AWS Lambda and returns the response via Python's WSGI interface. After your app returns, the "server" dies.

I thought this was not a good thing? Didn’t we dump CGI precisely because it used one process per request? Why would this be *better*?

**Comment by Miserlou** [comment]
Because AWS handles the horizontal scaling for us automatically - there is never anything that blocks anything else. Updating the docs to emphasize this.

**Comment by Kwpolska** [comment]
Oh, okay. Note that your [demo](https://zappa.gun.io/) is really slow, has a broken SSL cert, and broken links. A slow demo is not very convincing.

**Comment by Miserlou** [comment]
Ah, that's fair enough. It's not a real website yet! And the slowness is from that gigantic database query, not Zappa. Let's see what I can do about that..

**Comment by Kwpolska** [comment]
The DB-less [POSTback view](https://zappa.gun.io/post_echo/) or the other 404-ing links are not hitting the database. 2.11 seconds waiting for a response (time to first byte) is **awful**.

I’ll stay with uwsgi, thank you very much.

**Comment by Miserlou** [comment]
New page, https://zappa.gun.io/

Still needs a cert though. Hopefully AWS Certificate Manager will work with API Gateway soon.

**Comment by bjinwright** [comment]
You should use Cloudfront's whole site delivery strategy. Then you could AWS Certificate Manager.

**Comment by bjinwright** [comment]
Here's an example using the base Django app.https://zappa.cloudxl.com/

**Comment by Miserlou** [comment]
That's an interesting idea, but not something that I have any experience with yet. Do you have any good resources to share?
