### ISSUE TITLE
Error: No module named

### ISSUE THREAD

**Issue by shakna-israel** [Miserlou/Zappa#50]
So, using a Flask hello world...

shaknaisrael.py
```
from flask import Flask
from jinja2 import Environment, FileSystemLoader
import os

app = Flask(__name__)
site_globals = {'site_title':'Shakna Israel'}
THIS_DIR = os.path.dirname(os.path.abspath(__file__))
j2_env = Environment(loader=FileSystemLoader(THIS_DIR), trim_blocks=True)

@app.route("/")
def hello():
    locals = {}
    render_data = site_globals.copy()
    render_data.update(locals)
    return j2_env.get_template('index.html').render(render_data)

if __name__ == "__main__":
    app.run()
```

index.html
```
<html>
<head>
<title>{{ site_title }}</title>
</head>
<body>
Hello World.
</body>
</html>
```

zappa_settings.json
```
{
    "production": {
       "s3_bucket": "shaknaisrael",
       "app_function": "shaknaisrael.app",
       "delete_zip": true,
       "debug": true
    }
}
```

The intial deploy went absolutely fine, worked great. Then I tried to add the template stuff, so I can build a reasonably sized site.

Upon running ```zappa update production```, then it "appears" to upload fine. Except the page is blank. No body in the HTTP request.

But, in the tail logs:
```
1459875734099] No module named shaknaisrael
[1459875734099] local variable 'app_module' referenced before assignment: UnboundLocalError
Traceback (most recent call last):
  File "/var/task/handler.py", line 161, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 55, in lambda_handler
    return cls().handler(event, context)
  File "/var/task/handler.py", line 150, in handler
    debug = bool(getattr(app_module, settings.DEBUG, True))
UnboundLocalError: local variable 'app_module' referenced before assignment
```

Is Zappa failing to upload the shaknaisrael.py file?

**Comment by Miserlou** [comment]
I'm unable to reproduce this error.

Live version here: https://fkd7btfxzg.execute-api.us-east-1.amazonaws.com/production

*shrug*

**Comment by shakna-israel** [comment]
Is there a way to re-deploy the APIs from scratch, perhaps?

https://2e4go8e0ol.execute-api.us-east-1.amazonaws.com/production is the one linked, and as you can see... It fails.

**Comment by Miserlou** [comment]
The error indicates that it's not loading the settings properly. Can you check your zappa_settings file?

You can change the name of the environment and then call deploy again on that name. There isn't a way to un-deploy an environment yet, but that's a good idea.

**Comment by shakna-israel** [comment]
I can't see anything wrong in the zappa_settings.json file.

I tried renaming it and re-deploying, but the same error occurs in ```tail```, and the [live site](https://qckm8fuqsi.execute-api.us-east-1.amazonaws.com/prod) is still empty.

```
{
    "prod": {
       "s3_bucket": "shaknaisrael",
       "app_function": "shaknaisrael.app",
       "delete_zip": true,
       "debug": true
    }
}
```

Now, if in the same folder, I open a python REPL:

```
> import shaknaisrael
> shaknaisrael.app
$ <Flask 'shaknaisrael'>
> shaknaisrael.app.run()
$ * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

The local Flask app hits no errors, and I'm fairly positive that ```shaknaisrael.app``` is a WSGI object, that zappa should read fine.

**Comment by Miserlou** [comment]
Hm. Let me investigate more. Like I said, this is quite confounding because I was able to run this example with no problems.

Did the error happen immediately when you called deploy in the new environment? Or only upon update?

If you'd be so kind, if you could change delete_zip to false and then look in the archive for a file named 'zappa_settings.py' (py, not JSON), and paste the contents here, that would be useful as well!

**Comment by shakna-israel** [comment]
Yep, those kind of errors are terrible, and I'm sorry to be the one experiencing one...

Only upon update... However, since changing the name, upon deploy.

I just re-ran it, after manually deleting all other functions, and renaming the main python file to ```zap_app```, but still not getting anywhere.

The ```zappa_settings.py``` file reads:

```
# Generated by Zappa
APP_MODULE='zap_app'
APP_FUNCTION='app'
DEBUG='True'
```

The error is caused by the missing zap_app.py file... Which isn't missing. It was inside the archive.

In fact, the archive seems [fully intact](https://gist.github.com/shakna-israel/f1a9b62a5303c2e74237d50bc7e27601).

**Comment by Miserlou** [comment]
Hm. This is driving me nuts! :) Sorry that you had to be the one to find the bug, but it really helps to have opportunities to improve the software when unfortunate souls like you find errors like these. 

Can you 'pip freeze' and confirm that your zappa==0.16.0?

Mine still works with update, and the zappa_settings.py file looks the same as your too. Arghhhh..

**Comment by shakna-israel** [comment]
Hell.

I tried re-creating a new virtualenv, and the damn thing works.

So, comparing the two virtualenvs, I'd say that I may have found the culprit: ```awscli```, which installed a newer version of botocore over the old one. (1.4.8 instead of 1.3.30).

**Comment by Miserlou** [comment]
Ah! Interesting!

Okay! Hmmmmmmmmm!

Will be mindful of this for the next release.

Thanks for reporting back, glad you got it sorted.
