### ISSUE TITLE
Suggestions: Prebuild & Exclusions

### ISSUE THREAD

**Issue by shakna-israel** [Miserlou/Zappa#52]
Two little suggestions that I'd love to see in Zappa.

* Pre-build script. Basically allow you to add a python function to zappa_settings.json, which could get run before the deploy/update scripts.
* Folder exclusions. Specify a folder that Zappa *won't* bundle up, so you can keep assets that shouldn't be uploaded in the same directory tree.

**Comment by collingreen** [comment]
Both of these are great suggestions and wouldn't be terrible to implement.

**Comment by Miserlou** [comment]
Thanks for the comment Shakna!

Excludes are already in place, but it looks like it wasn't documented. Fixing that now - but you just add the patterns to exclude in "exclude": ["*.tar.gz", "*.pem"] or whatever. Adding to README now..

Pre build script is a good one, I've wanted that as well. Can you describe your use case for that?

**Comment by Miserlou** [comment]
Okay, there is now support for a "prebuild_script" setting in the latest master.

**Comment by shakna-israel** [comment]
@Miserlou Awesome. (For me, the prebuild was mostly minifying css, precompiling CoffeeScript and the like).

**Comment by Miserlou** [comment]
Ah, that makes total sense.

How are you serving up your static assets? YESTERDAY, API Gateway finally got the feature we need to serve binary data through it, but it's not a great practice and you should really use a CDN or something like that.

**Comment by shakna-israel** [comment]
[Whitenoise](https://github.com/evansd/whitenoise), but I only use it for text assets, like CSS and JS.

**Comment by Miserlou** [comment]
Oh wow, now that's really interesting! I've never seen that before.

Describing how to best handle static files is still an open and pressing matter for Zappa, so I'd love to know more about your setup!

If you don't mind, can you describe your setup in a bit more details? For example, are you using Django or Flask? Have you put Whitenoise on Lambda, or is that running on a dedicated machine somewhere?

**Comment by shakna-israel** [comment]
Sure thing.

I'm using Flask for now, and wrapping it with Whitenoise before hitting it on Lambda.

So, the application that Zappa serves looks like:

```python
import whitenoise
import routing

flaskApp = routing.app
app = whitenoise.WhiteNoise(flaskApp, root='/static')
```

I then have CloudFlare acting as a CDN around the site.

Since the only images I've used thus far are SVGs, and CSS shapes, I don't need to worry about binary formats and being served the wrong way.

That being said, Whitenoise should be enough to do it, if behind a CDN. So long as a user is using a CDN, then how they serve their files should be easy and simple, and fast.

That being said, I'm still getting used to Lambda, and haven't inspected to see if it obeys caching headers properly, or, like S3, completely fails to use gzip or the like.

**Comment by Miserlou** [comment]
That's fantastic, thanks for sharing! I look forward to experimenting with this myself.

WhiteNoise looks like it satisfies a number of requirements that I have, so once I try it out I hope to add it to the official Zappa documentation.

If you'd be so kind, I'd love it if you could see if it is obeying the caching headers like you say it should. If not, then perhaps there is something more that we could do to help with that.
