### ISSUE TITLE
Zappa shouldn't sluggify non-default project names

### ISSUE THREAD

**Issue by horenmar** [Miserlou/Zappa#521]
Configuration option `project_name` defaults to sluggified pwd (which I hope means the current dir, not the entire path, but thats beside the point), but it shouldn't sluggify custom project names.

Alternatively, it should be at least noted in documentation.

**Comment by Miserlou** [comment]
What are you trying to use?

It's just trying to force a valid name but there are probably better ways of doing that than what's available now.

**Comment by horenmar** [comment]
PascalCase.

`ZappaTestArch` in `dev` config is deployed as `zappatestarch-dev` and I would like it to be deployed as `ZappaTestArch-dev`

**Comment by Miserlou** [comment]
Ahhh. You're probably right, it should just let the user shoot themselves in the foot if that's what they want.

**Comment by horenmar** [comment]
Since there is a PR open that would fix this, I'd like to bump the issue.

**Comment by vlcinsky** [comment]
+1. It would make our lambda functions in AWS console a bit better readable, currently zappa managed ones break our naming conventions.

I checked the pull request code and it seems fine to me.

The new version would in fact allow to shoot in direction, the user aimed really (now it hits sometime a bit lower :-)).

If we care about preventing dangerous names, we could extend the test in place, which actually tests only for the length exceeding 16 chars, it could get extra check for other cases. 

AWS Lambda [spec states](http://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#API_CreateFunction_RequestSyntax)

Type: String

Length Constraints: Minimum length of 1. Maximum length of 140.

Pattern: ```(arn:aws:lambda:)?([a-z]{2}-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a-zA-Z0-9-_]+)(:(\$LATEST|[a-zA-Z0-9-_]+))?```

I could make PR for that if it seems reasonable solution.

**Comment by Miserlou** [comment]
+1 to matching the real validation, PR welcome.

**Comment by vlcinsky** [comment]
My proposal for validating lambda function name:

The pattern breaks down to following parts::


    # optional prefix 'arn:aws:lambda:'
    (arn:aws:lambda:)?
    # optional region name, e.g. 'eu-west-1'
    ([a-z]{2}-[a-z]+-\d{1}:)?
    # optional account id, e.g.: '123456789012'
    (\d{12}:)?
    # optional 'function:' string
    (function:)?
    # obligatory: actual name of the Lambda function
    ([a-zA-Z0-9-_]+)
    # optional suffix (alias, version or event source mapping-id)
    (:(\$LATEST|[a-zA-Z0-9-_]+))?


Real (fully qualified) lambda name may look as follows::

    arn:aws:lambda:ap-southeast-2:123456789012:function:actual-function-name:$LATEST

Lambda is supported in following regions:

- us-east-1
- us-east-2
- us-west-1
- us-west-2
- ap-northeast-2
- ap-southeast-1
- ap-southeast-2
- ap-northeast-1
- eu-central-1
- eu-west-1

The longest one is used in above example.

Calculating max lenght of actual-function-name:

- prefix:52 (`arn:....:function:`)
- suffix/alias:8 (`:$LATEST`, integer version or version alias - assuming version aliases used will not be longer than 7 chars)

length remaining from total 140 chars: 140 - (52+8) = 80

Pattern for actual-function-name: `[a-zA-Z0-9-_]+`[a-zA-Z0-9-_]+

The test would do three tests:
- string is not empty `len(name) > 0`
- string match the pattern `[a-zA-Z0-9-_]+`
- string is not longer than 80 chars `len(name) <= 80`
