### ISSUE TITLE
rsplit issue when trying to deploy

### ISSUE THREAD

**Issue by sarlindo** [Miserlou/Zappa#534]
I am just in the process of trying out zappa with a django project, however I can't seem to get past this issue below. 

(sptpokerenv) :~/projects/poker$ zappa deploy production
Packaging project as zip...
'NoneType' object has no attribute 'rsplit'

My zappa_settings.json file looks like this:

{
    "production": {
       "s3_bucket": "sptdb.abc.ca",
       "django_settings": "~/projects/poker/settings.py"
    }
}

**Comment by Miserlou** [comment]
That's a new one! Thanks for reporting. Is there any more information than that?

**Comment by Miserlou** [comment]
Two things:

Does it work if you replace the `~` with the full path?

Does it work if you have a bucket that doesn't have `.` in it?

**Comment by sarlindo** [comment]
I don't have too much more info yet, other than I am just trying to port over to lambda my existing django project following the zappa README instructions, which is basically install zappa, create this json settings file and try to deploy into my AWS account.
 
I tried this file as well, but same issue:
fyi... the aws bucket doesn't actually exist yet, but I would expect to see a different error if that was the issue. 
{
    "production": {
       "s3_bucket": "sptdbt123",
       "django_settings": "/home/arlindo/projects/poker/poker/settings.py"
    }
}

**Comment by Miserlou** [comment]
OS, Python and Zappa versions?

**Comment by sarlindo** [comment]
python 2.7.6
ubuntu 14.04
zappa==0.17.4

**Comment by Miserlou** [comment]
Zappa is now at 0.31.0 - can you update and try again?

**Comment by sarlindo** [comment]
sorry I though I did upgrade zappa, but I guess not. After the upgrade it got past this issue, but ran into another which is expected.

Question: Does zappa try to create the s3 bucket? or does it expect it to be created already?

ClientError: An error occurred (BucketAlreadyExists) when calling the CreateBucket operation: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.

**Comment by Miserlou** [comment]
Zappa expects the bucket to exist, if it doesn't, it tries to make it. Buckets are a global namespace (all users), so some other AWS user is using the one you want.

**Comment by sarlindo** [comment]
cool thanks for you help. my issue with the zappa version was that my "global" environment was at latest zappa version, but my virtualenv was at that older version. Again, thanks for your help.

**Comment by danielwhatmuff** [comment]
I had this same issue and an upgrade of both venv and global install of zappa fixed it.
