### ISSUE TITLE
Dead link in top level readme + missing instructions on running tests

### ISSUE THREAD

**Issue by horenmar** [Miserlou/Zappa#538]
I am trying to make a PR against zappa and when looking for information about how to run tests, etc, I found this in the readme 
"If you are adding a non-trivial amount of new code, please include a functioning test in your PR. For AWS calls, we use the placebo library, which you can learn to use in the test writing guide."

where "in the test writing guide" is a link to nonexistent page `https://github.com/Miserlou/Zappa/blob/master/docs/README.md`.

Also `docs/` subfolder and top level readme seem to be out of sync.

**Comment by Miserlou** [comment]
Good catch!
