### ISSUE TITLE
django & static content - can't seem to get the static content to work

### ISSUE THREAD

**Issue by sarlindo** [Miserlou/Zappa#544]
**python** version - 2.7.12
**Ubuntu:** 16.04
**zappa:** 0.31.0

I am having issue getting the static content to work properly for the django project within aws/lambda/zappa. The site comes up, but static content isn't working such as the "css" file. When I view the source and click on the link to the static content location for the css, I get permission denied. What is controlling the permission?

``` 
<!-- Custom styles for this template -->
<link href="/static/spt.css" rel="stylesheet">

```
## clicking on the "static" link location gives me this:
```
{"message":"Forbidden"} 

```
## My settings.py file contains this:

```
PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))
PROJECT_DIR = os.path.join(PROJECT_ROOT,'../apps/spt')

STATIC_ROOT = os.path.join(PROJECT_ROOT, 'staticfiles/')
STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(PROJECT_DIR, 'static/'),
)

```

**Comment by sarlindo** [comment]
Ok i should of read zappa documentation a little better. Looks like I need to find a different method. 

```
Serving Static Files / Binary Uploads

Zappa is for running your application code, not for serving static web assets. If you plan on serving custom static assets in your web application (CSS/JavaScript/images/etc.,), you'll likely want to use a combination of AWS S3 and AWS CloudFront.

Your web application framework will likely be able to handle this for you automatically. For Flask, there is Flask-S3, and for Django, there is Django-Storages.

Similarly, you will not be able to accept binary multi-part uploads through the API Gateway. Instead, you should design your application so that binary uploads go directly to S3, which then triggers an event response defined in your events setting! That's thinking serverlessly!

```

**Comment by bjinwright** [comment]
@sarlindo 

**Custom Django-Storages Backend**
https://gist.github.com/bjinwright/b51e1c09711238d81c009e9d6732b7e3

**Settings**
https://gist.github.com/bjinwright/c34b7cfece9911774276ca26bf2e73c0#file-settings-py-L148

**Comment by sarlindo** [comment]
@bjinwright thanks. I got it working with the s3 django-storages backend for static content. Now running into another issue with jquery/ajax calls defined as such doesn't make it to the backend, but this will be a different issue I may have to open up after I doing some digging. Maybe it needs the full URL path endpoint that zappa generates? 
```
<script src="https://MY-STATIC-S3-BUCKET/sptstats.js"></script>

$.getJSON('/get_profit', { }, function (callback) {

```

**Comment by bjinwright** [comment]
f@sarlindo It is probably because of the limitation of number of cookies APIGW will pass back to the user and the fact the CSRF Token isn't properly set.

**Comment by sarlindo** [comment]
@bjinwright if I change my ajax request to include the environment name that zappa add as part of the path then it works fine. 

$.getJSON('/production/get_profit', { }, function (callback) {
