### ISSUE TITLE
No such file or directory common-passwords.txt.gz 

### ISSUE THREAD

**Issue by muke5hy** [Miserlou/Zappa#555]
Getting following error while adding user via django admin

IOError: [Errno 2] No such file or directory: u'/var/task/django/contrib/auth/common-passwords.txt.gz'

When I checked for django/contrib/auth/common-passwords.txt.gz in my virtualenv file does not exists there.

**Comment by Miserlou** [comment]
Gzip files are ommited from packages by default to save space. You can change the excludes in your settings to change this.
