### ISSUE TITLE
cannot import name 'Zappa'

### ISSUE THREAD

**Issue by bussiere** [Miserlou/Zappa#562]
> (app) bussiere@kusanagi:~/Workspace/test_zappa$ zappa init
> Traceback (most recent call last):
>   File "/home/bussiere/Workspace/test_zappa/app/bin/zappa", line 7, in <module>
>     from zappa.cli import handle
>   File "/home/bussiere/Workspace/test_zappa/app/lib/python3.5/site-packages/zappa/cli.py", line 44, in <module>
>     from zappa import Zappa, logger, API_GATEWAY_REGIONS
> ImportError: cannot import name 'Zappa'
>

**Comment by Miserlou** [comment]
AWS Lambda currently only supports Python 2.7, so that's what Zappa supports.

Closing for now.
