### ISSUE TITLE
Share settings across environments

### ISSUE THREAD

**Issue by cyounkins** [Miserlou/Zappa#584]
Settings like `app_function`, `parameter_depth`, `memory_size`, `timeout_seconds`, `vpc_config` are the same across my dev/staging/prod environments. Is there a way we can not repeat them? Thank you!

**Comment by Miserlou** [comment]
yes you can do this with the `extends` key

From my phone..

**Comment by cyounkins** [comment]
Thanks! Closing in favor of #585
