### ISSUE TITLE
Clarify stages vs environments in docs

### ISSUE THREAD

**Issue by cyounkins** [Miserlou/Zappa#585]
> You can define as many environments as your like - we recommend having dev, staging, and production.

> ... and STAGE (dev, production, etc.) variables at any time.

In the documentation there are inconsistencies as to what to call these things, environments or stages. 

"Stages" is a little weird since "staging" is a common stage.

"Environment" could be confused with environment variables.

**Comment by Miserlou** [comment]
This is a good point, but I don't know which it should be. :-D

Which do you think? I'm leaning stage..

**Comment by cyounkins** [comment]
I agree with "stage". I'll try to do a PR

**Comment by Miserlou** [comment]
😄 👍
