### ISSUE TITLE
Default Start Time of Logs

### ISSUE THREAD

**Issue by mcrowson** [Miserlou/Zappa#586]
Currently zappa tail obtains logs as far back as possibl and then continues printing logs until present. This can be overwhelming and a little slow if the app has been deployed for a significant amount of time or is a verbose logger. Without losing the ability to get all of the logs, we might want some flags to customize the tail.

Some options for this could be:
 - Flag to specify time back `zappa tail --seconds 300`
 - Default to something like 5 minutes back and flag for entire history `zappa tail --entire`

Branch off of a @kapilt comment on #561 so it could be discussed on its own in this issue.

**Comment by koriaf** [comment]
I think if we copy behaviour of some service like Docker (`docker logs`, which is well-known and already discussed by people) it would be handy and easy to document.

**Comment by Miserlou** [comment]
+1 to this, not sure what the default should be though. 300 seconds seems a little small to me but I'm not passionate one way or another.

Is `--seconds` the right unit to use? Are we going to end up needing to support days/weeks/months/years too?

**Comment by mcrowson** [comment]
From Docker: https://docs.docker.com/engine/reference/commandline/logs/ 

The --since option shows only the container logs generated after a given date. You can specify the date as an RFC 3339 date, a UNIX timestamp, or a Go duration string (e.g. 1m30s, 3h). Besides RFC3339 date format you may also use RFC3339Nano, 2006-01-02T15:04:05, 2006-01-02T15:04:05.999999999, 2006-01-02Z07:00, and 2006-01-02. The local timezone on the client will be used if you do not provide either a Z or a +-00:00 timezone offset at the end of the timestamp. When providing Unix timestamps enter seconds[.nanoseconds], where seconds is the number of seconds that have elapsed since January 1, 1970 (midnight UTC/GMT), not counting leap seconds (aka Unix epoch or Unix time), and the optional .nanoseconds field is a fraction of a second no more than nine digits long. You can combine the --since option with either or both of the --follow or --tail options.

**Comment by Miserlou** [comment]
That's interesting. I like the "Go duration string" format, but is there a Python implementation of that?

**Comment by Miserlou** [comment]
Although weirdly, Go duration strings don't support days, months or years..
https://www.goinggo.net/2013/06/gos-duration-type-unravelled.html

**Comment by Miserlou** [comment]
Apparently, this is why:

https://github.com/golang/go/issues/17767

**Comment by Miserlou** [comment]
Related https://github.com/icholy/Duration.py/blob/master/duration.py

**Comment by mihow** [comment]
I'm a fan of the date parser in dateutil and have used an argument named `--since` in other apps.

For example, these all work:

```python
from dateutil.parser import parse

parse("8:00") # Today at 8am in 24-hour time
parse("8am UTC")
parse("8am EST") # Today at 8am local time
parse("Jan 1") # Jan 1, 2017 
parse("Dec 1, 2015")
parse("Dec 1, 2015 8am EST")
parse("2017-01-17")
```

So usage could be something like:
`zappa tail --since "8am UTC"`
`zappa tail --since "Jan 1"`

and to get the time delta seconds:
`(datetime.datetime.now() - parse(args['since'])).seconds`

**Comment by Miserlou** [comment]
That seems acceptable to me, although I did just get the Duration.py guy to submit to PyPi..

**Comment by koriaf** [comment]
if you support `--since (real datetime)`, `--limit (timedelta)` and `--lines` when I fail to see any case which won't be covered. Personally I would use `--lines 40`, expecting to see last 40 lines/records.

**Comment by mcrowson** [comment]
I would think since could include timedelta as well. In addition, limit seems like it would be inconsistent with "follow". Like if I'm limiting do I stop following when I've hit the limit. 

so --since (real datetime or timedelta) and --lines?

**Comment by Miserlou** [comment]
Is there a good standard way to determine if a string is a real datetime or a timedelta?

I think I also want duration support anyway..

**Comment by Miserlou** [comment]
I started working on this, but I'm having trouble making boto3's `filter_log_events` respect `startTime` >:[

**Comment by Miserlou** [comment]
Okay, I've added `--since` and `--filter`, but not lines, which I have decided I'm less excited about. If somebody wants to work on that one it's fine, but I think it needs a separate issue for implementation discussion, because it actually isn't as simple as since and filter.
