### ISSUE TITLE
Not processing input data for PUT method

### ISSUE THREAD

**Issue by abnerjacobsen** [Miserlou/Zappa#59]
Hi,

I'm developing a small API using zappa with pycnic (https://github.com/nullism/pycnic) but I have a problem: When I do an api call with PUT method and with some json data in the body, like:

> curl -i -X PUT -H "Authorization: xxxxyyyy662362632" -H "Content-Type:application/json" https://99999999999.execute-api.us-east-1.amazonaws.com/v1/uuid/cin2711b5000001qdk2fd5l3v -d '{"config": {"ADMIN_EMAIL": "abner@xxxxx.com.br"}}'

zappa is not setting the environ['CONTENT_LENGTH'] in file wsgi.py and because this picnic generate an exception - it's needed the environ['CONTENT_LENGTH'] to read the wsgi's PUT body. 

Zappa only set environ['CONTENT_LENGTH'] when the HTTP POST method is called,  as you can see in line 72 bellow  of wsgi.py.

```
        # Input processing
        if method == "POST":
            if 'Content-Type' in event_info["headers"]:
                environ['CONTENT_TYPE'] = event_info["headers"]['Content-Type']

                # Multipart forms are Base64 encoded through API Gateway
                if 'multipart/form-data;' in event_info["headers"]['Content-Type']:
                    body = base64.b64decode(body)

            environ['wsgi.input'] = StringIO(body)

            environ['CONTENT_LENGTH'] = str(len(body))
```

I think that line 72 of wsgi.py need's to be:

`if method == "POST" or method == "PUT":`

**Comment by Miserlou** [comment]
Nice, thanks for reporting this!

Do you want to submit a pull request for the fix?

**Comment by abnerjacobsen** [comment]
I submitted the pull request - It's first time I do it in Github, please, check if I done it correctly.

**Comment by Miserlou** [comment]
Perfect! Thanks!
