### ISSUE TITLE
cython extension which uses numpy won't import

### ISSUE THREAD

**Issue by fscottfoti** [Miserlou/Zappa#595]
I have a cython extension which I'm compiling on a Linux EC2 instance and deploying using Zappa.  It deploys fine with a simple version that does not import numpy, but when I import numpy in the extension it works locally but not after deployment.

It fails on import - I get a debug statement before the import but not after.  Technically in the logs I see [this](https://github.com/Miserlou/Zappa/issues/283) but that doesn't look helpful.

Has anyone tried this before? - it doesn't seem like a common case, but not terribly uncommon either.  I'm guessing it has to do with subbing out my local version of numpy with the pre-built version.  If you tend to agree, maybe I should know more about what kind of version is being subbed in and I can try to match my environment to that one?  Or do you think maybe I will have to build and include my own numpy?

**Comment by fscottfoti** [comment]
In fact, after some more hacking I was able to get this to work.  I just needed to start with a new ec2 instance and make sure I matched the precompiled version of numpy.

I think my issue was that I had another version of numpy installed on my build machine outside of my virtualenv and no matter what I tried it would keep getting included with -I/usr/include/python2.7 which overrode the correct numpy in my virtualenv.

At any rate, keep up the good work - very fun stuff!

**Comment by Miserlou** [comment]
Is there anyway that your work could be used to improve [lambda-packages](https://github.com/Miserlou/lambda-packages)? 

Possibly related https://github.com/Miserlou/Zappa/pull/108

**Comment by fscottfoti** [comment]
Actually the numpy in lambda-packages is working well for me - I just needed to make sure I had the right header to match the precompiled version and since then everything has gone smoothly.  (I didn't have to build my own numpy or anything.)

I do usually use conda to package my software, but in my case, the use of a virtualenv is not a big hassle.
