### ISSUE TITLE
Is multiple branches on my repo needed?

### ISSUE THREAD

**Issue by wobeng** [Miserlou/Zappa#596]
This is more of a question than an issue.

Before zappa, the model I had on my repo was develop and master branching...after testing on develop branch, I will merge with master branch, then master branch get automated to production servers.

With Zappa deployment to stages and rollback feature, is my model really needed? Can I just depend on master branch on my repo and use Zappa deployment to stages and rollback if I need to?

Any opinion on this?

**Comment by Miserlou** [comment]
My recommendation would to decouple software versioning and deployment versioning, but this the kind of the thing that people develop strong opinions on, and which depend strongly on the specific system you're developing.

Closing this as it's a non-issue, but feel free to stop by the Slack channel if you want to discuss this more.
