### ISSUE TITLE
Remote Environment Variables Returning None

### ISSUE THREAD

**Issue by wobeng** [Miserlou/Zappa#604]
I'm following the instruction on https://github.com/Miserlou/Zappa#remote-environment-variables

In the log I see it adding key and value to environment  but when I ask for it using

`import os
db_string = os.environ.get('DB_CONNECTION_STRING')`

It returns None.  FYI, os.environ.get('STAGE') works well

**Comment by mcrowson** [comment]
Turns out this was because json was saving the keys as unicode. Had to do the following:

os.environ.get(u'DB_CONNECTION_STRING')

Might want to cast the keys as string when saving to os.environ.
https://github.com/Miserlou/Zappa/blob/master/zappa/handler.py#L174
