### ISSUE TITLE
Application zip package is too large for AWS Lambda.

### ISSUE THREAD

**Issue by jfmyers** [Miserlou/Zappa#612]
## Context
I'm testing a deployment to Lambda for a flask app. I created a new flask app with one file `run.py` and ran `zappa init` and then `zappa deploy dev`. I receive the following client error:

```
ClientError: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: Unzipped size must be smaller than 262144000 bytes
```

Zappa says the zipped package is 156.5MB, however, the unzipped directory is only 15MB.

My requirements.txt contains one entry `Flask==0.10.1`.

Any ideas about what's going on here would be super helpful.

**Comment by Miserlou** [comment]
Are you in a venv?

**Comment by Miserlou** [comment]
You should check out the slim_handler setting now.
