### ISSUE TITLE
Tried creating a deploy group/policy from scratch and ran into issues

### ISSUE THREAD

**Issue by richiverse** [Miserlou/Zappa#613]
There is an issue with deploys where it can get stuck in a state where it will give the following error.

ClientError: An error occurred (ResourceConflictException) when calling the CreateFunction operation: Function already exist: test-dev

Deleting 
 

## Actual Behavior

I will be introducing a PR soon with the fix. It will require the "lambda:GetFunction" permission.

Create a profile with the following policies attached:
"iam:PassRole"
"s3:GetObject"
"lambda:CreateFunction"
"iam:GetRole"
"s3:PutObject"
"s3:CreateBucket"

now try zappa deploy dev a couple of times.

## Context

I'm trying to figure out minimum amount of policy requirements per zappa commands.
## Your Environment

* Zappa version used: latest from pip
* Operating System and Python version: ubuntu 16.04 and python 2.7.12 on pyenv
* Link to your project (optional):
* Your `zappa_settings.py`: 
I'm using cookie cutter settings and app.py

**Comment by Miserlou** [comment]
What's happening here?

**Comment by richiverse** [comment]
Starting from no permissions and gradually granting more led to an infinite loop situation where I needed to first try getting a function arn. Deleting my s3 zip files and deleting the lambda function had no effect on advanceing the deployer.

I broke some tests on travis inadvertently so I will try updating on the cli side of things and reopen my PR

**Comment by Miserlou** [comment]
Oh, okay, great. Thanks!
