### ISSUE TITLE
Intercooler.js apps fail (ajax requests return 403) when deployed via Zappa

### ISSUE THREAD

**Issue by bobcolner** [Miserlou/Zappa#616]
## Context
Intercooler.js http://intercoolerjs.org/ is a browser js library for "Simple AJAX using HTML attributes". A library to declarative make AJAX calls and update the DOM.

For reasons unknown to me,  Intercooler AJAX calls fail (`403`) when deployed on AWS via Zappa. The API routes used for the AJAX calls work when browsed to directly.
 

## Expected Behavior
Index.html contains a single `<h1>` tag endouded with a intercooler ajax directive. Clicking on the button should result in API path specified in `ic-get-from` being called and the `<h1>` element being replaced with the response.

`bug_server.py` implements the flask server for the example app.

## Actual Behavior
When run locally the app returns a new random string from the server each time the test button is clicked.

When deployed via Zappa the AJAX calls fails with a `403` forbidden code.
Details: https://raw.githubusercontent.com/bobcolner/zappa-intercoolerjs-issue/master/screenshots/ajax%20bug%20trace.png

## Steps to Reproduce

1. Minimal flask+intercooler.js app: https://github.com/bobcolner/zappa-intercoolerjs-issue
2. To Run locally in a virtual env (ajax 'click me' button should work): `pip install -r requirments.txt && python bug_server.py`
3. Deploy on AWS via `Zappa init` and `Zappa deploy dev`

## Context
Both Zappa and Intercooler.js enable **Low Complexity** development. I'm excited about combining serverless tech like Zappa (low complexity, great economics and scaling) and low-complexity but compelling UX frontend tech -aka Intercooler.js. 

Thanks for your help on this.

## Your Environment

* Zappa version used: latest
* Operating System and Python version: OS X, virtual env, python2.7
* Link to your project (optional): https://github.com/bobcolner/zappa-intercoolerjs-issue
* Your `zappa_settings.py`: 
{
    "dev": {
        "app_function": "bug_server.app", 
        "s3_bucket": "zappa-intercooler-issue"
    }
}

**Comment by collingreen** [comment]
Haven't looked into details here but have you tried your url without the intercooler part in the middle? It looks like you're trying to use the base url without the /dev on it

**Comment by bobcolner** [comment]
That is it -thanks! 

When I add /dev/ to the route the intercooler calls work when deployed to AWS -but now I can't run it locally.

Do you have a suggestion as to how to setup a flask app so I can still run in locally (without the /dev/) and in production via Zapp?

**Comment by bobcolner** [comment]
One solution is to setup custom domain for the zappa app so that the same URL structure works both when run locally and on lambda. (no more `/dev/` needed in the URLs).

The other solution I can think of is to conditionally renderer URLs based on where the app is running. E.g conditionally add `/dev/` to all URLs.

Honestly this seems so hacky that I'd bet that there is a better (probably obvious) way to accomplish this. Any one got a clean solution?

**Comment by Miserlou** [comment]
This is a limitation of API Gateway.

You shoudn't ever hardcode your URLs though, you should use the url generation function that Flask provides, which do work with Zappa.

The best solution is to deploy your application to a custom domain name or subdomain.
