### ISSUE TITLE
502 "Internal server error"

### ISSUE THREAD

**Issue by AcidLeroy** [Miserlou/Zappa#627]
With a basic "hello world" flask application, I am getting a 502 response from the API Gateway with a simple `zappa deploy dev` testing environment.

Based on the documentation, I should already be up and running with a simple `zappa init` and a `zappa deploy dev`, but I haven't been able to get close. Once I finally got the basic permissions setup for my user account, I was finally able to deploy the application, but now I am getting errors when testing the endpoint.
 

Here is my zappa settings file: 

```
{
    "dev": {
        "app_function": "test.app", 
        "s3_bucket": "zappa-XXXXXX"
    }   
}
```

and here is the Flask program (test.py) I am attempting to run: 

```
from flask import Flask
app = Flask(__name__)

@app.route("/")
def hello():
    return "Hello World!"

if __name__ == "__main__":
    app.run()
```

When I hit the endpoint, I would expect to see "Hello World!", but instead I get an internal server error message. Here are some more details about the error I retrieved from the AWS Console: 

```
Wed Jan 25 14:37:16 UTC 2017 : Execution failed due to configuration error: Malformed Lambda proxy response
Wed Jan 25 14:37:16 UTC 2017 : Method completed with status: 502
```

I assumed this should just work out of the box, but it looks like it does not. Have I configured something wrong? Do I need additional permissions in order to hit the API? 

Environment configuration: 

`python --version` = Python 2.7.9
`zappa --version` = 0.32.1

**Comment by mp3il** [comment]
what is the output you see when you run
zappa tail
?

**Comment by kadrach** [comment]
```
$ zappa tail
Traceback (most recent call last):
  File "/Zappa/example/env/lib/python2.7/site-packages/zappa/cli.py", line 1981, in handle
    sys.exit(cli.handle())
  File "/Zappa/example/env/lib/python2.7/site-packages/zappa/cli.py", line 398, in handle
    self.dispatch_command(self.command, environment)
  File "/Zappa/example/env/lib/python2.7/site-packages/zappa/cli.py", line 468, in dispatch_command
    filter_pattern=self.vargs['filter'],
  File "/Zappa/example/env/lib/python2.7/site-packages/zappa/cli.py", line 756, in tail
    filter_pattern=filter_pattern,
  File "/Zappa/example/env/lib/python2.7/site-packages/zappa/zappa.py", line 1831, in fetch_logs
    orderBy='LastEventTime'
  File "/Zappa/example/env/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Zappa/example/env/lib/python2.7/site-packages/botocore/client.py", line 543, in _make_api_call
    raise error_class(parsed_response, operation_name)
ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the DescribeLogStreams operation: The specified log group does not exist.
```

The CF stack does not contain any LogGroups/LogStreams.

**Comment by AcidLeroy** [comment]
I have the following errors repeated multiple times with `zappa tail`: 

- `[1485398037119] module initialization error: Attempted relative import in non-package`
- `[1485746084834] Unable to import module 'handler': No module named werkzeug.wrappers`

**Comment by fantamiracle** [comment]
Any updates on this post? I am having the same problem with same `Unable to import module 'handler': No module named werkzeug.wrappers` message.

**Comment by Miserlou** [comment]
that error is usually from a messed up venv, try remaking

From my phone..

**Comment by fantamiracle** [comment]
I actually updated my zappa to  0.32.2 and it seems this error went away... anyway thanks :)

**Comment by Miserlou** [comment]
Sweet
