### ISSUE TITLE
Better docs for EXCLUDES_LIST and virtualenv naming

### ISSUE THREAD

**Issue by bjinwright** [Miserlou/Zappa#63]
If your virtualenv's name is the same name as a package in your project's directory or virtualenv it will be added to the excludes list.

I propose that Zappa keeps this just document it better.

**Comment by bjinwright** [comment]
Example: My Django project's name is biggy and my virtualenv's name is biggy, this will result in the main package created by django-admin startproject biggy to be excluded from the zip folder.

**Comment by Miserlou** [comment]
Not totally fixed, but latest code will now print a warning if this is happening.

I think the best solution is just to explicitly define 'project_name' in your Zappa settings, or have a differently named venv. Annoyingly, you have to recreate it, you can't just rename virtualenvironments.

**Comment by bobshaw1912** [comment]
I believe this issue is still persistent... I have done the workload as @Miserlou suggested.

**Comment by ceefour** [comment]
I don't see any warning as of zappa 0.43.2.

I'd suggest that it's promoted to error, because project will be unusable anyway if venv == project name.
