### ISSUE TITLE
Zappa doesn't recognize Flask blueprint routes

### ISSUE THREAD

**Issue by laurentrivard** [Miserlou/Zappa#643]
I have a Flask app and I'm using flask_restful and blueprint to serve up my API. 
After deploying my app with Zappa, I have no problem accessing a route I define in app.py, but the other routes don't seem to be registered. 

My flask app looks something like this: 

```
app = Flask(__name__)

# load the default configuration
app.config.from_object('api.config.default')

# connect postgres
db = SQLAlchemy(app)

@app.route('/')
def index():
    return "Hello, world!", 200

def create_app(**config_overrides):
    # apply config overrides passed in as a dependency
    app.config.update(config_overrides)

    from v1_0 import app_bp as blueprint
    app.register_blueprint(
        blueprint,
        url_prefix='/v1.0')
    return app
```

As mentioned above, I am able to access `/`, but anything under `v1.0` I cannot access
 

## Expected Behavior

My blueprint is defined in `/v1_0/__init__.py` 
## Actual Behavior

I should be able to access the routes I created in my blueprint
## Possible Fix

I think a great use of Zappa is to deploy APIs. Everything has been straightforward, but it would be great to be able to use blueprints

**Comment by Miserlou** [comment]
If you change your app_function form 'blah.app' to 'blah.create_app', does it work?

**Comment by laurentrivard** [comment]
Yep, it gets me further. But I end up with this error whether my app function is 

`"app_function": "api.app_factory.create_app"`
`"app_function": "api.app_factory.create_app()"`
`"app_function": "api.app_factory.create_app(**config_overrides)"`

Error
`create_app() takes exactly 0 arguments (2 given)`

**Comment by laurentrivard** [comment]
I got it to work with the app object that was being returned in another file. 

Thanks!

**Comment by texonidas** [comment]
@laurentrivard could you elaborate on the way that it is being returned in the other file? I've run into the same problem.

**Comment by laurentrivard** [comment]
```
def create_app(self, **config_overrides):
   # setup some stuff
   return app
```

The other file just has

```
from app_factory import create_app

app = create_app()
```
