### ISSUE TITLE
Worker Processes

### ISSUE THREAD

**Issue by flux627** [Miserlou/Zappa#648]
I tried to find information on this but failed, so I apologize if this is readily available information. Most of the Django apps I develop are heavily reliant on worker processes (aka offline processing, via django-rq or Celery). Being that AWS Lambda's invocations are "workers" in their own way, it seems like support for this should not be too difficult.

Is there a current recommended way of accomplishing this? Maybe by using Amazon SQS as a broker for Celery?

**Comment by Miserlou** [comment]
There are lots of ways of doing this, but the right one depends on the constraints of your application.

I'm going to close this issue now, but feel free to chime in on the discussion on this topic happening here: https://github.com/Miserlou/Zappa/issues/603#issuecomment-277127507
