### ISSUE TITLE
When `zappa tail --filter` raises the InvalidParameterException, Provide Documentation

### ISSUE THREAD

**Issue by mcrowson** [Miserlou/Zappa#651]
## Context

The filter command for CW has some specific desires in how things are formatted. It was not apparent to me at first as I assumed it was just a basic text search.

http://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html

 

## Expected Behavior

When botocore raises the InvalidParameterException when calling FilterLogEvents, provide a warning and a link to the documentation on how to structure filters (suggested link above).

## Actual Behavior

When doing a filter on an email address `zappa tail stage --filter "email@domain.com"` I got the exception from botocore.

## Possible Fix

A nice warning message on how to fix the filter statement.

## Steps to Reproduce

1. What the heck this is a ridiculous issues templates
2.
3.
4.

## Context

Its so long. I mean really long

## Your Environment

* Zappa version used:
* Operating System and Python version:
* Link to your project (optional):
* Your `zappa_settings.py`: 

Especially for what I would think is a minor issue.

**Comment by Miserlou** [comment]
Oh, that is really annoying. I actually just assumed it was a regex string.

**Comment by Miserlou** [comment]
Added link to docs.
