### ISSUE TITLE
Code Sometimes References zappa_settings rather than the stage_config property.

### ISSUE THREAD

**Issue by mcrowson** [Miserlou/Zappa#655]
## Context

 
When using the "extends" key in the zappa_settings.json to inherit a keep_warm=false, it is having keep_warm=true. 

## Expected Behavior

All references to settings should be to the stage_config property.
 
## Actual Behavior

Some config references are going correctly to the stage_config property while others are just going to the original zappa_settings dict. 

## Possible Fix

references to self.zappa_settings should be replaced with self.stage_config in the cli.py file.

## Your Environment

* Zappa version used: 0.35.1
* Operating System and Python version: Mac OSX / Python 2.7.13
* Your `zappa_settings.py`: 
`
{
  "core":{
    "project_name": "proj",
    "app_function": "app.app",
    "s3_bucket": "bucketname",
    "keep_warm": false,
    "timeout_seconds": 300
  },
  "dev": {
    "extends": "core"
  }
}
`

**Comment by Miserlou** [comment]
Yep
