### ISSUE TITLE
app_function name seems to be set to 'source' when deploying from linux

### ISSUE THREAD

**Issue by eely22** [Miserlou/Zappa#656]
I have a Zappa project that works fine locally, I am able to deploy and update just fine from my development machine. We are now trying to move deployments to our automated deployment server and are running into issues.

The deployment system starts a clean, vanilla Ubuntu 16.04 docker container with our source code. We have a way to add our AWS credentials into it, and then we install Zappa and try to update. 

The issue is, it seems the system is picking up the wrong app_function. I try running the command:
zappa -a my_api.app -s zappa_settings.json status test

And on my local dev system it works fine. However, on the deployment server, I see
```
Error: No Lambda source-test detected in us-west-2 - have you deployed yet?
```

When I try to run the update function on the deployment server, I see the output in the attached file [zappa_log.txt](https://github.com/Miserlou/Zappa/files/764138/zappa_log.txt). 

The highlight is that it says "source-test-" instead of "my_api-test". So it seems that the app_function is getting defaulted to "source" somehow and I can't seem to force it to pickup the correct name.

It does seem to pick up the zappa_settings.json file as it does upload to the correct s3 bucket. So I think it is reading the file, just not using the right name.

Is there some reason it would pick up 'source' instead of the app_function name defined in the zappa_settings.json file? I am digging through the source code as well, but haven't found a reason yet. Am I just misconfiguring something?

This is my zappa_settings.json file:
```
{
    "test": {
        "app_function": "my_api.app", 
        "s3_bucket": "zappa-my-api",
        "cors": true
    }
}
```

I am using zappa 0.35.2 on the deployment server, but on my local dev machine I am using 0.32.1. Here is the full pip list on the deployment server:
appdirs (1.4.0)
argcomplete (1.8.2)
base58 (0.2.4)
boto3 (1.4.4)
botocore (1.5.8)
click (6.7)
docutils (0.13.1)
durationpy (0.3)
Flask (0.12)
Flask-Cors (3.0.2)
futures (3.0.5)
hjson (2.0.2)
itsdangerous (0.24)
Jinja2 (2.9.5)
jmespath (0.9.1)
kappa (0.6.0)
lambda-packages (0.13.0)
MarkupSafe (0.23)
packaging (16.8)
peewee (2.8.5)
pip (9.0.1)
placebo (0.8.1)
PyMySQL (0.7.9)
pyparsing (2.1.10)
python-dateutil (2.6.0)
python-slugify (1.2.1)
PyYAML (3.12)
requests (2.13.0)
s3transfer (0.1.10)
setuptools (34.1.1)
six (1.10.0)
toml (0.9.2)
tqdm (4.11.2)
troposphere (1.9.2)
Unidecode (0.4.20)
Werkzeug (0.11.15)
wheel (0.29.0)
wsgi-request-logger (0.4.6)
zappa (0.35.2)

**Comment by Miserlou** [comment]
That's an interesting one and I can't think of an explanation off the top of my head.

**Comment by eely22** [comment]
Ok, problem solved, it was a simple misunderstanding that led to a misconfiguration. Hopefully this helps someone else!  

The name of the lambda function that gets created comes from "project_name" and not "app_function". As I didn't have a "project_name" in my zappa_settings.json, it was picking up the name of the current working directory, which was 'source' on the deployment server. 

So the solution is to make sure that the "project_name" is correct in the zappa_settings.json file if you plan to deploy from someplace other than your development directory.
