### ISSUE TITLE
Fix default rollback behaviour (which does nothing today)

### ISSUE THREAD

**Issue by vlcinsky** [Miserlou/Zappa#673]
Calling:

    $ zappa rollback

reports "function was rolled back" while it does not change anything

## Context
I fixed my lambda function, made `zappa update` and realized, I have better check failing behaviour with previous version first and then check the new version imporoves that.

For that reason I called:

    $ zappa rollback
    Rolling back..
    Done!

I was surprised, the behaviour of my lambda did not change.

Using:

    $ zappa status
    Status for messageformatter-dev:
     Lambda Versions: 19
    ...

reported the same Lambda version as before.

My environment:
- Python 2.7.12 run from virtualenv
- Ubuntu 16.04.2 LTS
- zappa --version: 0.35.2

## Expected Behavior

Number of steps to rollback shall be by default `1`. Now it is apparently `0`.

Thus calling:

    $ zappa rollback

would rollback one step back.

## Actual Behavior
Currently, without specifying value for `-n` it does report rollback success, but in fact does not change anything.

## Possible Fix
Set default value for `-n` option to `1`.

## Steps to Reproduce
1. Create a lambda function, e.g. reporting version (file `roller.py`):
```
    def main():
        res = "one"
        return res
```
and configure `zappa_settings.json`:

    {
        "dev": {
            "app_function": "roller.main", 
            "aws_region": "eu-west-1", 
            "s3_bucket": "zappa<some_unique_number>",
            "apigateway_enabled": false,
            "keep_warm": false
        }

    }

    
2. Deploy it:

```
    $ zappa deploy
```
3.  Invoke it:

 ```
    $ zappa invoke roller.main
    Result of roller.main:
    one
```
4. Update the roller.py, change `res` to `"two"`:

```
    def main():
        res = "two"
        return res
```

5. Update on AWS:
```
    $ zappa update
```
6. Invoke it:
```
    $ zappa invoke roller.main
    Result of roller.main:
    two
```
7. Rollback:
```
    $ zappa rollback
    Calling rollback for environment dev..
    Rolling back..
    Done!
```
8. Invoke. Expect "one" to be the response:
```
    $ zappa invoke roller.main
    Result of roller.main:
    two
```
9. Rollback with `-n 1`:
```
    $ zappa rollback -n 1
    Calling rollback for environment dev..
    Rolling back..
    Done!
```
10. Invoke. This time we get what is expected ("one"):
```
    $ zappa invoke roller.main
    Result of roller.main:
    one
```
## Your Environment
* Zappa version used: 0.35.2
* Operating System and Python version: Ubuntu 16.04.2 LTS, Python 2.7.12 (run from virtualenv)

**Comment by Miserlou** [comment]
Thanks for reporting! I think this feature is underused, could be why. I think I know what the issue is, should be easy to fix..
