### ISSUE TITLE
Binary support doesn't play nicely with Django form POSTs

### ISSUE THREAD

**Issue by cameronmaske** [Miserlou/Zappa#677]
## Expected Behavior
Ability to post django forms. 
e.g.
template
```
    <form action="...someurl" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Submit" />
    </form>
```
View
```
@login_required
def delete(request, pk):
    if request.method == "POST":
        form = Confirm(request.POST)
        if form.is_valid():
             ...etc
```

## Actual Behavior
With `binary_support:true`, attempting to do basic django form actions results in CSRF errors.
![image](https://cloud.githubusercontent.com/assets/1007064/23106166/522b88cc-f6b7-11e6-9455-b583bee8f2c3.png)

## Possible Fix
![image](https://cloud.githubusercontent.com/assets/1007064/23106165/4bd65a88-f6b7-11e6-98c5-ef29bff6a636.png)
Do not base64 encode `content-type:application/x-www-form-urlencoded`
https://github.com/Miserlou/Zappa/blob/master/zappa/handler.py#L455

## Your Environment

* Zappa version used: 0.36.0
* Operating System and Python version: 2.7.13
* Link to your project (optional): 
* Your `zappa_settings.py`: 
(Names changed)
```
"dev": {
        "django_settings": "app.settings",
        "s3_bucket": "bucket-lambda",
        "remote_env": "s3://bucket-env/dev.json",
        "keep_warm": false,
        "debug": true,
        "binary_support" : true,
        "environment_variables": {
            "ALLOWED_HOSTS": "*"
        },
        "vpc_config": {
            "SubnetIds":["subnet-1", "subnet-2"],
            "SecurityGroupIds": ["sg-1"]
        }
    }
}
```

**Comment by Miserlou** [comment]
Thank you for reporting!

Is the 'application/x-www-form-urlencoded' content-type in the _returned_ response? Binary Support should only be touching responses on the way _out_, as far as I know..

**Comment by cameronmaske** [comment]
@Miserlou It's on the Request Headers being sent in. Here is a fuller network screenshot from chrome.
![image](https://cloud.githubusercontent.com/assets/1007064/23106282/e0051324-f6b8-11e6-946b-d0344db8903e.png)

**Comment by Miserlou** [comment]
If this is on the POST, then I guess that we need to make wsgi.py Base64-aware, which it currently isn't. I didn't realize that was necessary.

On the flip side, this may allow for binary file uploads if we do it properly. Pinging @wobeng 

Related: https://github.com/Miserlou/Zappa/issues/80

**Comment by Miserlou** [comment]
I'm also not able to reproduce this yet.

**Comment by Miserlou** [comment]
Is yours an AJAX request?

**Comment by cameronmaske** [comment]
@Miserlou It is not an AJAX request. Been trying to debug this further. 
Still occurs for me on Django 1.9 and 1.10 (just to rule that out).

I'm gonna try and create a mini project that demostrates it.

**Comment by cameronmaske** [comment]
Example project here:
https://github.com/cameronmaske/zappa-csrf-token-bug

**Comment by wobeng** [comment]
should we have a list of exclusions from base64.b64encode?

**Comment by Miserlou** [comment]
Can you try `master` now?

**Comment by cameronmaske** [comment]
@Miserlou Tested my [sample repo](https://github.com/cameronmaske/zappa-csrf-token-bug) and real world project against master. Can confirm forms play nicely with with binary support enabled!

**Comment by Miserlou** [comment]
Closing this, thanks all.

**Comment by cameronmaske** [comment]
Great stuff @Miserlou. Thanks for the quick turn around and for all the work on this awesome project :)

**Comment by oliviersels** [comment]
Just to chime in on this. I've forked zappa last year to implement binary support very quickly for our own use and I used a different approach. You can see the (tiny) commit here: https://github.com/oliviersels/Zappa/commit/fb40baa0144695fec5cc326705541c26714d13df

I use the "isBase64Encoded" flag which comes from api gateway and is
> "A boolean flag to indicate if the applicable request payload is Base64-encode"

Not really much documentation, but it works for our django 1.10 project.
I'll try your solution soon and take a closer look at your implementation to see if it works for us.
