### ISSUE TITLE
Binary Upload Support

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/Zappa#683]
Binary _downloads_ now work fine, (thanks @wobeng) - but uploads still don't. 

We'll have to fatten up our templates a bit to add support for the top _N_ MIME-types we want to support, but it should be fairly do-able. 

Related Django test function (for JPEGs):
```python
from django.shortcuts import render
from django.http import HttpResponse
from django import forms

class UploadFileForm(forms.Form):
    file = forms.FileField()

def upload_file(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():

            image = request.FILES['file'].read()
            mimetype = "image/jpeg"
 
            return HttpResponse(image, content_type=mimetype)

    else:
        form = UploadFileForm()
    return render(request, 'upload.html', {'form': form})
```
```html
<html>
    <form method="post" enctype="multipart/form-data">
	{%csrf_token%}
	{{form}}
    <input type="submit" >eyy</input>
    </form>
</html>
```

Related blog post here: https://aws.amazon.com/blogs/compute/binary-support-for-api-integrations-with-amazon-api-gateway/

**Comment by oliviersels** [comment]
I found the previous issue https://github.com/Miserlou/Zappa/issues/677#issuecomment-281704718 first and commented there, but it might also be relevant for this discussion.

I use https://github.com/oliviersels/Zappa/commit/fb40baa0144695fec5cc326705541c26714d13df for binary uploads with a FileField and I only had to configure the "multipart/form-data" mime type manually for it to work, but that probably won't work for raw uploads.

**Comment by Miserlou** [comment]
Where did you set it manually? We just need to add that line to our tropo template somewhere, but I don't know specifically where.

**Comment by wobeng** [comment]
Is binary upload really needed? it should be going to s3

**Comment by Miserlou** [comment]
For permanent assets, but you could see a case for non-permanent assets to be uploaded through the Gateway.

**Comment by wobeng** [comment]
What I do is create a presigned s3 upload and use ajax to upload to the presigned s3. It's faster and best practice

**Comment by Miserlou** [comment]
Sure, but that's perhaps not suitable for all cases. Regardless, we should make this change, I think it's going to boil down to a single line of code somewhere in the template.

**Comment by wobeng** [comment]
I think upload should work 

I think you just need to set Content-Type: application/octet-stream when you

**Comment by Miserlou** [comment]
@oliviersels - could you be more specific about how and which content types you manually added to the API Gateway? Did you also define a template?

**Comment by Miserlou** [comment]
Turns out it does work, you just have to turn it on. *facepalm*

**Comment by wobeng** [comment]
:)

**Comment by oliviersels** [comment]
Good to see that it works now :smile:
