### ISSUE TITLE
Kappa Update Now Raises Event Issues

### ISSUE THREAD

**Issue by mcrowson** [Miserlou/Zappa#688]
## Context

 
Scheduling events in S3 and SNS both raise warnings in the console. The events still appear to get created and work, but now a warning pops up in the console.

## Expected Behavior

Events should be scheduled and unscheduled without errors.

## Actual Behavior

Kappa seems to be raising an error. The error differs for different different event sources.

## Possible Fix

Revert Kappa to 0.6.0 to silence the warnings. This likely just hides the issue. Zappa 0.35.1 has that kappa version.

## Steps to Reproduce

1. Recent Zappa
2. `zappa schedule stage`

## Your Environment

* Zappa version used: Tried on 0.36.0 -> 0.37.1
* Operating System and Python version: OSX 2.7.13
* Link to your project (optional):
* Your `zappa_settings.py`:

**Comment by bdecotes-pl** [comment]
Perhaps related issue in scheduling s3 events:

From `zappa update` output:
```
Created s3:ObjectCreated:* event schedule for phishkit_parser.kit_event.phishkit_handler!
```
Which for my case now causes the following Exception to be raised when triggered by an `s3:ObjectCreated:*` event:
```
need more than 1 value to unpack: ValueError
Traceback (most recent call last):
File "/var/task/handler.py", line 499, in lambda_handler
return LambdaHandler.lambda_handler(event, context)
File "/var/task/handler.py", line 233, in lambda_handler
return handler.handler(event, context)
File "/var/task/handler.py", line 392, in handler
app_function = self.import_module_and_get_function(whole_function)
File "/var/task/handler.py", line 223, in import_module_and_get_function
module, function = whole_function.rsplit('.', 1)
ValueError: need more than 1 value to unpack
```

After adding logging just before this line 223 in `handler.py`, I get the following output:
 ```
whole function is: phishkit-parser-dev
```

When inspecting my s3 event configuration, the event name now triggered on my s3 bucket is the following:
 ```
arn:aws:lambda:us-east-1:<ACCOUNT_NUMBER>:function:phishkit-parser-dev
```

Manually editing the event name to the following:
```
phishkit-parser-dev:phishkit_parser.kit_event.phishkit_handler
```
or more generally:
```
{{project_name}}-{{stage_name}}:{{events_function_name}}
```
resolves the issue for me, and my event handler is correctly triggered on a new event invocation.

Relevant zappa settings:
```
"events": [{
      "function": "phishkit_parser.kit_event.phishkit_handler",
      "event_source": {
        "arn": "MY_BUCKET_ARN",
        "events": [
          "s3:ObjectCreated:*"
        ]
      }
    }]
```

Using Zappa version 0.37.1

**Comment by Miserlou** [comment]
> phishkit

Bruhhhhh

**Comment by bdecotes-pl** [comment]
guess I could have sanitized everything :1st_place_medal:

**Comment by Miserlou** [comment]
Possibly fixed in 0.37.2, let me know if not and I'll reopen.

**Comment by bdecotes-pl** [comment]
Can confirm this issue is resolved for me with 0.37.2. Great work! 🎉

**Comment by Miserlou** [comment]
Good luck with your phishing!

**Comment by bdecotes-pl** [comment]
White-hat parsing only!
