### ISSUE TITLE
For the docs: Make sure to use python >= 2.7.9 in your venv

### ISSUE THREAD

**Issue by vectorien** [Miserlou/Zappa#69]
I ran into problems caused by ssl failing (SNI (Server Name Indication), Insecureplatform warnings etc)  in the requests / urllib modules. 

Using latest python 2.7. (2.7.11 in my case) helped.

A very good howto to do that only for a venv is here: http://mbless.de/blog/2016/01/09/upgrade-to-python-2711-on-ubuntu-1404-lts.html#example-virtualenv

**Comment by Miserlou** [comment]
Interesting, thanks for reporting. You can also install requests[security], I think.
