### ISSUE TITLE
Unable to undeploy. Update leads to error(104, 'Connection reset by peer')

### ISSUE THREAD

**Issue by neotheicebird** [Miserlou/Zappa#697]
$ zappa undeploy
Calling undeploy for environment dev..
Are you sure you want to undeploy? [y/n] y
Deleting API Gateway..
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/vol/home/ubuntu/python2713/lib/python2.7/sit
e-packages/zappa/cli.py", line 2084, in handle
    sys.exit(cli.handle())
  File "/vol/home/ubuntu/python2713/lib/python2.7/sit
e-packages/zappa/cli.py", line 399, in handle
    self.dispatch_command(self.command, environment)
  File "/vol/home/ubuntu/python2713/lib/python2.7/sit
e-packages/zappa/cli.py", line 475, in dispatch_command
    remove_logs=self.vargs['remove_logs']
  File "/vol/home/ubuntu/python2713/lib/python2.7/sit
e-packages/zappa/cli.py", line 843, in undeploy
    domain_name=domain_name
  File "/vol/home/ubuntu/python2713/lib/python2.7/sit
e-packages/zappa/zappa.py", line 1167, in undeploy_api_gateway
    was_deleted = self.delete_stack(lambda_name, wait=True)
  File "/vol/home/ubuntuF/python2713/lib/python2.7/sit
e-packages/zappa/zappa.py", line 1207, in delete_stack
    self.cf_client.delete_stack(StackName=name)
  File "/vol/home/ubuntu/python2713/lib/python2.7/sit
e-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/vol/home/ubuntu/python2713/lib/python2.7/sit
e-packages/botocore/client.py", line 543, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (InternalFailure) when calling the DeleteStack op
eration (reached max retries: 4): Unknown

==============

Essential changes made:

1. Using a new virtualenv. Had to delete the old virtualenv
2. Changed the AWS credentials. used `aws configure` to use the new `AWS_ID`, `AWS_SECRET`

**Comment by Miserlou** [comment]
This could be related to the current AWS outage.

**Comment by Miserlou** [comment]
I'm pretty much gonna avoid debugging this kinda stuff until everything is green again: https://status.aws.amazon.com/

Suggest you go and drink beers for the rest of the day.

**Comment by neotheicebird** [comment]
Haha :D Thanks! Great work with zappa by the way. Loving it :)

**Comment by Miserlou** [comment]
Try now! Stuff is back!

**Comment by neotheicebird** [comment]
Yup, Things are back working. Thanks again.
