### ISSUE TITLE
[Cross-Post] Django example not working

### ISSUE THREAD

**Issue by flux627** [Miserlou/Zappa#703]
Just cross-posting this issue from narfman0/zappa-examples as I'm not sure if it's a bug here or there:

https://github.com/narfman0/zappa-examples/issues/1

**Comment by philipn** [comment]
See also https://github.com/Miserlou/Zappa/issues/351.  It seems that Zappa no longer works with Django.

**Comment by flux627** [comment]
Closing as this is a duplicate of #351 and I just found the regression (see my comments #351 for details).
