### ISSUE TITLE
Automatically created zip bucket in the wrong region

### ISSUE THREAD

**Issue by carhartl** [Miserlou/Zappa#71]
Given a configuration with a region other than default, and a bucket that hasn't yet been created:

```json
{
    "dev": {
        "aws_region": "eu-west-1",
        ...
        "s3_bucket": "not-yet-existing-bucket"
    }
}
```

when running `zappa deploy dev`, I was seeing this error:
```
An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: Error occurred while GetObject. S3 Error Code: PermanentRedirect. S3 Error Message: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
```

The error occurs because of the bucket being created in a different region - I checked and `not-yet-existing-bucket` was created in US/Standard instead of in `eu-west-1`.

Creating the bucket in the same region as in the configuration beforehand solved the problem, though it would be nice if this was fixed.

Using zappa 0.17.6.

**Comment by Miserlou** [comment]
GOOD CATCH. Bucket region code got fiddled with recently and I guess this slipped through. (Bucket creation is supposed to be kind of a secret feature anyway, but still a good catch.)

**Comment by carhartl** [comment]
Yeah, I have to admit I was surprised that the bucket was created for me, I was assuming I had to create it beforehand but then simply forgot that step in a hurry... ha!

**Comment by carhartl** [comment]
Another thing just came to my mind - I believe I didn't setup a default location when setting up my AWS account on the computer, this may be another circumstance required for causing this in the first place. I need to check tomorrow morning whether that's the case.

**Comment by carhartl** [comment]
^ No, I do have a default region configured in `~/.aws/config`, same one I was using to configure Zappa.
