### ISSUE TITLE
`zappa update` won't reflect the current state of `api_key_required`

### ISSUE THREAD

**Issue by aehlke** [Miserlou/Zappa#724]
## Context

 
I have an existing zappa deployment. I want to make API keys required, so I set `api_key_required: true` and run `zappa update`.

## Expected Behavior

Zappa creates an API key.

## Actual Behavior

Zappa doesn't create an API key.

## Possible Fix

Add API key management to `zappa deploy` command.

## Steps to Reproduce

See above.

## Your Environment

* Zappa version used:
* Operating System and Python version:
* Link to your project (optional):
* Your `zappa_settings.py`:

**Comment by alfonsomhc** [comment]
I found the same issue

**Comment by Miserlou** [comment]
Essentially, `update` deals with Lambda and `deploy` deals with API Gateway. Since API Key Required is an API Gateway setting, that it requires redeploy. I can update the docs to reflect this.

**Comment by Miserlou** [comment]
In fact, the docs already mention this.
