### ISSUE TITLE
Broken link in Zappa Guides section of README.md: "Deploy a Serverless WSGI App using Zappa, CloudFront, RDS, and VPC"

### ISSUE THREAD

**Issue by dylanjw** [Miserlou/Zappa#725]
## Context

 
Zappa project's README.md

## Expected Behavior
The link titled: "Deploy a Serverless WSGI App using Zappa, CloudFront, RDS, and VPC", links to a missing google doc at: https://docs.google.com/presentation/d/1aYeOMgQl4V_fFgT5VNoycdXtob1v6xVUWlyxoTEiTw 

## Actual Behavior
Links to doc instead of no doc.

## Possible Fix

Link should be updated (to what I dont know), or removed.

## Steps to Reproduce

1. Review README.md: Zappa Guides, last link

## Your Environment

n/a

**Comment by bjinwright** [comment]
https://docs.google.com/presentation/d/1aYeOMgQl4V_fFgT5VNoycdXtob1v6xVUWlyxoTEiTw0/edit?usp=sharing

**Comment by bjinwright** [comment]
@Miserlou If I see changes in the README do you won't me to just commit them to master or to a branch a create a pull request.

**Comment by Miserlou** [comment]
For small things that don't warrant discussion, feel free to simply push commits.
