### ISSUE TITLE
Add an entry in zappa_settings to configure the Dead Letter Queue to which triple failed async invokes are sent to

### ISSUE THREAD

**Issue by chuckoy** [Miserlou/Zappa#738]
## Context

 
There's a feature in AWS Lambda where if an async event fails to execute properly after three tries you can opt to send it to a Dead Letter Queue. [AWS docs](http://docs.aws.amazon.com/lambda/latest/dg/retries-on-errors.html)
It would be nice to have an entry in `zappa_settings.json` where if we specified the ARN of the SQS queue/SNS topic Zappa would hook the lambda function to that DLQ. My specific use case is for replacing celery with Zappa.

## Possible Fix

Something along the lines of: `"dead_letter_queue": "sqs_or_sns_arn"` seems to be the most straightforward implementation. I'm happy to start a pull request for this once I've managed to grok exactly how `zappa_settings.json` works. It seems fairly simple and beginner-friendly.

**Comment by chuckoy** [comment]
I've decided to use the dictionary format config that the boto3 client uses instead of <key>: <ARN>(String) to be consistent.

`"dead_letter_config": {
    "target_arn": "<arn here">
}`

**Comment by chuckoy** [comment]
Just popped up in my mind. We could also include an option where the user could opt to deploy/create a new SQS/SNS queue/topic upon deploy so everything's done from Zappa.

I'll have to study the codebase even further for this, though. This is the current limit of my limited knowledge of Zappa.

**Comment by Miserlou** [comment]
Great, looking forward to reviewing and merging this tomorrow. Auto-queue creation stuff relates to https://github.com/Miserlou/Zappa/issues/603

**Comment by Miserlou** [comment]
Fixed by PR.
