### ISSUE TITLE
Confusing error message if not in package env

### ISSUE THREAD

**Issue by hayd** [Miserlou/Zappa#74]
If you forget to enter your packages env, `source env/bin/activate`, the deploying simply prints 'VIRTUAL_ENV':

```
$ zappa deploy dev
Packaging project as zip...
'VIRTUAL_ENV'
$
```

(This was after *nearly* following the instructions with the basic flask app and settings.)

Would be great if this could show a more descriptive message "not inside local virtual env" (or potentially this is as my global virtual env has some packages that not in lambda-package.

**Comment by Miserlou** [comment]
Good idea!

**Comment by hayd** [comment]
Awesome, thanks for the quick fix! and thanks for zappa!

**Comment by Miserlou** [comment]
💯 💯 💯
