### ISSUE TITLE
Async code not working , results in exceptions 

### ISSUE THREAD

**Issue by bitshark** [Miserlou/Zappa#749]
## Context
Details can be found in the logs from the Slack channel from March 28th 2017, but the main idea is that I've not been able to get async invocation working with the latest Zappa codebase published today on master.

```
[..]
from zappa.async import run

app = Flask(__name__)
error = None

def send_data_test(post_data):
    time.sleep(15)
    archive_url = os.getenv('ARCHIVE_URL', 'https://www.google.com')
    r = requests.post(archive_url, json=post_data, verify=False)
    print(r.status_code)

@app.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'GET':
        return jsonify({'status': 'ok'})
    elif request.method == 'POST':
        request_body = request.get_json()
        run(send_data_test, args=request_body)
        return jsonify({ 'status': 'ok'})
```

When POST'ing to the main route , Zappa has unexpected exceptions.

## Expected Behavior
I'm expecting that an HTTP Post to the main route to invoke the function send_data_test asynchronously. Zappa should provide the function the serializable arguments found in request_body which is passed into the HTTP Post.  Send_data_test in turn, does some additional work after a sleep.  So I'm expecting my HTTP post to immediately return, and I'm expecting the rest of send_data_test to complete 15 seconds later.

## Actual Behavior
The initial HTTP Post results in a return of an HTTP 500 and an exception appears in the zappa tail logs.

```
[1490743150535] [INFO] 2017-03-28T23:19:10.535Z XXXXXXXX-140c-11e7-ad19-ab40e39d92e8 XXX.XXX.XXX.XXX - - [28/Mar/2017:23:19:10 +0000] "POST / HTTP/1.1" 500 291 "" "curl/7.53.1" 0/112.425
[1490743150574] 'NoneType' object has no attribute 'rsplit': AttributeError
Traceback (most recent call last):
  File "/var/task/handler.py", line 507, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 241, in lambda_handler
  return handler.handler(event, context)
  File "/var/task/handler.py", line 359, in handler
  result = self.run_function(app_function, event, context)
  File "/var/task/handler.py", line 286, in run_function
  result = app_function(event, context)
  File "/var/task/zappa/async.py", line 177, in route_lambda_task
  func = _import_and_get_task(message['task_path'])
  File "/var/task/zappa/async.py", line 154, in _import_and_get_task
  module, function = task_path.rsplit('.', 1)
```

## Possible Fix
I have a fix already figured out, and I'll issue the pull request as soon as I finish writing this issue up.

## Steps to Reproduce
Code is enclosed above.  Additional context can be found in todays Zappa slack log (March 28th 2017).

## Your Environment

* Zappa version used:  Latest (installed from master today via)
```
pip install -e git+https://github.com/Miserlou/Zappa.git@master#egg=Zappa --no-cache-dir
```
* Operating System and Python version:  Void Linux , w/ Ubuntu 16 in an LXC container , Python 2.7.12
* Link to your project (optional): NA
* Your `zappa_settings.py`: 
```
{
    "uswest1_dev": {
        "app_function": "my_app.app",
        "aws_region": "us-west-1",
        "s3_bucket": "zappa-XXX",
        "environment_variables": {
          "ARCHIVE_URL": "https://XXXX.execute-api.us-east-1.amazonaws.com/useast1_dev/api/ingest"
        }
    }
}
```

**Comment by amajeed-dinCloud** [comment]
I am using latest version of zappa and having this issue.

```
from zappa.async import task
ImportError: No module named async
```


tell me what to do??

**Comment by mp3il** [comment]
@amajeed-dinCloud  - my guess is that they didn't publish the latest version to pypi yet, you can install it directly from the git repo.

**Comment by amajeed-dinCloud** [comment]
Thanks, @mp3il . Strange they have updated the doc and published it before actual feature. 
https://github.com/Miserlou/Zappa#asynchronous-task-execution

**Comment by Miserlou** [comment]
This should be pushed to pip today. Zappa Github always reflects master until we state otherwise.

I believe the problems mentioned above are fixed.
