### ISSUE TITLE
Message: 'phantomjs' executable may have wrong permissions.

### ISSUE THREAD

**Issue by stevezau** [Miserlou/Zappa#752]
Relating to issue https://github.com/Miserlou/Zappa/issues/682

Using the latest from GIT i seem to be hitting this issue again. It looks like the code fixes were removed from zappa.py??

**Comment by stevezau** [comment]
Oh wait, they are still there.

Hmm, wonder why it's not working then..

**Comment by stevezau** [comment]
Nevermind, i implemented this workaround https://github.com/Miserlou/Zappa/issues/720 which caused the issue with incorrect permissions...

I rebooted PC and i can update again.

**Comment by THC222** [comment]
Do you solve the problem?
