### ISSUE TITLE
Domain isn't updated if project_name is changed

### ISSUE THREAD

**Issue by aehlke** [Miserlou/Zappa#759]
## Context

 
Our devs renamed the project, expecting the domain name to point to the new project, however it continued to point to the old function.

## Expected Behavior

Updating `project_name` and deploying would update the Route53 record to point to the new lambda function/API gateway.

## Actual Behavior

Updating `project_name` and deploying did not update the Route53 record to point to the new lambda function/API gateway.

## Possible Fix

Add logic to check if the Route53 record needs to be updated.

## Your Environment

* Zappa version used: 0.39.1
* Operating System and Python version: Ubuntu, 2.7
* Link to your project (optional):
* Your `zappa_settings.py`:

**Comment by Miserlou** [comment]
`update` generally refers to updating the Lambda code, `certify` handles the domain and SSL. Calling `certify` would remedy this. If you did call certify and it didn't update the domain, feel free to reopen.

**Comment by aehlke** [comment]
Sorry, just came back to this ticket to close it after I realized that. Thanks.
