### ISSUE TITLE
Zappa doesn't play well with chargebee-python

### ISSUE THREAD

**Issue by FrederikP** [Miserlou/Zappa#766]
## Context
I'd like to use the chargebee client library (https://pypi.python.org/pypi/chargebee/2.2.7) in my zappa app. It doesn't work and I think it's due to them storing their ssl cert in a subfolder of the library.

## Expected Behavior
I want to be able to use the chargebee client lib without getting an error.

## Actual Behavior
An error is thrown:
AttributeError: 'module' object has no attribute 'CERT_NONE'
  File "tmp/pip-build-tjL06K/chargebee/chargebee/models/subscription.py", line 36, in list
  File "tmp/pip-build-tjL06K/chargebee/chargebee/request.py", line 13, in send_list_request
  File "tmp/pip-build-tjL06K/chargebee/chargebee/request.py", line 23, in send
  File "tmp/pip-build-tjL06K/chargebee/chargebee/http_request.py", line 35, in request
  File "tmp/pip-build-tjL06K/chargebee/chargebee/compat.py", line 52, in set_cert

My theory is that the "import ssl" statement in the chargebee library actually picks up its own subfolder ("ssl") which contains the certificate and the __init__.py that Zappa generating while packaging, instead of picking up the standard ssl package.

## Possible Fix
Right now https://github.com/Miserlou/Zappa/blob/master/zappa/zappa.py#L541 creates an __init__.py file if not available in the folder, while going through all folders. If we could only add this file, if there are other python files available, maybe that would fix it.

## Steps to Reproduce
1. create test chargebee account
2. import chargebee library
3. configure chargebee library with api key
4. call any resource using the client

## Your Environment
* Zappa version used: 0.40.0
* Operating System and Python version: ubuntu, python 2.7

**Comment by Miserlou** [comment]
Thanks for this bug report! Maybe you can use `"delete_zip": false` to inspect the package that it produces and compare it to your client package?

**Comment by FrederikP** [comment]
I actually did that and there was an init file in the zip in that subfolder, while there is none in my local venv. On Apr 3, 2017 3:22 PM, Rich Jones <notifications@github.com> wrote:Thanks for this bug report! Maybe you can use "delete_zip": false to inspect the package that it produces and compare it to your client package?

**Comment by FrederikP** [comment]
This is what I get:

```
$ ls /venv/lib/python2.7/site-packages/chargebee/ssl/
ca-certs.crt

$ unzip -l app-dev-1491223335.zip | grep chargebee/ssl
217141  2017-04-03 13:02   chargebee/ssl/ca-certs.crt
0  2017-04-03 14:42   chargebee/ssl/__init__.py
```

**Comment by FrederikP** [comment]
In PR #769 I changed the way how `__init__.py` files are created. They are not created anymore if the folder does not have any subfolders and no python files.
In my case this leads to the expected zip contents:

```
unzip -l app-dev-1491315572.zip | grep chargebee/ssl
217141  1980-01-01 00:00   chargebee/ssl/ca-certs.crt
```

**Comment by Miserlou** [comment]
Merged!
