### ISSUE TITLE
wsgi remote_addr can be user spoofed

### ISSUE THREAD

**Issue by oliviersels** [Miserlou/Zappa#772]
### Summary
The `REMOTE_ADDR` wsgi environment value can be easily spoofed by a user. Zappa takes the first value from the `X-Forwarded-For` header. This should be changed to the second to last one.

https://github.com/Miserlou/Zappa/blob/36ff4941f6ad37276944f16c12e101e461f9767e/zappa/wsgi.py#L71-L73

I will open a pull request with a fix.

### Explanation
AWS adds ips to the back of the existing `X-Forwarded-For` header. The last one is the ip of the cloudfront proxy server while the second to last is the real client ip. Everything before that can be user supplied.

Currently if a client already sends a `X-Forwarded-For` header that value will then be used by Zappa as the remote_addr instead of the client ip.

See http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html for more information

**Comment by aehlke** [comment]
This was merged, so this can now be closed?

**Comment by Miserlou** [comment]
Yep
