### ISSUE TITLE
https connection is not reflected in wsgi environment

### ISSUE THREAD

**Issue by oliviersels** [Miserlou/Zappa#773]
Using zappa with a custom domain and https connection is not reflected in the wsgi environment. The values for `SERVER_PORT` and `wsgi.url_scheme` are still 80 and http. This can be solved by looking at the X-Forwarded-Port and X-Forwarded-Proto header.

https://github.com/Miserlou/Zappa/blob/36ff4941f6ad37276944f16c12e101e461f9767e/zappa/wsgi.py#L84

I will open a pull request with a fix.

See http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html for more information

**Comment by Miserlou** [comment]
Merged and fixed! Thank you!
