### ISSUE TITLE
Hello World - module initialization error: Attempted relative import in non-package

### ISSUE THREAD

**Issue by AlexLast** [Miserlou/Zappa#777]
## Context
First of all let me start by saying I'm really excited about using Zappa and can't wait to get it working!

For some reason however when deploying my Flask application I keep getting the following error when trying to access: 

```
module initialization error: Attempted relative import in non-package
```

It's possible I'm doing something wrong or there's issues with the structure of my code, the current directory layout is:

- myapp > app.py + other classes
- setup.py
- venv
- zappa_settings.json

I activate my virtualenv and pip install awscli, zappa and run ```python setup.py install``` which installs my application, not sure if it matters or not but app.py imports other classes using the full package path e.g ```from myapp.modules.user import User```.

My zappa_settings.json is really simple just specifying the s3 bucket and the detected app function of myapp.app.app.

I've even swapped out my app.py for a Flask hello world example and get the same error, what am I doing wrong?

## Expected Behavior
Flask application should respond successfully. 

## Actual Behavior
Get the above error.

## Your Environment
* Zappa version used: 0.40.0
* Operating System and Python version: Ubuntu 16.04, Python 2.7.12
* Your `zappa_settings.py`: Noted above

**Comment by robertdfrench** [comment]
Hi @AlexLast,

I have also had trouble getting zappa to import app objects from other than top-level packages. Would it make sense for your project if you tried moving `myapp/app.py` to `myapp/__init__.py`? That would allow you to specify your app object in `zappa_settings.json` as `myapp.app`, which may help.

**Comment by Miserlou** [comment]
Sorry for not getting to this sooner, must have missed it.

You don't want to `p setup.py install` into your own virtualenvironment if you're already working in that environment. This is probably the problem.

**Comment by Miserlou** [comment]
Related: https://github.com/Miserlou/Zappa/pull/542

**Comment by AlexLast** [comment]
@Miserlou Thanks, seems to have fixed things 👍
