### ISSUE TITLE
Authorizer: "errorMessage": "'module' object has no attribute 'AUTHORIZER_FUNCTION'"

### ISSUE THREAD

**Issue by creimers** [Miserlou/Zappa#781]
## Context
* **zappa A** - a lambda authorizer created from the official [blueprints](https://github.com/awslabs/aws-apigateway-lambda-authorizer-blueprints/blob/master/blueprints/python/api-gateway-authorizer-python.py), deployed with zappa and the `apigateway_enabled: false` option.

* **zappa B** - a *normal* zappa deployment using flask that specifies **zappa A's** `arn` in the `authorizer` settings.

 

## Expected Behavior

Requests to **zappa B** authorized by **zappa A**.
## Actual Behavior

Requests to **zappa B** return a 500 internal server error.

Output on the test result on the API Gateway Authorizers screen:
<img width="1446" alt="bildschirmfoto 2017-04-07 um 16 29 13" src="https://cloud.githubusercontent.com/assets/6090492/24805333/a68d7c76-1bb1-11e7-8f4a-ee7222c731af.png">

## Your Environment

* Zappa version used:  0.40.0
* Operating System and Python version: Mac OS X 10.11.6

* Your `zappa_settings.py`: 

### zappa A - the authorizer
```
{
    "dev": {
        "app_function": "main.lambda_handler", 
        "s3_bucket": "zappa-dingdong",
        "apigateway_enabled": false,
        "environment_variables": {
             "AUTH_URL": "http://dingdong.elasticbeanstalk.com/token-verify/"
        }
    }
}
```

### zappa B - the *normal* zappa flask app

```
{
    "dev": {
        "app_function": "main.app", 
        "s3_bucket": "zappa-dongding",
        "authorizer": {
          "arn": "arn:aws:lambda:eu-central-1:dingdong:function:lambda-authorize-dev"
        }
    }
}

```

**Comment by bharling** [comment]
Sorry to resurrect this issue but I'm having the exact same problem @creimers would you be able to share how you solved this?
