### ISSUE TITLE
import numpy fails due to python unicode mismatch with aws lambda

### ISSUE THREAD

**Issue by jwkvam** [Miserlou/Zappa#783]
This particular error has been solved. It's recorded here to help others.

## Context
I get an error when importing numpy or see something like
```
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.
```
I then uncomment the line from https://github.com/numpy/numpy/blob/master/numpy/core/__init__.py#L15 and redeploy and I found get the following error.
```
  File "/tmp/zappaserv/numpy/core/__init__.py", line 16, in <module>
  from . import multiarray
ImportError: /tmp/zappaserv/numpy/core/multiarray.so: undefined symbol: PyUnicodeUCS2_AsUTF8String
```
This means the python you are using is using UCS2 unicode but AWS Lambda python expects UCS4 unicode. That means you need to get a python compiled with UCS4 unicode.

For example, I was using python provided by linuxbrew and I reinstalled python by doing:
```
brew reinstall python --with-unicode-ucs4 
```

**Comment by Miserlou** [comment]
AN EXCELLENT REPORT!
