### ISSUE TITLE
Lambda offline support in Zappa?

### ISSUE THREAD

**Issue by kienpham2000** [Miserlou/Zappa#79]
Hey guys,

Awesome project! I want to be able to run and test my Zappa setup locally and simulate AWS Lambda request, how can I do it currently? 

Ex Use Case: lambda function watching for new S3 put object. I can simulate that from AWS UI, but don't know how to do it within Zappa.

Thanks.

**Comment by Miserlou** [comment]
This is an excellent question!

It is probably a non-trivial task, but do able. We will likely need to use other frameworks to make this possible, for instance: https://github.com/fugue/emulambda, and I think there may be other similar initiatives we should investigate.

What would your workflow for something like this look like? What's the syntax/API you'd want?

**Comment by kienpham2000** [comment]
Hi @Miserlou, 

I think be able to transparently run my lambda function locally and get debugging output offline would be best. Now if Zappa have to upload to AWS Lambda and execute it, that's fine, but I would love to be able to debug my Python app offline like a regular app.

**Comment by zeroaltitude** [comment]
Hi @kienpham2000 

I did what you were suggesting simply by designing my entire local project around a lightweight, easily-locally-runnable python framework -- in my own case, Falcon.  By doing this, I run my entire stack locally as a simple WSGI app, and by the magic of Zappa, it runs remotely almost identically.

Did I miss the thrust of your request, or is that what you were looking for?

**Comment by zeroaltitude** [comment]
Editors note: made a comment that didn't really address the original request.  Sorry!
