### ISSUE TITLE
Python 3.6 Support

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/Zappa#793]
<img src="http://i.imgur.com/7drHiqr.gif">

https://aws.amazon.com/releasenotes/5198208415517126

**Comment by jleclanche** [comment]
Is this where the party is? :)

**Comment by Miserlou** [comment]
Yep!

I don't think this will actually be _too_ hard to take care of, I've tried to keep most of the code forward-compatible so far, at least on the Lambda side. Some parts of `cli.py` and `zappa.py` may need small refactors here and there, especially around some of the imports, string casts and hex operators. We'll also have to wait 24 hours for it to actually arrive on AWS, according to that link.

**Comment by ryansb** [comment]
It's been available in us-east-2 all day, so it depends on your region.

**Comment by FlipperPA** [comment]
AWESOMENESS.

**Comment by Miserlou** [comment]
<img width="573" alt="screen shot 2017-04-20 at 12 02 26 pm" src="https://cloud.githubusercontent.com/assets/139987/25240608/43a0d2ba-25c1-11e7-8b29-742569167302.png">

Ohhhhhhhhhh snappppppp

**Comment by fifthecho** [comment]
When this is merged, would there be any issues using [sanic](https://github.com/channelcat/sanic) rather than Flask/Django?

**Comment by Miserlou** [comment]
That's the plan - want to try it? `master` is ready..

**Comment by fifthecho** [comment]
Working on my first Sanic app now. Will test in Zappa Master when the app is working.

**Comment by Miserlou** [comment]
Python3 support has arrived! Try it out in 0.41.0! Please report any bugs you find! Nothing is guaranteed but it **_Works For Me™!_**

@fifthecho - Please explore Sanic integration in a new Issue. Thanks!

**Comment by tomchristie** [comment]
Awesomeness! 👍 
Related: #801 (Now have API Star successfully deployed using Zappa, thanks @Miserlou)
