### ISSUE TITLE
Binary Multipart Uploads Don't Work

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/Zappa#80]
Investigating, I thought we no longer required B64 encoding, but it seems way may, or there is another problem at work.

**Comment by Miserlou** [comment]
File uploads appear to be ballooning up in size across the APIGW:

176372: local app
314044: Zappa app

Investigating..

**Comment by Miserlou** [comment]
I don't know. I suspect it has something to do with byte encodings, but it looks like the file is too big by the time it even makes it through the APIGW, before we even touch it.

**Comment by Miserlou** [comment]
Bugger. This is an API Gateway problem - B64 encoding image uploads is still necessary for the time being: https://forums.aws.amazon.com/thread.jspa?threadID=231371&tstart=0

**Comment by anush0247** [comment]
we have implemented  django admin file widget to upload files in django zappa admin panels. I hope this can help. check out: https://github.com/anush0247/zappa-file-widget

**Comment by Miserlou** [comment]
Woah, that's awesome!

**Comment by Miserlou** [comment]
Related: https://github.com/Miserlou/Zappa/issues/481

**Comment by Miserlou** [comment]
Binary downloads work, could be interesting to revisit binary uploads now.

**Comment by Miserlou** [comment]
Binary uploads work now.

**Comment by JamesQAQ** [comment]
I have deployed my django project to s3 bucket about 3 weeks ago, and find out there is an issue about binary file uploads.
After seeing this issue closed, I updated zappa and tried to update but get the warning below:

`Warning! Couldn't get function treasure-django-dev in us-east-1 - have you deployed yet?`

My command:
`zappa update dev`

My `zappa_settings.json`:
```
{
    "dev": {
        "django_settings": "treasure.settings",
        "s3_bucket": "free-gifts-zappa"
    }
}
```
