### ISSUE TITLE
API Star support

### ISSUE THREAD

**Issue by tomchristie** [Miserlou/Zappa#801]
I've just adding [installation instructions for Zappa to API Star](https://github.com/tomchristie/apistar#serverless-deployments), having got my [first deployment up & running](https://ty9oub8a70.execute-api.us-east-1.amazonaws.com/dev).

API Star is a Python 3 only framework, so figured I'd jump on the latest support and try it out. 👍 

There were a couple of things that I ran into, that are worth mentioning here...

The `ujson` package appeared to not be installed remotely for some reason, despite existing in the virtualenv. Presumably something to do with it being a C package.

```
[1492889820236] Instancing..
[1492889820896] No module named 'ujson': ModuleNotFoundError
Traceback (most recent call last):
  File "/var/task/handler.py", line 514, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 259, in lambda_handler
  handler = cls()
  File "/var/task/handler.py", line 148, in __init__
  self.app_module = importlib.import_module(self.settings.APP_MODULE)
  File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 936, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/var/task/app.py", line 1, in <module>
  from apistar import App, Route
  File "/var/task/apistar/__init__.py", line 8, in <module>
  from apistar.app import App
  File "/var/task/apistar/app.py", line 7, in <module>
  from apistar import commands, pipelines, routing, schema
  File "/var/task/apistar/routing.py", line 11, in <module>
  from apistar import exceptions, http, pipelines, schema, wsgi
  File "/var/task/apistar/http.py", line 10, in <module>
  import ujson as json
ModuleNotFoundError: No module named 'ujson'
```

I've worked around this by making `ujson` an optional dependency of `apistar`, and falling back to `json` when it doesn't exist.

Secondly, API Star has a layout that doesn't quite work with Zappa without a minor tweak. Our wsgi interface is exposed as a property of the application instance (rather than a `__call__` on the app instance itself) this is because we expect to expose various *other* interfaces, rather than only being a WSGI interface.

Not particularly surprising, but `"app_function": "app.app.wsgi"` didn't work correctly.

This isn't a great problem as we can work around by having the user expose the WSGI callable at the top level of the module...

    app = App(...)
    wsgi_app = app.wsgi

Then `"app_function": "app.wsgi_app"` works as expected in the config.

It's worth noting that running under, say gunicorn, the slightly different calling syntax `gunicorn app:app.wsgi` works fine. Perhaps there's something to consider there, perhaps not.

Finally I'd be interested to know if there's anything we could do to include API Star as one of the listed supported options, or to have API Star included in the "automatic detection"?

Thanks so much for the incredible work! ⚡️ ⚡️ ⚡️

**Comment by bcongdon** [comment]
Perhaps `ujson` could be included in [Miserlou/lambda-packages](https://github.com/Miserlou/lambda-packages) if it really is the C extension that's causing an issue

**Comment by Miserlou** [comment]
This! Is! Awesome!

I'd be more than happy to include greater support in Zappa for API Star. There should be two places we can do this, one in the `init` command, and the other is just in the documentation about this.

The tricky part about this is just that, as you mentioned, the user has to modify their application to expose `wsgi_app`, so `init` probably won't work out of the box. Is there _anything_ we can do there on the API Star side, maybe have it so that the naked `app` is smart enough to know when to return the WSGI object if it can spy some Zappa environment variables? Maybe that's asking too much.

Otherwise, then the only other thing is making any changes to the documentation, which I'm more than happy to merge in.

Thanks for taking the initiative on this, I'm really happy to see these working together. API Star seems really snappy on Lambda!

Re `ujson` - we could either make a package for `lambda-packages`, as @bcongdon mentioned, or you could lobby get upstream `ujson` distributed as a manylinux wheel, which I think would probably be preferable at this point.

**Comment by tomchristie** [comment]
> The tricky part about this is just that, as you mentioned, the user has to modify their application to expose wsgi_app, so init probably won't work out of the box. Is there anything we can do there on the API Star side, maybe have it so that the naked app is smart enough to know when to return the WSGI object if it can spy some Zappa environment variables? Maybe that's asking too much.

I guess most likely I'll just introduce a `__call__` on the app instance itself. Once I've done that I'll have a look at making a pull request introducing API Star auto-discovery to Zappa.

I'm not particularly concerned about `ujson` support. Being able to fall back to the system JSON is sufficient for now, and I've got higher priority stuff on my list at the moment, although might come back to it at a future date.
