### ISSUE TITLE
Deploy at Root

### ISSUE THREAD

**Issue by brianjpetersen** [Miserlou/Zappa#805]
Is it possible to deploy at ```/``` as opposed to under a namespace (eg, ```/dev```).  I've tried specifying ```""``` in my ```zappa_settings.json``` without luck.

This is a really amazing library, BTW.  I wouldn't be able to use Lambda without it - thanks!

**Comment by Miserlou** [comment]
You have to use a domain or a subdomain, this is out of our control, it's just how APIGW is.

**Comment by Miserlou** [comment]
Thanks for using Zappa!
