### ISSUE TITLE
Compare last modified with .py vs .pyc when packaging project

### ISSUE THREAD

**Issue by tipu** [Miserlou/Zappa#81]
An optimization currently exists that uses the .pyc instead of the .py if it's available. The problem is that if the .py is newer but not compiled, the old .pyc will continue to be used. Should a .pyc present itself, ensure that the update time of the .pyc exceeds that of the .py file.

**Comment by Miserlou** [comment]
One line needed here: https://github.com/Miserlou/Zappa/blob/master/zappa/zappa.py#L341

**Comment by tipu** [comment]
I have code in place for this. How do I test this? I went into my `env`'s `site-packages` and created a symlink to the `dev` `Zappa/zappa` dir, however I was getting an unusual error,

`An error occurred (InvalidLocationConstraint) when calling the CreateBucket operation: The specified location-constraint is not valid`

In `master` this didn't appear. Any idea how I can test my changes?

**Comment by Miserlou** [comment]
You should have a look at tests/tests.py for writing tests! This one shouldn't be too hard to test, the ones with the @placebo decorator are bit trickier, you just have to read the placebo documentation.

**Comment by Miserlou** [comment]
"The specified location-constraint is not valid" is a weird error that makes me think you've put an invalid aws_region in your settings? I don't think that's related to the packaging code at all.

**Comment by Miserlou** [comment]
If we can get this patched today then I'll can publish the next version

**Comment by tipu** [comment]
Solved with a301aa67
