### ISSUE TITLE
zappa package -o doesn't work

### ISSUE THREAD

**Issue by fantamiracle** [Miserlou/Zappa#814]
Despite instruction, it seems like for some reason --output or -o are not working!

Here is an example:

```
$ zappa package prod -o x.zip
usage: zappa [-h] [-v] [-a APP_FUNCTION] [-s SETTINGS_FILE]
             {certify,deploy,init,package,invoke,manage,rollback,schedule,status,tail,undeploy,unschedule,update}
             ...
zappa: error: unrecognized arguments: -o x.zip
```

I have the last version of zappa (0.35.2). 
I just skimmed through the code and it seems the logic is there, but for some reason it is not working.

**Comment by Miserlou** [comment]
It just got added yesterday, it's in `master` but not the published version yet. :)

**Comment by Miserlou** [comment]
Also the latest version is 41.1, but even that doesn't have `-o`! 

0.42.0 should published fairly soon with the new `lambda-packages` stuff for Python 3.

**Comment by fantamiracle** [comment]
Oh cool... then I will try master then! Thanks!
