### ISSUE TITLE
Zappa CLI Python3 support

### ISSUE THREAD

**Issue by kienpham2000** [Miserlou/Zappa#82]
I'm having this error when running zappa master on Python 3.5.1:
```
env/lib/python3.5/site-packages/zappa/cli.py", line 452
    os.chmod(temp_settings.name, 0644)
SyntaxError: invalid token

```

When I switch back to Python 2.7, no problem.

Also looks like the pypi version (0.17.6) is out of date. Can you please start tagging release?

**Comment by Miserlou** [comment]
Yeah, I think dropping any notion of 3 support is probably the best move. It was a nice idea but it's too difficult to maintain the two in parallel given that Lambda still requires 2.7.

**Comment by kienpham2000** [comment]
cool makes sense, I'll use 2.7.
