### ISSUE TITLE
Repeated get params are stripped off in lambda

### ISSUE THREAD

**Issue by apierleoni** [Miserlou/Zappa#824]
## Context
I am deploying an API with flask in lambda using zappa.
For an endpoint I need to allow the same parameter to be passed one or more time, parsing it as a list with the method `request.params.getlist('myparam')`.

 

## Expected Behavior

It works normally if I run the flask app locally, getting all the passed parameters as a list
## Actual Behavior

When deployed to lambda just the last parameter is passed to the flask app, and the others are stripped off
## Steps to Reproduce

1. expose this function in a flask app
```python
@app.route('/test/url', methods=['GET'])
def test_params():

    return jsonify({'request.args.getlist' :request.args.getlist('field'),
                        'request.query_string' : request.query_string,
                        'request.url' : request.url})
```
2. output in localhost

```
{request.args.getlist: [
"a",
"b"
],
request.query_string: "field=a&field=b",
request.url: "http://localhost:5000/test/url?field=a&field=b"
}
```

3. output in lambda

```
{parsed_params: [
"b"
],
query_string: "field=b",
url: "https://qkorhkwgf1.execute-api.eu-west-1.amazonaws.com/dev/test/url?field=b"
}
```
4. can be tested live [here](https://qkorhkwgf1.execute-api.eu-west-1.amazonaws.com/dev/test/url?field=a&field=b)

## Your Environment

* Zappa version used: zappa-0.41.2
* Operating System and Python version: OS X and python 2.7.13
* Link to your project (optional):
* Your `zappa_settings.py`: 
```
{
  "dev": {
    "app_function": "myapp.app",
    "profile_name": "default",
    "aws_region": "eu-west-1",
    "s3_bucket": "zappa-myapp",
    "cache_cluster_enabled": true,
    "cache_cluster_size": 0.5,
     "binary_support" : true,
    "use_precompiled_packages": true
  }
}
```

**Comment by Miserlou** [comment]
Yeah, this is known. It's an API Gateway problem, it has nothing to do with Zappa. AWS are aware of it, but who knows when it'll be fixed.

**Comment by apierleoni** [comment]
Sounds like a huge problem for an api gateway... Thanks for the info and the hard work on zappa.

**Comment by coco-egaliciar** [comment]
Today this is the status with api gateway
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-known-issues.html

![image](https://user-images.githubusercontent.com/38989410/43876688-ca3a65c8-9b5b-11e8-8f33-6f39cb33f744.png)
 I think this behaviour is correct, Why? if you can create a Object you should create with POST verb no with GET.

**Comment by clarson** [comment]
There is a claim in October that it is now supported, but doesn't appear to work out of the box for me.https://aws.amazon.com/about-aws/whats-new/2018/10/amazon-api-gateway-adds-support-for-multi-parameters/
