### ISSUE TITLE
environment variables not working with Python 3.6.0

### ISSUE THREAD

**Issue by romabysen** [Miserlou/Zappa#826]
The `environment_variables` option does not work with Python 3.6.

If I have the following in my Zappa settings:

```json
    "environment_variables": {
        "MYVARIABLE": "something"
    }
```

it will end up as
```python
    {"b'MYVARIABLE'": "something"}
```

in my app.

Since it works fine with the Python 2.7 runtime it's probably related to the unicode changes in Python 3.

* zappa 0.41.1
* bottle 0.12.13
* Python 3.6.0

**Comment by Miserlou** [comment]
Ah, god dammit. Yep.

Want to send a PR?

**Comment by romabysen** [comment]
Yep, can do. However,I have been looking at #604 which seems to be the cause of this problem and I can't replicate those issues.

Given the following json file:
```json
{
    "TEST_VAR": "x"
}
```

and this python code:
```python
# -*- coding: utf-8 -*-
from __future__ import print_function
import os
import json

d = json.load(open('test.json'))
for key in d.keys():
    os.environ[key] = d[key]
print(os.environ['TEST_VAR'])
print(os.environ.get('TEST_VAR'))
```
It works fine on both 2.7.11 and 3.5.2. I'll do some tests but presumably changing `str(key)` back to `key` should fix it.
Btw, is there an easy way to test this that doesn't involve deploying to Lambda?

**Comment by Miserlou** [comment]
Make sure you test with 3.6, as that's the Lambda version.

Best way to test is just do the whole code path with a mocked response object in the tests file, or you could use Placebo, but I don't think that's necessary for this one.

**Comment by romabysen** [comment]
So I tested this with 0.41.2 and to my surprise the issue is not there.

**Comment by Miserlou** [comment]
Closing, seems fixed.

**Comment by strahius** [comment]
Issue wtill happens in 0.45.1.
