### ISSUE TITLE
How to deploy lambda function without creating API Gateway endpoint?

### ISSUE THREAD

**Issue by kienpham2000** [Miserlou/Zappa#83]
I don't always need the API Gateway endpoint. One of my lambda function is to watching for changes happening in S3 bucket. How can I disable Gateway endpoint creation when I do: zappa deploy dev?

**Comment by Miserlou** [comment]
Related to this: https://github.com/Miserlou/Zappa/issues/61

**Comment by Miserlou** [comment]
Closing as duplicate in fact
