### ISSUE TITLE
Binary support preventing django uploads

### ISSUE THREAD

**Issue by bxm156** [Miserlou/Zappa#836]
## Context
I just upgraded to zappa 0.41.2 from 0.39.0, and I am no longer able to upload images in django.
The follow traceback appears in the POST:
```
"{u'message': u'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.', u'traceback': ['Traceback (most recent call last):\\n', '  File \"/var/task/handler.py\", line 448, in handler\\n    binary_support=settings.BINARY_SUPPORT\\n', '  File \"/tmp/pip-build-5i1jVL/zappa/zappa/wsgi.py\", line 64, in create_wsgi_request\\n', \"UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte\\n\"]}"
```
```
Traceback (most recent call last):
File "/var/task/handler.py", line 448, in handler
  binary_support=settings.BINARY_SUPPORT
File "/tmp/pip-build-5i1jVL/zappa/zappa/wsgi.py", line 64, in create_wsgi_request, 
"UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte"

```

I tried turning binary_support to false, which then revealed the error message.
```
Error while generating thumbnail: cannot identify image file <StringIO.StringIO instance at 0x7f46590e77a0>
```

Is there any more information I can provide that would be helpful in diagnosing this?

## Your Environment

* Zappa version used: 0.41.2
* Django :1.9.X
* Operating System and Python version: py2.7

**Comment by bxm156** [comment]
I realized that my Pillow version was not 3.4.2, which is the version on lambda packages, so I set requirements.txt to Pillow==3.4.2 and updated my env, but still saw the issue.

My lambda-packages is at 0.15.0. 

I tried downgrading down to zappa 0.39.0 and lambda-packages 0.14.2, but still encountered the issue. 

I looked at a copy of a working lambda package, and discovered it had Pillow 3.1.0 from manylinux installed, so  I tried switching to that, but it still didn't work. :/ 

I noticed in the WHEEL file in the packages, it referenced manylinux. Does that mean its not using lambda-packages's version?

**Comment by bxm156** [comment]
I added some debug print statements to the core.py. And discovered why Pillow 4.1.1 is getting installed:

```
Calling update for environment dev..
Downloading and installing dependencies..
Installing lxml from lambda-packages
Installing psycopg2 from lambda-packages
Installing Pillow from lambda-packages
pyterminalsize from manylinux
Installing pillow from manylinux
Packaging project as zip..
```

Looks like we are installing Pillow from lambda packages, then it gets installed from manylinux again.

**Comment by bxm156** [comment]
I think the Pillow issue might be somewhat of  red herring.  I opened a separate ticket for it.
https://github.com/Miserlou/Zappa/issues/841

**Comment by bxm156** [comment]
Example header for the requests the fail:

```
:method:POST
:path:/admin/filer/clipboard/operations/upload/1/?qqfile=13835918_10153856054586317_430246434_o.jpg
:scheme:https
accept:*/*
accept-encoding:gzip, deflate, br
accept-language:en-US,en;q=0.8
cache-control:no-cache
content-length:199634
content-type:application/octet-stream
x-file-name:13835918_10153856054586317_430246434_o.jpg
x-requested-with:XMLHttpRequest
```

**Comment by bxm156** [comment]
I was able to fix this by:

1. Enabling Binary Support
2. Commenting out the following lines in wsgi.py

if body and isinstance(body, six.string_types):
     body = body.encode("utf-8")


When my image post request happens
Note. the upload is in indeed isBase64Encoded. So the data gets decoded. Vut then this "encode" function messes things up I guess.

i will continue to investigate more

**Comment by bxm156** [comment]
Based on https://github.com/oliviersels/Zappa/commit/fb40baa0144695fec5cc326705541c26714d13df...

I believe the zappa code is incorrectly encoding data as utf8 for all str(), when it should only
be doing so for when binary support is enabled but the data is not base 64 (as per the above commit).

**Comment by Miserlou** [comment]
Fixed via PR.
