### ISSUE TITLE
Zappa installs two versions of pillow

### ISSUE THREAD

**Issue by bxm156** [Miserlou/Zappa#841]
## Context
Despite having Pillow==3.4.2 in my env. Zappa installs version 4.1.1 from manylinux. I added debug statements durning the package install process and discovered:
```
Calling update for environment dev..
Downloading and installing dependencies..
Installing lxml from lambda-packages
Installing psycopg2 from lambda-packages
Installing Pillow from lambda-packages
pyterminalsize from manylinux
Installing pillow from manylinux
Packaging project as zip..
```
I checked the package.zip, and sure enough PIL/__init__.py was version 4.1.1. It looks like zappa doesn't consider 'Pillow' and 'pillow' to be the same package, so it is re-installed in the manylinux step, and its instal, and overwrites the previous version.

After some more investigation in core.py, I realized the check for packages to install via manylinux might be invalid.  It checks to see if the name of the package to be installed is in lambda_packages, but the case is wrong.

## Expected Behavior
I would expect zappa not to even consider needing to download 'pillow' as a pre-compiled package, since its not in my virtualenv

## Your Environment
* Zappa version used: 0.42.2
* Operating System and Python version: py2.7

**Comment by bxm156** [comment]
I tried the following fix, which fixed the duplicate package install issue for me:

https://github.com/bxm156/Zappa/commit/aa09e68ae75f12bf135957c28388374069de0a09

**Comment by nikbora** [comment]
Hey @bxm156, I believe this is related to the fact that Zappa is ignoring version numbers of packages when looking at both lambda-packages and wheels. I have a PR for it here, do you mind checking out my branch of Zappa to see if this fixes your issue here? (i.e. correct pillow is downloaded). Maybe can kill multiple issues with one PR.

https://github.com/Miserlou/Zappa/pull/843

**Comment by bxm156** [comment]
Closed by https://github.com/Miserlou/Zappa/pull/843
