### ISSUE TITLE
AWS X-Ray Integration?

### ISSUE THREAD

**Issue by nueverest** [Miserlou/Zappa#842]
## Feature Request

Integrate support for AWS XRay. https://aws.amazon.com/xray/

> AWS X-Ray helps developers analyze and debug production, distributed applications, such as those built using a microservices architecture. With X-Ray, you can understand how your application and its underlying services are performing to identify and troubleshoot the root cause of performance issues and errors. X-Ray provides an end-to-end view of requests as they travel through your application, and shows a map of your application’s underlying components. You can use X-Ray to analyze both applications in development and in production, from simple three-tier applications to complex microservices applications consisting of thousands of services.

**Comment by mathom** [comment]
I have a barebones wrapper started for python here: https://github.com/mathom/xrayvision

Xray has official support for other languages, just not python yet. The way it works requires a bunch of monkey patching for libraries (I've just done WSGI and requests for now) so it's a work in process.

**Comment by nueverest** [comment]
I see.

**Comment by mathom** [comment]
I'd love to accept contributions for your favorite library. I'm mostly running this project as a stopgap solution until AWS comes out with their own official python library (they have one for node and java already).

**Comment by kapilt** [comment]
another implentation for py https://github.com/racker/fleece/blob/master/fleece/xray.py

**Comment by Miserlou** [comment]
Would love to have this be part of Zappa but I think `xrayvision` is the best bet until there's official Python support.

**Comment by geeknam** [comment]
Update: AWS released python SDK for X-Ray: http://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-python.html

**Comment by mathom** [comment]
I have this working with Zappa in https://github.com/Miserlou/Zappa/pull/1056 if you want to try it out
