### ISSUE TITLE
ImportError: No module named six.moves.http_client

### ISSUE THREAD

**Issue by jonathanglima** [Miserlou/Zappa#845]
I'm migrating a Django application from EC2 to Lambda and I'm configuring it to run with Zappa.

This application uses elasticsearch and I got the error below. All my packages are up to date and I'm running a python 2.7 venv using virtualenvwrapper.

I reached  kennethreitz/requests#3985 and even with a full package update, I still had the error.

I also added "delete_local_zip" to my zappa_settings so I could take a look inside the generated zip and check if the file isn't really there. I wasn't.

> [1494523900501] No module named six.moves.http_client: ImportError
> Traceback (most recent call last):
>   File "/var/task/handler.py", line 514, in lambda_handler
>   return LambdaHandler.lambda_handler(event, context)
>   File "/var/task/handler.py", line 259, in lambda_handler
>   handler = cls()
>   File "/var/task/handler.py", line 162, in __init__
>   wsgi_app_function = get_django_wsgi(self.settings.DJANGO_SETTINGS)
>   File "/var/task/django_zappa_app.py", line 20, in get_django_wsgi
>   return get_wsgi_application()
>   File "/private/var/folders/vv/9gq0jj317ql4dsjhr532k2z40000gq/T/pip-build-erQj35/Django/django/core/wsgi.py", line 13, in get_wsgi_application
>   File "/private/var/folders/vv/9gq0jj317ql4dsjhr532k2z40000gq/T/pip-build-erQj35/Django/django/__init__.py", line 27, in setup
>   File "/private/var/folders/vv/9gq0jj317ql4dsjhr532k2z40000gq/T/pip-build-erQj35/Django/django/apps/registry.py", line 116, in populate
>   File "/private/var/folders/vv/9gq0jj317ql4dsjhr532k2z40000gq/T/pip-build-erQj35/Django/django/contrib/admin/apps.py", line 23, in ready
>   File "/private/var/folders/vv/9gq0jj317ql4dsjhr532k2z40000gq/T/pip-build-erQj35/Django/django/contrib/admin/__init__.py", line 26, in autodiscover
>   File "/private/var/folders/vv/9gq0jj317ql4dsjhr532k2z40000gq/T/pip-build-erQj35/Django/django/utils/module_loading.py", line 50, in autodiscover_modules
>   File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
>   __import__(name)
>   File "/Users/jonathan/Projects/my_custom_project/just_a_module/admin.py", line 1, in <module>
>   File "/var/task/elasticsearch/__init__.py", line 17, in <module>
>   from .client import Elasticsearch
>   File "/var/task/elasticsearch/client/__init__.py", line 4, in <module>
>   from ..transport import Transport
>   File "/var/task/elasticsearch/transport.py", line 4, in <module>
>   from .connection import Urllib3HttpConnection
>   File "/var/task/elasticsearch/connection/__init__.py", line 3, in <module>
>   from .http_urllib3 import Urllib3HttpConnection
>   File "/var/task/elasticsearch/connection/http_urllib3.py", line 2, in <module>
>   import urllib3
>   File "/var/task/urllib3/__init__.py", line 8, in <module>
>   from .connectionpool import (
>   File "/var/task/urllib3/connectionpool.py", line 11, in <module>
>   from .exceptions import (
>   File "/var/task/urllib3/exceptions.py", line 2, in <module>
>   from .packages.six.moves.http_client import (
> ImportError: No module named six.moves.http_client

## Expected Behavior
The folder packages and the file six should exist.

## Actual Behavior
They don't

## Possible Fix
The error went away when I added "slim_handler": true. Maybe it's something specific when It's trying to save space? But I dunno what could be the possible fix, all I got is this hint.

## Steps to Reproduce
Not sure. It's a proprietary solution, so I'm not able to give the source. But could be something like that:
1. Create a django project
2. Add elasticsearch support
3.  Deploy

## Your Environment
* Zappa version used: 0.41.2
* Operating System and Python version: macOS Sierra, python 2.7
* `zappa_settings.py`: 

> {
>     "production": {
>         "aws_region": "us-east-1",
>         "django_settings": "custom_project.envs.production",
>         "profile_name": "profile2",
>         "s3_bucket": "custom_project",
>         "remote_env": "s3://production.json",
>         "delete_local_zip": false,
>         "slim_handler": true,
>     }
> }

**Comment by jakul** [comment]
This was fixed in https://github.com/jakul/Zappa/commit/6cde3fbeb06fab4e8fbfef8bdd0ce74f894e269e. This issue can be closed.
