### ISSUE TITLE
How to deploy Hug app?

### ISSUE THREAD

**Issue by nealmcb** [Miserlou/Zappa#846]
## Context
Now that Python 3 is supported (congrats!), how might we use Zappa to deploy apps that provide RESTful services via [Hug](https://github.com/timothycrosley/hug) rather than Flask or Django?

**Comment by marcinzaremba** [comment]
Zappa supports WSGI apps. According to documentation of a framework of your choice it exposes [WSGI app](https://github.com/timothycrosley/hug#running-hug-with-other-wsgi-based-servers) (callable).
It's a matter of pointing this app in your zappa_settings.{json,yaml}:
`app_function: 'your_module.__hug_wsgi__'`.
Everything said here is valid under assumption that what `__hug_wsgi__` is really WSGI compatible callable. If not you have to wrap it in some other function, eg.:
```
def zappa_app(app, environ):
    wsgi_app = your_module.__hug_wsgi__
    # Do necessary steps to comply with the standard
    # ...
    return wsgi_app(app, environ)
```
and point that in your `zappa_settings.{json,yaml}`.

**Comment by Miserlou** [comment]
Thanks @marcinzaremba 

Related:

https://github.com/Miserlou/Zappa/issues/798
https://github.com/Miserlou/Zappa/issues/801

**Comment by nealmcb** [comment]
Thanks - simply telling `zappa init` that the `modular path  to your app's function` is `<my_module>.__hug_wsgi__` works like a charm!
