### ISSUE TITLE
Prebuild script not working

### ISSUE THREAD

**Issue by carhartl** [Miserlou/Zappa#87]
When specifying a prebuild script like so:

```json
{
    "dev": {
        ...
        "prebuild_script": "foo.prebuild_me"
    }
}
```

I'm getting this error, when running `zappa update dev`:

> No module named foo

There is a `foo.py` within the project root. I've no experience with it, is it because `importlib.import_module(prebuild_module_s)` is looking in the wrong place?

**Comment by Miserlou** [comment]
Fixed by replacing importlib with 'imp'. Thanks for reporting.

**Comment by carhartl** [comment]
With that, now whatever I put in, getting `[Errno 2] No such file or directory`...

**Comment by Miserlou** [comment]
With the code in -master? Works for me.

I'm assuming that you have a file called 'foo.py' with the a function called 'prebuild_me'?

**Comment by carhartl** [comment]
Yeah, I installed zappa via `pip install https://github.com/Miserlou/Zappa/zipball/master`

Let me try that again, maybe I overlooked something. File layout:

```
├── app.py
├── prebuild.py
├── static
│   ├── css
│   └── js
├── templates
│   └── app.html
```

zappa_settings.json:
```json
{
    "dev": {
        "app_function": "app.app",
        ...
        "prebuild_script": "prebuild.upload_assets"
    }
}
```
Not sure that's the proper layout...

**Comment by Miserlou** [comment]
Yeah, that looks right. Hm. I tried the exact same thing and it works fine now. Can you post the full error?

**Comment by carhartl** [comment]
👍

**Comment by carhartl** [comment]
Retried, that was a different error...

**Comment by carhartl** [comment]
Thanks!

**Comment by Miserlou** [comment]
Great! Thanks for reporting this.
