### ISSUE TITLE
"domain" in the zappa_setting.json doesn't do anything?

### ISSUE THREAD

**Issue by kienpham2000** [Miserlou/Zappa#88]
I set the "domain" in the setting file and it doesn't seem to do anything. I have to create custom domain manually from API Gateway. I thought the "domain" setting was creating the custom domain for me?

**Comment by Miserlou** [comment]
Ah, no, that's just to be able to give domain-awareness to your app (ex in Django), it won't create the domain for you because you have to set that up in your DNS server, as well as supply your SSL information. More info: https://github.com/Miserlou/Zappa/blob/master/docs/domain_with_free_ssl.md
