### ISSUE TITLE
Does Zappa support Event Sources?

### ISSUE THREAD

**Issue by kienpham2000** [Miserlou/Zappa#89]
I would like to trigger my function when an object is put on S3 bucket. I don't see such setting from Zappa in the doc? Can you show me how I can do it? Thanks.

**Comment by Miserlou** [comment]
Not yet! That is what I'm literally working on right now! :D :D :D

It does work for time-based event sources: https://github.com/Miserlou/Zappa#scheduling (in master), but not yet for AWS event sources.

**Comment by Miserlou** [comment]
There are two parts to this, one is to use CloudWatch Events for anything that uses the AWS API, the other is specific to S3, because it uses its own notification system for events. This is annoying.

**Comment by kienpham2000** [comment]
awesome, I'll manually add Event Source for now and play with it.

**Comment by kienpham2000** [comment]
@Miserlou I just test added an S3 event source manually to a deployed zappa function (using Flask), I see it triggered something from the `zappa tail dev`

`[1461119631] [INFO]	2016-05-12T19:25:19.631Z	42fa668a-1877-11e6-9ec1-975469d3	172.89.7.15 - - [12/May/2016:19:25:19 +0000] "GET / HTTP/1.1" 200 5 "https://us-west-2.console.aws.amazon.com/apigateway/home?region=us-west-2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36" 0/426.108
`

Does it mean I have to implement a regular function and can't use Zappa yet for this?
`def lambda_handler(event, context):`

**Comment by Miserlou** [comment]
Ah, yeah, so we need to define the code path for those type of events, which aren't implemented yet https://github.com/Miserlou/Zappa/blob/master/zappa/handler.py#L68

**Comment by kienpham2000** [comment]
@Miserlou I see, are you cool if I tackle something like: zappa build where it just help me create a local .zip file? I plan to write the `def lambda_handler(event, context):` and use zappa build to upload the zip file manually for now.

**Comment by kienpham2000** [comment]
I was able to use the current version of Zappa now to watch for S3 event. 

What I did is to deploy `zappa deploy dev` like normal and just change the Handler from `handler.lambda_handler` to `my_package.lambda_handler` and got the event fine.

**Comment by Miserlou** [comment]
Ah, okay, good. That'll work in the interim.

**Comment by kienpham2000** [comment]
Fixed via: https://github.com/Miserlou/Zappa/pull/142
