### ISSUE TITLE
Zappa package command spends lots of time downloading manylinux wheel metadata from Pypi

### ISSUE THREAD

**Issue by suriya** [Miserlou/Zappa#899]
The `zappa package` command is slower than ideal. One reason is that Zappa checks whether a package has a manylinux wheel by downloading the package's Python metadata from PyPI. When a project's virtualenv has a lot of packages, this can consume a lot of time.

## Possible Fix
It would be good to cache the metadata files and reuse them in the next invocation.

## Steps to Reproduce
Have a lot of packages in your virtual environment and run `zappa package`

**Comment by Miserlou** [comment]
Fixed via merge, thank you.
