### ISSUE TITLE
Zappa_flask-ask (Alexa skill) internal server error

### ISSUE THREAD

**Issue by Telecast101** [Miserlou/Zappa#904]
Zappa returns "Internal server error" after setting up an Alexa skill (works with ngrok)

## Context
I tried to load up an Alexa skill to a server by using Zappa and flask-ask. The Alexa skill works with ngrok. After installing Zappa by using this [guide](https://developer.amazon.com/de/blogs/post/8e8ad73a-99e9-4c0f-a7b3-60f92287b0bf/new-alexa-tutorial-deploy-flask-ask-skills-to-aws-lambda-with-zappa) from John Wheeler, everything works but if I enter the deploy-link to the browser it says "{"message": "Internal server error"}".

**Comment by rschmidtz** [comment]
Hello, I have the exact problem, this is the output that I get from AWS API Gateway

`"{u'message': u'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.', u'traceback': ['Traceback (most recent call last):\\n', '  File \"/var/task/handler.py\", line 433, in handler\\n    response = Response.from_app(self.wsgi_app, environ)\\n', '  File \"/tmp/pip-build-jW5QZX/Werkzeug/werkzeug/wrappers.py\", line 903, in from_app\\n', '  File \"/tmp/pip-build-jW5QZX/Werkzeug/werkzeug/wrappers.py\", line 57, in _run_wsgi_app\\n', '  File \"/tmp/pip-build-jW5QZX/Werkzeug/werkzeug/test.py\", line 884, in run_wsgi_app\\n', \"TypeError: 'NoneType' object is not callable\\n\"]}"`

My Alexa skill works locally with ngrok

Here is my zappa_settings.json

`{
    "dev": {
        "app_function": "skill.app", 
        "profile_name": "default", 
        "s3_bucket": "zappa-AAABBSSc"
    }
`
