### ISSUE TITLE
Running the lambda function in two different aws regions

### ISSUE THREAD

**Issue by eddwardo** [Miserlou/Zappa#908]
## Context
When trying to deploy apps to two different aws regions I am getting this error message:
```
InvalidParameterValueException: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: Error occurred while GetObject. S3 Error Code: AuthorizationHeaderMalformed. S3 Error Message: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'
```

I'd expect to be able to deploy to multiple aws regions with single zappa configuration, but It seems that I am getting it wrong. I google for the solution but I couldn't fine one.

 

## Expected Behavior
Deployment to 2 different locations.

## Actual Behavior
Getting error message, `InvalidParameterValueException: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: Error occurred while GetObject. S3 Error Code: AuthorizationHeaderMalformed. S3 Error Message: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'`

## Possible Fix
Dunno.

## Steps to Reproduce

1. `zappa deploy qa`
2. `zappa deploy prod`

## Your Environment

* Zappa version used: 0.42.0
* Operating System and Python version: Mac OS 
* The output of `pip freeze`:
```
appdirs==1.4.3
argcomplete==1.8.2
base58==0.2.4
boto3==1.4.4
botocore==1.5.40
certifi==2017.4.17
chardet==3.0.3
click==6.7
docutils==0.13.1
durationpy==0.4
Flask==0.11.1
future==0.16.0
futures==3.1.1
hjson==2.0.2
idna==2.5
itsdangerous==0.24
Jinja2==2.9.6
jmespath==0.9.2
kappa==0.6.0
lambda-packages==0.15.0
MarkupSafe==1.0
packaging==16.8
placebo==0.8.1
pyparsing==2.2.0
python-dateutil==2.6.0
python-slugify==1.2.4
PyYAML==3.12
requests==2.17.3
s3transfer==0.1.10
six==1.10.0
toml==0.9.2
tqdm==4.11.2
troposphere==1.9.3
Unidecode==0.4.20
urllib3==1.21.1
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.42.0
```
* Link to your project (optional):
* Your `zappa_settings.py`: 
```
{
    "qa": {
        "profile_name": "beta",
        "aws_region": "eu-west-1",
        "app_function": "project.app.app",
        "debug": true,
        "log_level": "DEBUG",
        "http_methods": ["GET"],
        "parameter_depth": 1,
        "timeout_seconds": 300,
        "memory_size": 128,
        "use_precompiled_packages": true,
        "exclude": [".tox", ".git"],
        "s3_bucket": "project-qa",
        "events": [{
          "function": "project.app.pull_maintenance_status",
          "expression": "rate(1 minute)"
        }]
    },
    "main": {
        "profile_name": "prod",
        "aws_region": "us-east-1",
        "app_function": "project.app.app",
        "http_methods": ["GET"],
        "parameter_depth": 1,
        "timeout_seconds": 300,
        "memory_size": 128,
        "use_precompiled_packages": true,
        "exclude": [".tox", ".git"],
        "s3_bucket": "prject-prod",
        "events": [{
          "function": "project.app.pull_maintenance_status",
          "expression": "rate(1 minute)"
        }]
    }
}
```

**Comment by danodonovan** [comment]
Changing the name of the bucket to be unique accross AWS should fix this issue - I guess `prject-prod` and `project-qa` are already taken in the US.

**Comment by eddwardo** [comment]
it was last year and I don't have to project to verify.
Closing.
