### ISSUE TITLE
Python interpreter version is not checked

### ISSUE THREAD

**Issue by marcoesposito1988** [Miserlou/Zappa#911]
## Context

 
Zappa only supports Python 2.7 and 3.6, as stated in the documentation. However, using it with another version of Python succeeds without error, only to result in a cryptic error when the handler runs and tries to load an incompatible native library.

This is very error prone since some distros (Ubuntu *cough*) ship with Python 3.5. Inserting a meaningful error message could be helpful for new users.

## Expected Behavior

Running Zappa with e.g. Python 3.5 should fail with a helpful error message.

## Actual Behavior

Zappa creates a package and uploads it. The lambda function execution fails with a cryptic OSError because a native DLL could not be loaded.

## Possible Fix

Inserting a check in e.g. `__init__.py` throwing an error if the current Python interpreter version is not supported.

## Steps to Reproduce

1. Create a Python3.5 virtualenv and install Zappa
2. Upload a trivial application making use of a native library
3. Profit (NOT!)

## Your Environment

* Zappa version used: 34bc7a8 
* Operating System and Python version: Kubuntu 17.04, Python 3.5-3.6

**Comment by Miserlou** [comment]
Fixed via PR, thank you!

**Comment by mjschultz** [comment]
I understand wanting this, but it's a bit annoying that I now have to install a different version of python from what my host os provides to even use the command line app.

It seems like a flag to not raise the RuntimeError would suffice (or drop it to a RuntimeWarning) would be better? E.g., "hey you're not using a lambda supported python so your code might not work as expected once deployed"
