### ISSUE TITLE
aws-region not working

### ISSUE THREAD

**Issue by andytwoods** [Miserlou/Zappa#917]
I can only deploy to Singapore (ap-southeast-1) when I used the awscli package and specify my default location as ap-southeast-1. I dont think 'aws-region' within my zapp-settings.json works I am afraid.
Cheers,
Andy.
```
    "dev": {
        "django_settings": "aci_data_backup.settings",
        "profile_name": "default",
        "s3_bucket": "zappa-aci-data-backup",
        "aws-region": "ap-southeast-1"
    }
```

**Comment by Miserlou** [comment]
Use `_`, not `-`.

**Comment by andytwoods** [comment]
May I ask, is there an error reported when I've a config setting wrong? Didn't spot one, but sort of thing I wouldn't see!  Thanks, Andy.
