### ISSUE TITLE
zappa may truncate virtualenv name in .python-version

### ISSUE THREAD

**Issue by knowsuchagency** [Miserlou/Zappa#921]
## Issue

If the .python-version file that pyenv uses doesn't end in a newline, then the last letter in the
virtualenv is truncated and zappa won't be able to correctly instantiate.

 

## Expected Behavior

If .python-version only contains

    venv_name

without a newline, the env_name in get_current_env() should be venv_name

## Actual Behavior

Instead, `env_name == 'venv_nam'`

## Possible Fix

```python3
env_name = f.read()[:-1]
# could be replaced with
env_name = f.readline().strip()
```

## Steps to Reproduce

1. create a .python-version file at the root of your project that doesn't end in a newline
2. run `zappa package` or `zappa deploy`

## Your Environment

* Zappa version used: 0.42
* Operating System and Python version: MacOS Sierra Python 3.6.1

**Comment by Miserlou** [comment]
great bug, but I'm not a pyenv user, want to PR?

From my phone..

**Comment by Miserlou** [comment]
also your pun game is on point

From my phone..

**Comment by knowsuchagency** [comment]
Haha thanks I went ahead and [just now submitted it](https://github.com/Miserlou/Zappa/pull/922)
