### ISSUE TITLE
'No space left on device' when using slim_handler=True

### ISSUE THREAD

**Issue by bharling** [Miserlou/Zappa#924]
When trying to upload a  fairly large project using slim_handler, it all seems to work, but when calling the API gateway I get `NoneType object is not callable`. In zappa tail I'm seeing `OSError: [Errno 28] No space left on device` during what looks like the package deploy phase.

## Context
Deployed a large-ish application ( 160mb ) using python-3.6 and slim_handler=true

## Expected Behavior
The app should work

## Actual Behavior
API gateway returns
```"{'message': 'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.', 'traceback': ['Traceback (most recent call last):\\n', '  File \"/var/task/handler.py\", line 427, in handler\\n    response = Response.from_app(self.wsgi_app, environ)\\n', '  File \"/var/task/werkzeug/wrappers.py\", line 903, in from_app\\n    return cls(*_run_wsgi_app(app, environ, buffered))\\n', '  File \"/var/task/werkzeug/test.py\", line 884, in run_wsgi_app\\n    app_rv = app(environ, start_response)\\n', \"TypeError: 'NoneType' object is not callable\\n\"]}"```

## Possible Fix
The underlying cause seems to be that the package cannot be extracted from the zip file during deployment:

```[1497023292878] [DEBUG] 2017-06-09T15:48:12.860Z 08987163-4d2b-11e7-8a47-eb73e2a439c7 Executing task IORenameFileTask(transfer_id=0, {'final_filename': '/tmp/crowdcomms_current_project.zip'}) with kwargs
{'fileobj': <s3transfer.utils.DeferredOpenFile object at 0x7f3bc6b87128>, 'final_filename': '/tmp/crowdcomms_current_project.zip', 'osutil': <s3transfer.utils.OSUtils object at 0x7f3bc6b4b4e0>}
[1497023292878] [DEBUG] 2017-06-09T15:48:12.860Z 08987163-4d2b-11e7-8a47-eb73e2a439c7 Releasing acquire 0/None
[1497023314039] [Errno 28] No space left on device: OSError
Traceback (most recent call last):
  File "/var/task/handler.py", line 484, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 240, in lambda_handler
  handler = cls()
  File "/var/task/handler.py", line 102, in __init__
  self.load_remote_project_zip(project_zip_path)
  File "/var/task/handler.py", line 169, in load_remote_project_zip
  z.extractall(path=project_folder)
  File "/var/lang/lib/python3.6/zipfile.py", line 1491, in extractall
  self.extract(zipinfo, path, pwd)
  File "/var/lang/lib/python3.6/zipfile.py", line 1479, in extract
  return self._extract_member(member, path, pwd)
  File "/var/lang/lib/python3.6/zipfile.py", line 1543, in _extract_member
  shutil.copyfileobj(source, target)
  File "/var/lang/lib/python3.6/shutil.py", line 82, in copyfileobj
  fdst.write(buf)
OSError: [Errno 28] No space left on device
[1497023328404] [DEBUG] 2017-06-09T15:48:48.404Z 2096b6c4-4d2b-11e7-b31e-7967dfecd85f Zappa Event: {'resource': '/', 'path': '/', 'httpMethod': 'GET', 'headers': {'Accept': 'text/html,application/xhtml+xm
l,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch, br', 'Accept-Language': 'en-US,en;q=0.8', 'CloudFront-Forwarded-Proto': 'https', 'CloudFront-Is-Desktop-Viewer': 'tr
ue', 'CloudFront-Is-Mobile-Viewer': 'false', 'CloudFront-Is-SmartTV-Viewer': 'false', 'CloudFront-Is-Tablet-Viewer': 'false', 'CloudFront-Viewer-Country': 'GB', 'Host': '2w5xnqk1a2.execute-api.eu-west-1.a
mazonaws.com', 'upgrade-insecure-requests': ```

## Steps to Reproduce
Find a large-ish django project with lots of deps, try deploying using zappa.

## Your Environment

**Comment by jwkvam** [comment]
AWS Lambda only has 512 MB of disk space for you to use. How large is your packaged unzipped? I don't know if it's possible to create more by making a ramdisk somehow.

https://docs.aws.amazon.com/lambda/latest/dg/limits.html

**Comment by bharling** [comment]
Sorry for delay in reply, my package unzipped is 358MB, so well below 512MB, not sure what else to try :(

**Comment by jwkvam** [comment]
Perhaps you can post the `pip freeze` from your virtualenv to reproduce? Otherwise I don't know, sorry :(

**Comment by bharling** [comment]
Sure here it is, thanks for taking a look:
`aiohttp==2.0.7
amqp==1.4.9
amqplib==1.0.2
anyjson==0.3.3
apiclient==1.0.3
apipkg==1.4
appdirs==1.4.2
appnope==0.1.0
argcomplete==1.8.2
argh==0.26.2
astroid==1.4.9
async-timeout==1.2.1
Babel==2.3.4
backports-abc==0.5
backports.ssl-match-hostname==3.5.0.1
base58==0.2.4
billiard==3.3.0.23
blinker==1.4
boto==2.47.0
boto3==1.4.4
botocore==1.5.40
brotlipy==0.6.0
CacheControl==0.12.0
celery==3.1.25
certifi==2017.4.17
cffi==1.9.1
chardet==3.0.4
click==6.7
ConfigArgParse==0.11.0
construct==2.8.10
coreapi==2.3.0
coreschema==0.0.4
coverage==4.3.4
cryptography==1.7.2
cssutils==1.0.1
decorator==4.0.11
defusedxml==0.5.0
dj-database-url==0.4.2
dj-static==0.0.6
Django==1.10.7
django-admin-tools==0.8.0
django-allauth==0.30.0
django-auditlog==0.4.1
django-cacheops==3.2.1
django-cors-headers==2.0.2
django-countries==4.0
django-csp==3.3
django-debug-toolbar==1.6
django-debug-toolbar-request-history==0.0.4
django-filter==1.0.1
django-guardian==1.4.6
django-jsonfield==1.0.1
django-modeltranslation==0.12.1
django-pdb==0.5.1
django-polymorphic==1.1
django-redis==4.7.0
django-rest-auth==0.9.0
django-rest-swagger==2.1.2
django-s3-folder-storage==0.5
django-sslify==0.2.7
django-sslserver==0.19
django-storages==1.5.2
django-timezone-field==2.0
django-toolbelt==0.0.1
djangorestframework==3.6.2
djangorestframework-bulk==0.2.1
djangorestframework-csv==2.0.0
docutils==0.13.1
dodgy==0.1.9
drf-cached-instances==0.3.4
drf-nested-routers==0.90.0
durationpy==0.4
easy-thumbnails==2.4.1
ecdsa==0.13
EditorConfig==0.12.1
enum-compat==0.0.2
et-xmlfile==1.0.1
eventlet==0.17.4
execnet==1.4.1
Faker==0.7.7
first==2.0.1
flower==0.9.1
funcy==1.7.5
future==0.16.0
futures==3.1.1
gevent==1.2.2
google-api-python-client==1.6.2
-e git+https://github.com/panalysis/Google2Pandas@0c0f138ab7c6ed1c3c0adae8cba9544a488cbdef#egg=Google2Pandas
graphviz==0.5.2
greenlet==0.4.12
gunicorn==19.6.0
h2==2.6.0
heroku3==3.2.2
HireFire==0.5
hjson==2.0.2
hpack==2.3.0
html2text==2016.9.19
httplib2==0.10.3
hyperframe==4.0.2
idna==2.5
ipython==5.2.2
ipython-genutils==0.1.0
isort==4.2.5
itypes==1.1.0
jdcal==1.3
Jinja2==2.9.6
jmespath==0.9.2
jsbeautifier==1.6.11
JsonForm==0.0.2
jsonschema==2.6.0
JsonSir==0.0.2
kaitaistruct==0.6
kappa==0.6.0
kombu==3.0.37
lambda-packages==0.15.0
lazy-object-proxy==1.2.2
logger==1.4
loremipsum==1.0.5
lxml==3.7.3
Markdown==2.6.8
MarkupSafe==1.0
mccabe==0.6.1
mitmproxy==2.0.0
money==1.3.0
msgpack-python==0.4.8
multidict==2.1.4
ndg-httpsclient==0.4.2
netlib==0.17
newrelic==2.78.0.57
nose==1.3.7
numpy==1.12.1
oauth2client==4.0.0
oauthlib==2.0.1
objgraph==3.1.0
olefile==0.44
opbeat==3.5.2
openapi-codec==1.3.1
openpyxl==2.4.5
packaging==16.8
pandas==0.19.2
passlib==1.7.1
pathtools==0.1.2
pep8-naming==0.4.1
pexpect==4.2.1
pickleshare==0.7.4
Pillow==4.1.0
pip-tools==1.8.0
pipdeptree==0.9.0
placebo==0.8.1
pluggy==0.4.0
prompt-toolkit==1.0.13
prospector==0.12.4
psutil==5.1.3
psycopg2==2.6.2
ptyprocess==0.5.1
pusher==1.6
py==1.4.32
pyasn1==0.2.3
pyasn1-modules==0.0.8
pycodestyle==2.0.0
pycparser==2.17
pycrypto==2.6.1
pydocstyle==1.0.0
pyflakes==1.5.0
Pygments==2.2.0
PyJWT==1.4.2
pylint==1.6.5
pylint-celery==0.3
pylint-common==0.2.2
pylint-django==0.7.2
pylint-flask==0.5
pylint-plugin-utils==0.2.4
pyOpenSSL==16.2.0
pyparsing==2.1.10
pyperclip==1.5.27
PySocks==1.6.6
pystache==0.5.4
pytest==3.0.6
pytest-cov==2.4.0
pytest-cover==3.0.0
pytest-coverage==0.0
pytest-django==3.1.2
pytest-xdist==1.15.0
python-dateutil==2.6.0
Python-EasyConfig==0.1.6
python-http-client==2.2.1
python-jose==1.3.2
python-slugify==1.2.4
python-social-auth==0.3.6
python3-openid==3.1.0
pytz==2016.10
PyYAML==3.12
RanCat==1.0.0
redis==2.10.5
requests==2.17.3
requests-oauthlib==0.8.0
requirements-detector==0.5.2
rest-social-auth==1.1.0
rsa==3.4.2
ruamel.yaml==0.13.14
s3transfer==0.1.10
sendgrid==3.6.3
setoptconf==0.2.0
simplegeneric==0.8.1
simplejson==3.3.1
six==1.10.0
smtpapi==0.3.1
social-auth-app-django==0.1.0
social-auth-core==1.2.0
sortedcontainers==1.5.7
sqlparse==0.2.2
static3==0.7.0
stripe==1.46.0
toml==0.9.2
tornado==4.2
tox==2.6.0
tqdm==4.11.2
traitlets==4.3.2
troposphere==1.9.4
twilio==5.7.0
unicodecsv==0.14.1
Unidecode==0.4.20
uritemplate==3.0.0
urllib3==1.21.1
urwid==1.3.1
vine==1.1.3
virtualenv==15.1.0
vulture==0.14
watchdog==0.8.3
wcwidth==0.1.7
Werkzeug==0.12
wrapt==1.10.8
wsgi-request-logger==0.4.6
yarl==0.10.2
zappa==0.42.0
`

**Comment by jwkvam** [comment]
hmm works for me, but it seems zappa doesn't remove the zipfile so it ends up being close. For example this is what is on /tmp did an `ls -lah` and `du -hd 1` on /tmp
```
[1497370336669] drwx------ 3 sbx_user1076  470 4.0K Jun 13 16:11 .
[1497370336669] drwxr-xr-x  21 root   root 4.0K Jun 13 12:51 ..
[1497370336669] drwxrwxr-x 276 sbx_user1076  470  20K Jun 13 16:12 tmpzappa
[1497370336669] -rw-rw-r-- 1 sbx_user1076  470 121M Jun 13 16:11 tmpzappa_current_project.zip
[1497370336669] 0
[1497370336870] 385M /tmp/tmpzappa
[1497370336870] 505M /tmp
[1497370336886] 0
```

**Comment by bharling** [comment]
aha - this looks like it could be an actual issue then, with our app code I'm sure it would go over 505M quite easily. That said, deleting the zip after extraction won't really help much. I did see a ticket regarding streaming the zip file extraction, that is probably the most likely solution here I guess.

**Comment by bharling** [comment]
Closed this as a dupe of the linked issue
