### ISSUE TITLE
issue with zappa certify rate limits

### ISSUE THREAD

**Issue by anush0247** [Miserlou/Zappa#926]
I ran into below issue, while I am trying to do zappa certify

```

Setting DNS challenge..
Waiting for DNS to propagate..
Deleting DNS challenge..
Error signing certificate: 429 {
  "type": "urn:acme:error:rateLimited",
  "detail": "Error creating new cert :: too many certificates already issued for: ****",
  "status": 429
}
Failed to generate or install certificate! :(

```

I am referring this link [https://letsencrypt.org/docs/rate-limits/](https://letsencrypt.org/docs/rate-limits/) but I could n't understand under which rate limit my error will be categorized

can anyone suggest how to fix this?

**Comment by Miserlou** [comment]
There is a secret flag to keep the keys around if you want to capture them and move them into ACM or manually manage them, but this is a LetsEncrypt issue, not a Zappa issue. Thanks!
