### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by CarlosV89** [Miserlou/Zappa#932]
## `
Collecting zappa
Collecting tqdm==4.14.0 (from zappa)
  Using cached tqdm-4.14.0-py2.py3-none-any.whl
Collecting base58==0.2.4 (from zappa)
  Using cached base58-0.2.4-py3-none-any.whl
Collecting kappa==0.6.0 (from zappa)
Collecting lambda-packages==0.15.1 (from zappa)
Collecting argcomplete==1.8.2 (from zappa)
  Using cached argcomplete-1.8.2-py2.py3-none-any.whl
Collecting Werkzeug==0.12 (from zappa)
  Using cached Werkzeug-0.12-py2.py3-none-any.whl
Collecting troposphere>=1.9.0 (from zappa)
Collecting toml==0.9.2 (from zappa)
Collecting futures==3.1.1 (from zappa)
Collecting botocore==1.5.40 (from zappa)
  Using cached botocore-1.5.40-py2.py3-none-any.whl
Collecting durationpy==0.4 (from zappa)
Requirement already satisfied: future==0.16.0 in /home/carlosv/.virtualenvs/ats-mydynamics/lib/python3.6/site-packages (from zappa)
Requirement already satisfied: docutils>=0.12 in /home/carlosv/.virtualenvs/ats-mydynamics/lib/python3.6/site-packages (from zappa)
Collecting boto3==1.4.4 (from zappa)
  Using cached boto3-1.4.4-py2.py3-none-any.whl
Collecting PyYAML==3.12 (from zappa)
  Using cached PyYAML-3.12.tar.gz
Requirement already satisfied: wheel==0.29.0 in /home/carlosv/.virtualenvs/ats-mydynamics/lib/python3.6/site-packages (from zappa)
Collecting hjson==2.0.7 (from zappa)
Collecting requests>=2.10.0 (from zappa)
  Using cached requests-2.18.1-py2.py3-none-any.whl
Requirement already satisfied: python-dateutil==2.6.0 in /home/carlosv/.virtualenvs/ats-mydynamics/lib/python3.6/site-packages (from zappa)
Requirement already satisfied: six==1.10.0 in /home/carlosv/.virtualenvs/ats-mydynamics/lib/python3.6/site-packages (from zappa)
Requirement already satisfied: jmespath==0.9.3 in /home/carlosv/.virtualenvs/ats-mydynamics/lib/python3.6/site-packages (from zappa)
Collecting python-slugify==1.2.4 (from zappa)
  Using cached python_slugify-1.2.4-py2.py3-none-any.whl
Collecting wsgi-request-logger==0.4.6 (from zappa)
Collecting placebo>=0.8.1 (from kappa==0.6.0->zappa)
Requirement already satisfied: click>=5.1 in /home/carlosv/.virtualenvs/ats-mydynamics/lib/python3.6/site-packages (from kappa==0.6.0->zappa)
Requirement already satisfied: s3transfer<0.2.0,>=0.1.10 in /home/carlosv/.virtualenvs/ats-mydynamics/lib/python3.6/site-packages (from boto3==1.4.4->zappa)
Collecting urllib3<1.22,>=1.21.1 (from requests>=2.10.0->zappa)
  Using cached urllib3-1.21.1-py2.py3-none-any.whl
Collecting idna<2.6,>=2.5 (from requests>=2.10.0->zappa)
  Using cached idna-2.5-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.10.0->zappa)
  Using cached certifi-2017.4.17-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.10.0->zappa)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting Unidecode>=0.04.16 (from python-slugify==1.2.4->zappa)
  Using cached Unidecode-0.04.20-py2.py3-none-any.whl
Building wheels for collected packages: PyYAML
  Running setup.py bdist_wheel for PyYAML ... error
  Complete output from command /home/carlosv/.virtualenvs/ats-mydynamics/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-2728j5_h/PyYAML/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpaeat284fpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/tokens.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/constructor.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/reader.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/representer.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/loader.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/nodes.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/__init__.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/composer.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/scanner.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/serializer.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/parser.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/cyaml.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/error.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/events.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/dumper.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/resolver.py -> build/lib.linux-x86_64-3.6/yaml
  copying lib3/yaml/emitter.py -> build/lib.linux-x86_64-3.6/yaml
  running build_ext
  creating build/temp.linux-x86_64-3.6
  checking if libyaml is compilable
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-mTGOPz/python3.6-3.6.0~b2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/carlosv/.virtualenvs/ats-mydynamics/include/python3.6m -c build/temp.linux-x86_64-3.6/check_libyaml.c -o build/temp.linux-x86_64-3.6/check_libyaml.o
  checking if libyaml is linkable
  x86_64-linux-gnu-gcc -pthread build/temp.linux-x86_64-3.6/check_libyaml.o -lyaml -o build/temp.linux-x86_64-3.6/check_libyaml
  building '_yaml' extension
  creating build/temp.linux-x86_64-3.6/ext
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-mTGOPz/python3.6-3.6.0~b2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/carlosv/.virtualenvs/ats-mydynamics/include/python3.6m -c ext/_yaml.c -o build/temp.linux-x86_64-3.6/ext/_yaml.o
  ext/_yaml.c:4:20: fatal error: Python.h: No such file or directory
   #include "Python.h"
                      ^
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for PyYAML
  Running setup.py clean for PyYAML
Failed to build PyYAML
Installing collected packages: tqdm, base58, placebo, PyYAML, botocore, boto3, kappa, lambda-packages, argcomplete, Werkzeug, troposphere, toml, futures, durationpy, hjson, urllib3, idna, certifi, chardet, requests, Unidecode, python-slugify, wsgi-request-logger, zappa
  Running setup.py install for PyYAML ... error
    Complete output from command /home/carlosv/.virtualenvs/ats-mydynamics/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-2728j5_h/PyYAML/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-64pz_wnf-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/carlosv/.virtualenvs/ats-mydynamics/include/site/python3.6/PyYAML:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/tokens.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/constructor.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/reader.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/representer.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/loader.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/nodes.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/__init__.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/composer.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/scanner.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/serializer.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/parser.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/cyaml.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/error.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/events.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/dumper.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/resolver.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/emitter.py -> build/lib.linux-x86_64-3.6/yaml
    running build_ext
    creating build/temp.linux-x86_64-3.6
    checking if libyaml is compilable
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-mTGOPz/python3.6-3.6.0~b2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/carlosv/.virtualenvs/ats-mydynamics/include/python3.6m -c build/temp.linux-x86_64-3.6/check_libyaml.c -o build/temp.linux-x86_64-3.6/check_libyaml.o
    checking if libyaml is linkable
    x86_64-linux-gnu-gcc -pthread build/temp.linux-x86_64-3.6/check_libyaml.o -lyaml -o build/temp.linux-x86_64-3.6/check_libyaml
    building '_yaml' extension
    creating build/temp.linux-x86_64-3.6/ext
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-mTGOPz/python3.6-3.6.0~b2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/carlosv/.virtualenvs/ats-mydynamics/include/python3.6m -c ext/_yaml.c -o build/temp.linux-x86_64-3.6/ext/_yaml.o
    ext/_yaml.c:4:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
`

Im running python 3.6 on Ubuntu 16.10, trying to install zappa using pip3, but it is throwing me this error
 

## Expected Behavior

Zappa should get installed
## Actual Behavior

Erroring out
## Steps to Reproduce

1. apt-get python3.6
2. install zappa using pip from python3.6
3. yaml error

## Your Environment

* Zappa version used:
* Operating System and Python version: Ubuntu 16.10 Python 3.6
* The output of `pip freeze`: ``` base58==0.2.4
botocore==1.5.68
click==6.7
colorama==0.3.7
docutils==0.13.1
ecdsa==0.13
Flask==0.12.2
future==0.16.0
itsdangerous==0.24
Jinja2==2.9.6
jmespath==0.9.3
MarkupSafe==1.0
placebo==0.8.1
pyasn1==0.2.3
python-dateutil==2.6.0
python-dotenv==0.6.4
rsa==3.4.2
s3transfer==0.1.10
six==1.10.0
tqdm==4.14.0
Werkzeug==0.12.2 ```
* Link to your project (optional):
* Your `zappa_settings.py`:

**Comment by CarlosV89** [comment]
pip install zappa is also failing for me

**Comment by mjschultz** [comment]
You probably need to `apt-get install python3.6-dev`

**Comment by byrro** [comment]
Solved it for me:
`sudo apt-get install python3.6-dev`

**Comment by Miserlou** [comment]
Great
