### ISSUE TITLE
Feature Request - Allow mapping API Gateway context values to HTTP headers

### ISSUE THREAD

**Issue by brianrower** [Miserlou/Zappa#939]
## Context
API Gateway allows mapping api gateway context values to HTTP headers, it seems that some of these values may be exposed in the request.environ, however if converting from a server based application to a lambda based application, using request.environ would require a modification to the app, whereas if zappa had a way to replicate the context to HTTP header mapping, no code changes would need to be made.
More details on api gateway context: http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html

## Possible Fix
I have this implemented here: https://github.com/brianrower/Zappa/tree/feature/context-to-http-header-mapping
Testing and README update still needed, which I can do after discussion.
I've added a new setting to zappa_settings similar to environment variables where you map an HTTP header to it's api gateway context value, at runtime, the headers are mapped from the api gateway context, which is inside the lambda event.

**Comment by brianrower** [comment]
Update now that I've done more investigation: 

- Zappa includes the LAMBDA context in request.environ['lambda.context']
- BUT Zappa does NOT include the API gateway context (which is different)
- The API gateway context is sent to the lambda in event['requestContext']
- The API Gateway context is in the lambda's event['requestContext'], but this is not set in the request.environ like the lambda context is, so there currently is no way to access these values in the wsgi app
- One solution would be to pass the whole event into the wsgi environ, this could be done with a simple 1 liner like this "environ['event'] = event" in handler.py right under "environ['lambda.context'] = context" but that would still require a user switching from API Gateway + a traditional web service to zappa to make a small modifcation to their code
- A more full featured alternative would be the pull request I've submitted which uses zappa_settings to configure HTTP header mappings for the api gateway context, just like you can do in API Gateway if you're mapping to an API gateway to an HTTP request instead of a lambda.

My use case is blocked without being able to get the api gateway context. I'm utilizing AWS cognito to do IAM authentication in the API gateway and I need to get the cognito identity id to know who the user is.
I believe if I check the checkbox in api gateway that says "Invoke with caller credentials" the cognito identity id in the lambda context would get set, BUT that would require me granting all my cognito users the same IAM permissions as my lambda execution role, which would NOT be a good idea.

**Comment by jasonrhaas** [comment]
Thanks for adding this in!  I just wanted to add a user case example in case anyone else was trying to figure this out.

After adding the `context_header_mappings` to your zappa_settings file, the values can be accessed by using the `request.headers` object in Flask.

For example,
If I add this to my **zappa_settings.yml** file:

```
  context_header_mappings:
    user_id: authorizer.user_id
```

In my Flask app, I can how access this header using code like this:

```
from flask import request

@route('/hello')
def hello_world:
   print(request.headers.get('user_id'))
```

**Comment by Miserlou** [comment]
Added this example to documentation, closing ticket as resolved. (Feel free to reopen if this isn't resolved to satisfaction yet.)
