### ISSUE TITLE
Can zappa deploy without an URL suffix after the domain?

### ISSUE THREAD

**Issue by palewire** [Miserlou/Zappa#958]
I am loving my early experiments with Zappa but there's a fundamental question I'm having trouble getting the answer to. Can I create an API gateway on Amazon with zappa that doesn't have "dev" or "production" or anything at all after the root domain? Right now I get something like: ```https://<amazon_url>/<zapp_env_name>```

I'd like to ultimately map my application to a custom domain and I don't want to have to have the two things work the same way with the domain name followed by the active URLs with no env indicator inbetween.

**Comment by Miserlou** [comment]
Custom domains work without the <env_name> suffix, <amazon_url> urls don't.
