### ISSUE TITLE
Disabling `keep_warm` doesn't seem to take effect.

### ISSUE THREAD

**Issue by bradwood** [Miserlou/Zappa#969]
Turning off keep_warm in the settings file does not appear to stick.
## Context
1. Run `zappa deploy` without a `keep_warm` parameter in the settings file.
2. Run `zappa status` to see the status, the following is shown:
```
	Num. Event Rules:     1
	Event Rule Name:      app-dev-zappa-keep-warm-handler.keep_warm_callback
	Event Rule Schedule:  rate(4 minutes)
	Event Rule State:     Enabled
	Event Rule ARN:       arn:aws:events:eu-west-2:241336439024:rule/app-dev-zappa-keep-warm-handler.keep_warm_callback
```
3. add        ` "keep_warm": false, ` to the zappa settings file.
4. run `zappa update`
5. run `zappa status` again.
## Expected Behavior
Keep warm handler Rule state should be "Disabled"
## Actual Behavior
It remains "Enabled"

## Steps to Reproduce
As above

## Your Environment
MacOS 
Zappa version 0.42.2

* My `zappa_settings.json`: 
```
{
    "dev": {
        "domain": "dev.xxxxx.com",
        "keep_warm": false,
        "lets_encrypt_key": "s3://searchlight-letsencrypt/private_key",
        "lets_encrypt_expression": "rate(15 days)", // LE Renew schedule
        "route53_enabled": true
        "timeout_seconds": 60, // needed for lets-encrypt/DNS..
        "app_function": "xxxxx-gateway.app",
        "aws_region": "eu-west-2",
        "profile_name": "default",
        "s3_bucket": "zappa-xxxxxx",
        "log_level": "DEBUG",
        "delete_local_zip": false, // for debug purposes
        "cors": true,
        "apigateway_description": "xxxxxx Dev Environment"
    }
}

```

**Comment by Miserlou** [comment]
Once an event is schedule, you will have to call `unschedule`.
