### ISSUE TITLE
Rule name truncation causing collisions for long lambda names

### ISSUE THREAD

**Issue by mdodsworth** [Miserlou/Zappa#970]
We have lengthy lambda names that reflect a service's name, deployed environment, and stage. For example: `<service name>-<env>-<stage>`

The truncation that happens to the combined event name (here https://github.com/Miserlou/Zappa/blob/master/zappa/core.py#L1978) can cause the environment to get truncated, resulting in the same rule being mapped to multiple lambdas (e.g., `<service name>-<env>-dev` gets truncated to `<service name>-<env>-` causing that rule to be used for *all* stages).

## Possible Fixes

- allow the keep warm handler event name to be configurable (allowing it to be shortened)
- for cases where rule names get truncated, use `<name hash>-handler.keep_warm_callback` for _just_ that rule name

**Comment by Miserlou** [comment]
I like both of those solutions!

**Comment by Miserlou** [comment]
We could also change `keep_warm_callback` to `kw_cb` always or in just that case.

**Comment by mdodsworth** [comment]
Great. I'm leaning towards the hashed approach, as it solves the problem for all lengths of lambda name. I'll send over a PR

**Comment by illing2005** [comment]
This seems to be a problem again.
Because `Zappa.get_scheduled_event_name` truncates the name already to 64 characters, line 2667 gets never executed:

https://github.com/Miserlou/Zappa/blob/23cede829f2a76957cf514a8799dddd25dbd041a/zappa/core.py#L2663-L2670
