### ISSUE TITLE
Support .yaml extension for zappa settings

### ISSUE THREAD

**Issue by bxm156** [Miserlou/Zappa#975]
Zappa doesn't support looking for ```zappa_settings.yaml```, it only looks for the .yml extension

According to http://www.yaml.org/faq.html:
```
Is there an official extension for YAML files?
Please use ".yaml" when possible.
```

Should be a fairly minor/easy change. Maybe the only question is which should take precedence?

**Comment by Miserlou** [comment]
![image](https://user-images.githubusercontent.com/139987/27715120-0bdd2cf6-5d03-11e7-8226-9c838fd85f30.png)

**Comment by bxm156** [comment]
Haha, fair, though I don't mind doing the work here.

**Comment by Miserlou** [comment]
Sure. PR welcome. If you could, do it from TML/TOML as well while you're at it.
