### ISSUE TITLE
Exit with Error from CLI when Not in Virtualenv

### ISSUE THREAD

**Issue by mcrowson** [Miserlou/Zappa#979]
## Context

 
Zappa works best when using a virtualenv. Not using one causes some strange things to happen as reported in our slack channel from time to time.

## Expected Behavior

An warning is raised when outside of a venv

## Actual Behavior

Zappa doesn't care if you're using system python or venv 

## Possible Fix

Early on in the cli:

```python
import sys

if not hasattr(sys, 'real_prefix'):
    # Not currently in a virtual environment
    click.echo("You are currently deploying outside of a virtual environment. This may cause unexpected problems in lambda as Zappa deploys your locally installed packages.)
```

**Comment by Miserlou** [comment]
Which commands does this happen for? When I try, I get:

```
zappa init
Zappa must be run inside of a virtual environment!
Learn more about virtual environments here: http://docs.python-guide.org/en/latest/dev/virtualenvs/
```

**Comment by mcrowson** [comment]
Man, I had just assumed that wasn't already built in because so many people have trouble it its usually attributed to venv. Guess you're ahead of it this time. Not sure how else we could fix this for people. Feel free to close if not much else could be done here.
