### ISSUE TITLE
Use AWS Credentials and Region When Creating a new Boto Session to Fetch Project Zip

### ISSUE THREAD

**Issue by bahoo** [Miserlou/Zappa#984]
I ran into an issue where [fetching the project zip from S3](https://github.com/Miserlou/Zappa/blob/master/zappa/handler.py#L165) was failing, with a very unhelpful `400 Bad Request` from S3, and no response in the body to illuminate on the problems.

## Context
I'm using the `us-west-2` region, with `slim_handler` set to `true`.

## Expected Behavior
The handler should download the zip successfully from S3.

## Actual Behavior
The handler tried to download my project zip from S3, and it failed.

## Possible Fix

I eventually discovered it was because of the [`boto`session being initiated](https://github.com/Miserlou/Zappa/blob/master/zappa/handler.py#L155-L156) above it, without the right kwargs being passed in. Namely, in my case, I needed these set:

- `aws_access_key_id`
- `aws_secret_access_key`
- `region_name`

I *think* `region_name` was the clincher for me (I'm using `us-west-2`), as the access and secret key should be part of the environment variables. But interestingly, if `aws_session_token` was passed in, it would still fail. That was puzzling to me, but I didn't have the bandwidth to unpack further.

I've made these changes, sitting in a branch here: https://github.com/bahoo/Zappa/tree/use_aws_credentials_in_creating_boto_session Happy to add a PR if that seems like a good idea to others.

## Steps to Reproduce
1. Set your AWS region to `us-west-2`
2. Use `slim_handler: true`
3. Deploy

## Your Environment
* Zappa version used: 0.42.0
* Operating System and Python version: macOS Sierra, Python 2.7.12
* The output of `pip freeze`: 
```
appdirs==1.4.3
argcomplete==1.8.2
base58==0.2.4
boto3==1.4.4
botocore==1.5.40
click==6.7
dj-database-url==0.4.2
Django==1.10.6
django-bootstrap3==8.2.1
django-dotenv==1.4.1
docutils==0.13.1
durationpy==0.4
EasyProcess==0.2.3
future==0.16.0
futures==3.1.1
googlemaps==2.4.6
gunicorn==19.7.1
hjson==2.0.7
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.16.1
packaging==16.8
placebo==0.8.1
psycopg2==2.7.1
pyparsing==2.2.0
python-dateutil==2.6.0
python-slugify==1.2.4
pyunpack==0.1.2
PyYAML==3.12
requests==2.11.1
s3transfer==0.1.10
six==1.10.0
toml==0.9.2
tqdm==4.14.0
troposphere==1.9.4
Unidecode==0.4.21
Werkzeug==0.12
whitenoise==3.3.0
wsgi-request-logger==0.4.6
zappa==0.42.0
```

* Your `zappa_settings.py`: 
```
{
    "production": {
        "aws_region": "us-west-2", 
        "django_settings": "culverstack.settings_zappa", 
        "profile_name": "default",
        "s3_bucket": "culverstack",
        "slim_handler": true,
        "remote_env": "[ ... snipped ... ]"
    }
}
```

**Comment by Miserlou** [comment]
Seems like a good fix, PR welcome!

**Comment by pjz** [comment]
According to [Boto docs](https://boto3.readthedocs.io/en/latest/guide/configuration.html#environment-variable-configuration), it already checks environment variables for those values, so it would seem redundant to duplicate that work.  Did you try setting the region by setting the `AWS_DEFAULT_REGION` environment variable?

**Comment by bahoo** [comment]
Yes, setting `AWS_DEFAULT_REGION` environment variable didn't do the trick in my case. I needed to pass it directly to the session, and pass the access key + secret access key too.

My take, I was following a convention set elsewhere in Zappa: https://github.com/Miserlou/Zappa/blob/6ec233853ba7d8210c59124915d5492393b3420b/zappa/core.py#L2409-L2420 And I think there's [enough gray area in order of precedence on credentials](http://boto3.readthedocs.io/en/latest/guide/configuration.html#configuring-credentials) that being explicit is better than implicit here. 

That all said, I still suspect the `AWS_SESSION_TOKEN` may be causing a conflict here, or otherwise playing some part. When I passed it in to the session explicitly via `aws_session_token=`, it failed.

**Comment by pjz** [comment]
You can pass all those things via environment variables - unless for some reason they're not reaching the environment that Boto sees?  In which case, IMO, we should fix *that*, not reimplement the mechanism.

**Comment by mjschultz** [comment]
Does your `remote_env` file have any `AWS_` keys in it? You talk about how you're tweaking environment variables, so I'm curious which ones you are setting because those trigger different paths within boto. Hide the values for the access/secret/session ones if they are set of course.

**Comment by bahoo** [comment]
I've got these set: `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_DEFAULT_REGION`

**Comment by mjschultz** [comment]
So, under the original zappa handler the way boto would work here would be to connect using those values + a incorrect session token that is built-in to the lambda environment.

With your change you do not bring in that session token and it will work as you expect, but I suspect many people let boto use the underlying environment vars that lambda provides (we do, though we don't use the slim handler).

Is it possible for you to remove those `AWS_*` vars from the `remove_env` file? This would make the lambda use only the IAM role associated with in. Note that it successfully gets your `remote_env` file from S3 already.

**Comment by bahoo** [comment]
My application uses those AWS credentials, but renaming them does work. 👍

Can you elaborate on how this conflict comes to be? I don't completely follow, and I'm still getting my feet wet with Lambda.

**Comment by mjschultz** [comment]
If you were to create a very simple Lambda that just prints out `os.environ` it would include (among others):

```
'AWS_REGION': 'us-west-2'
'AWS_DEFAULT_REGION': 'us-west-2'
'AWS_ACCESS_KEY_ID': '...'
'AWS_SECRET_ACCESS_KEY': '...'
'AWS_SESSION_TOKEN': '...'
'AWS_SECURITY_TOKEN': '...'
```

Overtime these have standardized across the various AWS SDKs for different languages (session and security token are the same, as are region and default_region).

Since the zappa code calls `boto3.Session()` it'll use whatever mechanism matches, because lambda defines these vars it'll use the environment mechanism. That environment mechanism will look up the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` values. They'll also look up `AWS_SESSION_TOKEN` (and `AWS_SECURITY_TOKEN` for legacy reasons if the other isn't set), as well as `AWS_DEFAULT_REGION` when creating the session.

Since you're providing a separate `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` in the `remote_env` file, *Zappa will end up over-writing the existing vars with yours*.

BUT since Lambda provides the `AWS_SESSION_TOKEN`, boto will see that and pass that to the AWS API for authentication which will fail because your `AWS_ACCESS_KEY_ID`/`AWS_SECRET_ACCESS_KEY` combo doesn't need one.

Does that make sense?

I will also say that AWS Best Practice guides strongly discourage the use of personal access keys for code because they have indefinite lifetimes and/or when revoked might cause unexpected breakage. That's why I'd try to use the Lambda role for your access and remove your personal tokens from the environment. Of course I understand how complex authentication and authorization are in AWS, so it's up to you!

**Comment by mjschultz** [comment]
I suppose something Zappa could do more proactively is issue a warning when loading the environment if it overrides something that is already in os.environ.

**Comment by bahoo** [comment]
Ah :D that makes sense, thank you. Yeah relying on the role and giving it the right perms seems like a better bet here. I will close this and update my code accordingly. Thank you!

**Comment by pjz** [comment]
I like @mjschultz idea of warning when an existing environment variable is being overridden. Maybe open a new issue for that?

**Comment by mjschultz** [comment]
I think I captured it in https://github.com/Miserlou/Zappa/issues/1000

**Comment by monkut** [comment]
Hit the same issue recently, and just want to clarify the displayed error.

The error I saw when credentials were overridden as a result of using AWS* fields in zappa_settings environment_variables when using slim_handler=True results in following error:

```
botocore.exceptions.ClientError: An error occurred (InvalidToken) when calling the GetObject operation: The provided token is malformed or otherwise invalid.
```
