### ISSUE TITLE
make cookie hack case-insensitive 

### ISSUE THREAD

**Issue by Argentan** [Miserlou/Zappa#990]
## Context
Some wsgi compliant frameworks, like Falcon, convert all headers to lower case before calling start_response. While it's easy to work around this behavior to make the response compatible with Zappa's cookie hack, it is a really hard bug to find, Since the HTTP protocol specifies that the headers are case-insensitive, I think it is reasonable to change two lines of code that could accommodate any casing for the set-cookie header .

## Expected Behavior
All cookies are send to the client with casings permutations

## Actual Behavior
Only one cookie is sent (the last one) 'cause the "set-cookie" header set by the wsgi app is lower case and thus, it is not intercepted by the cookie hack middleware. 

## Possible Fix

change zappa/middleware.py, lines 57 to 59 from:
```python
new_headers = [(header[0], header[1]) for header in headers if
               header[0] != 'Set-Cookie']
cookie_headers = [x for x in headers if x[0] == "Set-Cookie"]
```
TO: 
```python
new_headers = [header for header in headers
               if ((type(header[0]) != str) or (header[0].lower() != 'set-cookie'))]
cookie_headers = [header for header in headers 
                  if ((type(header[0]) == str) and (header[0].lower() == "set-cookie"))]
```
I've already forked the the project and made the proposed changes, but didn't made the pull request yet. 

NOTE: I am not sure if it's needed to check the type of the header's name, but since I am calling a string method on it, I'd rather be safe than sorry.

**Comment by Miserlou** [comment]
Looks good, but why the type checking?

**Comment by Miserlou** [comment]
Closed via merge. Thank you for fixing this!

**Comment by Argentan** [comment]
My pleasure and my very first PR :)
