### ISSUE TITLE
Create APIGateway on wrong region

### ISSUE THREAD

**Issue by ebertti** [Miserlou/Zappa#995]
## Expected Behavior
Use lambda, apigateway and bucket on same region configured on `zappa_settings.json` 

## Actual Behavior
Lamda and bucket using region on `zappa_settings.json` and apigateway using env AWS_DEFAULT_REGION
He also ignore `~/aws/.config`

## Possible Fix
everything using `zappa_settings.json`

## Steps to Reproduce
1. set  `zappa_settings.json` with region `us-east-1`
2. on bash: `export AWS_DEFAULT_REGION=us-west-1`
3. run `zappa deploy`

## Your Environment

* Zappa version used:
* Ubuntu python 3.6 on semaphoreci

**Comment by Miserlou** [comment]
This is the intended behavior. No setting uses default, you are overriding with the settings file.
