### ISSUE TITLE
Frequency of zappa pulling remote environment variables

### ISSUE THREAD

**Issue by taylor-revcascade** [Miserlou/Zappa#997]
I had a question on the functionality of remote_env.  How often will a deployed lambda function look to load the remote environment variables file or does it only load them at invocation or on an update/deploy?  If I update the remote file with a new environment variable, what is the recommended path for pushing those variables out?

**Comment by Miserlou** [comment]
They're cached if using remote env, I think they're dynamic if local or AWS. Best to ask in Slack for this kind of stuff.
